### ISSUE TITLE
Could not get identity $edgeAgent

### ISSUE THREAD

**Issue by dme-development** [Azure/iotedge#7380] opened 2024-10-09 07:53 UTC
We noticed yesterday that our IoT devices could not download their modules anymore. It all started with the message:
Unable to process module xxxxxx add or update as the module identity could not be obtained.

What we already did:
- removed the device from the IoT Hub and had it provision again -> DPS provisioning seems to work fine, the device is recognized and gets added to the IoT Hub.
- removed all modules (docker image prune -f -a) so that the edgeAgent would start downloading again -> This fails because now even the edgeAgent will not start anymore. The logs show: HTTP request failed: [401 Unauthorized] errorCode:401002, but how can this be happening while the device gets registered correctly?

IoT Edge version on the device is: 1.0.10 and 1.1.15, because we cannot upgrade remote to 1.4 or 1.5.

<details>
<summary>iotedged logs</summary>

```

Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Configuring certificates...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Transparent gateway certificates not found, operating in quick start mode...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Finished configuring provisioning environment variables and certificates.
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Initializing hsm...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Finished initializing hsm.
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Initializing hsm X509 interface...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Finished initializing hsm X509 interface...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Provisioning edge device...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Starting provisioning edge device via X509 provisioning...
Okt 09 09:45:50 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:45:50Z [INFO] - Starting DPS registration with scope_id "0ne00xxxxxx", registration_id "S360N12011023C82HU"
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - DPS registration assigned device "S360N12011023C82HU" in hub "xxx.azure-devices.net"
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Successful DPS provisioning.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Finished provisioning edge device.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Initializing the module runtime...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Initializing module runtime...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Using runtime network id azure-iot-edge
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Successfully initialized module runtime
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Finished initializing the module runtime.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Stopping all modules...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Finished stopping modules.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Reprovisioning status InitialAssignment will trigger reconfiguration of modules.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Detecting if configuration file has changed...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - No change to configuration file detected.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Edge issuer CA expiration date: 2041-03-14T06:54:01Z
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Obtaining workload CA succeeded.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Starting management API...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Starting workload API...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Starting watchdog with 60 second frequency...
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Listening on fd://iotedge.mgmt.socket/ with 1 thread for management API.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Listening on fd://iotedge.socket/ with 1 thread for workload API.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Checking edge runtime status
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [INFO] - Creating and starting edge runtime module edgeAgent
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [WARN] - Error in watchdog when checking for edge runtime status:
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [WARN] - A module runtime error occurred.
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [WARN] -         caused by: Could not get identity $edgeAgent
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [WARN] -         caused by: Could not get module $edgeAgent
Okt 09 09:46:01 S360N12011023C82HU iotedged[12003]: 2024-10-09T07:46:01Z [WARN] -         caused by: HTTP request failed: [401 Unauthorized] {"Message":"{\"errorCode\":401002,\"message\":\"Unauthorized access\",\"trackingId\":\"9AF43B5BAC6B47C38DDE1AD6CF64AECB-G2:-TimeStamp:2024-10-09T07:46:01.963158726Z\",\"timestampUtc\":\"2024-10-09T07:46:01.963158726Z\",\"info\":null}","ExceptionMessage":""}

```
</details>

**Comment by dperez83** [comment] 2024-10-16 15:37
Hello @dme-development 

I am having the same problem since yesterday.  I just opened a support ticket on Azure and I advise you to do the same. I don't think this github will be able to provide a solution for us.

Module name is redacted.

**iotedge logs edgeAgent**
```
<6> 2024-10-16 11:24:01.378 -04:00 [INF] - Plan execution started for deployment 242
<6> 2024-10-16 11:24:01.378 -04:00 [INF] - Executing command: "Saving xxxx to store"
<6> 2024-10-16 11:24:01.378 -04:00 [INF] - Plan execution ended for deployment 242
<6> 2024-10-16 11:24:20.708 -04:00 [INF] - Unable to process module xxxx add or update as the module identity could not be obtained
```

**iotedged**
```
TimeCreated : 2024-10-16 10:51:52
Message     : info: edgelet_http::logging -- [mgmt] - - - [2024-10-16 14:51:52.807863200 UTC] "GET 
              /identities/?api-version=2020-07-07 HTTP/1.1" 500 Internal Server Error 468 "-" "-" auth_id(-)
 
TimeCreated : 2024-10-16 10:51:52
Message     : error: edgelet_http_mgmt::error -- Internal server error: Could not list identities
              	caused by: Could not list identities
              	caused by: Could not list modules
              	caused by: HTTP request failed: [401 Unauthorized] 
              {"Message":"{\"errorCode\":401002,\"message\":\"Unauthorized access\",\"trackingId\":\"76CA4DD4C56F4B3C9A
              7C0FD4B234CFED-G2:-TimeStamp:2024-10-16T14:51:52.751062776Z\",\"timestampUtc\":\"2024-10-16T14:51:52.7510
              62776Z\",\"info\":null}","ExceptionMessage":""}
```

BTW how did you got iotedged logs in that format?

**Comment by dme-development** [comment] 2024-10-17 08:09
Hi @dperez83 ,

I already have an open case with Microsoft, but since its 1.0 and 1.1, it's hard getting support. Now we know that multiple users are affected, we might be able to convince them looking into it. Do you mind sharing your case number, so I can pass it in mine as a reference?

Regarding the logs, we get them from journalctl: journalctl -u iotedge

**Comment by dme-development** [comment] 2024-10-22 09:51
@dperez83 : if you have an update on your ticket, please keep us updated here. From my end, still no progress made on my ticket.

**Comment by maskimthedog** [comment] 2024-10-24 12:04
We are seeing the same error on 1.4 and 1.5.  We are getting error 401002.  Same firmware ran fine until about two weeks ago.

**Comment by maskimthedog** [comment] 2024-10-24 12:05
We are also seeing an error which mentions something about an illegal HTTP status code returned.

**Comment by ryanwinter** [comment] 2024-10-24 19:57
Thankyou for raising this issue and creating a support ticket. I believe this issue is relating to the IoT Hub service itself but I will follow up to make sure there is no changes needed with IoT Edge runtime.

**Comment by ryanwinter** [comment] 2024-10-24 20:27
@dme-development - I have share this GitHub with the engineering handling your case internally to see if we can move this forward.

**Comment by ryanwinter** [comment] 2024-10-24 20:59
@dme-development: We have identified a change on IoT Hub that is possibly causing your issue and have escalated to that team.

**Comment by dperez83** [comment] 2024-10-25 03:45
> [@dperez83](https://github.com/dperez83) : if you have an update on your ticket, please keep us updated here. From my end, still no progress made on my ticket.

Sorry for the delay, Azure support rolled back an update to our IoT Hub and after that the deployment and everything works fine.

**Comment by dme-development** [comment] 2024-10-25 06:34
> [@dme-development](https://github.com/dme-development): We have identified a change on IoT Hub that is possibly causing your issue and have escalated to that team.

Thank you very much, Ryan. If possible, please keep me updated.

**Comment by dme-development** [comment] 2024-10-28 08:21
Our IoT Hub was also rolled back and now everything is working again.

**Comment by bishal41** [comment] 2024-10-28 16:21
Closing this issue as it seems the issue is now resolved. Let us know if you have any questions.

**Closed by bishal41** 2024-10-28 16:21 UTC

**Comment by licensedslacker** [comment] 2024-10-30 13:28
Hello,

Sorry for posting closed ticket but we have also encountered this problem and I have done some inspection around this issue.

I have two test systems where the system 1 is running iotedge version 1.1.15 and the system 2 is running iotedge 1.5. When using X.509 certificates in the device provisioning, the system 1 is unable to communicate with the iot hub. The error is the same "401 Unauthorized" error as described in the first post. The DPS service is working fine. The system 2 is working correctly with the same certificates. The certificates are generated with the "certGen.sh" script found from the project files.

This problem does not reproduce on all of IoT hub instances the were are currently using. The only differentiating factor seems to be when an IoT hub instance has been created. Older instances seems to work, but more recent ones do not.

Certificate based enrollment creates new devices into a IoT hub with "Self-signed X509 Certificate" authentication. Under my understanding, the device shopuld authenticate with the same identity certificate as used in DPS service to IoT hub. I tested manual X.509 provisioning while using the certificates, but the result was the same: iotedge 1.1 gives "401 Unauthorized" error and 1.5 is working correctly.

I'd like to gain understanding what is the difference between these two version. After intercepting HTTP calls done by iotedge I got following findings:
iotedge 1.1.15 uses DPS service's api-version 2019-04-15. iotedge 1.5 is using api-version 2021-06-01. Both version are using IoT hub's api-version 2017-11-08-preview.
There seems to be little difference in communication with DPS, expect 2019-04-15 version returns 2 additional fields in the response JSON that are set to a value null.

**The main difference in the communication with the IoT Hub seems to be that iotedge 1.1.15 is sending "authorization" filed with SAS token in the HTTP header while the iotedge 1.5 does not.**

My current theory is that the behavior of the IoT hub has been changed in some recent update. If IoT hub expects X.509 authentication and finds SAS token from the request, this leads to immediate termination of the request. The prevous behavior expects either a token or x.509 certificate. Because the DPS or manual provisioning does not work with iotedge 1.1 and x.509 certificates, it looks like that this feature is broken at moment when using the older (and yes, not supported) version.

**Comment by bishal41** [comment] 2024-10-30 16:26
@licensedslacker would you mind opening a support ticket via Azure Portal? this seems to require investigation/involvement from broader teams.

**Comment by ryanwinter** [comment] 2024-10-30 16:29
@licensedslacker You are correct, there has been a change in the IoT Hub and certain older auth paths were eliminated due to no longer being supported. Please open an ICM and the IoT Hub team will assist you.

**Comment by ryanwinter** [comment] 2024-11-12 17:29
@dme-development I totally understand and agree that being out of support shouldnt mean it just stops working. Out of support means that we no longer ship updates for security and critical fixes.

In this case, there was an inconsistency in how iot edge authenticated which was fixed in a later version, and unfortunately when IoT Hub team was pushing out the update, they eliminated this authentication fallback. 

The team is aware of this and is migrating customer back to the older stack while until they have addressed the issue. This is only impacting a very small number of customers / IoT Hubs which was why this was missed.

**Comment by TomiLahtinen** [comment] 2025-05-06 10:23
Late to the party but I'm seeing this issue in only one of our total of three IoT Hub instances. The one that seems to be broken has feature flag "GWV2" in it's features collection while the other two don't. Is it possible that GWV2 is causing this behavior in IoT Hub when using old IoT Edge version. Using current version of IoT Edge seems to work in all IoT Hubs we have

**Comment by maskimthedog** [comment] 2025-05-06 10:48
> Late to the party but I'm seeing this issue in only one of our total of three IoT Hub instances. The one that seems to be broken has feature flag "GWV2" in it's features collection while the other two don't. Is it possible that GWV2 is causing this behavior in IoT Hub when using old IoT Edge version. Using current version of IoT Edge seems to work in all IoT Hubs we have. It would be really helpful if someone from Microsoft could verify if we can trust the non-GWV2 instances to work with older Edge version.

We ran into this issue a couple of years ago with what was then the current version of IoT Edge.  Our issue was that reprovsioning between IoT Hubs did not work for GWV2 instances.  For non-GWV2 instances reprovisioning worked fine.  MSFT could not locate the issue, so we had them roll back our IoT Hubs to non-GWV2 instances to resolve.  We need to go back and re-test with the current IoT Edge version and a GWV2 instance.  Maybe the issue is now fixed.

**Comment by TomiLahtinen** [comment] 2025-05-06 11:11
> We ran into this issue a couple of years ago with what was then the current version of IoT Edge. Our issue was that reprovsioning between IoT Hubs did not work for GWV2 instances. For non-GWV2 instances reprovisioning worked fine. MSFT could not locate the issue, so we had them roll back our IoT Hubs to non-GWV2 instances to resolve. We need to go back and re-test with the current IoT Edge version and a GWV2 instance. Maybe the issue is now fixed.

Thanks for the clarification. I should've probably also mentioned that the three IoT Hub instances serve different environments so the device will always be re-provisioned back to same IoT Hub instance. We bumped into this issue when we started rolling out new x509 root certificate for device provisioning. Devices that use identity certs signed by old root cert work just fine until we have to roll the device certs due to expiration or some other reason. At that point, when we sign the device cert with new root cert, this issue appears. DPS provisioning works with any valid cert we toss at it, but IoT Hub is not working. When resorting back to symmetric key, IoT Hub connection starts working again. And this only happens in the environment where the IoT Hub has GWV2 feature.
