### ISSUE TITLE
iotedge unable to start containers under poor network conditions

### ISSUE THREAD

**Issue by Hammatt** [Azure/iotedge#1470] opened 2019-07-23 20:23 UTC
## Expected Behavior
IoT Edge should start images available on the device as per the device manifest

## Current Behavior
IoT Edge seems to try to do a pull of a docker image without checking if it already has the image, failing in some scenarios.

## Steps to Reproduce
Unknown

### Output of `iotedge check`
```
error: Found argument 'check' which wasn't expected, or isn't valid in this context

USAGE:
    iotedge [OPTIONS] <SUBCOMMAND>

For more information try --help

```

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
`1.0.5`

#### Edge Agent
`1.0.5`

#### Edge Hub
`1.0.5`

#### Docker

```
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       74baf62
  Built:            Tue Dec  4 20:29:24 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Logs

<details>
<summary>iotedged logs</summary>

```
Jul 22 19:07:54 ubuntu iotedged[7561]: 2019-07-22T19:07:54Z [INFO] - [mgmt] - - - [2019-07-22 19:07:54.037724229 UTC] "PUT /identities/<REDACTED, Module tag>?api-version=2018-06-28 HTTP/1
Jul 22 19:08:27 ubuntu iotedged[7561]: 2019-07-22T19:08:27Z [ERR!] - Internal server error: Could not update identity <REDACTED, Module tag>
Jul 22 19:08:27 ubuntu iotedged[7561]:         caused by: Could not update identity <REDACTED, Module tag>
Jul 22 19:08:27 ubuntu iotedged[7561]:         caused by: Could not upsert module <REDACTED, Module tag>
Jul 22 19:08:27 ubuntu iotedged[7561]:         caused by: Could not perform HTTP request
Jul 22 19:08:27 ubuntu iotedged[7561]:         caused by: an IO error occurred: Connection reset by peer (os error 104)
Jul 22 19:08:27 ubuntu iotedged[7561]: 2019-07-22T19:08:27Z [INFO] - [mgmt] - - - [2019-07-22 19:08:27.714522656 UTC] "PUT /identities/<REDACTED, Module tag>?api-version=2018-06-28 HTTP/1.1" 50
Jul 22 19:08:27 ubuntu iotedged[7561]: 2019-07-22T19:08:27Z [INFO] - [mgmt] - - - [2019-07-22 19:08:27.833586752 UTC] "PUT /identities/<REDACTED, Module tag>?api-version=2018-06-28 HTTP/1.1" 20
Jul 22 19:08:27 ubuntu iotedged[7561]: 2019-07-22T19:08:27Z [INFO] - Pulling image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>...
Jul 22 19:08:35 ubuntu iotedged[7561]: 2019-07-22T19:08:35Z [INFO] - Checking edge runtime status
Jul 22 19:08:35 ubuntu iotedged[7561]: 2019-07-22T19:08:35Z [INFO] - Edge runtime is running.
Jul 22 19:08:38 ubuntu iotedged[7561]: 2019-07-22T19:08:38Z [WARN] - Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
Jul 22 19:08:38 ubuntu iotedged[7561]: 2019-07-22T19:08:38Z [WARN] -         caused by: Get https://<REDACTED, Azure Container Registry>/v2/: net/http: TLS handshake timeout
Jul 22 19:08:38 ubuntu iotedged[7561]: 2019-07-22T19:08:38Z [INFO] - [mgmt] - - - [2019-07-22 19:08:38.142749569 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server
Jul 22 19:08:38 ubuntu iotedged[7561]: 2019-07-22T19:08:38Z [INFO] - Pulling image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>...
Jul 22 19:08:48 ubuntu iotedged[7561]: 2019-07-22T19:08:48Z [WARN] - Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
Jul 22 19:08:48 ubuntu iotedged[7561]: 2019-07-22T19:08:48Z [WARN] -         caused by: Get https://<REDACTED, Azure Container Registry>/v2/: net/http: TLS handshake timeout
Jul 22 19:08:48 ubuntu iotedged[7561]: 2019-07-22T19:08:48Z [INFO] - [mgmt] - - - [2019-07-22 19:08:48.446781657 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server
Jul 22 19:08:53 ubuntu iotedged[7561]: 2019-07-22T19:08:53Z [INFO] - Pulling image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>...
Jul 22 19:09:03 ubuntu iotedged[7561]: 2019-07-22T19:09:03Z [WARN] - Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
Jul 22 19:09:03 ubuntu iotedged[7561]: 2019-07-22T19:09:03Z [WARN] -         caused by: Get https://<REDACTED, Azure Container Registry>/v2/: net/http: TLS handshake timeout
Jul 22 19:09:03 ubuntu iotedged[7561]: 2019-07-22T19:09:03Z [INFO] - [mgmt] - - - [2019-07-22 19:09:03.822445499 UTC] "POST /modules?api-version=2018-06-28 HTTP/1.1" 500 Internal Server
Jul 22 19:09:14 ubuntu iotedged[7561]: 2019-07-22T19:09:14Z [INFO] - Pulling image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>...
```
</details>

<details>
<summary>edge-agent logs</summary>

```
2019-07-22 18:28:42.547 +00:00 [INF] - Plan execution ended for deployment 6
2019-07-22 18:28:42.547 +00:00 [ERR] - Edge agent plan execution failed.
System.AggregateException: One or more errors occurred. (Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 176
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86<---

2019-07-22 18:28:42.552 +00:00 [WRN] - Reconcile failed because of the an exception
System.AggregateException: One or more errors occurred. (Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout) ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException: Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.<>c.<ExecuteAsync>b__7_0(List`1 f) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 114
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 115
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 176
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 187
---> (Inner Exception #0) Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module <REDACTED, Module name>: Could not create module <REDACTED, Module name>
        caused by: Could not pull image <REDACTED, Azure Container Registry>/<REDACTED, Module name>:<REDACTED, Module tag>
        caused by: Get https://<REDACTED, Azure Container Registry>: net/http: TLS handshake timeout, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 194
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 89
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 36
   at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 61
   at Microsoft.Azure.Devices.Edge.Agent.Core.PlanRunners.OrderedRetryPlanRunner.ExecuteAsync(Int64 deploymentId, Plan plan, CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planrunners/OrdererdRetryPlanRunner.cs:line 86<---

2019-07-22 18:28:43.342 +00:00 [INF] - Updated reported properties
2019-07-22 18:28:48.690 +00:00 [INF] - Plan execution started for deployment 6
2019-07-22 18:28:48.691 +00:00 [INF] - Plan execution ended for deployment 6
2019-07-22 18:28:53.970 +00:00 [INF] - Plan execution started for deployment 6
2019-07-22 18:28:53.970 +00:00 [INF] - Plan execution ended for deployment 6
2019-07-22 18:28:59.273 +00:00 [INF] - Plan execution started for deployment 6
2019-07-22 18:28:59.274 +00:00 [INF] - Plan execution ended for deployment 6
2019-07-22 18:29:04.550 +00:00 [INF] - Plan execution started for deployment 6
2019-07-22 18:29:04.551 +00:00 [INF] - Plan execution ended for deployment 6
```
</details>

<details>
<summary>edge-hub logs</summary>

```
Was not able to get off the production box at the time. Could go back and get if required.
```
</details>

## Additional Information
We were also able to confirm that doing a straight `docker pull {container}` on the device itself also gave the TLS handshake timeout so we are pretty sure that there is something going on in the network between the device and the container registry.

However, this device was running just fine the other day, and already has these docker images cached locally. I believe that the daemon should try to run from local images first instead.

The production downtime caused by this has since resolved itself (about 24h of downtime).

**Comment by varunpuranik** [comment] 2019-07-24 20:12
@Hammatt ,
Thanks for the issue. I understand your issue, and also the concern. 
One question I have is - were the modules wiped out, when the downtime occurred? If the Edge runtime is in a running or stopped state and the modules (and their containers) have been created, then it should be able to keep running or start the stopped containers without having to pull first. 
I will add this issue to our backlog.

**Comment by Hammatt** [comment] 2019-07-24 20:17
For some clarification, what happened at the time was the customer reported the system was slow (later turned out to be because of the network) so the first thing that the operations team tried was to do the good old turn it off and back on again. 
At which time it couldn't start back up. The modules shouldn't have been wiped out as far as I understand it.

**Comment by varunpuranik** [comment] 2019-07-24 22:08
If the modules were not deleted, then it should have started back up fine.
Can you provide the full EdgeAgent logs for the scenario? You can replace the actual module names (and any other PII) with Guids (instead of Redacted), that way we can correlate the different log lines for the same module.
Also, it looks like you are using the 1.0.5 version of the Edge runtime (iotedged, EdgeHub and EdgeAgent). Those are relatively old bits and there have been several updates and fixes in the components. I would recommend trying with the latest bits (1.0.8) if the issue still repros.

**Comment by Hammatt** [comment] 2019-07-24 23:16
We only have that snippet of the logs unfortunately. Due to the space we work in we can't get onto the device ourselves and had to have the customer send us the logs. Is there any way to get the edgeAgent logs via the hub in azure?

Also we are aware we are running an old version and hope that we can update soon but there's lots of paperwork involved in doing said update for us.

**Comment by arsing** [comment] 2019-08-20 23:16
To clarify the behavior, the service attempts to start the existing module container if it already exists. But if the module container does not exist (say because it was deleted earlier), then it tries to pull the image via `docker pull`. Pulling the image may not actually *download* anything if the image matches what the registry has for that tag, but determining that requires communicating with the registry. So even though the image exists on disk, there is still a network call to the registry that is required.

So the point of investigation is to figure out why the module was deleted.

I'll close this since there has been no update for quite some time. We can reopen if you still have the issue and can get logs, though as varunpuranik said you should at the very least update to the latest release first.

**Closed by arsing** 2019-08-20 23:16 UTC
Labels: needinfo

**Comment by Hammatt** [comment] 2019-08-20 23:23
@arsing

what you describe makes sense. The problem is caused by the fact that it still tries to pull in poor network conditions and fails to start up instead of just using the image.

What happens if the pull to check weather the image is up to date fails? will it still failover and just use the local copy?

**Comment by arsing** [comment] 2019-08-20 23:26
>The problem is caused by the fact that it still tries to pull in poor network conditions and fails to start up instead of just using the image.

To be precise, the problem is caused by the fact that the module was deleted, which is why we were asking for Edge Agent logs to see why that happened.

>What happens if the pull to check weather the image is up to date fails? will it still failover and just use the local copy?

No, it will fail to start the container.
