### ISSUE TITLE
IoT Edge produces too much traffic with default configuration, it is not conducive for billable networks such as cellular.

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/iotedge#7252] opened 2024-03-27 16:27 UTC
Hello IoT Edge team,

I hope you can help us and the community to fine-tune our iot edge design for billable networks.
To give you perspective, our IoT device sends compressed and batched telemetry on periodicity and on event changes.
This application, running stand-alone using MQTT and device SDK consumes less than 1MB a day.

We had good reasons to add containers and more features, and ported the application to a Linux constrained device, running IoT Edge with a cellular modem. but now the bill from telco is 12x

After some exploration, we identified some possible optimizations, but we would love to get best practices and recommendations from you:
1. Amqp appears to be the recommended protocol in documentation because `$upstream` multiplexing capability. But the ModuleClient in the custom modules runs thinner using Mqtt. Is there a comparison to illustrate when to mix and match Transport protocols? And if we use marketplace modules, is there a way to define the channel or at least, read it?
2. Could you help figure out what variable controls the following traces and how these affect traffic:
  2.1.  Done refreshing device scope identities cache. Waiting for **60** minutes.
  2.2. Entering periodic task to reauthenticate connected clients. //this shows every 5 minutes
  2.3. Started task to cleanup processed and stale messages for endpoint test_<module name>

3. I am surprised to see messages like the following, but this might be our code, and unrelated to traffic
`Cleaned up 516 messages from queue for endpoint test_<route> and 516 messages from message store.`

4. Could you explain how `ConfigRefreshFrequencySecs` works? why is it set by default every hour if the edge agent subscribes for property changes?
5. What is the advantage to set `CacheTokens` to true?
6. Do you have any other advice to reduce **downlink** traffic if the application is mainly a telemetry pump?

Here are more configuration variables
`"edgeAgent": {
                        "env": {
                            "SendRuntimeQualityTelemetry": {
                                "value": false
                            },
                            "ConfigRefreshFrequencySecs": {
                                "value": 86400
                            },
                            "DisableDeviceAnalyticsMetadata": {
                                "value": true
                            },
                            "MetricsEnabled": {
                                "value": false
                            },
                            "UpstreamProtocol": {
                                "value": "Mqtt"
                            }

"edgeHub": {
                        "env": {
                            "OptimizeForPerformance": {
                                "value": false
                            },
                            "HttpSettings__Enabled": {
                                "value": false
                            },
                            "CloudConnectionIdleTimeoutSecs": {
                                "value": 7200
                            },
                            "ConfigRefreshFrequencySecs": {
                                "value": 86400
                            },
                            "RuntimeLogLevel": {
                                "value": "info"
                            },
                            "CacheTokens": {
                                "value": true
                            },
                            "UpstreamProtocol": {
                                "value": "Mqtt"
                            },
                            "AmqpSettings__Enabled": {
                                "value": false
                            }
`

**Comment by nyanzebra** [comment] 2024-03-27 17:38
@varunpuranik / @veyalla do we have any customer facing documentation on the performance breakdowns of mqtt vs amqp?

1. This might be marketplace module specific, do you have a specific set of modules in mind? For example, the SimulatedTemperatureSensor can have a custom route defined.
2. Believe those messages correspond to device token refreshes for connections, are you saying you want control over that frequency? 
3. The queue cleanup should be after messages are sent and doing a batch cleanup of messages from underlying store. Can double check this, but think this happens every so often to clean up state from the underlying database.


For 4,5,6 @vipeller or @varunpuranik any guidance on these?

**Comment by uriel-kluk** [comment] 2024-03-27 18:05
Thanks @nyanzebra,

> Believe those messages correspond to device token refreshes for connections, are you saying you want control over that frequency?

My only motivation to ask about `token refreshnes` is to reduce traffic. I see a periodic trace every 5 minutes reauthenticating connected clients. I hope this is not creating cellular traffic.

But the main question remains the same, what is causing downloads, if the application is just pumping telemetry?
![image](https://github.com/Azure/iotedge/assets/41210115/06124024-8089-4bb3-9b69-6893e925cf16)

**Comment by nyanzebra** [comment] 2024-03-28 17:03
@uriel-kluk is the graph for network traffic to/from device? There should be occasional twin data sent to device to see if any changes in modules need to happen as well as some connectivity checks, but would be surprised if it is significant. I think the next steps are to dig deeper. 

If you have [metrics](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-access-built-in-metrics?view=iotedge-1.4) it will be interesting to see what the following say:
* `edgehub_gettwin_total`
* `edgeAgent_total_network_in_bytes`

Additionally, if you can provide a support bundle that will be useful.

**Comment by uriel-kluk** [comment] 2024-03-28 19:38
Hi Robert,

here is a chart that shows the docker networkstats​ by container.

[cid:c307df9c-e9cf-4d83-bdfd-3b440afe4994]

Clearly the traffic comes from edgeHub, in this ilustration, SimulatorModule is just reporting telemetry periodically. and you can see the line follows along and the delta is almost flat.

But edgeAgent​ had a spike of 35K.

I am going to move all the heads to AMQP to see if I gain anything. But I am almost sure it has to do with authentication.

Note: The edge device uses x509 to authenticate with iothub, and the modules use SasTokens

```c#
 var mqttSetting = new MqttTransportSettings(TransportType.Mqtt_Tcp_Only)
 {
     KeepAliveInSeconds = 5 * 60
 };

 var options = new ClientOptions
 {
     SasTokenTimeToLive = TimeSpan.FromHours(31),
     SasTokenRenewalBuffer = 50,
     ModelId = ModelId,
 };

 ITransportSettings[] settings = { mqttSetting };

 // OpenAsync a connection to the Edge runtime
 _client = await ModuleClient.CreateFromEnvironmentAsync(settings, options);

 if (_client == null)
 {
     Log.LogError("Failed to connect to IoT Hub");
     return;
 }
```
________________________________

**Comment by uriel-kluk** [comment] 2024-03-29 12:50
Hi @nyanzebra ,

Attached support bundle.

Please look at this chart:

![image](https://github.com/Azure/iotedge/assets/41210115/519c6c22-a996-4ac0-b3fd-2f9a14ec43a8)


It is clear that the edgeHub is renogotiating credentials **every hour**. Is there a way to control the frequency?
Identity attestation uses x.509 in this illustration.

Also, the custom module is doing authentication **every hour**. this is less impactful but yet it creates traffic.
This is the code I am using to connect the custom module with the edgeHub:
[edge-device-support-bundle.tar.gz](https://github.com/Azure/iotedge/files/14804399/edge-device-support-bundle.tar.gz)

```c#
ITransportSettings[] GetTransportSettings()
            {
                switch (transportType)
                {
                    case TransportType.Mqtt:
                    case TransportType.Mqtt_Tcp_Only:
                        return new ITransportSettings[] { new MqttTransportSettings(TransportType.Mqtt_Tcp_Only) };
                    case TransportType.Mqtt_WebSocket_Only:
                        return new ITransportSettings[] { new MqttTransportSettings(TransportType.Mqtt_WebSocket_Only) };
                    case TransportType.Amqp_WebSocket_Only:
                        return new ITransportSettings[] { new AmqpTransportSettings(TransportType.Amqp_WebSocket_Only) };
                    default:
                        return new ITransportSettings[] { new AmqpTransportSettings(TransportType.Amqp_Tcp_Only) };
                }
            }

            var settings = GetTransportSettings();
            var options = new ClientOptions
            {
                ModelId = ModelId,
                SasTokenTimeToLive = TimeSpan.FromDays(1),
            };

            // OpenAsync a connection to the Edge runtime
            _moduleClient = await ModuleClient.CreateFromEnvironmentAsync(settings, options);
```

**Comment by nyanzebra** [comment] 2024-04-01 16:49
@uriel-kluk would you mind trying to set `DeviceScopeCacheRefreshRateSecs` to a much larger number (default is 3600s or 1hr). I am hoping this reduces the download quite a bit, it also shouldn't effect edgeHub really.

**Comment by david-emakenemi** [comment] 2024-04-04 19:11
@uriel-kluk did the solution that Robert provided solve the issue?

**Comment by claya75** [comment] 2024-04-08 16:26
@david-emakenemi @nyanzebra Unfortunately, no. Thanks for all the great input on keeping our IoT Edge traffic lean on cellular. I've been digging into this with @uriel-kluk and with Wireshark I found some spots where we're using more bandwidth than we'd like or expect. I've attached some captures and charts to help illustrate. 

We would love to get your take on understanding why we'd be getting so much Rx traffic on edgeHub as shown below, and/or how to reduce it.
![2024-04-08 12 14 44](https://github.com/Azure/iotedge/assets/143425707/70ecefe5-a6af-435c-bd0e-23ec01c68e4e)

This screenshot is of a Wireshark capture with all Tx traffic filtered out, so this is only Rx traffic coming into our edge device, viewed both in bytes downloaded over time and the delta time between packets over time.
![Rx only--bytes and delta time](https://github.com/Azure/iotedge/assets/143425707/b02109c3-f15e-4acb-b38f-2967147ffad7)

This is a typical 24 hour period reported with our SuperSIM from Twilio.
![image](https://github.com/Azure/iotedge/assets/143425707/f03bf72b-7ac3-4f10-bf58-44fff3a16d39)

Capture files (.pcapng) both for 2.5hrs, one with TCP and TLS only filtered.
[captures.zip](https://github.com/Azure/iotedge/files/14908380/captures.zip)

**Comment by nyanzebra** [comment] 2024-04-09 16:15
@claya75 & @uriel-kluk 

Looking at the attached pcap, it looks like packets regarding certs are few and while large, aren't the majority of downloads.

When looking further it looks like there is a consistent traffic being sent from `20.49.109.144`, which I assume to be your iothub, of about 135 length (TLS record len 64). Given the size, these are likely not PUBACKs within MQTT. 

I will try to reproduce by setting up a local device and see if can monitor traffic w/o TLS to see if can get some answers. Will also ask IoTHub team if they have any ideas.

**Comment by uriel-kluk** [comment] 2024-04-09 16:35
Thank you for Robert looking deeper.


We are changing the runtime settings as follows:

"systemModules": {
    "edgeAgent": {
        "type": "docker",
        "env": {
            "SendRuntimeQualityTelemetry": {
                "value": false
            },
            "ConfigRefreshFrequencySecs": {
                "value": 86400
            },
            "DisableDeviceAnalyticsMetadata": {
                "value": true
            },
            "MetricsEnabled": {
                "value": false
            },
            "RuntimeLogLevel": {
                "value": "info"
            },
            "UpstreamProtocol": {
                "value": "Mqtt"
            }
        },
        "settings": {
            "image": "mcr.microsoft.com/azureiotedge-agent:DEFAULT_RT_IMAGE",
            "createOptions": {
                "LogConfig": {
                    "Type": "json-file",
                    "Config": {
                        "max-size": "1m",
                        "max-file": "3"
                    }
                }
            }
        }
    },
    "edgeHub": {
        "type": "docker",
        "status": "running",
        "restartPolicy": "always",
        "env": {
            "UpstreamProtocol": {
                "value": "Mqtt"
            },
            "OptimizeForPerformance": {
                "value": true
            },
            "HttpSettings__Enabled": {
                "value": false
            },
            "AmqpSettings__Enabled": {
                "value": false
            },
            "CloudConnectionIdleTimeoutSecs": {
                "value": 86400
            },
            "ConfigRefreshFrequencySecs": {
                "value": 86400
            },
            "RuntimeLogLevel": {
                "value": "info"
            },
            "DeviceScopeCacheRefreshRateSecs": {
                "value": 86400
            },
            "MinTwinSyncPeriodSecs": {
                "value": 86400
            },
            "ConnectivityCheckFrequencySecs": {
                "value": 300
            }
        },
        "settings": {
            "image": "mcr.microsoft.com/azureiotedge-hub:DEFAULT_RT_IMAGE",
            "createOptions": {
                "HostConfig": {
                    "PortBindings": {
                        "5671/tcp": [
                            {
                                "HostPort": "5671"
                            }
                        ],
                        "8883/tcp": [
                            {
                                "HostPort": "8883"
                            }
                        ],
                        "443/tcp": [
                            {
                                "HostPort": "443"
                            }
                        ]
                    }
                }
            }
        }
    }
},
________________________________

**Comment by uriel-kluk** [comment] 2024-05-22 18:41
We opened a support ticket and we can close the current issue. Thanks

**Closed** 2024-05-22 22:40 UTC
