### ISSUE TITLE
Interruption of data receiving after 30 days after automatic server certificate renewal; The documentation for the installation of production certificates on a IoT Edge device is incomplete

### ISSUE THREAD

**Issue by draganrmijailovic** [Azure/iotedge#6044] opened 2022-01-26 08:29 UTC
## Expected Behavior
Messages are received without any interruptions after the installation of production certificates on the IoT Edge device. 

After reading the article https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=windows I should install the production certificates on an IoT Edge device.

## Current Behavior
Messages are received without any interruptions for 30 days. Then automatic server certificate renewal is performed and the error happens and messages can't be received after that. The IoT Edge service must be restarted for the messages to be received for the next 30 days.

**That is why I want to install production certificates on the IoT Edge device but the documentation is incomplete.** There is no explanation for how I can get the three files if I have one standard .cer and one standard .pfx file. Otherwise, I used them for other things not related to IoT Edge.

The article contains the following:

> You should use your own certificate authority to create the following files:
> 
> - Root CA
> - Device CA certificate
> - Device CA private key

**But there is no description of how to get those three files.** There is a description of how test certificates can be created but they are temporary. I should install production certificates. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. The IoT Edge device is set up for receiving messages
2. Messages are received for 30 days without any interruptions
3. After 30 days messages can't be received due to the error that happens after automatic server certificate renewal. The logs are attached.
4. The IoT Edge service must be restarted and messages are received again for the next 30 days
5. I decide to install production certificates due to the previous error
6. But, I can't install the production certificates because (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=windows) does not describe how the three files are created. I have standard the .cer and . pfx file.

### Output of `iotedge check`
[iotedge check.txt](https://github.com/Azure/iotedge/files/7939959/iotedge.check.txt)

### Device Information
* Ubuntu 18.04
* amd64
* Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.4
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

## Logs

[edgeAgent - Logs.txt](https://github.com/Azure/iotedge/files/7939958/edgeAgent.-.Logs.txt)

**Comment by scb01** [comment] 2022-01-27 20:42
@draganrmijailovic 

Glad that you are looking into installing production certificates, as that is recommended path. 

The process to get production certificates depends on the commercial PKI management provider you use. We don't have any specific preferences on providers, so the documentation mentions that you need to work with your certificate authority and leaves it at that.

**Comment by draganrmijailovic** [comment] 2022-01-27 23:09
@scb01

Thanks for your answer. I have two files from my commercial PKI management provider: one .cer file and one .pfx file. Otherwise, I used them for SAML SSO and communication between the Identity Provider (it contains .pfx - private key) and Service Providers (they contain .cer file). I just know the basics about private and public keys.

Your document (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=windows) mentions the three files:
Device CA certificate: <WRKDIR>\certs\iot-edge-device-MyEdgeDeviceCA-full-chain.cert.pem
Device CA private key: <WRKDIR>\private\iot-edge-device-MyEdgeDeviceCA.key.pem
Root CA: <WRKDIR>\certs\azure-iot-test-only.root.ca.cert.pem

**Should my commercial PKI management provider send me the three files with these extensions? What should I ask of them?**

And your document contains 3 paths to be set in the '/etc/aziot/config.toml' file - It is clear. You have specified which paths to set, it is OK.  But, I don't know how to get to the right files.

**Comment by windnfc** [comment] 2022-01-28 13:49
@scb01 @draganrmijailovic 
Hi, I think this is the same issue I reported under issue #6008. It's not caused by the three certificates: 

>     Root CA
>     Device CA certificate
>     Device CA private key

**Comment by draganrmijailovic** [comment] 2022-01-28 15:39
@scb01  
Thanks, @windnfc for your answer. You are right, I have the same issue. Data interruption for my Linux IoT Edge device happened twice after 30 days. The error was the same in both cases.
That is why I want to install production certificates.

**Comment by arsing** [comment] 2022-01-28 19:29
>I just know the basics about private and public keys.

There is a public component and a private component. The public component is the "certificate". The private component is the "private key".

The certificate can be encoded in a binary representation called DER, or a textual representation called PEM that is `-----BEGIN CERTIFICATE-----` + base64-encoded DER + `-----END CERTIFICATE-----`.

The private key can be encoded in a binary representation called DER, or a textual representation called PEM that is `-----BEGIN PRIVATE KEY-----` + base64-encoded DER + `-----END PRIVATE KEY-----`

Because PEM is clearly delineated, it is also possible to construct a PEM that contains both the `CERTIFICATE` and `PRIVATE KEY` one after the other in the same file.

Lastly, the certificate and private key can be encoded together in another binary representation called PKCS#12, that is encrypted with an optional password.

File extensions are completely arbitrary and one needs to run `file` on the file / open it to check, but in general:

- `.cer` is probably a certificate in DER or PEM form.

- `.pem` is probably a certificate or private key or both in PEM form.

- `.pfx` is probably a PKCS#12 file.

So:

1. If you have a `.pfx` from your PKI provider, that is likely the certificate + private key they issued you. Double-check with `file` that it's a PKCS#12 file.

1. IoT Edge needs the certificate and private key to be a) in PEM format each, and b) in separate files. You can convert your PKCS#12 file to that with `openssl pkcs12` command. The two PEMs you get from this are your `edge_ca.cert` and `edge_ca.pk` files in your config.toml

1. The `.cer` may contain the same certificate as what they gave you in the `.pfx`. Or it might be the PKI provider's issuing certificate. Inspect it with `openssl x509` command to figure out which one it is. If it's the latter, then a) convert it to PEM with the `openssl x509` command, and b) use that as the `trust_bundle_cert` file in your config.toml.

**Comment by draganrmijailovic** [comment] 2022-01-29 20:16
@scb01 @windnfc 

Thanks, @arsing for the excellent explanation. That part is missing in the document :)

I did everything as you wrote except setting file paths in the config.toml file. The three files are prepared.

Now, I would change the three file paths in the config.toml file but my config.toml file does not contain the trust_bundle_cert parameter and the [edge_ca] section. Should I add them? I attached config.toml file and config.toml.edge.template file that contains the missing parameter and the missing section. **They have many different sections as they have different structures. Maybe I am wrong.** Both files are attached.
[config.toml.edge.zip](https://github.com/Azure/iotedge/files/7964533/config.toml.edge.zip)

**Comment by draganrmijailovic** [comment] 2022-01-29 22:21
@scb01 @windnfc 

@arsing There is another template file in the /etc/aziot - config.toml.template I attached it. I should change config.toml based on the article. It was attached to the previous po
[config.toml-template.zip](https://github.com/Azure/iotedge/files/7964878/config.toml-template.zip)
![etc-aziot-folder-structure](https://user-images.githubusercontent.com/28098446/151679394-42b2b21b-b4c8-4990-97e4-5d5cd25bbda5.jpg)

**Comment by arsing** [comment] 2022-02-02 04:00
For IoT Edge users, `config.toml.edge.template` is the relevant file. The `config.toml.template` file is for people using the `aziot-identity-service` package directly instead of through `aziot-edge`.

The contents of that file will be identical to [this file.](https://github.com/Azure/iotedge/blob/release/1.2/edgelet/contrib/config/linux/template.toml#L295-L299)

https://github.com/Azure/iotedge/blob/release/1.2/edgelet/contrib/config/linux/template.toml#L295-L299 is the `[edge_ca]` section.

https://github.com/Azure/iotedge/blob/release/1.2/edgelet/contrib/config/linux/template.toml#L28 is the `trust_bundle_cert` line.

**Comment by draganrmijailovic** [comment] 2022-02-02 13:40
@arsing 
Thanks for your answer. 

I created the IoT Edge device via the Azure portal. I guess that after creating the IoT Edge device the config.toml file was created. But, how should I apply config.toml.edge.template file? Should I start the process or should I change the current config.toml manually (which lines should I uncomment?)? I propose, in the end there should only one config.toml file. Templates files help us to create a concrete config file.

**Comment by arsing** [comment] 2022-02-02 18:21
>I guess that after creating the IoT Edge device the config.toml file was created.

No. You created the `config.toml` yourself, either by copying one of the `.template` files, or by running `iotedge config import` to import the config from 1.1 into the config.toml format, or by running `iotedge config mp` which creates a minimal config with just the provisioning section configured for manual provisioning that can then be edited to add more sections from the template as required. The config.toml does not automatically get created by anything, certainly not creating a device in a portal.

>1. But, how should I apply configuration from config.toml.edge.template file?

Copy-paste into your existing config.toml. Or copy the .template into a new config.toml and copy-paste whatever you want from the one you already have.

>2. Should I start a process for automatic creating config file that uses config.toml.edge.template or should I change the current config.toml manually

Whatever you want.

>which lines should I uncomment?

The ones that correspond to settings you want to override, or that the comments tell you are required to be specified (like `[provisioning]`).

>4. What should be the name of this file: config.toml.edge or config.toml?

Whatever you want. The path `/etc/aziot/config.toml` is only a suggested default. The file's only purpose is to be used with `iotedge config apply`, which allows you to specify any path you want.

---

We have documentation for creating a config.toml from scratch at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-x509?view=iotedge-2020-11&tabs=individual-enrollment%2Cubuntu#provision-the-device-with-its-cloud-identity . You may not have seen it if you followed the alternate tutorial for manual provisioning, since that one tells you to run `iotedge config mp` as a shortcut and doesn't go through the details of manually creating the config.toml.

**Comment by draganrmijailovic** [comment] 2022-02-03 20:01
Thanks, @arsing for the answer and the link.

I did not run _iotedge config import_ or i_otedge config mp commands. I only created the IoT Edge device based on the following link: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-single-device-linux-symmetric?view=iotedge-2020-11&tabs=azure-portal%2Cubuntu

I read your document https://docs.microsoft.com/en-us/azure/iot-edge/how-to-provision-devices-at-scale-linux-x509?view=iotedge-2020-11&tabs=individual-enrollment%2Cubuntu#provision-the-device-with-its-cloud-identity We don't have a device provisioning service and we only have one IoT Edge device on Ubuntu Virtual Machine that was created based on the first link.  But OK, in our config.toml file there is the provisioning section when a device provisioning service does not exist.

I'll try and report the result.

**Comment by draganrmijailovic** [comment] 2022-02-05 19:29
Hi @arsing 

I tried to install certificates based on your instructions:

- First I created three files based on your earlier post.
- I used config.toml.edge.template file and I uncommented only the provisioning section, the trust_bundle_cert parameter line, and the [edge_ca] section
- I have set permissions and owners for the three files
- But in the end, there is an error in the IoT Edge Hub module: Error calling CreateServerCertificateAsync: Could not get server cert caused by: internal error 
- I think files paths, permissions, and owners are right in according to the document. The files are attached.

**What is your opinion, what could I do to eliminate the error?** 

![Certificates files](https://user-images.githubusercontent.com/28098446/152655942-bd83aa44-08a4-4509-9331-0f0272c9c064.jpg)
![Iot Edge Hub - Error](https://user-images.githubusercontent.com/28098446/152655947-cb2cf742-0cfd-4be6-9f3e-dc18821e4985.jpg)
![IoT Edge Runtime Response](https://user-images.githubusercontent.com/28098446/152655952-fabf625b-ed23-4e5b-acee-950798ec8a32.jpg)
[iotedge check.txt](https://github.com/Azure/iotedge/files/8008740/iotedge.check.txt)
[config.toml.txt](https://github.com/Azure/iotedge/files/8008748/config.toml.txt)

**Comment by scb01** [comment] 2022-03-23 04:53
@draganrmijailovic For this issue, it is possible that the config may be messed up as you transitioned it from your previous setup to the certificate based setup. As mentioned [here]( https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?msclkid=35c0f678aa6411ecbb82f9860a57aa82&view=iotedge-2020-11&tabs=linux#configure-iot-edge-with-the-new-certificates), did you delete the files in directory as mentioned in step 5 and restart iotedge, which will cause the server certs to be recreated?

**Comment by draganrmijailovic** [comment] 2022-03-23 08:00
Thanks, @scb01 for your answer. There were some files in the /var/lib/aziot/certd/certs. I have deleted them and restarted IoT edge (the screenshot has been added). But, I got the same certification error from the screenshot above.
![certs is empty](https://user-images.githubusercontent.com/28098446/159651030-609a1b3e-6b00-4595-8405-b05e2460d22d.jpg)

**Comment by scb01** [comment] 2022-03-23 15:41
@draganrmijailovic Thanks for trying that out - I was thinking that this was a cert gen problem, which the restart would fix.  Could you grab a support bundle and attach it here so I can dive in deeper?

**Comment by draganrmijailovic** [comment] 2022-03-23 16:07
Hi @scb01 The support bundle has been attached for last 24h. Thanks.
[support_bundle.zip](https://github.com/Azure/iotedge/files/8334620/support_bundle.zip)

**Comment by scb01** [comment] 2022-03-24 03:17
Hello @draganrmijailovic Thanks for attaching the support bundle.
Just to get one more variable out of the way. Can you make sure that you have the 1.2 version of EdgeHub and EdgeAgent in your deployment? It will be great if you could share your deployment json.

**Comment by draganrmijailovic** [comment] 2022-03-24 07:39
Hello, @scb01 I attached deployment JSON from our project with all our modules. Currently, there are not any modules that are installed on the IoT Edge device. 

The deployment JSON contains the following: "image": "mcr.microsoft.com/azureiotedge-agent:1.2" for system modules. But, on the Azure portal, the situation is different or I am wrong. I attached the screenshot.

Otherwise, we use the Azure IoT Edge task for building and pushing the image based on the deployment JSON: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?msclkid=7b719c7fab4211ec8af35dcf43d866e7&view=azure-devops 

And I think the IoT Edge device worked properly before installing certificates (system modules were only installed).

[deployment.amd64.zip](https://github.com/Azure/iotedge/files/8339313/deployment.amd64.zip)
![Edge Agent](https://user-images.githubusercontent.com/28098446/159865171-f093ace5-ab98-4ea0-a8d5-898c8449d32d.jpg)
![IoT Edge device](https://user-images.githubusercontent.com/28098446/159865178-682eff30-2783-4088-adf8-0f326ba6e841.jpg)
![Edge Hub](https://user-images.githubusercontent.com/28098446/159865189-f11ec1de-c383-4689-8d9e-196f906d8d3d.jpg)

**Comment by draganrmijailovic** [comment] 2022-03-24 07:42
But yeah, we did not run our pipeline for installing the modules on the test IoT Edge. Our production IoT Edge device uses 1.2. The screenshot is attached:
![Production IoT Edge device - 1 2](https://user-images.githubusercontent.com/28098446/159866437-a427a61f-fd3f-4021-a3bd-4770c547d57d.jpg)

It seems that the test device for installing certificates uses 1.1. Should it be changed?

**Comment by draganrmijailovic** [comment] 2022-03-24 16:23
Hi, @scb01 I just changed it to 1.2 and restart the IoT Edge service. It is the same error as before the change. I attached the screenshots and the support bundle for the last hour.
[support_bundle.zip](https://github.com/Azure/iotedge/files/8343485/support_bundle.zip)
![Edge Hub - Error - Troubleshoot](https://user-images.githubusercontent.com/28098446/159962861-e1fc8e0e-c089-47f4-b31d-4208864e79f2.jpg)
![IoT Edge - Error](https://user-images.githubusercontent.com/28098446/159962879-347686e3-dcd8-464c-b887-5f18ce9502bb.jpg)
![Edge Hub - 1 2](https://user-images.githubusercontent.com/28098446/159962884-679d8cd2-12e6-4552-8431-bc5d989434b6.jpg)
![IotEdge Agent - 1 2](https://user-images.githubusercontent.com/28098446/159962892-7ae1b9be-9da9-4bd2-8076-aa21f1794c39.jpg)

**Comment by varunpuranik** [comment] 2022-03-24 19:09
@draganrmijailovic - 
Looks like your cert PEM files have pass phrase, because of which IoT Edge is not able to use it. Can you please generate certs with no pass phrase and try?

```
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [INFO] - <-- GET /keypair/aziot-edged-ca?api-version=2020-09-01 {}
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: Enter PEM pass phrase:
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [ERR!] - error:2807106B:UI routines:UI_process:processing error:../crypto/ui/ui_lib.c:543:while reading strings, error:0906406D:PEM routines:PEM_def_callback:problems getting password:../crypto/pem/pem_lib.c:59:, error:0907B068:PEM routines:PEM_read_bio_PrivateKey:bad password read:../crypto/pem/pem_pkey.c:64:
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [ERR!] - !!! internal error
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [ERR!] - !!! caused by: could not load key pair
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [ERR!] - !!! caused by: could not load key pair: AZIOT_KEYS_RC_ERR_EXTERNAL
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [INFO] - --> 500 {"content-type": "application/json"}
Mar 24 15:28:57 vmiotstaging aziot-keyd[1523]: 2022-03-24T15:28:57Z [INFO] - <-- GET /keypair/aziot-edged-ca?api-version=2020-09-01 {}
```
Alternatively, you can use the steps here to generate the certificates - 
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11#set-up-on-linux

**Comment by draganrmijailovic** [comment] 2022-03-25 21:58
Thanks @varunpuranik I will check the certificate files and I'll let you know the result.

**Comment by draganrmijailovic** [comment] 2022-03-29 21:56
Hi @varunpuranik, I repeated the process of creating the certificate and the private key in PEM format based on the earlier link https://www.ssl.com/how-to/export-certificates-private-key-from-pkcs12-file-with-openssl. 
It seems to me that the contents of the files were similar to before. Maybe I'm wrong. 
After that, I have set permissions and owners for the files as before. And after restarting the IoT Edge runtime the IoT Edge device works with no errors! The screenshots are attached. We will apply this solution to the production IoT Edge device.
The issue can be closed. Thanks! 
![IoT Edge Device - Status](https://user-images.githubusercontent.com/28098446/160713272-aa25e0ec-8a6f-4fb4-8204-1e1a48d71d35.jpg)
![IoT Edge Agent - Logs](https://user-images.githubusercontent.com/28098446/160713283-a422235f-892c-4ff9-983d-a6020850a99d.jpg)

**Comment by varunpuranik** [comment] 2022-03-29 22:14
@draganrmijailovic - thanks for confirming! 
I will close this issue.

**Closed by varunpuranik** 2022-03-29 22:14 UTC
Labels: question, iotedge, customer-reported

**Comment by jlian** [comment] 2022-04-19 23:47
@draganrmijailovic to help customers avoid this problem in the future, can you share how did you create the files to end up with the passphrases?

**Comment by draganrmijailovic** [comment] 2022-04-22 11:49
Hi, @jlian and @varunpuranik I apologize for the later reply. I used the link https://www.ssl.com/how-to/export-certificates-private-key-from-pkcs12-file-with-openssl and earlier post of your IoT Edge team. I could not give any additional advice.
After certificates installation, the states of the edgeHub and the edgeAgent modules were valid. There weren't any custom modules on the IoT Edge Device. Before I attached the screenshot.
But, after the installation of three custom modules by built-in Azure IoT Edge tasks (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-continuous-integration-continuous-deployment?view=iotedge-2020-11) in our Azure Pipeline the IoT Edge device and all its modules are invalid, even system modules - the edgeHub and the edgeAgent! The screenshot is attached. 
After calling "sudo iotedge config apply" command the following message is displayed:
Note: Symmetric key will be written to /var/secrets/aziot/keyd/device-id
Command failed: could not create /etc/aziot/certd/config.d/00-super.toml
Caused by:
    No such file or directory (os error 2)
The screenshot is attached.
I restarted the IoT Edge device several times but without any positive effect.
I guess that after installing modules by built-in Azure IoT Edge tasks previous settings were overridden or am I wrong? But config.toml and the certificates weren't changed, and I don't know why installing modules caused the IoT device to be in an invalid state.
A bundle of support files from your Azure IoT Edge for the last five hours is attached.
Note: There is the following in aziot-certd.txt:
Apr 22 05:00:07 vmiotstaging aziot-certd[12260]: 2022-04-22T05:00:07Z [ERR!] - could not read config
Apr 22 05:00:07 vmiotstaging aziot-certd[12260]: 2022-04-22T05:00:07Z [ERR!] - caused by: could not read config
Apr 22 05:00:07 vmiotstaging aziot-certd[12260]: 2022-04-22T05:00:07Z [ERR!] - caused by: missing field `homedir_path`

![IoT Edge Device - Invalid status](https://user-images.githubusercontent.com/28098446/164708373-d5757497-bc31-4513-9c76-64e0bd66422d.jpg)
![IoT Edge Config Apply command - Error](https://user-images.githubusercontent.com/28098446/164708571-8863ecf2-10df-4c38-a3bf-d64c60ba1f3b.jpg)
[support_bundle.zip](https://github.com/Azure/iotedge/files/8540654/support_bundle.zip)
