### ISSUE TITLE
Renaming a custom module

### ISSUE THREAD

**Issue by MaxThom** [Azure/iotedge#2944] opened 2020-05-11 16:38 UTC
## Expected Behavior
Delete old module, and replace with the new

I wanted to change the name of our custom module from **agent** to **telemetryAgent**.
Ive simply edited the deployment manifest and change the name under edgeAgent/modules.
I did a deployment with the updated manifest. Since then, no data is coming in. Upon checking the edgeHub logs, it seems the hub is trying to use the module agent instead of the new one. See errors below : 
 - Unable to find identity rpi4-dev/agent in device scopes cache or credentials cache
- Error cleating cloud connection for client rpi4-dev/agent

I restarted both module using : iotedge restart.
I also restarted runtime using : 
![image](https://user-images.githubusercontent.com/26239574/81587205-b6334180-9384-11ea-969b-9f34440ae3a4.png)

## Current Behavior
edgeHub is trying to use old module name to connect to iothub

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Renamed a moduleName in the device deployment
2. Deploy

## Context (Environment)
RPI4

### Output of `iotedge check`

DNS is configured at module level
<details>
<summary>Click here</summary>

![image](https://user-images.githubusercontent.com/26239574/81585417-242a3980-9382-11ea-9284-4495602470bc.png)

</details>

### Device Information
* Host OS :  Ubuntu
* Architecture : Arm64
* Container OS : Ubuntu

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.9
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.9
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.9
* Docker/Moby [run `docker version`]: 19.03.8

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs
<details>
<summary>edge-hub logs</summary>

![image](https://user-images.githubusercontent.com/26239574/81585696-85520d00-9382-11ea-89ba-3bc6c9e71ff9.png)

![image](https://user-images.githubusercontent.com/26239574/81585699-86833a00-9382-11ea-8b1a-e0d9c7c0cd69.png)

</details>

## Additional Information

<details>
<summary>Deployment manifest</summary>

>
![image](https://user-images.githubusercontent.com/26239574/81586363-63a55580-9383-11ea-9da4-bb80898c3f18.png)
 

</details>
 
<details>
<summary>Portal</summary>

>

 
![image](https://user-images.githubusercontent.com/26239574/81586859-34431880-9384-11ea-9c78-751fde5bfdcd.png)

![image](https://user-images.githubusercontent.com/26239574/81586874-3c02bd00-9384-11ea-89fb-c3af4c8313db.png)

</details>

**Comment by darobs** [comment] 2020-05-12 18:24
Hello @MaxThom,

My attempt to reproduce this with 1.0.9 did not get the same results. 

The deployment you show has "#buildid#" as the module tag, but should I assume this is replaced before sending the deployment?

Is it possible to see the edgeAgent logs as well?

**Comment by MaxThom** [comment] 2020-05-12 18:31
Hi,
so yes the buildid is replaced in our pipeline. Our pipeline create an image with the project, set the right id in the manifiest and than make a deployment.
So the problem is now fixed. I've simply manually deleted all containers (docker rm) and relaunched the iotedge.

**Comment by ebertrams** [comment] 2020-05-19 17:20
Great to hear that the problem is now fixed. @MaxThom , can we then close this issue? Thanks!

**Closed** 2020-05-19 17:37 UTC
