### ISSUE TITLE
Issue while running Custom Module in IoT Edge

### ISSUE THREAD

**Issue by kharsha345** [Azure/iotedge#4620] opened 2021-03-18 14:36 UTC
IoT Edge Agent and Hub are running in my machine. Now i had deployed a Custom Module called Motion_Detection following the steps in [Azure_Doc](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-vs-code-develop-module?view=iotedge-2018-06) and deployed the module.

When i publish some data from a Downstream device to the Edge, I can clearly see that the data is being received by the hub. But the data is not received to my custom module. 
Below are the logs of Motion_Detection module
```
ConnectOperation: completing with error None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091).  Setting timer.
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)

ConnectOperation: completing with error None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091).  Setting timer.
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)

```

These are the IP Address
Downstream Device ```192.168.0.104```
IoT Edge Device ```192.168.0.192```

Container IP's
Edge Hub  ```172.20.0.4```
Edge Agent ```172.20.0.2```
Registry ```172.20.0.2```
Motion_Detection ```172.20.0.3```
azure-iot-edge [Bridge] ```172.20.0.1```

Please help me with this, what am i missing?
Thanks, 
Harsha.

**Comment by dmolokanov** [comment] 2021-03-18 22:30
Hello @kharsha345 ! Could you please use a template to file an issue and provide all required information for us to identify root cause of the issue you have? It include OS and runtime versions, main components logs, etc..

Based on the description you provided I assume your module cannot establish TLS connection to the EdgeHub and certificate considered invalid.
> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.0.192'. (_ssl.c:1091)

It's really hard to say more without additional information. What certificates were used in your setup?

**Comment by dmolokanov** [comment] 2021-04-05 16:27
Closing the issues for now as non-responsive. Please feel free to re-open at any time in future.

**Closed by dmolokanov** 2021-04-05 16:27 UTC
Labels: customer-reported, iotedge
