### ISSUE TITLE
Azure IoT Edge Daemon failed to start

### ISSUE THREAD

**Issue by yashapatel786** [Azure/iotedge#940] opened 2019-03-11 09:57 UTC
I am trying to start IoT edge runtime on my Linux VM (16.04).
I am following documentation from [how-to-install-iot-edge-linux-64-bit](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux). But facing issues in starting IoT Edge daemon. 
Getting following logs after running command : journalctl -u iotedge --no-pager --no-full

**Logs :** 
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Starting Azure IoT Edge Security Daemon
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Using config file: /etc/iotedge/config.yaml
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Using runtime network id azure-iot-edge
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Initializing the module runtime...
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [INFO] - Initializing module runtime...
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] - Could not initialize module runtime
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] -         caused by: Container runtime error
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] -         caused by: an error occurred trying to connect: Connection refused (os error 111)
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] - Could not initialize module runtime
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] -         caused by: Container runtime error
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27334]: 2019-03-11T06:53:17Z [WARN] -         caused by: an error occurred trying to connect: Connection refused (os error 111)
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Unit entered failed state.
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Failed with result 'exit-code'.
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: Stopped Azure IoT Edge daemon.
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: Started Azure IoT Edge daemon.
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Starting Azure IoT Edge Security Daemon
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Using config file: /etc/iotedge/config.yaml
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Using runtime network id azure-iot-edge
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Initializing the module runtime...
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [INFO] - Initializing module runtime...
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] - Could not initialize module runtime
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] -         caused by: Container runtime error
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] -         caused by: an error occurred trying to connect: Connection refused (os error 111)
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] - Could not initialize module runtime
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] -         caused by: Container runtime error
Mar 11 06:53:17 VPCAZIN17-026 iotedged[27367]: 2019-03-11T06:53:17Z [WARN] -         caused by: an error occurred trying to connect: Connection refused (os error 111)
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Unit entered failed state.
Mar 11 06:53:17 VPCAZIN17-026 systemd[1]: iotedge.service: Failed with result 'exit-code'.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: Stopped Azure IoT Edge daemon.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: Started Azure IoT Edge daemon.
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Starting Azure IoT Edge Security Daemon
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Version - 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Using config file: /etc/iotedge/config.yaml
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Using runtime network id azure-iot-edge
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Initializing the module runtime...
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [INFO] - Initializing module runtime...
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [WARN] - Could not initialize module runtime
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [WARN] -         caused by: Container runtime error
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [WARN] -         caused by: an error occurred trying to connect: Connection refused (os error 111)
Mar 11 06:53:18 VPCAZIN17-026 iotedged[27403]: 2019-03-11T06:53:18Z [WARN] - Could not initialize module runtime
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Main process exited, code=exited, status=1/FAILURE
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Unit entered failed state.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Failed with result 'exit-code'.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Service hold-off time over, scheduling restart.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: Stopped Azure IoT Edge daemon.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: Dependency failed for Azure IoT Edge daemon.
Mar 11 06:53:18 VPCAZIN17-026 systemd[1]: iotedge.service: Job iotedge.service/start failed with result 'dependency'.

I have created device on IoT hub on azure cloud cli itself and copied connection string from there as well. @veyalla  @thorpebt  @myagley @MicahMcKittrick-MSFT @sergaz-msft

**Comment by myagley** [comment] 2019-03-11 16:04
Is Docker running on this device? `systemctl status docker`

**Comment by yashapatel786** [comment] 2019-03-12 04:28
> Is Docker running on this device? `systemctl status docker`

No Docker is not running .. it is showing inactive (dead). : 
docker.service - Docker Application Container Engine
Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
Active: inactive (dead) (Result: exit-code) since Mon 2019-03-11 06:53:17 UTC;
@myagley

**Comment by myagley** [comment] 2019-03-12 15:21
Docker not running is the root cause for why the daemon isn't starting. Is it possible to look at the docker logs to see why it failing? `journalctl -u docker`

**Comment by yashapatel786** [comment] 2019-03-13 04:38
Please look upon docker logs. I tried with starting docker service with `service start docker` but it is showing docker is unrecognized service.  

Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Stopped Docker Application Container Engine.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Starting Docker Application Container Engine...
Mar 12 09:17:50 VPCAZIN17-026 dockerd[25919]: failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Failed to start Docker Application Container Engine.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Unit entered failed state.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Stopped Docker Application Container Engine.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Starting Docker Application Container Engine...
Mar 12 09:17:50 VPCAZIN17-026 dockerd[25954]: failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: Failed to start Docker Application Container Engine.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Unit entered failed state.
Mar 12 09:17:50 VPCAZIN17-026 systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: Stopped Docker Application Container Engine.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: Starting Docker Application Container Engine...
Mar 12 09:17:51 VPCAZIN17-026 dockerd[25985]: failed to start daemon: pid file found, ensure docker is not running or delete /var/run/docker.pid
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: Failed to start Docker Application Container Engine.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Unit entered failed state.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: Stopped Docker Application Container Engine.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: docker.service: Start request repeated too quickly.
Mar 12 09:17:51 VPCAZIN17-026 systemd[1]: Failed to start Docker Application Container Engine.
@myagley

**Comment by yashapatel786** [comment] 2019-03-13 04:50
I restarted the docker service by removing the file `/var/run/docker.pid` and then restarted docker using `sudo service start docker`. 
Then I restarted IoTEdge using `sudo systemctl restart iotedge` and then checked with `systemctl status iotedge` and service is active now.  ( ` Edge runtime is running.` )
Thanks @myagley  for helping out. :) 👍

**Comment by myagley** [comment] 2019-03-13 15:26
Great! It sounds like you are unblocked. I am going to close this issue, but feel free to reopen if you have further questions.

**Closed by myagley** 2019-03-13 15:26 UTC

**Comment by akhtar927** [comment] 2019-05-30 12:29
Docker status: running
i am using Raspberry pi 3b+ (stretch)
My Iot Edge service failed to start giving me this error.

â iotedge.service - Azure IoT Edge daemon
   Loaded: loaded (/lib/systemd/system/iotedge.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Thu 2019-05-30 17:42:19 IST; 13min ago
     Docs: man:iotedged(8)
  Process: 5135 ExecStart=/usr/bin/iotedged -c /etc/iotedge/config.yaml (code=exited, status=
 Main PID: 5135 (code=exited, status=1/FAILURE)
      CPU: 254ms

May 30 17:42:18 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
May 30 17:42:19 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scheduli
May 30 17:42:19 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
May 30 17:42:19 raspberrypi systemd[1]: Dependency failed for Azure IoT Edge daemon.
May 30 17:42:19 raspberrypi systemd[1]: iotedge.service: Job iotedge.service/start failed wit



bt then i regenerated the key and modified the config file and restarted my Iot Edge service became active.



But when i ran `sudo journalctl -u iotedge --no-pager --no-full`  gives this error

May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Using config fâ¦yaml
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Starting Azureâ¦emon
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Version - 1.0.â¦9f3)
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Using runtime â¦edge
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Initializing tâ¦e...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Initializing mâ¦e...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Successfully iâ¦time
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Finished initiâ¦ime.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Configuring /vâ¦ory.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Configuring ceâ¦s...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Transparent gaâ¦e...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Finished confiâ¦tes.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Initializing hsm...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Finished initiâ¦hsm.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Detecting if câ¦d...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - No change to câ¦ted.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Obtaining workâ¦ded.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Provisioning eâ¦e...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Manually proviâ¦net"
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Finished proviâ¦ice.
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Starting managâ¦I...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Starting worklâ¦I...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Starting watchâ¦y...
May 30 17:42:18 raspberrypi iotedged[5135]: 2019-05-30T12:12:18Z [INFO] - Listening on uâ¦API.
May 30 17:42:18 raspberrypi systemd[1]: iotedge.service: Main process exited, code=exitâ¦ILURE
May 30 17:42:18 raspberrypi systemd[1]: iotedge.service: Unit entered failed state.
May 30 17:42:18 raspberrypi systemd[1]: iotedge.service: Failed with result 'exit-code'.
May 30 17:42:19 raspberrypi systemd[1]: iotedge.service: Service hold-off time over, scâ¦tart.
May 30 17:42:19 raspberrypi systemd[1]: Stopped Azure IoT Edge daemon.
May 30 17:42:19 raspberrypi systemd[1]: Dependency failed for Azure IoT Edge daemon.
May 30 17:42:19 raspberrypi systemd[1]: iotedge.service: Job iotedge.service/start failâ¦ncy'


and when i run this again  `sudo systemctl status iotedge`  it gives the same error. 
Help Please.

**Comment by sanmoy** [comment] 2020-09-01 20:55
I also have the same issue.

Docker is running, but iotedge has failed to start
