### ISSUE TITLE
Automatic renewal of IoT Edge Hub Server Certificate failed

### ISSUE THREAD

**Issue by windnfc** [Azure/iotedge#6008] opened 2022-01-18 07:58 UTC
## Expected Behavior
Edgehub module automatically renew the IoT Edge Hub Server Certificate without any influence on the other modules

## Current Behavior
The whole system has been working correctly for one month till the scheduled date for renewal of the IoT Edge Hub Server Certificate. Edgehub module tried to renew the IoT Edge Hub Server Certificate, which caused all other modules got disconnected. Even after several hours it is still the same state. The system is working again after a manual restart of the edgeHub module.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Wait until the scheduled date for renewal of the IoT Edge Hub Server Certificate
2. See that other modules get disconnected.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04.5 LTS
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
IoT Edge daemon version: 1.2.5
Docker daemon version: 20.10.11+azure-1
edgeHub version: 1.2.6
edgeAgent version: 1.2.6

### Details
There are four certificate types used in IoT Edge 1.2 according to this document: [https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs?view=iotedge-2020-11#example-of-iot-edge-certificate-hierarchy](url)
- Root CA Certificate
- Intermediate CA Certificate
- Device CA Certificate ( in 1.2 it is renamed to Edge CA Certificate)
- IoT Edge Hub Server Certificate

With the script Microsoft provided we can generate the first three certificates without problem. The last one,  IoT Edge Hub Server Certificate, is an auto-generated one. Its expiration date can be seen in the edgeHub module log, when the edgeHub module starts. Like this:
![edgehub_log](https://user-images.githubusercontent.com/16647375/149894247-94b38498-76a3-4b2e-bdcb-3ebfd0434a88.png)

According to [https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=linux#customize-certificate-lifetime](url), 
> There is a third auto-generated certificate that the IoT Edge security manager creates, the IoT Edge hub server certificate. This certificate always has a 90 day lifetime, but is automatically renewed before expiring. The auto-generated CA lifetime value set in the config file doesn't affect this certificate. 

There are two issues with the IoT Edge Hub Server Certificate:
1. the above documentation said it always has a 90 day lifetime, but the log shows that it only has 30 days. 
2. The automatic renewal process did not work correctly. I have two test stations, at the expiration date I observed the status, all edge modules got disconnected and after several hours the connection has not been reestablished. Only after I manually restarted the edgeHub module, which regenerated the Edge Hub Server Certificate, all modules worked correctly again.
My both test stations experienced the same problem. It is a bit difficult to find the issue, as whenever you restarted the edgeHub module, the Edge Hub Server Certificate will be regenerated and the life time will be a new month from that time.

The edge device was started on 08/12/2021. The Edge CA certificate is valid till 07/18/2061. The information about the Edge Hub Server Certificate as stated in the log:

> <6> 2021-12-08 13:33:16.614 +00:00 [INF] - Loaded server certificate with expiration date of "2022-01-07T13:33:13.0000000+00:00"
> <6> 2021-12-08 13:33:17.718 +00:00 [INF] - Scheduling server certificate renewal for "2022-01-07T13:30:43.0002606Z".

[edge0005_$edgeHub_Logs_20211208.txt](https://github.com/Azure/iotedge/files/7870614/edge0005_.edgeHub_Logs_20211208.txt)
It is obvious, that the Edge Hub Server Certificate is only valid for one month.

There were no restarts of the edgeHub module till 07/01/2022. Then on 07/01/2022, it can be seen in the log of edgeHub, that the renewal process did start at the planned renewal time.

> <6> 2022-01-07 13:30:43.000 +00:00 [INF] - Restarting process to perform server certificate renewal.

Afterwards, all edge modules got disconnected. Two custom modules, one module "IoTEdgeMetricsCollector" from Microsoft and the edgeAgent. At 14:45, these modules were still disconnected, then I restarted the edgeHub module and all mdoules began to work correctly again. This means, the regeneration of the Edge Hub Server Certificate at every start of the edgeHub module solved the issue, which leads to the assumption that the issue is likely in the scheduled renewal process. 
[edge0005_$edgeAgent_Logs_20220107.txt](https://github.com/Azure/iotedge/files/7870653/edge0005_.edgeAgent_Logs_20220107.txt)
[edge0005_$edgeHub_Logs_20220107.txt](https://github.com/Azure/iotedge/files/7870655/edge0005_.edgeHub_Logs_20220107.txt)
[edge0005_BatchSendingModule_Logs_20220107.txt](https://github.com/Azure/iotedge/files/7870656/edge0005_BatchSendingModule_Logs_20220107.txt)
[edge0005_IoTEdgeMetricsCollector_Logs_20220107.txt](https://github.com/Azure/iotedge/files/7870657/edge0005_IoTEdgeMetricsCollector_Logs_20220107.txt)

**Comment by ancaantochi** [comment] 2022-01-19 21:52
Thanks for reporting the issue.
There seem to be 2 problems: 
1. certificate lifetime doesn't match docs, I will look into updating the docs to match the certificate lifetime.
2. Renewal leaves edgeHub in an inconsistent state and requires manual restart. Did you reproduce this multiple times or it just happened once? I will try to reproduce it and let you know what I find.

**Comment by windnfc** [comment] 2022-01-20 07:22
Hi ancaantochi, Thanks for the reply.

I observed two test stations at the expiration day. Both showed the same behavior. My other test stations still need some days till the expiration day. I don't know how to reduce the period, as the Edge Hub Server Certificate is automatically generated and 30 days valid. If you have some tricks to reduce that, I'll be happy to test it on my other test stations.

**Comment by ancaantochi** [comment] 2022-01-24 23:12
Server certificate expiry period can't be configured. I will try to reproduce it and investigate the cause. 
Can you please share logs from both stations that run into the issue?

Thanks!

**Comment by windnfc** [comment] 2022-01-25 10:50
Teststation edge0005: 2022-01-07 13:30:43 server certificate renewal
Teststation edge0001: 2022-01-08 09:35:11 server certificate renewal
[support-bundle-edge0005.zip](https://github.com/Azure/iotedge/files/7932863/support-bundle-edge0005.zip)
[support-bundle-edge0001.zip](https://github.com/Azure/iotedge/files/7932868/support-bundle-edge0001.zip)

**Comment by ancaantochi** [comment] 2022-01-25 18:12
Thanks for support-bundle, we are investigating this issues and will update here once I have more details.

**Comment by ancaantochi** [comment] 2022-01-26 01:19
@windnfc  
Please note that support bundle contains iothub name and modules logs that you might not want expose, please remove any sensitive data or you can remove completely support-bundles.

We are able to reproduce this issue and investigating the cause.

**Comment by ancaantochi** [comment] 2022-03-01 18:18
Issue was fixed in edgeHub 1.2.8

**Comment by ancaantochi** [comment] 2022-03-11 17:38
1.1.11 was released and has the fix as well

**Closed by ancaantochi** 2022-03-11 17:38 UTC
Labels: bug, iotedge, customer-reported, 1.1, 1.2

**Comment by malavvvakharia** [comment] 2026-02-18 10:58
I am facing a related issue due to this: https://github.com/Azure/iotedge/issues/7497
