### ISSUE TITLE
Transparent Gateway GatewayHostName

### ISSUE THREAD

**Issue by Ilheu** [Azure/iotedge#992] opened 2019-03-22 19:04 UTC
Hi,
I'm trying to configure my Iot Edge device into a transparent gateway without success, following this tutorial : https://docs.microsoft.com/pt-pt/azure/iot-edge/how-to-create-transparent-gateway;

I am confused in which GatewayHostName should I use, it can be anything I want ? It is my device IP ? It is the hostname variable in config.yaml file ? In every post I read different things, but nothing is really working ...

**Comment by mrohera** [comment] 2019-03-24 19:12
Sorry that things were not quite clear for you. We have tailored the scripts to be a bit more resilient such that users can add any name. I personally like the choice of making it the hostname you put in the config.yaml, this way you know it is that device's CA certificate. If you create the Edge device's CA certificate, using your hostname, it will have CN "<your hostname>.ca". Note the '.ca' at the end. This Edge device CA certificate will generate a server certificate using the hostname you set in the config.yaml. More about certificates can be seen here: https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs

Now to address the real problem, can you please elaborate what is not working?

**Comment by Ilheu** [comment] 2019-03-25 15:45
**Thank you for the answer ! I'm trying to connect a downstream device to an edge device without SDK through MQTT.I used the hostname  in GatewayHostName, which was "muvugateway". But When I use the command :** 

sudo openssl s_client -connect muvugateway:8883 -CAfile /home/muvu-tech/Desktop/certs/azure-iot-test-only.root.ca.cert.pem

**I receive the following answer:** 

140431539151296:error:20087002:BIO routines:BIO_lookup:system lib:../crypto/bio/b_addr.c:693:Name or service not known

connect:errno=2

**But if I change the hostname in the command by the device IP :** 

sudo openssl s_client -connect "IP":8883 -CAfile /home/muvu-tech/Desktop/certs/azure-iot-test-only.root.ca.cert.pem 

I get : 
CONNECTED(00000003)

depth=4 CN = Azure IoT Hub CA Cert Test Only

verify return:1

depth=3 CN = Azure IoT Hub Intermediate Cert Test Only

verify return:1

depth=2 CN = "<gatewaymuvu>.ca"

verify return:1

depth=1 CN = iotedged workload ca

verify return:1

depth=0 CN = gatewaymuvu

verify return:1

---

Certificate chain

 0 s:/CN=gatewaymuvu

   i:/CN=iotedged workload ca

 1 s:/CN=Azure IoT Hub Intermediate Cert Test Only

   i:/CN=Azure IoT Hub CA Cert Test Only

 2 s:/CN=<gatewaymuvu>.ca

   i:/CN=Azure IoT Hub Intermediate Cert Test Only

 3 s:/CN=iotedged workload ca

   i:/CN=<gatewaymuvu>.ca

---

Server certificate

-----BEGIN CERTIFICATE-----

MIIEbzCCAlegAwIBAgIELo3YAzANBgkqhkiG9w0BAQsFADAfMR0wGwYDVQQDDBRp

b3RlZGdlZCB3b3JrbG9hZCBjYTAeFw0xOTAzMjUxNTE2MDFaFw0xOTA0MjAxNjM2

MThaMBYxFDASBgNVBAMMC2dhdGV3YXltdXZ1MIIBIjANBgkqhkiG9w0BAQEFAAOC

AQ8AMIIBCgKCAQEA0UsY9sGmJnUEa5Db0jChIxXvrF0jYQsJ+pmbecuKNPniqcLZ

1bxsh/ieXrsGcjZIs7uQiqHfv++ITN19WR/dwGC12Qoff5Krp7VYulA6zUSL9tG5

/n7UB043EPc0iAivftH3Z4uzv4m5sDFWkEVmYIEMI5/QSVwEf5DkCLZmMZGYCdgq

Mm3PiUF9FTJcf9VUz/UsgnYAmO1zx8tF8Fd57nazjPNJm85ws7MXQlwwhbFUU5VX

UnEAHCnefhOdKDnUEzAFkEjE4BiLvSBZAK3F3CCofFqK7OaopmoS7EcstBwYPl1O

aUygj7hYvGQKk4naBxtl+F906BLSjInkPekkJwIDAQABo4G7MIG4MAkGA1UdEwQC

MAAwDgYDVR0PAQH/BAQDAgP4MBMGA1UdJQQMMAoGCCsGAQUFBwMBMB8GA1UdEQQY

MBaCC2dhdGV3YXltdXZ1ggdlZGdlaHViMB0GA1UdDgQWBBR7VcKfV8K+7RY+I/B4

f/YceTl7oDBGBgNVHSMEPzA9gBTVNQhTsLsD1/wb0gkllucG9gB1CKEfpB0wGzEZ

MBcGA1UEAwwQPGdhdGV3YXltdXZ1Pi5jYYIEeN7WZTANBgkqhkiG9w0BAQsFAAOC

AgEAM2vTsj2wnCLlle5xuzIixM/Xpg9VdybjZ0Z4ZNBjYz037qZKs3nsgu+SkZo8

J5i5jMfu+DE8h8cAzH9Z29R0z4cTXtne53U7pXISCF2xkoi24+9kqg53rSBh6C6l

m1rAgL2MsxKr+HKHYBdeAqMn9lczmcFA6YoQ34AnM0knIEjoZEFKiu/LRmCma69k

aF9h3pdFJrv3R5wc7nJdIVgmZf0mq9rnbjPr62SiejPeuYDh/AAeRJT4OMuEOw5O

7NUhadhsc7nRA0z07PY+KvHhItpzb9UWHuMo1B+617NRuKLPpcl2Tyrk03dH9vHm

R/JfgKQ/KaqjVQXjPbZvc6BE24VlSE17+wXFbDfSSP1LaegmSajZPtcspflsJ6hQ

yhH7XnA1CufZn3Osfm2ylHgxMsMnipyQyDalQd39GbXNP0mBDEl9sV2dl24qBvmi

GoI3eM3bONdFRSSUyqpoJaNpd5R8uj5eRDHR0KcBcEW/1wPVv1yIt2uqSzrCFH0V

03vyMhc6WGUoyPHRpix7sgTFMmhLVwzxR4tQi4T5KaSQQ4L+UyKfsPkg1AnHprUw

YOckR17PIsV3w4Wooj5SjiDWMT8EwF4WbrQI3aKaVVWLdSdhiWXIzFBRkgeOf1w5

gd4RAucygR/SloFOM/JctGXvJbLGvaO6OrRGIbLKKRUyOh4=

-----END CERTIFICATE-----

subject=/CN=gatewaymuvu

issuer=/CN=iotedged workload ca

---

No client certificate CA names sent

Client Certificate Types: RSA sign, DSA sign, ECDSA sign

Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1

Shared Requested Signature Algorithms: RSA+SHA512:DSA+SHA512:ECDSA+SHA512:RSA+SHA384:DSA+SHA384:ECDSA+SHA384:RSA+SHA256:DSA+SHA256:ECDSA+SHA256:RSA+SHA224:DSA+SHA224:ECDSA+SHA224:RSA+SHA1:DSA+SHA1:ECDSA+SHA1

Peer signing digest: SHA512

Server Temp Key: ECDH, P-256, 256 bits

---

SSL handshake has read 5894 bytes and written 314 bytes

Verification: OK

---

New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384

Server public key is 2048 bit

Secure Renegotiation IS supported

Compression: NONE

Expansion: NONE

No ALPN negotiated

SSL-Session:

    Protocol  : TLSv1.2

    Cipher    : ECDHE-RSA-AES256-GCM-SHA384

    Session-ID: 2E3B1A159FE93E4EE3E9C82B57447F808B146ED4C60E85CB39BD06D070E25FDE

    Session-ID-ctx:

    Master-Key: 34E77725ED8A0A10A501BCC2EBC4B2DBB3F4D8659A280E3D320FA7E98E55B12DC9EC16D44827AED8A300B9918E980FAE

    PSK identity: None

    PSK identity hint: None

    SRP username: None

    TLS session ticket lifetime hint: 300 (seconds)

    TLS session ticket:

    0000 - 1b e8 f3 5a e5 7b ca a4-86 f3 11 be 55 68 a5 f3   ...Z.{......Uh..

    0010 - a9 f4 d7 b3 3e 95 17 bc-ad 98 3f e3 54 a7 9e 43   ....>.....?.T..C

    0020 - 65 93 94 4b eb 8b db 39-a5 03 c8 a3 b8 3a e9 8c   e..K...9.....:..

    0030 - de 77 e1 75 34 17 83 05-51 7b d7 39 b7 2d ef 08   .w.u4...Q{.9.-..

    0040 - 7b 1c 0e 6b b1 cc 2a d9-07 2a a7 dc 9e 54 8d fe   {..k..*..*...T..

    0050 - 0d 7a f1 6a ca 9f 39 4e-54 3b fd 52 fc 4e c2 2a   .z.j..9NT;.R.N.*

    0060 - a3 57 fb 7c 6d 6a 2e 2e-d2 90 66 cf 1b cc 5f f1   .W.|mj....f..._.

    0070 - ac 7f 50 2b 86 dc d4 89-43 76 e2 7c 25 6a 97 24   ..P+....Cv.|%j.$

    0080 - fa b5 e5 16 00 35 f6 1b-5a 92 54 fa c4 c5 6c 27   .....5..Z.T...l'

    0090 - bc 92 63 6e 08 84 cb 57-05 99 8c 0b 89 72 ec 48   ..cn...W.....r.H

    Start Time: 1553527378

    Timeout   : 7200 (sec)

    Verify return code: 0 (ok)

    Extended master secret: no


- **Is it supposed to used the IP ? If so, do I have to make my IP adress static ?!**
- **What parameters I need to connect a downstream device to an edge device through MQTT ?**

**Comment by myagley** [comment] 2019-03-25 16:48
Are you running `openssl s_client -connect muvugateway:8883 -CAfile /home/muvu-tech/Desktop/certs/azure-iot-test-only.root.ca.cert.pem` on a different machine than the gateway?

If this is the case, you will need to give that machine some way to resolve the IP address from the hostname. The quickest way to get this to work is to add an entry to your `/etc/hosts` file. Add this at the end of the file:

```
<your device's ip address>    muvugateway
```

You would replace the `<your device's ip address>` with the actual ip address of the gateway. You probably already have a `localhost` entry in this file that you can use as an example.

You don't necessarily need to make the IP address of the gateway static, but if the IP changes, you need to update the name resolution in `/etc/hosts`. We are looking at ways to make this easier in the future. It's a little tricky because it requires the runtime to start configuring hostname --> IP address resolution. There is no one size fits all solution to this problem.

**Comment by Ilheu** [comment] 2019-03-26 11:00
**So do my downstream devices need to know the edge device IP ? I'm not really understanding how to connect my downstream device to Edge.**

**I was communicating with Iot Hub through MQTT with this code :** 
 public void run() { 
        try {
            Thread.sleep(10000);
            MyMQTTClient Mqtt_c = new MyMQTTClient(DeviceName, "MuvuIoT.azure-devices.net");
            Mqtt_c.setOption("port", "8883");
            Mqtt_c.setOption("log", "1");
            Mqtt_c.setOption("keepalive", "300");
            Mqtt_c.setOption("TLSVERSION", "tlsv1.2");
            Mqtt_c.setOption("PROTOCOLVERSION", "3.1.1");       
            Mqtt_c.setOption("cafile", "/usr/" + "BaltimoreCyberTrustRoot.pem");
            Mqtt_c.setOption("CertFile", "/usr/flexy.crt");
            Mqtt_c.setOption("KeyFile", "/usr/flexy.key");
            Mqtt_c.setOption("Username", "HUBNAME.azure-devices.net/" + DeviceName + "/?api-version=2018-06-30");
            Mqtt_c.setOption("Password", "HostName=HUBNAME;DeviceID=" + DeviceName + ";x509=true"); 
            Mqtt_c.connect();

**How can I change it, so I can communicate with my Gateway transparent ?**

**Comment by Ilheu** [comment] 2019-03-27 09:19
@mrohera  and  @myagley can you answer me ? 
I am the only one in my department who has not yet given up on the Iot Edge  and consequently the Iot Hub... and I only lack this last step to finish the architecture ...

**Comment by myagley** [comment] 2019-03-27 16:00
**Root cause of the difficulty**
Yes, the leaf device ultimately needs to know the IP address of the edge device. The edge device is acting as a server and the client (the leaf device) needs the IP address to connect.

This isn't an issue when connecting to IoT Hub because the IoT Hub hostname is added to the public DNS. DNS lets the leaf device resolve the hostname to an IP address without any extra configuration.

In edge scenarios, the edge device is acting as a server (like IoT Hub) but its hostname is usually not registered in public DNS. There are several reasons for this: lack of a public domain name, cost, edge device is on a private network, etc. This means that there is nothing that will automatically translate the edge device's hostname to an IP address. So, there is some extra configuration required. Like I mentioned above, the simplest way to handle this is to update the `/etc/hosts` file to map the edge device hostname to an IP address.

So if you need to know the IP address, why bother with a hostname? Why not just connect with the IP address? The reason is TLS. The Edge Hub only serves using TLS, and in order for the client to validate the server during the TLS handshake, a hostname is required.

**How to make it work**
It looks like you are using Java. Have you tried using the [Azure IoT Java SDK](https://github.com/Azure/azure-iot-sdk-java)? This SDK handles a bunch of the difficulties with authentication, etc.  There is a [sample](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-event/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEvent.java) that shows how to connect to IoT Hub. This sample can be modified to connect IoT Edge.

There is a page in the documentation that discusses how to setup the leaf device: [Connect a downstream device](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device). At a high level, three things need to happen for the leaf device to connect. It should be noted that these three things are required for connecting to all gateways that serve TLS, not just IoT Edge:

1. Tell the device to connect to a gateway, instead of IoT Hub (by appending GatewayHostName to the connection string)
2. Enable the device to find the gateway IP address (by updating /etc/hosts on the leaf device)
3. Enable the device to trust the gateway (by installing the CA certificate used to sign the edge device's TLS certificate)

To get things working, I would suggest using the Java SDK and SAS tokens as the authentication method. Then, once you can connect, we can help with changing to certificate based authentication, which requires a couple of extra steps.

**Comment by Ilheu** [comment] 2019-03-27 16:14
Thank you @myagley ! My leaf device is a Flexi Ewon 205, unfortunately it can't run your SDK ... 
Can't you help me with an alternative way ? The code I showed in a post above connects to Iot Hub, how can I change it to connect with Edge ?

**Comment by veyalla** [comment] 2019-03-27 16:35
@Ilheu  - This [blog post](http://busbyland.com/connect-mqtt-client-to-azure-iot-edge/) from one of our Azure IoT Global Black Belts might help in your scenario.

**Comment by ancaantochi** [comment] 2019-05-08 03:33
Closing, please reopen if you still have this issue.

**Closed by ancaantochi** 2019-05-08 03:33 UTC

**Comment by davidzwa** [comment] 2020-01-10 16:49
> **Root cause of the difficulty**
> Yes, the leaf device ultimately needs to know the IP address of the edge device. The edge device is acting as a server and the client (the leaf device) needs the IP address to connect.

So I've been trying to setup Zeroconf and mDNS to dynamically resolve IP-addresses to services, which seems to fail in docker itself (multicast not passing to host). Could this be a first step in iotedge's daemon to work our way to setting up a hostname of the gateway?
For me having a gateway is not the primary focus, its about peer discovery in iotedge/docker-based systems, but if it can help both... would be awesome for this static gateway issue as well as device-to-device communication.

Our application is not entirely in line with edge-computing, I have to admit.
