### ISSUE TITLE
Layered deployment modules are not removed when deployment is no longer applied

### ISSUE THREAD

**Issue by mquilling** [Azure/iotedge#7057] opened 2023-06-29 18:52 UTC
## Expected Behavior
A layered deployment module should be removed if that deployed is no longer applied

## Current Behavior
The modules are not removed and stay running

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. create a layered deployed adding any module
2. apply that to the device via tags
3. wait for it to get deployed
4. remove tag from device
5. module is not removed

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
‼ production readiness: identity certificates expiry - Warning
    DPS identity 'device-id' will expire soon (2023-06-30 01:51:02 UTC, in 0 days)
‼ production readiness: EST identity and bootstrap certificates expiry - Warning
    x509 identity 'est-id' will expire soon (2023-06-30 01:51:00 UTC, in 0 days)
× preloaded certificates are valid - Error
     'est-bootstrap-id' expired at 2023-06-22 21:01:57 UTC
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
× ensure all preloaded certificates match preloaded private keys with the same ID - Error
    preloaded cert with ID "est-bootstrap-id" does not match preloaded private key with ID "est-bootstrap-id"

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
24 check(s) succeeded.
7 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS:  Debian GNU/Linux 11 (bullseye)
* Architecture: aarch64 
* Container OS:  Linux

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4.10
* Edge Hub [image tag (e.g. 1.0.0)]:  1.4.10
* Docker/Moby [run `docker version`]:  20.10.25+azure-2

**Comment by brotherneeru** [comment] 2023-07-27 18:44
We do not modify the content of the desired properties when you remove the configuration(we just stop applying or targeting the device). You probably need another deployment to undo your changes if needed.

**Comment by mquilling0** [comment] 2023-07-27 18:55
interesting - i would think the aggregated deployment would overwrite desired so the device is in sync with whats applied. 

are you saying whenever a module is added to a device via a deployment (layered or base) the ONLY way to remove it is to set it as null? this is essentially orphaning containers as they become unmanaged - this seems like a bug to me.

**Comment by jlian** [comment] 2023-08-04 18:53
In the original issue, the device is no longer targeted right, due to the tag removal on IoT Hub side? If that's the case, I believe the deployment doesn't reach the device and there's no way for IoT Edge to know they you want things to change.

> interesting - i would think the aggregated deployment would overwrite desired so the device is in sync with whats applied.
> 
> are you saying whenever a module is added to a device via a deployment (layered or base) the ONLY way to remove it is to set it as null? this is essentially orphaning containers as they become unmanaged - this seems like a bug to me.

No, I think this is different. If you remove the module config from the deployment manifest, I believe IoT Edge will remove it from the device - as long as the deployment actually reaches the device. The difference is leaving the device out of the deployment target or not

**Comment by mquilling0** [comment] 2023-08-07 20:01
The issue is:
1. target device with base deployment
2. add tag that applies layered deployment with new container
3. remove tag that applied layered deployment

Does 3 result in a device twin update and push down to the device?

**Comment by jlian** [comment] 2023-08-15 20:16
Oh I see what you're saying. In layered deployments the way to remove the module is to create a new deployment and set it to null. Removing the tag won't work. Is this a critical issue for you?

**Comment by mquilling0** [comment] 2023-08-15 21:00
Not really, but once we start to scale to thousands of devices it would be nice for this to be fixed. The expected behavior really should be the container is removed when the layered deployment is.

**Comment by jlian** [comment] 2023-08-29 18:17
I see. Such a fix would require a substantial change on IoT Hub side and is currently not planned, so I'm closing the issue to reflect it. If this is a critical issue, please comment below.

**Closed by jlian** 2023-08-29 18:17 UTC
Labels: iotedge, customer-reported

**Comment by ortogonal** [comment] 2024-12-31 07:04
> In layered deployments the way to remove the module is to create a new deployment and set it to null.

How do you actually do this?

Even if this is not a planned change from your side it would be nice it the documentation is updated about this.
