### ISSUE TITLE
Use another container engine

### ISSUE THREAD

**Issue by iAmoric** [Azure/iotedge#1433] opened 2019-07-11 09:57 UTC
Hi,

I would like to know if it's possible to install IoT Edge using another container engine, a different one from moby.
If yes, how can I do it?

Thanks

**Comment by myagley** [comment] 2019-07-11 16:32
The only supported container engine at the moment is the Moby engine that we provide.

What container engine are you looking at using? It's possible we can get it to work with some configuration changes.

**Comment by iAmoric** [comment] 2019-07-11 19:21
I would like to dockerize edge for run it on balenaOS with balena-engine instead of moby

**Comment by arsing** [comment] 2019-07-11 23:45
Duplicate of #1420 (which already has the answer to your question and in which you are already participating, so there's no reason to open a new issue.)

**Closed by arsing** 2019-07-11 23:45 UTC
