### ISSUE TITLE
iotedge for hardknott

### ISSUE THREAD

**Issue by embitude** [Azure/iotedge#5984] opened 2022-01-12 04:27 UTC
I have a yocto build for hardknott. However, it seems that the iotedge is not available for same. Is anybody able to port meta-iotedge for hardknott?

Any inputs would be of great help.

Regards,
Pradeep

**Comment by and-rewsmith** [comment] 2022-01-13 22:06
I can confirm, but I believe our approach is to only spend effort supporting the current LTS.
https://wiki.yoctoproject.org/wiki/Releases

Any reason you are using hardknott over dunfell?

**Comment by embitude** [comment] 2022-01-14 01:22
Actually, we are using the IMX8MN board and had some or the issues with dunfell bsp from NXP. However, everything is working fine with hardknott bsp. That's the whole reason we would like to use hardknott yocto release.

**Comment by and-rewsmith** [comment] 2022-01-15 00:31
Ah that's unfortunate. Since hardknott isn't an LTS and is only supported for another 2 more months, we aren't currently considering enhancements to `meta-iotedge` repo.

My recommendation would be to try to resolve the issues with dunfell.

**Comment by jlian** [comment] 2022-01-20 00:35
I'm closing this issue as adding support for hardknott isn't in our roadmap since support is ending soon.

**Closed by jlian** 2022-01-20 00:35 UTC
Labels: enhancement, area:packaging, area:tooling, iotedge, customer-reported
