### ISSUE TITLE
Azure - IoTEdge EFLOW NTP configuration/errors

### ISSUE THREAD

**Issue by sitaalbeMarp** [Azure/iotedge#6748] opened 2022-10-29 08:32 UTC
Dear all,
I've tried to configure chronyd to use a company owned NTP server.

Currently the command: "sudo iotedge check --verbose --ntp-server <server name>" gives the error message reported here:
https://learn.microsoft.com/en-us/answers/questions/1056524/azure-iotedge-eflow-ntp-configurationerrors.html

Same happens if you use pool.ntp.org ntp server.

I've restarted chronyd and iotedge service.
Also the DNS is ok. I have tested the name resolution of the NTP server and it is working.

Also the output of chronyc is fine regarding the time of the host.

Maybe this issue is related to a mis-configuration of EFLOW? Can you please give me a hint for checking NTP configuration in EFLOW?
Or can it be a problem of the check routine itself? In my case i do not have problem with timing and seems that chrony is working fine.

The version installed is: https://github.com/Azure/iotedge-eflow/releases/tag/1.1.2207.13102
on Windows Server 2019

Kind regards,
Alberto S.

**Comment by sitaalbeMarp** [comment] 2022-11-07 08:23
Dear all,
any news on this topic?

Thanks a lot for helping!
Alberto.

**Comment by fcabrera23** [comment] 2022-11-10 20:10
Hi @bishal41 @jlian,

Could you please take a look at this issue?

Thanks,
Francisco

**Comment by yophilav** [comment] 2022-11-17 22:42
@fcabrera23 
Thank you for your help :)

@sitaalbeMarp 
When in doubt, you can always append `--help` to the end of iotedge cli i.e. `iotedge check --help`. 
There you'll see there is an option 
```
   --ntp-server <NTP_SERVER>
            Sets the NTP server to use when checking host local time. [default: pool.ntp.org:123]
```

Please give that a try against your NTP server.

**Comment by sitaalbeMarp** [comment] 2022-11-18 06:30
Dear @yophilav ,
as shown in the above images in the thread, I've already tested the --ntp-server <NTP_SERVER> option but there is a socket error. 
Please see this (I have removed the proprietary url): https://github.com/Azure/iotedge/issues/6748#issuecomment-1297177789

I have configured chrony but it seems to me that the tool iotedge check is not able to communicate with the ntp server.

I am using the latest version of 1.1 LTS.

I am missing something? Probably can be a configuration issue, but I have followed this: https://github.com/Azure/iotedge/issues/6748#issuecomment-1297177783
and the problem is still present.

Chrony and "date" command inside CBL-Mariner are working fine.

Kind regards,
Alberto.

**Comment by sitaalbeMarp** [comment] 2022-12-14 14:28
Dear All, Dear @yophilav, @fcabrera23
any update on this issue?

I've updated to EFLOW 1.4 LTS (last version) and it is still present. 
I'm currently running IoTEdge 1.4.2 (daemon) with EdgeHub and EdgeAgent at version 1.4.4.

The command: "sudo iotedge check --verbose --ntp-server <corporate server FQDN> "
is still failing on using the corporate ntp server.

I've checked also the name resolution and DNS configuration on the runtime and on Docker engine, but the error is still present.

I have experienced this on Windows server 2019/2022.

Thank you for helping, I really appreciate!

Alberto S.

**Comment by lfitchett** [comment] 2023-01-13 23:01
@sitaalbeMarp Is the edge runtime itself also not working? Or is this just the check tool that fails?

**Comment by sitaalbeMarp** [comment] 2023-01-14 13:06
Dear @lfitchett ,
up to now, the edge runtime is working fine (both v.1.1 LTS and 1.4 LTS in EFLOW).
My idea is that the check tool has some kind of bugs that cause the problem.
I do not have time related issues with the container that are running on the edge node.

Thanks a lot for helping.

Kind Regards,
Alberto.

**Comment by lfitchett** [comment] 2023-01-17 21:40
@sitaalbeMarp Thanks for reporting this. I have filed a bug and it will go through our internal prioritization process. Once this has been fixed I'll update this thread. 

Since your setup is running correctly and the issue is with the diagnostic tool, I will go ahead and close this issue. If you have any further issues please open another issue.

**Closed by lfitchett** 2023-01-17 21:40 UTC
Labels: iotedge, customer-reported

**Comment by sitaalbeMarp** [comment] 2023-01-18 07:03
@lfitchett 
Thank you! When the new version will be available i will try it.

Kind Regards,
Alberto.
