### ISSUE TITLE
Error creating or updating the cloud proxy for client device

### ISSUE THREAD

**Issue by szymonprokopiuk** [Azure/iotedge#611] opened 2018-12-06 12:56 UTC
## Expected Behavior
EdgeHub should start normally.

## Current Behavior
EdgeHub cannot start.
Error in logs.

## Steps to Reproduce
1. Make clean installation of IoT Edge
2. Make clean deployment

### Device (Host) Operating System
raspbian stretch

### Architecture
arm32

## Logs
[logs](https://gist.github.com/szymonprokopiuk/ff87514ca7ba9315ebb8a5232be05acb)

**Comment by myagley** [comment] 2018-12-06 16:24
Hello. This error is normally caused by no internet connection between the Edge Hub and IoT Hub. You can verify this by running the following command on the device:

```
docker exec -it edgeHub curl https://<your iothub name>.azure-devices.net
```

This should return an HTTP response. (The response will be an error, but we just care about the connection).

We've also seen these exceptions when the device doesn't get a proper DNS server. This can sometimes be resolved by specifying a specific DNS server in `/etc/resolv.conf`. It also can be resolved by specifying a DNS server in the Docker Engine's config. 

For instance, update/create `/etc/docker/daemon.json` and add the following:
```json
{
    "dns": ["8.8.8.8"]
}
```
You should use the DNS server that makes sense for your networking environment. (`8.8.8.8` is Google's public DNS server, and is only an example)

You can learn more about networking in IoT Edge here: https://github.com/Azure/iotedge/blob/master/doc/networking.md

**Comment by szymonprokopiuk** [comment] 2018-12-07 07:15
First command return 
{"Message":"ErrorCode:InvalidProtocolVersion;BadRequest","ExceptionMessage" so there is connection.

Adding dns to daemon.json doesn't change anything.

Do you have any other options?

Thanks

**Comment by myagley** [comment] 2018-12-07 23:14
Is this consistently reproducible?

**Comment by myagley** [comment] 2019-01-02 17:12
I'm going to close this issue for now, but please feel free to reopen. Thanks!

**Closed by myagley** 2019-01-02 17:12 UTC
