### ISSUE TITLE
Device Twin shows connectionState disconnected, edgeAgent no direct methods, yet edgeHub responding to ping

### ISSUE THREAD

**Issue by robinmholt** [Azure/iotedge#6686] opened 2022-09-23 15:07 UTC
We had a failure detected yesterday where the IoTHub's device twin was indicating a connectionState of Disconnected.  We could not send a `ping` direct method to the edgeAgent, but could to the edgeHub as well as our module.  We were also receiving telemetry data from the device periodically as expected.

I ran a `docker exec -ti edgeAgent /bin/sh` and within that container, did a `netstat -ant`.  It showed the edgeAgent being connected to an external IP (20.x.y.z) port 443.  This was consistent with the other devices which were working that I compared to.

I ended up running a `docker stop edgeAgent`.  A short while later, the edgeAgent container was restarted and now it shows as connected.

edgeAgent is 1.1.14.  The container was created 3 months ago and the device has not been rebooted since.

edgeAgent logs from around this time:
```
<6> 2022-09-19 10:56:41.366 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 145.
<4> 2022-09-19 10:59:32.809 +00:00 [WRN] - Error getting edge agent twin from IoTHub
System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.TimeoutException: The operation has timed out.
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.RoundTripTwinMessage(AmqpTwinMessageType amqpTwinMessageType, TwinCollection reportedProperties, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Amqp.AmqpTransportHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass24_0.<<SendTwinGetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendTwinGetAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.InternalClient.GetTwinAsync()
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.ModuleClient.GetTwinAsync() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs:line 97
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<>c__DisplayClass40_0.<<GetTwinFromIoTHub>g__GetTwinFunc|0>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 351
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.GetTwinFromIoTHub(Boolean retrying) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 386
<6> 2022-09-19 10:59:32.820 +00:00 [INF] - Current module client closed. Initializing a new one
<6> 2022-09-19 10:59:32.820 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2022-09-19 11:00:34.610 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_WebSocket_Only...
<6> 2022-09-19 11:37:45.001 +00:00 [INF] - Uploading Metrics
<6> 2022-09-19 11:37:45.030 +00:00 [INF] - Published metrics
...
<6> 2022-09-22 18:01:58.312 +00:00 [INF] - Uploading Metrics
<6> 2022-09-22 18:01:58.334 +00:00 [INF] - Published metrics
2022-09-22 19:12:20  Starting Edge Agent
2022-09-22 19:12:20  Changing ownership of storage folder: /tmp/edgeAgent to 1000
2022-09-22 19:12:20  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
2022-09-22 19:12:20.478 +00:00 Edge Agent Main()
<6> 2022-09-22 19:12:21.219 +00:00 [INF] - Initializing Edge Agent.
<6> 2022-09-22 19:12:21.823 +00:00 [INF] - Version - 1.1.14.56054166 (96bc69739936234f858264a61ff838c5ccf4850e)
<6> 2022-09-22 19:12:21.824 +00:00 [INF] - 
        �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97> �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<95><97>   �<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97> �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>
       �<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<96><88>�<96><88>�<95><97>�<95><9A>�<95><90>�<95><90>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>�<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<95><94>�<95><90>�
<95><90>�<95><90>�<95><90>�<95><9D>
       �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<96><88>�<95><94>�<95><9D> �<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>
       �<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<96><88>�<96><88>�<95><91> �<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>  �<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><9D>
       �<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>�<95><9A>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>�<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�
<96><88>�<96><88>�<95><97>
       �<95><9A>�<95><90>�<95><9D>  �<95><9A>�<95><90>�<95><9D>�<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D> �<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D> �<95><9A>�<95><90>�<95><9D>  �<95><9A>�<95><90>�<95><9D>�<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>

 �<96><88>�<96><88>�<95><97> �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97> �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>    �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>  �
<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97> �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>
 �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><90>�<96><88>�<96><88>�<95><97>�<95><9A>�<95><90>�<95><90>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><9D>    �<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<96>
<88>�<96><88>�<95><97>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D> �<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>
 �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>       �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>  �<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�
<96><88>�<96><88>�<96><88>�<95><97>
 �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>       �<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><9D>  �<96><88>�<96><88>�<95><91>  �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><91>   �<96><88>�<96><88>�<95><91>�<96><88>�<96><88>�<95><94>�<95><90>�<95><90>�<95><9D>
 �<96><88>�<96><88>�<95><91>�<95><9A>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>   �<96><88>�<96><88>�<95><91>       �<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>�<95><9A>�<96><88>�<96><88>�
<96><88>�<96><88>�<96><88>�<96><88>�<95><94>�<95><9D>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<96><88>�<95><97>
 �<95><9A>�<95><90>�<95><9D> �<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>    �<95><9A>�<95><90>�<95><9D>       �<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>�<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>  �<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95>
<90>�<95><9D> �<95><9A>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><90>�<95><9D>

<6> 2022-09-22 19:12:21.980 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2022-09-22 19:12:22.437 +00:00 [INF] - Installing certificates [CN=Device_CA_SOLU220600001:06/20/2032 17:06:54] to Root
<6> 2022-09-22 19:12:22.798 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2022-09-22 19:12:23.268 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2022-09-22 19:12:23.285 +00:00 [INF] - Started operation Get system resources
<6> 2022-09-22 19:12:23.290 +00:00 [INF] - Collecting metadata metrics
<6> 2022-09-22 19:12:23.540 +00:00 [INF] - Set metadata metrics: 1.1.14.56054166 (96bc69739936234f858264a61ff838c5ccf4850e), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.1.15","Provisioning":{"Type":"dps.x509","DynamicReprovisioning":true},"ServerVersion":"20.10.18+azure-1","KernelVersion":"5.4.0-122-generic","OperatingSystem":"Ubuntu 20.04.5 LTS","NumCpus":4,"Virtualized":"no"}, True
<6> 2022-09-22 19:12:23.605 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2022-09-22 19:12:23.619 +00:00 [INF] - Started operation refresh twin config
<6> 2022-09-22 19:12:23.681 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2022-09-22 19:12:24.778 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2022-09-22 19:12:25.021 +00:00 [INF] - Started operation Metrics Scrape
<6> 2022-09-22 19:12:25.022 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2022-09-22 19:12:25.801 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2022-09-22 19:12:25.801 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2022-09-22 19:12:25.802 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2022-09-22 19:12:25.802 +00:00 [INF] - Registering request handler RestartModule
<6> 2022-09-22 19:12:27.074 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2022-09-22 19:12:27.371 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2022-09-22 19:12:27.581 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 145.
<6> 2022-09-22 19:12:28.828 +00:00 [INF] - Updated reported properties
<6> 2022-09-22 19:12:54.984 +00:00 [INF] - Received direct method call - ping
<6> 2022-09-22 19:12:54.990 +00:00 [INF] - Received request ping with payload
<6> 2022-09-22 19:12:55.001 +00:00 [INF] - Successfully handled request ping
<6> 2022-09-22 20:12:23.796 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 2 and reported properties version 146.

```

I will attach the full logs.

**Comment by robinmholt** [comment] 2022-09-23 15:08
[docker-logs-edgeAgent-2022-09-22-failure.log](https://github.com/Azure/iotedge/files/9634861/docker-logs-edgeAgent-2022-09-22-failure.log)

**Comment by jlian** [comment] 2022-09-23 18:06
Looks like it was just a transient network issue and it looks like edgeAgent was able to automatically recover (?)

I'm not sure if we'd be able to repro this given the transient nature. Has this happened again? When this happens is it a severe issue?

**Comment by robinmholt** [comment] 2022-09-23 18:19
It did not automatically recover.

I had to manually `docker stop edgeAgent` and let the iotedge.service restart the edgeAgent container to recover.

**Comment by robinmholt** [comment] 2022-09-23 18:22
To clarify my last comment. at `2022-09-19 10:59:32.809 +00:00` the exception occurred.  It was still disconnected on 2022-09-22 when I intervened.  You can see the container restart at `2022-09-22 19:12:21.219 +00:00`

**Comment by robinmholt** [comment] 2022-09-26 13:21
@jlian, this has occurred once across the dozen devices we are closely monitoring across the last 5 months.

It did not recover automatically.

Over the course of 3 days, the customer was reporting the device as being offline in the cloud.  Our first line support person had incorrectly identified the issue as being a transient modem/connectivity issue.  When the customer eventually reported  they were seeing updated values in the cloud, the investigation dove deeper and identified that telemetry data and direct methods to our module were still working, but the edgeAgent was not able to receive direct methods and the problem was escalated.

That is when I captured the log and opened this issue.

**Comment by jlian** [comment] 2022-09-29 19:46
Hmm, really don't know what happened here. Tagging @onalante-msft for on-call

**Comment by nlcamp** [comment] 2022-10-11 21:09
@robinmholt @jlian - We'll try to repro this. Looking at the logs, what I find interesting is that after each transient network errors, edgeAgent consistently closed the old module client and initialized a new one, after which periodic upload of metrics succeeded. It sounds like during these periods of time when device-to-cloud messages were succeeding, cloud-to-device messages were failing silently. 

We'll have to try forcing a transient network error and seeing if we can get a test device into a similar state. @robinmholt if you could share more details about your device environment, that would help with a repro -- the issue template includes a list of info such as OS, edgeAgent version, iotedged version, etc. that is useful for this purpose.

**Comment by raisalitch** [comment] 2022-10-19 20:36
@robinmholt Are you able to share more details on the device environment, as @nlcamp mentioned? Thanks

**Comment by robinmholt** [comment] 2022-10-19 22:58
The device is cellular connected.  edgeHub and edgeAgent as well as the iotedged were all the 1.14 version (IIRC).  Host OS is Ubuntu focal.  unattended-upgrades are enabled so packages get updated automatically.

The network drop-outs come from a weak cellular signal in the area of this device.

**Comment by onalante-msft** [comment] 2022-11-04 15:05
My apologies about the delay. I lost track of this issue in an email flurry.

edgeAgent and edgeHub are built with Alpine containers. From what I have found (most notably [this question on StackOverflow](https://stackoverflow.com/a/72678681)) The `ConnectAsync` call returning `EAGAIN` is attributable to DNS failure. DNS failures from long-running containers are entirely possible when the host is updated continuously since `resolv.conf` is not updated automatically in the container if the host's `resolv.conf` changes:

- https://github.com/docker/for-linux/issues/889
- https://github.com/moby/moby/issues/38243

Was `systemd-resolved` (or any other package modifying `/etc/resolv.conf` and/or `/run/systemd/resolve/resolv.conf`) updated around the time the container stopped functioning?

**Comment by onalante-msft** [comment] 2022-11-08 05:10
Yes, you are correct. Upon further consideration, I think it is also unlikely that multiple devices are hitting DNS issues.

I do not have anything concrete at this point, but my guess is that there is a deadlock somewhere among [`EdgeAgentConnection.twinLock`](https://github.com/Azure/iotedge/blob/d8d72da84a522f8ec3bf9c4a495d3ecc41fd507c/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs#L35), [`ModuleConnection.stateLock`](https://github.com/Azure/iotedge/blob/d8d72da84a522f8ec3bf9c4a495d3ecc41fd507c/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleConnection.cs#L17), and [`WrappingSdkModuleClient.getTwinTaskLock`](https://github.com/Azure/iotedge/blob/d8d72da84a522f8ec3bf9c4a495d3ecc41fd507c/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs#L14). Which of these is the root cause depends on when the handlers passed through the module clients are called (especially with respect to state changes). I will consult with some colleagues and report back to you.

**Comment by onalante-msft** [comment] 2022-11-14 18:52
Update: colleague said that deadlock is not impossible, but they had not seen this behavior before. I have not personally been able to reproduce this with `tc`, though this is not unexpected given that the customer setup is more complicated than what I can simulate. It would be easier to determine what is happening if there were debug logs; I suppose this is impossible given that these devices are field-deployed and this issue is not immediately reproducible.

**Comment by onalante-msft** [comment] 2022-11-15 23:20
I did some additional searching through the C# SDK, and it appears that WebSockets and cellular modems have a history of misbehaving when used together: https://github.com/Azure/azure-iot-sdk-csharp/issues/1720#issuecomment-768576789. Since the last reconnection attempt is with `Amqp_WebSocket_Only` and `Amqp_Tcp_Only` appears to work as-is, I would suggest fixing the upstream protocol to AMQP-TCP as a possible workaround.

**Comment by micahl** [comment] 2022-12-13 21:40
@robinmholt are you able to try setting the upstream protocol to AMQP-TCP and does that work for you?

**Comment by robinmholt** [comment] 2023-01-12 14:50
@micahl 

> @robinmholt are you able to try setting the upstream protocol to AMQP-TCP and does that work for you?

I could switch it if I had documentation indicating how.

At the moment, if I look in either the edgeAgent or edgeHub container, they are connecting on port 5671 which I assume means they are connecting using AMQP-TCP already.

That said, if I watch for outbound TCP Syn packets, I do see connections to the cloud using https:, so maybe something further needs to be adjusted.

**Comment by micahl** [comment] 2023-01-12 19:14
@robinmholt you can find an example of setting EdgeAgent's UpstreamProtocol environment variable [here](https://learn.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support#configure-the-iot-edge-agent).  The set of allowable values for UpstreamProtocol are found [here](https://github.com/Azure/iotedge/blob/main/doc/EnvironmentVariables.md).  The default behavior if not specified is to use AMQP with a fallback to AMQP over websockets.  Explicitly setting it to "Amqp" should avoid the fallback behavior and if @onalante-msft's hunch is correct avoid the issue.

Btw, if you haven't already I encourage you to upgrade to the 1.4 since the 1.1 reached its EOL in December.

**Comment by robinmholt** [comment] 2023-01-12 19:29
@micahl, thanks for the pointer.  I thought I was looking for something controlling the iotedge security daemon's connection.

I have changed the edgeHub and edgeAgent in our deployment.json for my test device to use AMQP (Actually had done that quite some time ago and forgot about it).  Unfortunately, that device's cellular connection is not as unstable as the device which failed.

I will bring this topic up with the product team next time we meet and ask for a survey of devices which currently are experiencing blocked AMQP connections.  If there are none, I will ask for approval to change the edgeHub and edgeAgent's connection to AMQP in all devices deployments.

As for the switch from 1.1 to 1.4, that would be much easier if it didn't require us to change package names and switch configuration file formats.  Given that our normal means of deploying device updates is via debian packages, we have a team working on a proposal for deploying a package which in turn waits a period of time until all debian package deployments are complete, and then switches from iotedge (1.1) to aziot-edge (1.4), but a _LOT_ of testing is needed since anything going wrong could mean we need to physically accessing each device which could mean truck rolls with support people scheduling visits to sites.  We have been at this for a couple months already and expect it will take another month or two.  If I sound frustrated, I am.

**Comment by micahl** [comment] 2023-01-12 22:11
@robinmholt RE pains of upgrading: feedback received

**Comment by micahl** [comment] 2023-02-08 00:21
@robinmholt I'm closing this issue for now.  Please reactive (or minimally comment here and I can reactivate) if you find evidence of this still occurring in the 1.4.

**Closed by micahl** 2023-02-08 00:21 UTC
Labels: iotedge, customer-reported
