### ISSUE TITLE
edgeAgent not using deployed ENV vars

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/iotedge#4256] opened 2021-01-20 18:21 UTC
## Expected Behavior
Our deployment is successful and showing that for the device, the edgeAgent should have a MaxRestartCount variable changed.

## Current Behavior
The edgeAgent does not load the new env var even after restarting the module, and restarting iotedge as a whole.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. In the deployment manifest include:
```json
"edgeAgent": {
  "env": {
    "MaxRestartCount": {
      "value": 2000
    }
  },
```
2. Do the deployment to a device.
3. Look at the portal for that specific module:
![image](https://user-images.githubusercontent.com/55600928/105216326-64040c00-5b20-11eb-85a9-6abadc3326a3.png)
4. Check the module on device:
```bash
sudo docker exec edgeAgent printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=41d7369d1d17
IOTEDGE_WORKLOADURI=unix:///var/run/iotedge/workload.sock
IOTEDGE_MODULEGENERATIONID=637419130498796436
NetworkId=azure-iot-edge
Mode=iotedged
EDGEDEVICEHOSTNAME=svi-vitro-crestline-4
IOTEDGE_MODULEID=$edgeAgent
IOTEDGE_IOTHUBHOSTNAME=svi-vitro-iothub.azure-devices.net
IOTEDGE_DEVICEID=some test device
IOTEDGE_APIVERSION=2019-11-05
IOTEDGE_AUTHSCHEME=sasToken
IOTEDGE_MANAGEMENTURI=unix:///var/run/iotedge/mgmt.sock
ASPNETCORE_URLS=http://+:80
DOTNET_RUNNING_IN_CONTAINER=true
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
EDGEAGENTUSER_ID=1000
HOME=/root
```
5. try: `iotedge restart edgeAgent` and do step 4
6. try: `systemctl restart iotedge` and do step 4

## Context (Environment)
```json
"systemModules": {
  "edgeAgent": {
    "env": {
      "MaxRestartCount": {
        "value": 2000
      }
    },
    "settings": {
      "createOptions": "",
      "image": "mcr.microsoft.com/azureiotedge-agent:1.0"
    },
    "type": "docker"
  },
  "edgeHub": {
    "env": {
      "OptimizeForPerformance": {
        "value": "true"
      },
      "UsePersistentStorage": {
        "value": "False"
      }
    },
    "restartPolicy": "always",
    "settings": {
      "createOptions": "",
      "image": "mcr.microsoft.com/azureiotedge-hub:1.0.8.4"
    },
    "status": "running",
    "type": "docker"
  }
}
```
### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
‼ latest security daemon - Warning
    Installed IoT Edge daemon has version 1.0.9.4 but 1.0.10.4 is the latest stable version available.
    Please see https://aka.ms/iotedge-update-runtime for update instructions.
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: certificates - OK
‼ production readiness: container engine - Warning
    Device is not using a production-supported container engine (moby-engine).
    Please see https://aka.ms/iotedge-prod-checklist-moby for details.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

17 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS  Ubuntu 18.04: 
* Architecture amd64: 
* Container OS Linux containers (docker): 
```bash
### Runtime Versions
* aziot-edged iotedge 1.0.9.4: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby: 
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Wed Oct 14 19:00:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Oct 14 16:52:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:
```

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

2021-01-20 18:02:24.614 +00:00 Edge Agent Main()
<6> 2021-01-20 18:02:24.756 +00:00 [INF] - Initializing Edge Agent.
<6> 2021-01-20 18:02:24.858 +00:00 [INF] - Version - 1.0.10.4.37804714 (57772714c81c8b823a5ef05bf11bf343b923fb6a)
<6> 2021-01-20 18:02:24.859 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2021-01-20 18:02:24.887 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false}
<6> 2021-01-20 18:02:24.963 +00:00 [INF] - Installing certificates [CN=Azure_IoT_Hub_CA_Cert_Test_Only:08/08/2030 06:39:57] to Root
<6> 2021-01-20 18:02:25.057 +00:00 [INF] - Starting metrics listener on Host: *, Port: 9600, Suffix: /metrics
<6> 2021-01-20 18:02:25.152 +00:00 [INF] - Updating performance metrics every 05m:00s
<6> 2021-01-20 18:02:25.155 +00:00 [INF] - Started operation Get system resources
<6> 2021-01-20 18:02:25.156 +00:00 [INF] - Collecting metadata metrics
<6> 2021-01-20 18:02:25.184 +00:00 [INF] - Set metadata metrics: 1.0.10.4.37804714 (57772714c81c8b823a5ef05bf11bf343b923fb6a), {"Enabled":false,"DisableCloudSubscriptions":false}, {"OperatingSystemType":"linux","Architecture":"x86_64","Version":"1.0.9.4","Provisioning":{"Type":"","DynamicReprovisioning":false},"ServerVersion":"","KernelVersion":"","OperatingSystem":"","NumCpus":0,"Virtualized":""}, True
<6> 2021-01-20 18:02:25.195 +00:00 [INF] - Started operation Checkpoint Availability
<6> 2021-01-20 18:02:25.197 +00:00 [INF] - Started operation refresh twin config
<6> 2021-01-20 18:02:25.208 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Amqp_Tcp_Only...
<6> 2021-01-20 18:02:25.412 +00:00 [INF] - Created persistent store at /tmp/edgeAgent
<6> 2021-01-20 18:02:25.445 +00:00 [INF] - Started operation Metrics Scrape
<6> 2021-01-20 18:02:25.445 +00:00 [INF] - Started operation Metrics Upload
Scraping frequency: 01:00:00
Upload Frequency: 1.00:00:00
<6> 2021-01-20 18:02:25.585 +00:00 [INF] - Registering request handler UploadModuleLogs
<6> 2021-01-20 18:02:25.585 +00:00 [INF] - Registering request handler GetModuleLogs
<6> 2021-01-20 18:02:25.585 +00:00 [INF] - Registering request handler UploadSupportBundle
<6> 2021-01-20 18:02:25.585 +00:00 [INF] - Registering request handler RestartModule
<6> 2021-01-20 18:02:25.875 +00:00 [INF] - Edge agent connected to IoT Hub via Amqp_Tcp_Only.
<6> 2021-01-20 18:02:26.027 +00:00 [INF] - Initialized new module client with subscriptions enabled
<6> 2021-01-20 18:02:26.124 +00:00 [INF] - Obtained Edge agent twin from IoTHub with desired properties version 48 and reported properties version 420.
module starting logs
<6> 2021-01-20 18:13:19.888 +00:00 [INF] - Updated reported properties

```
</details>

<details>
<summary>edge-hub logs</summary>

```

2021-01-20 18:02:41  Starting Edge Hub
2021-01-20 18:02:42.098 +00:00 Edge Hub Main()
[01/20/2021 06:02:42.957 PM] Found intermediate certificates: [CN=iotedged workload ca:08/08/2030 06:40:03],[CN=SVIEdgeDeviceCA.ca:08/08/2030 06:40:03],[CN=Azure_IoT_Hub_Intermediate_Cert_Test_Only:08/08/2030 06:39:58],[CN=Azure_IoT_Hub_CA_Cert_Test_Only:08/08/2030 06:39:57]
<6> 2021-01-20 18:02:43.492 +00:00 [INF] - Using in-memory store
<6> 2021-01-20 18:02:43.539 +00:00 [INF] - Initializing Edge Hub
<6> 2021-01-20 18:02:43.540 +00:00 [INF] - 
        █████╗ ███████╗██╗   ██╗██████╗ ███████╗
       ██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
       ███████║  ███╔╝ ██║   ██║██████╔╝█████╗
       ██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
       ██║  ██║███████╗╚██████╔╝██║  ██║███████╗
       ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

 ██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
 ██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
 ██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
 ██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
 ██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
 ╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝

<6> 2021-01-20 18:02:43.541 +00:00 [INF] - Version - 1.0.8.4.26769994 (7f452949464b45ed67f1cdcc5755654d211674ab)
<6> 2021-01-20 18:02:43.541 +00:00 [INF] - OptimizeForPerformance=True
<6> 2021-01-20 18:02:43.543 +00:00 [INF] - Loaded server certificate with expiration date of "2021-04-20T18:02:41.0000000+00:00"
<6> 2021-01-20 18:02:43.566 +00:00 [INF] - Created new message store
<6> 2021-01-20 18:02:43.566 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2021-01-20 18:02:43.575 +00:00 [INF] - Created device scope identities cache
<6> 2021-01-20 18:02:43.590 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2021-01-20 18:02:43.655 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2021-01-20 18:02:43.684 +00:00 [INF] - Initialized storing twin manager
<6> 2021-01-20 18:02:43.710 +00:00 [INF] - Initializing configuration
<6> 2021-01-20 18:02:43.728 +00:00 [INF] - New device connection for device device/$edgeHub
<6> 2021-01-20 18:02:43.791 +00:00 [INF] - Attempting to connect to IoT Hub for client device/$edgeHub via AMQP...
<6> 2021-01-20 18:02:43.829 +00:00 [INF] - Starting periodic operation Get EdgeHub config...
<6> 2021-01-20 18:02:43.857 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2021-01-20 18:02:43.857 +00:00 [INF] - Initialized edge hub configuration
<6> 2021-01-20 18:02:43.869 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2021-01-20 18:02:43.941 +00:00 [INF] - Scheduling server certificate renewal for "2021-04-20T18:00:11.0000922Z".
<6> 2021-01-20 18:02:43.943 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2021-01-20 18:02:43.947 +00:00 [INF] - Starting MQTT head
<6> 2021-01-20 18:02:43.975 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2021-01-20 18:02:44.018 +00:00 [INF] - Starting AMQP head
<6> 2021-01-20 18:02:44.029 +00:00 [INF] - Started MQTT head
<6> 2021-01-20 18:02:44.080 +00:00 [INF] - Started AMQP head
<6> 2021-01-20 18:02:44.082 +00:00 [INF] - Starting HTTP head
<6> 2021-01-20 18:02:44.162 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
<4> 2021-01-20 18:02:44.487 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
<6> 2021-01-20 18:02:44.508 +00:00 [INF] - Started HTTP head
<6> 2021-01-20 18:02:44.569 +00:00 [INF] - Exiting disconnected state
<6> 2021-01-20 18:02:44.572 +00:00 [INF] - Received device connected callback
<6> 2021-01-20 18:02:44.594 +00:00 [INF] - Device connected to cloud, processing subscriptions for connected clients.
<6> 2021-01-20 18:02:44.594 +00:00 [INF] - Processing subscriptions for client device/$edgeHub.
<6> 2021-01-20 18:02:44.601 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2021-01-20 18:02:44.608 +00:00 [INF] - Entering connected state
<6> 2021-01-20 18:02:44.611 +00:00 [INF] - Cloud connection for device/$edgeHub is True
<6> 2021-01-20 18:02:44.616 +00:00 [INF] - Connection status for device/$edgeHub changed to ConnectionEstablished
<6> 2021-01-20 18:02:44.619 +00:00 [INF] - Client device/$edgeHub connected to cloud, processing existing subscriptions.
<6> 2021-01-20 18:02:44.623 +00:00 [INF] - Created cloud proxy for client device/$edgeHub via AMQP, with client operation timeout 20 seconds.
<6> 2021-01-20 18:02:44.627 +00:00 [INF] - Initialized cloud proxy 31f1532e-e9e3-49ef-9cd6-3f4af6bde330 for svi-vitro-crestline-4/$edgeHub
<6> 2021-01-20 18:02:44.629 +00:00 [INF] - Created cloud connection for client device/$edgeHub
<6> 2021-01-20 18:02:44.962 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2021-01-20 18:02:44.992 +00:00 [INF] - Updated reported properties for device/$edgeHub
<6> 2021-01-20 18:02:45.003 +00:00 [INF] - Obtained edge hub config from module twin
<6> 2021-01-20 18:02:45.143 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2021-01-20 18:02:45.145 +00:00 [INF] - Successfully completed periodic operation Get EdgeHub config<6> 2021-01-20 18:07:43.871 +00:00 [INF] - Reauthenticating connected clients
<6> 2021-01-20 18:12:43.870 +00:00 [INF] - Reauthenticating connected clients
```
</details>

**Comment by darobs** [comment] 2021-01-26 02:06
@davilu, @josiahlaivins 

I reproduced this with iotedged 1.0.9.4 and agent 1.0.10.4 in amd64/Ubuntu 18.04. The current behavior is to **not** update edgeAgent if edgeAgent is currently running. It **will** update the container if the image version has changed. If you change the image version in the portal (to say `mcr.microsoft.com/azureiotedge-agent:1.0.10.4`), the Env variable settings would be applied.

This behavior is by design, but we are open to allowing edgeAgent to be updated for any configuration. The best way for us to understand the priority of this problem by contributing to [User Voice](https://aka.ms/iotedge-suggestion). 

I am closing this issue, but if you have more questions, please reopen this or create a new issue.

**Closed by darobs** 2021-01-26 02:06 UTC
Labels: customer-reported, iotedge
