### ISSUE TITLE
Get Edge device name from inside an Edge module

### ISSUE THREAD

**Issue by ewertons** [Azure/iotedge#3327] opened 2020-07-31 19:47 UTC
Filed on behalf of @gri6507.

First referenced on https://github.com/Azure/azure-iot-sdk-c/issues/1501.

------------------

I am writing an IoT Edge module using the azure-iot-sdk-c library. I would like to get the name of the current edge device at runtime into my module. Is there C API to do that?

When I do `docker exec <ContainerIdOfRunningModule> /bin/bash -c 'env'` I can see that there is a `IOTEDGE_DEVICEID` environment variable set in the container. However, getting the module name from the environment seems fragile as the name of that environment variable may change over time.

**Comment by arsing** [comment] 2020-08-02 08:03
Duplicate of #986

And to further allay the concerns: `IOTEDGE_DEVICEID` is guaranteed to be defined. It's part of the API. So relying on it should not be considered brittle.

**Closed by arsing** 2020-08-02 08:03 UTC
