### ISSUE TITLE
edgeHub low module-to-module throughput

### ISSUE THREAD

**Issue by maciej-kepa** [Azure/iotedge#6845] opened 2023-01-09 13:12 UTC
Hello,

Our team is currently working on a solution involving multiple modules running on IoT Edge along with some routes between them. We noticed that the internal throughput of edgeHub when OUTPUT is set to be BrokeredEndpoint(...) is very small, up to 20 messages per second. 

Logs inspection show that this happens due to **50ms** latency between message being sent by edgeHub and receiving feedback of it.
```
<7> 2023-01-09 13:00:29.448 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 45173aec-41a1-46a1-a1c1-f8163ad5d858 to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.448 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.449 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id 45173aec-41a1-46a1-a1c1-f8163ad5d858 to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.498 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 45173aec-41a1-46a1-a1c1-f8163ad5d858 from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.499 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 7d77fbd0-45c1-49be-acb6-b4b362f923d4 to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.499 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.499 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id 7d77fbd0-45c1-49be-acb6-b4b362f923d4 to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.549 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 7d77fbd0-45c1-49be-acb6-b4b362f923d4 from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.549 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID e9cbeb32-f4f6-4bad-bdaa-bfc700547aea to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.549 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.550 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id e9cbeb32-f4f6-4bad-bdaa-bfc700547aea to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.599 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message e9cbeb32-f4f6-4bad-bdaa-bfc700547aea from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.599 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID e4455eaf-be06-41c8-8753-b2d18d03f1cb to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.599 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.600 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id e4455eaf-be06-41c8-8753-b2d18d03f1cb to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.649 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message e4455eaf-be06-41c8-8753-b2d18d03f1cb from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.649 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 01de9042-acda-44a4-b46f-b3c17c7a4047 to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.649 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.650 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id 01de9042-acda-44a4-b46f-b3c17c7a4047 to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.698 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 01de9042-acda-44a4-b46f-b3c17c7a4047 from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.698 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID eb0b3ed1-497e-4841-8be4-e1f8bb00405f to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.699 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.699 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id eb0b3ed1-497e-4841-8be4-e1f8bb00405f to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.748 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message eb0b3ed1-497e-4841-8be4-e1f8bb00405f from device/module parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.749 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID dd2aca89-069a-4110-9b4b-99a313e00b36 to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.749 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.ClientConnectionHandler] - Sending telemetry message to parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.750 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.SendingLinkHandler] - Sent message with id dd2aca89-069a-4110-9b4b-99a313e00b36 to device parentDevice/KafkaSender
<7> 2023-01-09 13:00:29.799 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message dd2aca89-069a-4110-9b4b-99a313e00b36 from device/module parentDevice/KafkaSender
```

The case is not the output module, because even with no message processing (just send OK feedback on message received) the same latency occurs. 

We are using **Azure IoT Java SDK v2.1.2** for modules development.

What is the possible cause of that 50ms latency and is there any configuration possible for edgeHub to achieve better internal throughput considering that the solution could require to process internally about 2000 messages per second?

Thanks in advance,
M.

**Comment by vipeller** [comment] 2023-01-09 20:18
@maciej-kepa  it was an issue a time ago with the c# sdk too, by a mechanism a bit similar to Nagle's algorithm. The underlying AMQP library held back the ack, because it was waiting a bit that maybe other data comes, that it can send together.

 I can imagine that there is a similar problem going on with java sdk as the same team created the amqp library, I beleive.

Two things: 
- if you have resources, could you try using MQTT between the modules and edge, to see if the problem still stands
- in the meanwhile, I contact the Java SDK team to ask about the amqp library and how they use it.

**Comment by timtay-microsoft** [comment] 2023-01-09 22:31
We're taking a look into this behavior on the Java SDK side, and we'll provide updates in this thread as well as in the new issue thread on the Java SDK repo [here](https://github.com/Azure/azure-iot-sdk-java/issues/1654)

**Comment by maciej-kepa** [comment] 2023-01-10 09:35
I tried changing the protocol to MQTT on receiving module side and it indeed have lower latency - about **10ms**:
```
<7> 2023-01-10 09:23:27.607 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 2a2de9e2-5b67-4db6-9013-f816c3d5c2a1 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.616 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 2a2de9e2-5b67-4db6-9013-f816c3d5c2a1 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.616 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID b2e18c61-fc28-41ed-8a04-24aae5f04b14 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.626 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message b2e18c61-fc28-41ed-8a04-24aae5f04b14 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.627 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 0d91d94a-926e-4e4a-8d41-a3633daf118e to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.637 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 0d91d94a-926e-4e4a-8d41-a3633daf118e from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.637 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 76d0718f-a6d2-4c4b-b8f4-c4eac63c3129 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.647 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 76d0718f-a6d2-4c4b-b8f4-c4eac63c3129 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.647 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 321b3665-164c-4773-89da-d2951265fc33 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.657 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 321b3665-164c-4773-89da-d2951265fc33 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.657 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 3fecf3d1-442e-495b-b843-34a2f063005f to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.667 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 3fecf3d1-442e-495b-b843-34a2f063005f from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.667 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 59758210-7611-43d7-ab2a-991e660512a2 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.677 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 59758210-7611-43d7-ab2a-991e660512a2 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.678 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID 52458270-d30d-438e-a868-9bb50b2381d7 to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.688 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message 52458270-d30d-438e-a868-9bb50b2381d7 from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.688 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID fb6ca6cc-253a-4d70-b999-2b96e05211de to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.698 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message fb6ca6cc-253a-4d70-b999-2b96e05211de from device/module parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.698 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Sent message with correlation ID aa1afa93-78d5-4e88-bccf-c3c71333e9ac to parentDevice/KafkaSender
<7> 2023-01-10 09:23:27.708 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler] - Received feedback Complete for message aa1afa93-78d5-4e88-bccf-c3c71333e9ac from device/module parentDevice/KafkaSender
```

While its actually still not enough for our case, it kind of confirms that there is some issue with underlaying AMQP protocol implementation.

**Comment by timtay-microsoft** [comment] 2023-01-11 18:05
Can you try updating the module client's receive period? The default period is 10 ms, but it can go lower.

https://github.com/Azure/azure-iot-sdk-java/blob/a5b5a1fa1020ac8e833b827d7dc4e9296edcbc52/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/ClientOptions.java#L138

```java
ClientOptions options = ClientOptions.builder().receiveInterval(1).build();
ModuleClient client = new ModuleClient(..., options);
```

**Comment by maciej-kepa** [comment] 2023-01-12 12:04
I tried updating the module client's receive period to several values both lower and higher than default 10ms but it doesn't seem to change anything - latency is 10ms using MQTT protocol regardless the receive interval.

However I'm using createFromEnvironment method to create ModuleClient instance rather than direct constructor :
```java
IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
ClientOptions options = ClientOptions.builder().receiveInterval(1).build();
ModuleClient client = ModuleClient.createFromEnvironment(unixDomainSocketChannel, protocol, options);
```
But I think it should work regardless of the client creation method.

**Comment by timtay-microsoft** [comment] 2023-01-13 01:09
Yeah, the client options would be respected regardless of what constructor you used. We'll look into this more on the SDK side. It's possible that this 10 ms interval is set at the MQTT/AMQP library level and that we'd need to alter it within the SDK in cases like this.

**Comment by maciej-kepa** [comment] 2023-01-30 07:25
Hi again.
Just wanted to ask is there any update on this issue?
Thanks in advance,
M.

**Comment by vipeller** [comment] 2023-02-10 19:06
@maciej-kepa I am transferring this issue to this SDK ticket: https://github.com/Azure/azure-iot-sdk-java/issues/1654
Please, monitor the progress on that thread, the SDK team does not get notified on changes on this thread.
Sorry, that the issue is still not got fixed.

**Closed by vipeller** 2023-02-10 19:06 UTC
Labels: iotedge, customer-reported
