### ISSUE TITLE
./certGen.sh create_edge_device_certificate "<CA cert name>" not working

### ISSUE THREAD

**Issue by asergaz** [Azure/iotedge#3644] opened 2020-10-02 06:11 UTC
## Expected Behavior
Remove functions that are not working from ./certGen.sh 

## Current Behavior
`./certGen.sh create_edge_device_certificate "<CA cert name>"` is mentioned in the doc [Create demo certificates to test IoT Edge device features](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates) though it is not working. Only `./certGen.sh create_edge_device_ca_certificate "<CA cert name>"` is working.

- This issue started first in MicrosoftDocs repo: https://github.com/MicrosoftDocs/azure-docs/issues/63333

PS: We will fix the documentation if we find this is a bug.

**Comment by asergaz** [comment] 2020-10-02 06:13
fyi @sandervandevelde @kgremban

**Comment by veyalla** [comment] 2020-10-06 20:23
@asergaz If I'm understanding https://github.com/MicrosoftDocs/azure-docs/issues/63333#issuecomment-702667318 correctly, it seems like a docs issue?

**Comment by asergaz** [comment] 2020-10-07 06:39
@veyalla the reason I opened the issue here is that we may need to remove `create_edge_device_certificate` from the script since as describred by @sandervandevelde , only create_edge_device_**ca**_certificate is working.

After the decision here we can update the doc accordingly as well.

**Comment by sandervandevelde** [comment] 2020-10-07 07:57
Hello @veyalla @asergaz . From my perspective, the issue is the docs documentation. In this child device flow, create_edge_device_ca_certificate is the one to use (as seen in the MS Learn module).

**Comment by kgremban** [comment] 2020-10-07 18:11
Although as @asergaz pointed out, both create_edge_device_certificate and create_edge_device_ca_certificate look like call identical functions. I'm happy to standardize around one across the docs, but I'd like to know why create_edge_device_certificate isn't working in case the same issues show up down the line for create_edge_device_ca_certificate.

**Comment by veyalla** [comment] 2020-10-09 17:42
Thanks all, closing as this is being handled in the docs.

**Closed by veyalla** 2020-10-09 17:42 UTC
Labels: customer-reported, iotedge
