### ISSUE TITLE
Runtime error: "The system cannot find the specified file."

### ISSUE THREAD

**Issue by Peter-B-** [Azure/iotedge#1186] opened 2019-05-08 09:00 UTC
## Expected Behavior
IoT Edge devcies should send messages to the IoT Hub. 

## Current Behavior
I updated 2 devices from 1.0.6 to 1.0.7. Both devices start and connect to the IoT Hub. As far as I can say all modules are started correctly and send messages to the IoT Hub for approximately 30 minutes. Than they stop.

When I invoke `iotedge list`, I see

```
PS C:\tmp\1.0.7> iotedge list
A module runtime error occurred
        caused by: Could not list modules
        caused by: Client error
```

`Get-IoTEdgeLog` produces

```
TimeCreated         Message
-----------         -------
08.05.2019 10:24:47 info: edgelet_core::watchdog -- Checking edge runtime status
08.05.2019 10:24:47 warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
08.05.2019 10:24:47 warn: edgelet_utils::logging -- A module runtime error occurred.
08.05.2019 10:24:47 warn: edgelet_utils::logging --     caused by: an error occurred trying to connect: Das System kann die angegebene Datei nicht finden. (os error 2)                                             
08.05.2019 10:24:47 warn: edgelet_utils::logging -- Could not list modules
08.05.2019 10:24:47 warn: edgelet_utils::logging --     caused by: Container runtime error                                                                                                                          
08.05.2019 10:24:47 warn: edgelet_utils::logging --     caused by: an error occurred trying to connect: Das System kann die angegebene Datei nicht finden. (os error 2)                                             
08.05.2019 10:24:47 warn: edgelet_utils::logging --     caused by: Container runtime error                                                                                                                          
08.05.2019 10:24:47 warn: edgelet_utils::logging --     caused by: Could not list modules    
```

In the Windows Event Viewer, I see the "The system cannot find the specified file"-Error, but I cannot find any hint about which file it was searching for:

```
error: edgelet_http_mgmt::error -- Internal server error: Could not list modules
	caused by: Could not list modules
	caused by: Container runtime error
	caused by: an error occurred trying to connect: Das System kann die angegebene Datei nicht finden. (os error 2)
```

## Problems with the Upgrade
I should mention, that we had serious problems with upgrading from 1.0.6 to 1.0.7:

On all three of our test installations `Uninstall-IoTEdge -Force` failed to delete the Moby data directory:

```
PS C:\tmp\1.0.7> Uninstall-IoTEdge -Force
Uninstalling...
Deleting data directory 'C:\ProgramData\iotedge'...
Deleting Moby data root directory 'C:\ProgramData\iotedge-moby-data'...
Could not delete Moby data root directory 'C:\ProgramData\iotedge-moby-data'. Please reboot your device and run "Uninstall-IoTEdge" again with "-Force".
```

Restarting did not work and on one machine, we still cannot delete this directory. Not event if we start the computer in Safe Mode. On the other 2 machines, we eventually managed to remove the directory after trying several tricks we found on stackoverflow.

After that, the installation of the update and the deployment of the IoT Edge modules worked as expeted.

## Steps to Reproduce
Hard to say.

### Device (Host) Operating System
Window 10 1809

### Architecture
x64

### Container Operating System
Windows containers

#### iotedged
iotedge 1.0.7 (f455ae2cd66db716c4bd8e7aaa7984ce092481c0)

#### Edge Agent
1.0.7

#### Edge Hub
1.0.7

#### Docker
```
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false
```

**Comment by Peter-B-** [comment] 2019-05-10 10:45
I formatted one of the devices and installed a clean Windows 10 IoT Enterprise 1809. 

I installed iot-edge and deployed the modules. They ran for a couple of hours until the same error occured.

The `iotedge-moby` service stopped. I have no idea why. I created a [gist with the Event Viewer logs](https://gist.github.com/Peter-B-/ed6e41b9262b45e9d9c49b29a4472ac0).

The most specific message I found there is

```
error: edgelet_http_mgmt::error -- Internal server error: Could not list modules
	caused by: Could not list modules
	caused by: Container runtime error
	caused by: an error occurred trying to connect: The system cannot find the file specified. (os error 2)
```

I manually restarted the `iotedge-moby` service, but the iotedge and iotagent modules were not restarted until I rebootet the system.

Right now it is working again.

Do you have any idea how I could pin down the problem?


## Context (Environment)
### Device (Host) Operating System
Windows 10 Enterprise LTSC 
1809
build 17763.107

### Docker Version
```
Client:
 Version:           3.0.2
 API version:       1.40
 Go version:        go1.11.1
 Git commit:        e042b58f
 Built:             Tue Dec  4 20:13:19 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.3
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.11.4
  Git commit:       5ec3138
  Built:            Thu Jan 24 17:16:18 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by Peter-B-** [comment] 2019-05-10 11:26
I just had another crash. I exported `Get-IoTEdgeLog` for the last hour. It can be found [in this gist](https://gist.github.com/Peter-B-/0a32491d3f63f1410595c9fc205bddfd).

The interresting line may be
```
5/10/2019 12:51:07 PM info: edgelet_http::logging -- [work] - - - [2019-05-10 10:51:07.140205100 UTC] "POST /modules/%24edgeHub/genid/636885772520166081/sign?api-version=2019-01-30 HTTP/1.1" 404 Not Found 254 "-" "-" pid(12936)                                           
```

I see regular `Get` and `Post` calls, but the line above is the first one with an error return code (404). The same request succeeded only 2 seconds before. 

Can this information help?

**Comment by veyalla** [comment] 2019-05-10 14:39
Thanks for the report @Peter-B-, some questions:
1. What modules do you have running on the system?
1. Are you mounting any directories from the host into the container?
1. Does this repro with Windows VM as suggested in the [Windows quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart) or [How to install on Windows Server VM](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-server-vm)?
1. Can you attach logs from docker by issuing the following command (for the past 12 hours):
```
Get-WinEvent -ea SilentlyContinue `
-FilterHashtable @{ProviderName= "docker";
LogName = "application"; StartTime = [datetime]::Now.AddHours(-12)} |
select TimeCreated, Message |
sort-object @{Expression="TimeCreated";Descending=$false} |
format-table -autosize -wrap
```

**Comment by Peter-B-** [comment] 2019-05-13 06:55
Hallo @veyalla,

thanks for your response. 

## 1
There are the following modules:

- `edgeHub` and `edgeAgent`
- 12 .Net core IoT Edge modules
- 1 node.js module

All the modules are managed in the IoT edge deployment. 

## 2
The node.js module has a file system directory mounted.

## 3
Do you propose creating a Azure VM with 
```az vm create -g IoTEdgeResources -n EdgeVM --image MicrosoftWindowsServer:WindowsServer:2019-Datacenter-Core-with-Containers:latest  --admin-username azureuser --generate-ssh-keys --size Standard_DS1_v2```
and deploying everything there?

We did not try this, yet.

## 4 
The command does not execute on my machine. 
```
Get-WinEvent : The parameter is incorrect
At line:1 char:1
+ Get-WinEvent -ea SilentlyContinue `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogException
    + FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.GetWinEventCommand
```

As far as I see, there is no "docker" provider. I see an event source called "iotedge-moby", but there are no events for that.

**Comment by StefanDoubleU** [comment] 2019-05-13 15:36
When restarting the iotedge-moby service we are getting the following error in the log of the security daemon:
>13.05.2019 17:30:35 info: edgelet_core::watchdog -- Checking edge runtime status
13.05.2019 17:30:35 info: edgelet_docker::runtime -- Starting module edgeAgent...
13.05.2019 17:30:35 info: edgelet_core::watchdog -- Edge runtime status is failed, starting module now...
13.05.2019 17:30:35 warn: edgelet_utils::logging -- A module runtime error occurred.
13.05.2019 17:30:35 warn: edgelet_utils::logging --     caused by: Could not start module edgeAgent                                                                                                                                                                            
13.05.2019 17:30:35 warn: edgelet_utils::logging --     caused by: hcsshim::ActivateLayer failed in Win32: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (0x20)                                                             
                    path=C:\ProgramData\iotedge-moby\windowsfilter\bb11e5abd9e9885aac81b2dd6ccbc1bed9af52538ef366a45f2e9f1b440b6bdf
13.05.2019 17:30:35 warn: edgelet_utils::logging -- Could not start module edgeAgent
13.05.2019 17:30:35 warn: edgelet_utils::logging --     caused by: hcsshim::ActivateLayer failed in Win32: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird. (0x20)                                                             
                    path=C:\ProgramData\iotedge-moby\windowsfilter\bb11e5abd9e9885aac81b2dd6ccbc1bed9af52538ef366a45f2e9f1b440b6bdf
13.05.2019 17:30:35 warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:

**Comment by veyalla** [comment] 2019-05-13 18:30
@StefanDoubleU is this the same device and deployment that @Peter-B- created this issue about or is it a different context?

**Comment by StefanDoubleU** [comment] 2019-05-13 18:39
Its the same device.

**Comment by veyalla** [comment] 2019-05-13 18:52
Ok great, there are probably two separate issues -

- Node.js modules are not yet supported for Windows containers. "IoT Edge does not support Node.js modules for Windows devices" (source: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module#solution-scope)

- For the ActivateLayer error, this seems like a known issue for Windows containers. See this link for mitigation instructions: https://success.docker.com/article/windows-server-node-fails-to-restart-containers

**Comment by StefanDoubleU** [comment] 2019-05-14 06:33
Thank you for your reply, but it actually doesn't help with our problem. 
1. The node.js module is not actually a edge module but a plain container running a node.js application. Can't we do that?
2. This "fix" for the restart - which is in our opinion no real solution because it needs extra management on the device - does not help with the issue that the docker daemon stops. 

what can we do? Peter has already told, that the logfile you requesting is not available.

**Comment by veyalla** [comment] 2019-05-14 16:41
@StefanDoubleU Re:

1. I don't think this is supported, the Moby engine supplied with IoT Edge is licensed to exclusively run containers managed by IoT Edge. Please see the license terms located in `$Env:ProgramFiles\iotedge-moby\legal-engine\LICENSE`. You might want to re-think your architecture.

1. The extra management on the devices is required for production deployments even outside this fix/workaround. For example [rolling logs](https://aka.ms/iotedge-prod-checklist-logs), [specifying DNS servers](https://aka.ms/iotedge-prod-checklist-dns) or [using production certificates](https://aka.ms/iotedge-prod-checklist-certs)

Not sure why getting logs from `docker` service is not working for you. 

Can you provide the output for `iotedge check` (needs release 1.0.7 or newer).

**Comment by StefanDoubleU** [comment] 2019-05-16 08:28
```
PS C:\Windows\system32> iotedge check --verbose

Configuration checks
--------------------
√ config.yaml is well-formed
√ config.yaml has well-formed connection string
× container engine is installed and functional
    Could not communicate with container engine at npipe://./pipe/iotedge_moby_engine.
    Please check your moby-engine installation and ensure the service is running.
        caused by: docker returned exit code: 1, stderr = error during connect: Get http://%2F%2F.%2Fpipe%2Fiotedge_moby_engine/v1.40/version: open //./pipe/iotedge_moby_engine: Das System kann die angegebene Datei nicht finden.
√ config.yaml has correct hostname
‼ config.yaml has correct URIs for daemon mgmt endpoint
    skipping because of previous failures
√ latest security daemon
√ host time is close to real time
‼ container time is close to host time
    skipping because of previous failures
‼ DNS server
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: Das System kann die angegebene Datei nicht finden. (os error 2)
‼ production readiness: certificates
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry
‼ production readiness: container engine
    skipping because of previous failures
‼ production readiness: logs policy
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Could not open container engine config file C:\ProgramData\iotedge-moby\config\daemon.json
        caused by: Das System kann die angegebene Datei nicht finden. (os error 2)

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port
√ host can connect to and perform TLS handshake with IoT Hub HTTPS port
√ host can connect to and perform TLS handshake with IoT Hub MQTT port
‼ container on the IoT Edge module network can connect to IoT Hub AMQP port
    skipping because of previous failures
‼ container on the IoT Edge module network can connect to IoT Hub HTTPS port
    skipping because of previous failures
‼ container on the IoT Edge module network can connect to IoT Hub MQTT port
    skipping because of previous failures
‼ Edge Hub can bind to ports on host
    skipping because of previous failures

One or more checks raised errors.
```

```
PS C:\Windows\system32> Get-WinEvent -ea SilentlyContinue `
>> -FilterHashtable @{ProviderName= "docker";
>> LogName = "application"; StartTime = [datetime]::Now.AddHours(-12)} |
>> select TimeCreated, Message |
>> sort-object @{Expression="TimeCreated";Descending=$false} |
>> format-table -autosize -wrap
Get-WinEvent : Falscher Parameter
In Zeile:1 Zeichen:1
+ Get-WinEvent -ea SilentlyContinue `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WinEvent], EventLogException
    + FullyQualifiedErrorId : System.Diagnostics.Eventing.Reader.EventLogException,Microsoft.PowerShell.Commands.GetWinEventCommand
```

**Comment by StefanDoubleU** [comment] 2019-05-16 12:42
I found a panic.log in %ProgramData%\iotedge-moby directory. Maybe this helps finding the issue.
[https://gist.github.com/StefanDoubleU/77860cd9b54fcb93d5f319988b64653a](url)

**Comment by veyalla** [comment] 2019-05-17 04:39
Are you still running the node container outside of IoT Edge when you get this error? 

To rule our any environment specific issue, can you run the same edge deployment in a VM \ as documented in the [Windows quickstart](https://docs.microsoft.com/en-us/azure/iot-edge/quickstart#prerequisites)?

If possible it would also be good to take a look at your deployment manifest. You can send it to veyalla@microsoft.com if you don't want to share it here.

Thanks for your patience with this.

**Comment by StefanDoubleU** [comment] 2019-05-17 10:10
We are not running any module outside of IoT Edge deployment manifest. 
Its ist just not an "edge module" but a plain docker image for windows. 

And no, we haven't yet tried it with you VM, but we have three different machines, with all the same behavior. There are not just copies, but all differently installed Windows 10 1809 Enterprise (IoT). 

I sent you our deployment manifest via mail.

**Comment by rahulsehgal** [comment] 2019-06-19 18:10
Hi All,

Is there any update on this issue. I am also getting the same issue when my modules run for 2 days. Looks like iotedge runtime stops working and on when I try to Restart the runtime it does not work. Only System restart makes it to restart the edge runtime.

Other thing I observed is the log shows that the file is locked by other processes. This file is in C:\ProgramData\iotedge-moby\windowsfilter in one container folder which contains .vhdx file.

**Comment by rahulsehgal** [comment] 2019-06-20 05:32
@Peter-B-  Are you able to resolve this issue? Is there any workaround?

**Comment by rahulsehgal** [comment] 2019-06-21 17:46
@veyalla I am also experiencing this issue in 1.0.7.1 release. This does not happened with 1.0.6  release.
What is the way to install rollback to 1.0.6 version of iotedge.

**Comment by Peter-B-** [comment] 2019-06-21 18:14
@rahulsehgal We were not able to resolve the issue and did not really find any support. So we try the Linux version of IoT-Edge now. It seems to be more stable.

**Comment by rahulsehgal** [comment] 2019-06-21 18:23
@Peter-B- Thanks for reply Peter. I am also trying with 1.0.8-rc of edgeAgent and edgeHub. It it possible to run iotedge 1.0.8-rc version, because when I installed  with below command it deployed 1.0.7.1 version only. And the issue seems to be introduced in 1.0.7.1 release as our other devices are working fine on 1.0.6.
. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; `
Deploy-IoTEdge 1.0.8-rc1 -ContainerOs Windows

**Comment by veyalla** [comment] 2019-06-21 19:14
I was following up on the issue that @Peter-B- reported originally and got some info from the Moby team recently that it might be related to a regression in Moby that was fixed in https://github.com/moby/moby/pull/38681. The regression caused the Moby daemon to crash due to some concurrent map access and so iotedge would encounter a "cannot find the specified file" error when it tried to communicate with it via the named pipe that the daemon listens on.

@rahulsehgal 
1.0.8-RC of IoT Edge bundles a newer version of Moby that should have the fix for the issue. The way to install the the RC is to download the [1.0.8.rc2 cab file](https://github.com/Azure/azure-iotedge/releases/download/1.0.8-rc2/Microsoft-Azure-IoTEdge.cab) to, let's say, `c:\iotedge\`, uninstall any older versions and install using:

` {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge -OfflineInstallationPath c:\iotedge` 

...followed by `Initialize-IoTEdge...` as normal.

Let me know if this shows any improvement in your tests.

@Peter-B-  @StefanDoubleU Apologize for the delay in getting this info. Let me know if I can help with anything else.

**Comment by rahulsehgal** [comment] 2019-06-21 19:39
@veyalla Thanks for the update. I am now trying with the 1.0.8-rc release.

**Comment by rahulsehgal** [comment] 2019-06-24 09:30
Hi @veyalla,
I am now testing with the 1.0.8-rc2 version. It is working fine as of now.
Is there any way I can install release 1.0.6.1 of runtime as I dont find the .cab file under the releases for 1.0.6.1. As we want to deploy with Released version.
When release of 1.0.8 is expected?
Thanks,
Rahul

**Comment by sachidanand** [comment] 2019-06-24 14:16
> I was following up on the issue that @Peter-B- reported originally and got some info from the Moby team recently that it might be related to a regression in Moby that was fixed in [moby/moby#38681](https://github.com/moby/moby/pull/38681). The regression caused the Moby daemon to crash due to some concurrent map access and so iotedge would encounter a "cannot find the specified file" error when it tried to communicate with it via the named pipe that the daemon listens on.
> 
> @rahulsehgal
> 1.0.8-RC of IoT Edge bundles a newer version of Moby that should have the fix for the issue. The way to install the the RC is to download the [1.0.8.rc2 cab file](https://github.com/Azure/azure-iotedge/releases/download/1.0.8-rc2/Microsoft-Azure-IoTEdge.cab) to, let's say, `c:\iotedge\`, uninstall any older versions and install using:
> 
> ` {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Deploy-IoTEdge -OfflineInstallationPath c:\iotedge`
> 
> ...followed by `Initialize-IoTEdge...` as normal.
> 
> Let me know if this shows any improvement in your tests.
> 
> @Peter-B- @StefanDoubleU Apologize for the delay in getting this info. Let me know if I can help with anything else.

When would it release a general release 1.0.8 version ??? Actually we need to install it on production version so could you let me know the exact date of this release..

**Comment by veyalla** [comment] 2019-06-24 17:01
Don't have a set date for 1.0.8 yet, the ball park is 2nd week of Jul. 

I don't recommend any release older than 1.0.7 for Windows containers as that is the GA release. Since this issue is isolated to the bundled Moby, you can use the 1.0.8-RC2 .cab package and specify 1.0.7.1 versions for your edgeHub and edgeAgent containers. 

Usage of specific container version tags are recommended for production: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge#update-a-specific-tag-image

**Comment by arsing** [comment] 2019-08-07 00:10
1.0.8 has been released.

**Closed by arsing** 2019-08-07 00:10 UTC

**Comment by LarsKemmann** [comment] 2020-02-12 01:17
@veyalla I'm running 1.0.8 (`iotedge version` returns `iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)`) but am seeing this same problem. This is on a vanilla Windows Server 2019 Datacenter (1809, build 17763.973) VM in Azure. I ran through the initial setup steps & everything worked fine, then left it shut down (via auto-shutdown) for two weeks and now I just booted it up and am seeing the behavior described by the other commenters above. Any suggestions?

**Comment by veyalla** [comment] 2020-02-13 00:46
Windows Server 2019 VM comes with Docker Enterprise pre-installed, but iotedge doesn't use it. It uses a moby engine it installs side-by-side and available at npipe://./pipe/iotedge_moby_engine. So, I am not sure how changing its setting helped iotedged-moby. I do find it a bit surprising that the link you shared ask to put daemon.json in `%programdata%` instead of `%programdata%\docker`.


Using Docker Engine is not default because it is not available for free on other versions of Windows.
