### ISSUE TITLE
Cannot configure proxy for iotedge

### ISSUE THREAD

**Issue by MkTru** [Azure/iotedge#2020] opened 2019-11-20 16:27 UTC
When configuring a proxy for the iotedge daemon as documented at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support the service no longer starts.

**Versions**
- OS: Windows 10 IoT, LTSC, 1809, Build: 17763.107.
- iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

**Observed Behavior**:
As soon as the key HKLM\SYSTEM\CurrentControlSet\Services\iotedge\Environment
- exists (empty)
- contains any key=value entry
- contains https_proxy=http://test:80
- contains our correct proxy configuration

the iotedge service no longer starts. Deleting the key fixes the issue.

**Console log**
> Start-Service iotedge
> Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start
> service iotedge on computer '.'.
> At line:1 char:1
> + Start-Service iotedge
> + ~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
>    ServiceCommandException
>     + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

**Event log**
> Service Control Manager, EventId: 7040
> The Azure IoT Edge Daemon service failed to start due to the following error: 
> The parameter is incorrect.

**Diagnosis**
- I could not find any relevant information in the event log
- iotedge check: Same whether Environment key exists or not

**Comment by ancaantochi** [comment] 2019-11-20 20:34
Hi @MkTru,

Can you get more information if you try to get the logs using 
`. {Invoke-WebRequest -useb aka.ms/iotedge-win} | Invoke-Expression; Get-IoTEdgeLog`

Can you please run the command to query for the registry key and let me know what is returns:

`reg query HKLM\SYSTEM\CurrentControlSet\Services\iotedge /v Environment`

When it works did you only remove the registry key or did you make changes to the config.yaml too?

**Comment by MkTru** [comment] 2019-11-21 07:14
Get-IoTEdgeLog is empty, probably since the service does not start.

Here some sample entries:
> PS C:\Windows\system32> reg query HKLM\SYSTEM\CurrentControlSet\Services\iotedge /v Environment
> 
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\iotedge
>     Environment    REG_MULTI_SZ
> 
> PS C:\Windows\system32> reg query HKLM\SYSTEM\CurrentControlSet\Services\iotedge /v Environment
> 
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\iotedge
>     Environment    REG_MULTI_SZ    https_proxy=http://test:80
> 
> PS C:\Windows\system32> reg query HKLM\SYSTEM\CurrentControlSet\Services\iotedge /v Environment
> 
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\iotedge
>     Environment    REG_MULTI_SZ    Test1=a\0Test2=b

**Comment by ancaantochi** [comment] 2019-11-21 21:35
Please try to restart the service then run below commands to get logs. These filters the logs for the past 5 minutes

```
Get-WinEvent -ea SilentlyContinue -FilterHashtable @{LogName='application';StartTime=[datetime]::Now.AddMinutes(-5)} | Select TimeCreated, Message | Sort-Object @{Expression='TimeCreated';Descending=$false} | Format-Table -AutoSize -Wrap   
```  

```
Get-WinEvent -ea SilentlyContinue -FilterHashtable @{LogName='system';StartTime=[datetime]::Now.AddMinutes(-5)} | Select TimeCreated, Message | Sort-Object @{Expression='TimeCreated';Descending=$false} | Format-Table -AutoSize -Wrap  
```

**Comment by MkTru** [comment] 2019-11-22 12:24
The command Get-WinEvent... reports the same 

> 11/22/2019 1:21:04 PM The Azure IoT Edge Daemon service failed to start due to the following error:
>                       The parameter is incorrect.)

To me it seems like a general "windows problem" regarding the "Environment" key.
Could there be a problem with registry virtualization / ACLs?

**Comment by ancaantochi** [comment] 2019-11-23 21:57
Yes, it looks like an issue specific to Windows IoT. I was not able to reproduce.

@jiria, can you please help?

**Comment by lary12** [comment] 2019-11-25 07:57
> When configuring a proxy for the iotedge daemon as documented at https://docs.microsoft.com/en-us/azure/iot-edge/how-to-configure-proxy-support the service no longer starts.
> 
> **Versions**
> 
> * OS: Windows 10 IoT, LTSC, 1809, Build: 17763.107.
> * iotedge 1.0.8 ([208b220](https://github.com/Azure/iotedge/commit/208b2204fd30e856d00b280112422130c104b9f0))
> 
> **Observed Behavior**:
> As soon as the key HKLM\SYSTEM\CurrentControlSet\Services\iotedge\Environment
> 
> * exists (empty)
> * contains any key=value entry
> * contains https_proxy=http://test:80
> * contains our correct proxy configuration
> 
> the iotedge service no longer starts. Deleting the key fixes the issue.
> 
> **Console log**
> 
> > Start-Service iotedge
> > Start-Service : Service 'Azure IoT Edge Daemon (iotedge)' cannot be started due to the following error: Cannot start
> > service iotedge on computer '.'.
> > At line:1 char:1
> > 
> > * Start-Service iotedge
> > * ```
> >     + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
> >    ServiceCommandException
> >     + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
> >   ```
> 
> **Event log**
> 
> > Service Control Manager, EventId: 7040
> > The Azure IoT Edge Daemon service failed to start due to the following error:
> > The parameter is incorrect.
> 
> **Diagnosis**
> 
> * I could not find any relevant information in the event log
> * iotedge check: Same whether Environment key exists or not

10000000

**Comment by jiria** [comment] 2019-11-25 19:42
@MkTru , can you confirm if this reproes on IoT Core or IoT Enterprise?

**Comment by MkTru** [comment] 2019-12-02 09:43
I'm using a fresh install of "Windows 10 IoT Enterprise LTSC 2019" from my Visual Studio Subscription.

@ancaantochi: Which System did you try it on?

Anyway. It really seems like no service will start on that system when creating the Environment key as described in the online documentation. Which is what really confuses me. And I tried it both using scripts and via regedit.

**Comment by seanmcd-msft** [comment] 2019-12-04 01:09
i'm unable to reproduce a problem.  when i add the environment value per the docs it's working for me.  @MkTru when the system is in a failed state what is the output from the entire iotedge key per:
reg query HKLM\SYSTEM\CurrentControlSet\Services\iotedge /s
also, i'd like to double check we're running the exact same version.  what is the output from:
reg query "hklm\software\microsoft\windows nt\currentversion"

**Comment by veyalla** [comment] 2020-01-07 18:13
Closing, please re-open if this still repros and provide the info that @seanmcd-msft requested.

**Closed by veyalla** 2020-01-07 18:13 UTC
Labels: area:iotedged, needinfo, no-issue-activity
