### ISSUE TITLE
Error: container on the default network can connect to upstream  HTTPS / WebSockets port

### ISSUE THREAD

**Issue by yeonhooy** [Azure/iotedge#6791] opened 2022-11-19 00:55 UTC
## Expected Behavior
Create Edge Agent and Edge Hub when the device is child device (low layer device).

## Current Behavior
Runtime is not working due to the "container on the default network can connect to upstream  HTTPS / WebSockets port" is failed. 
TLS (HTTPS, MQTT, AMQP) connections success.  
Please check my Output of iotedge check logs. 

In device's config.toml, I set parent_hostname as gateway machine's hostname. 
When I set hostname as this device machine's hostname instead, it works well. However, in this way, the device machine is connected to IoT Hub directly. I want to make the device is connected to gateway device, instead IoT Hub. 

Also, without changing any settings, it connects once out of 100 times. this is weird..

Also, only upstream HTTPS/Websocket port is not working.. checking MQTT and AMQP for container networking is passed. Please check my Output of iotedge check logs. 

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. I have changed hostname IP to FQDN
2. I have checked that the image is pulled from registry
3. I have checked the TLS connection between gateway and device. 
4.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
√ parent hostname is resolvable from inside container - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
        caused by: SocketError - SocketErrorCode (TimedOut) : Operation timed out
                   One or more errors occurred. (Got bad response: )
        caused by: docker returned exit status: 1, stderr = SocketError - SocketErrorCode (TimedOut) : Operation timed out
                   One or more errors occurred. (Got bad response: )
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
        caused by: Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
                   Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
                   You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
        caused by: Container engine is not configured to rotate module logs which may cause it run out of disk space.
                   Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
                   You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
        caused by: The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
                   Data might be lost if the module is deleted or updated.
                   Please see https://aka.ms/iotedge-storage-host for best practices.
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
        caused by: Could not check current state of edgeHub container
        caused by: docker returned exit status: 1, stderr = Error: No such object: edgeHub
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
 HTTPS / WebSockets port× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to yyh-gateway.southeastasia.cloudapp.azure.com:443
        caused by: Container on the default network could not connect to yyh-gateway.southeastasia.cloudapp.azure.com:443
        caused by: docker returned exit status: 1, stderr = One or more errors occurred. (A task was canceled.)
√ container on the default network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to yyh-gateway.southeastasia.cloudapp.azure.com:443
        caused by: Container on the azure-iot-edge network could not connect to yyh-gateway.southeastasia.cloudapp.azure.com:443
        caused by: docker returned exit status: 1, stderr = One or more errors occurred. (A task was canceled.)
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
    skipping because of not required in this configuration
28 check(s) succeeded.
3 check(s) raised warnings.
4 check(s) raised errors.
2 check(s) were skipped due to errors from other checks.


```
</details>

### Device Information
*Host OS: Ubuntu 20.04
* Architecture: arm64 
* Container OS : Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.2
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4
* Docker/Moby [run `docker version`]: 20.10.21+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>

```

<Paste here between the triple backticks>

```
</details>

## Additional Information
There is no edge-agent logs, edge-hub logs.. 

$sudo iotedge list 

A module runtime error occurred
        caused by: A module runtime error occurred
        caused by: timed out

**Comment by nyanzebra** [comment] 2022-11-22 22:23
@yeonhooy to be clear you have a nested edge setup and want to use web sockets for connection from child to parent? When trying to connect child to parent with AMQP or MQTT it works, but websocket fails. Do you see on parent device calls to fetch the modules? There should be an API Proxy configured which can route requests. I assume there will be some errors in the logs there or maybe no requests at all with websockets. Would mind checking on that?

**Comment by yeonhooy** [comment] 2022-11-23 05:53
@nyanzebra Hi, thanks for response. I also think that the API Proxy connection has a problem. Because I opened 443 port of parent device to listen the API request of child device.  The check logs also said that the 443 port (HTTPS / WebSockets port) connection is wrong. However, I was so weird that TLS connection of 443 port works well.. 
By the way.. good news is that I solved that problem.. 
I applied the child's config file, then applied the parent's config file.. It works good..!! (Before.., I started parent device's runtime, then started child device's runtime) 
The problem was solved, but I don't understand the why it works well now, and why it didn't work before. 
Is the order of starting IoT edge runtime important for connection between parent and child?? or Is it kind of bug??

**Comment by nyanzebra** [comment] 2022-11-23 22:32
@varunpuranik tagging,

Reassigning to @and-rewsmith

**Comment by and-rewsmith** [comment] 2022-11-23 23:44
@yeonhooy The order of starting the runtime on parent / child device should not matter. Some questions:
1. I see you have fixed the problem. Is it possible that you can get the devices back into this state where iotedge web sockets check fails?
2. If you can reproduce the failure, or if you did check the parent device's api proxy logs, can you paste those logs here?
3. When the devices were in a problematic state, how long were they in this state for? I know you said it would fail connection 100 times so I am assuming this error would persist and not recover.
4. With these sort of weird behaviors, it is good to have iotedge check green in all possible areas before proceeding, as other errors in iotedge check may signal a more fundamental problem. In your iotedge check results I see there is a problem with this check `configuration has correct URIs for daemon mgmt endpoint`. Did you do anything to manually configure the uris for iotedge mgmt endpoint?

**Comment by yeonhooy** [comment] 2022-11-24 01:34
@and-rewsmith Thanks for response.
 1. Yes, before I mentioned, if I start parent device's runtime first, then the web sockets check goes back fail. 
 2. I attach the parent's proxy log file when the error exists.
 [yhdev1_IoTEdgeAPIProxy_Logs.txt](https://github.com/Azure/iotedge/files/10080172/yhdev1_IoTEdgeAPIProxy_Logs.txt)
 3. "100 time" means that I tried the 100 times for restarting the iotedge runtime. In that cases, It seems to have succeeded once when the child runtime is executed first. But, I didn`t find that fact last week. 
 Further, If web sockets/https fail, error stays till the end. 
 4.  `configuration has correct URIs for daemon mgmt endpoint ` seems to related the web socket / HTTP fail. The two errors don't seem to be independent.

**Comment by and-rewsmith** [comment] 2022-11-28 20:39
@yeonhooy Thanks for the information.

I looked at the IoTEdgeAPIProxy_Logs.txt file you shared. Is this log line and ip address from the child device where you ran iotedge check?
```
2022/11/24 01:30:37 [info] 10#10: *2363 client closed connection while waiting for request, client: 20.198.169.15, server: 0.0.0.0:443
```

**Comment by yeonhooy** [comment] 2022-11-29 02:08
@and-rewsmith yes, `client: 20.198.169.15` is child device's Ip address.

**Comment by and-rewsmith** [comment] 2022-12-01 03:17
@yeonhooy I could not reproduce this issue. I started the child's runtime after the parent. I suspect that this issue is specific to your setup and a support bundle will be needed. 

Can you please open a support ticket as our policy is to not show confidential information here?

**Comment by yeonhooy** [comment] 2022-12-01 03:47
@and-rewsmith Appreciate for checking my problem. In my progress, I just set my environment by starting child's runtime first. But, it does not make any other problem. So, I will do my work in here. If I struggle with another problem, I will open support ticket. 
Thanks!

**Closed** 2022-12-02 02:41 UTC
Labels: iotedge, customer-reported
