### ISSUE TITLE
Custom modules getting disconnected to IoT hub after  24 hours

### ISSUE THREAD

**Issue by arnabhetc** [Azure/iotedge#1979] opened 2019-11-11 08:22 UTC
## Expected Behavior
Running multiple custom module and using transparent gateway solution where leaf device is configured with X.509 certificates, using MQTT protocol 

## Current Behavior
custom modules are running fine  but  modules getting failed after ~24 hours and getting " Transient network error " ( more details in logs), No network disconnection observed

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Running all the IoTEdge modules 
2. Start the transparent gateway IoT device 
3.  After  ~24 hours , getting data from leaf device but module getting disconnected from IoT hub.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname mygateway.local but device reports hostname EdgeDevice.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: certificates - OK
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
√ production readiness: logs policy - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
√ Edge Hub can bind to ports on host - OK

22 check(s) succeeded.
1 check(s) raised errors.

```
</details>

### Device Information
* Host OS : Ubuntu 16.04 
* Architecture : arm64
* Container OS : Linux containers

### Runtime Versions
* iotedged : iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0) 
* Edge Agent :  mcr.microsoft.com/azureiotedge-agent:1.0.8.3
* Edge Hub : mcr.microsoft.com/azureiotedge-hub:1.0.8.3
* Docker/Moby : 3.0.6

## Logs

<details>
<summary>edge-agent logs</summary>

Go to this link to download the log file -->   [LINK](https://drive.google.com/file/d/1mlg2UANsYhUcTkfivlS38_lJUZCoif0c/view?usp=sharing)

</details>

<details>
<summary>edge-hub logs</summary>

Go to this link to download the log file -->   [LINK](https://drive.google.com/open?id=1cVAxeDtb0sum4JJz1aE_SSWNC2YF_Xtg)

</details>

**Comment by myagley** [comment] 2019-11-11 16:12
Hello. Is it possible to get logs from the `iotedged` as well? Specifically from the time `2019-11-10 10:20:00.000` going forward?

`journalctl -u iotedge --since "2019-11-10 10:00:00.000" > iotedge.log` and send the `iotedge.log`

There are some unexpected errors in the Edge Hub logs and these logs should help to fill in some missing information.

**Comment by arnabhetc** [comment] 2019-11-11 17:03
Hey Mike, 
Thanks for replying, I would like to let you know that, I have restated the IoT edge to get our services running.. So still can I retrieve those logs..

**Comment by myagley** [comment] 2019-11-11 18:13
You should still be able to get the logs. It is a little dependent on how `journald` is configured on the host machine, which will determine how long the logs are stored for.

**Comment by arnabhetc** [comment] 2019-11-12 04:33
Hi Mike,
I tried, its seems the logs are there from Nov 11 12:06:15 
You can take a look from  **[here](https://drive.google.com/open?id=1tVAqhizK6ASU0btKCvBO0v_51JxxlcVU)**

**Comment by philipktlin** [comment] 2019-11-15 23:59
Since we don't have iotedged log from Nov 10 10:20 forward, we can't find out the root cause.  Base on edgeAgent and edgeHub log, there is something wrong that parsermodule can't be started up.  Please keep monitoring and if happens again, provide logs of iotedged, edgeAgent and edgeHub and all other module logs for investigation.

**Comment by philipktlin** [comment] 2019-11-16 00:00
I will leave this issue open for now; and it will go to stale automatically after 30 days.

**Comment by arnabhetc** [comment] 2019-11-22 06:26
Hi , 

I faced the same issue in the gateway once more the same error, 

**version of Edge run time** --> 

`edgeHub                 running          Up a day         mcr.microsoft.com/azureiotedge-hub:1.0.8
`
`edgeAgent               running          Up a day         mcr.microsoft.com/azureiotedge-agent:1.0.8`

**The  error I faced in the one of the custom module  parsermodule**  --> 

```
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at parsermodule.Program.PublishMessage(Object userContext, Object dataPayload, String packetType) in /app/Program.cs:line 877
   at parsermodule.Program.HeartbeatTask(Object userContext, Object userContext1) in /app/Program.cs:line 904
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Here I will give the logs for the more clarity --> 
EdgeAgent logs ---> **[HERE](https://drive.google.com/open?id=1rkbvAsDdAwZfOv8xw843IYvS5nDqf_Vo)** 

EdgeHub logs -->  **[HERE](https://drive.google.com/open?id=1-itW5kQ627Wzygxs9Eq00Gh95VdIxb4R)**

Custom Module logs  [parsermodule] --> **[HERE](https://drive.google.com/open?id=1NCXm8LDNN4LUnML41QANSWFM0FXS0HhH)**

This time I am adding all the journalctl logs i have for iotedge ,
 
jurnalctu iotedge logs --> **[HERE](https://drive.google.com/open?id=1t5Vu8lcu_HYSpDwJEos4jlH_S4VikhXo)**

**Comment by arnabhetc** [comment] 2019-11-22 14:53
Hi, 

One more of our running gateway failed using the same issue above ---> 

Error in the custom module is [pasermodule] --> 

```
Unhandled Exception: Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.SendMessageAsync(IChannelHandlerContext context, Message message)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttIotHubAdapter.WriteAsync(IChannelHandlerContext context, Object data)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass22_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass14_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(String outputName, Message message)
   at parsermodule.Program.PublishMessage(Object userContext, Object dataPayload, String packetType) in /app/Program.cs:line 836
   at parsermodule.Program.HeartbeatTask(Object userContext, Object userContext1) in /app/Program.cs:line 863
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
Here I will give the logs for the more clarity -->

EdgeAgent logs ---> **[HERE](https://drive.google.com/open?id=1Nr0lInCLwQieyiydUjBw163P4-FMqRt0)**

EdgeHub logs --> **[HERE](https://drive.google.com/open?id=1f9YkzGMNKwiiblZpcrDwVxp9gPeQ1r54)**

Custom Module logs [parsermodule] --> **[HERE](https://drive.google.com/open?id=1Y0ucR3u_-kL8Y15IBgCUMuBHV3Ko5Fjk)**


jurnalctu iotedge logs --> **[HERE](https://drive.google.com/open?id=1kAyXeIlQpq_fdrrYuGeR9TqToBqqOTUE2p2hLN_DstQ)**

NOTE - Module is not getting restarted when the error comes, even after restarting with 
`iotedge restart <module name>`
it's not getting restarted just stuck in the same place...

**Comment by arsing** [comment] 2019-12-03 01:14
The `parsermodule` logs have no timestamps, so I can only guess what the correlation between the `parsermodule` logs and Edge Hub logs is.

Edge Hub says:

```
<6> 2019-11-22 12:43:26.633 +00:00 [INF] - Reauthenticating connected clients
<6> 2019-11-22 12:43:26.633 +00:00 [INF] - Error authenticating token for AaeonMVP2EdgeTest0001/parsermodule because the token is expired or could not be parsed
<6> 2019-11-22 12:43:26.634 +00:00 [INF] - Credentials for client AaeonMVP2EdgeTest0001/parsermodule are not valid.
<4> 2019-11-22 12:43:26.634 +00:00 [WRN] - Reauthenticating client AaeonMVP2EdgeTest0001/parsermodule failed, removing client connection
```

Indeed, `parsermodule` is using MQTT which can't refresh the token in-band (like AMQP can), so I believe it's expected that Edge Hub will disconnect the module and expect it to reconnect with a new token. @varunpuranik Is my understanding correct?

Edge Hub also has transient connectivity issues to IoT Hub, but I don't think there's any correspondence between that and disconnecting the user module; the latter appears to be happening entirely because the auth expires.

**Comment by arnabhetc** [comment] 2019-12-03 06:54
Hi @arsing,
I  have one more gateway that failed, this time it was running the edge agent and edge hub with 1.0.8.4 versions,

we are using transparent gateway solution with leaf device authentication [ connection string] 

I am posting logs  --> 

EdgeHub logs -->
[edgeHub_log.txt](https://github.com/Azure/iotedge/files/3915004/edgeHub_log.txt)

EdgeAgent logs-->
[edgeAgent_log.txt](https://github.com/Azure/iotedge/files/3915005/edgeAgent_log.txt)

custom modules ->
[parsermodule_log.txt](https://github.com/Azure/iotedge/files/3915009/parsermodule_log.txt)

journal logs --> 
[journalctu_logs.txt](https://github.com/Azure/iotedge/files/3915013/journalctu_logs.txt)

This time also after restarting the custom module did not help!

**Comment by varunpuranik** [comment] 2019-12-09 21:45
@arnabhetc - 
From the logs on both your gateway devices, I see the same thing- 
- The module parsermodule connects to EdgeHub, and functions normally
- After one hour, EdgeHub drops its token because the token is expired.
- The module re-connects to EdgeHub, but none of the operations work correctly. In particular, EdgeHub does not get feedback for the messages sent to the module.

What SDK is the leaf device using?

Also, what do you mean by restarting the module does not help and it gets stuck? Does it connect to EdgeHub? Or does that fail as well? Do you have EdgeHub logs for that part of the scenairo?

**Comment by arnabhetc** [comment] 2019-12-10 17:32
Hi @varunpuranik  
Thanks for your reply, 

- I am using azure [IoT python device SDK  v1](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated) SDK, as the latest SDK is in the preview we are not using that. 

-  in the logs, you can see with one exception the parser module fails, but according to the nature of edge it should auto restart the module and the module should work normally, but in this case, the parser module did not recover and could not process the data from the leaf device, but the nothing fails edgeHub and edgeAgent works with other custom modules, suppose now I try to restart the parser module manually by running `IoT edge restart parsermodule` even after that it won't process data from leaf device.  **the logs are already there included** 

- we are using the leaf device and same parsermodule in our production more than 7 months never faced this issue,  running edge version is 1.0.5 there, due to the storage problem issue with that edge version, we upgraded to 1.0.8.x, since then we are facing this issue.

**Comment by pietersap** [comment] 2019-12-16 11:48
I have [opened an issue](https://github.com/Azure/iotedge/issues/2134) that might be related. It includes detailed logs from edgeAgent, edgeHub and the iotedged service.

**Comment by lt72** [comment] 2019-12-19 17:37
@dmolokanov can you please take a look at this one?

**Comment by dmolokanov** [comment] 2019-12-20 18:18
Hi @arnabhetc! While we are investigating this issue on our side you may want to try python sdk v2 that was GA recently https://github.com/Azure/azure-iot-sdk-python.

**Comment by dmolokanov** [comment] 2020-01-06 19:35
Hi @arnabhetc. We have been running the test setup for more than 2 weeks now. Unable to reproduce this issue. I'm closing this issue for now. Feel free to re-open it if you still have it after an update to the latest Python SDK. Thanks!

**Closed by dmolokanov** 2020-01-06 19:35 UTC
Labels: area:connectivity, needinfo
