### ISSUE TITLE
How to stop IoT edge module using powershell command?

### ISSUE THREAD

**Issue by keshava-hm** [Azure/iotedge#2047] opened 2019-11-27 05:54 UTC
We have iotedge restart command to restart the module. But how to stop an iot edge module using powershell command?

There's a stop - and - start command for docker, but iot edge module restarts after few seconds automatically.

Any workaround/solution will be helpful.

Thanks
Keshava G N

**Comment by MPapst** [comment] 2019-11-27 07:43
That is done by the edgeAgent.
As IoTEdge is a cloud managed application, you are in need to set the module in stop using the cloud backend (which is the IoTHub) by using the „set modules“ function in the Azure Portal.

**Comment by keshava-hm** [comment] 2019-11-27 08:11
Thanks for the response, @MPapst . My requirement is to stop and start the module when I'm accessing a hardware resource (COM port) which is accessed by the module as well. I know that I can stop all the modules using stop-service iotedge command. But is there a similar command to just stop one module?

Stopping from portal is not useful for me. So, is there a way to do this from powershell ?

Thanks.

**Comment by MPapst** [comment] 2019-11-27 09:22
@keshava-hm there is the api you could use instead  of the Portal. I am not sure If there is a pwsh implementation for the module api. Nevertheless, I would Not recommend for Most Szenarios to have device management credentials on the edge device!
Is your requirement really to stop the module? If you can leave it running and just release some ressources, I would go for an interop implementation and handle the resource release inside the module code.
If this is possible, depends on your requirement.

**Comment by keshava-hm** [comment] 2019-11-28 03:52
> @keshava-hm there is the api you could use instead of the Portal. I am not sure If there is a pwsh implementation for the module api. Nevertheless, I would Not recommend for Most Szenarios to have device management credentials on the edge device!
> Is your requirement really to stop the module? If you can leave it running and just release some ressources, I would go for an interop implementation and handle the resource release inside the module code.
> If this is possible, depends on your requirement.

Thanks @MPapst . Yes, I'm checking to do it in the module, but main requirement is to stop the module and start it later. This is because, I have an MSI, installing which needs com port to be released which is being used by module.

**Comment by varunpuranik** [comment] 2019-12-04 19:39
@keshava-hm Starting and stopping of the modules depends on the IoT Edge deployment on the device, and is controlled by EdgeAgent by design. 
If you want to stop the module, the way to do that is to create a new deployment with the module status as Stopped. You can also stop the entire IoT Edge runtime ($>sudo systemctl stop iotedge), which will stop the modules as well.

**Comment by varunpuranik** [comment] 2019-12-04 19:39
I will close this issue. If you have any other questions or concerns, please feel free to re-open it or file a new one.

**Closed by varunpuranik** 2019-12-04 19:39 UTC
Labels: enhancement, question
