### ISSUE TITLE
iot edge devops plugin can't support  Azure Container service in China in Publish and Deploy

### ISSUE THREAD

**Issue by wenboyang214** [Azure/iotedge#898] opened 2019-03-01 09:43 UTC
I am testing the e2e solution in iot edge cicd using Azure DevOps iot edge plugins.

I found that the **iot edge plugins** does not support China Azure container service very well in **Publish** and **deployment** 

**already done below in connection service:**
1.  Connection service using China AAD service principal
2. a credential of Generic Docker registry 

**my issues:**
when do the publish, I can't list China Azure Container service (seem that the azure management api isn't able to list the ACR services in China). so my choice is the using a Generic docker registry instead.
![image](https://user-images.githubusercontent.com/18303105/53629033-8a2c1480-3c47-11e9-8a06-3d89117d08ab.png)
![image](https://user-images.githubusercontent.com/18303105/53629038-8f895f00-3c47-11e9-928e-580c7b033a3a.png)

when using Generic Docker Registry we found another problem in doing deploy into azure iot edge devices
I can find the build-ed image in China ACR after build and publish but can't achieve the deployment (can't pull the image from ACR to edge device) even the Azure DevOps service does not show any errors. 

I have also check the deployment file in azure devops artifact, the credential parameters are actually in
            **"registryCredentials": {
              "wbmooncakeacr": {
                "username": "$CONTAINER_REGISTRY_USERNAME_wbmooncakeacr",
                "password": "$CONTAINER_REGISTRY_PASSWORD_wbmooncakeacr",
                "address": "wbmooncakeacr.azurecr.cn"
              }**

**one word to summary:**
**Can do Push but can't be able do the Pull.**

Can any one show some suggestions ?

**Comment by myagley** [comment] 2019-03-01 17:20
@shizn can you please help look at this?

**Comment by shizn** [comment] 2019-03-01 19:08
Thanks for looping me in. @wenboyang214 I think we are in same email threads talking about the Mooncake issue. And the latest reply from you mentioned that it works. 
You mentioned that edgeAgent cannot pull down the image from Mooncake ACR, could you share the error logs from edgeAgent? So this can help identify the root cause.

**Comment by CindyXing** [comment] 2019-10-23 00:00
@wenboyang214, can we close this issue now? If I understand correctly, ACR supports mirror now in China. Thanks.

**Comment by lt72** [comment] 2019-11-19 17:56
Closing this issue as it seems stale. Please re-open as needed.

**Closed by lt72** 2019-11-19 17:56 UTC
