### ISSUE TITLE
Edge Agent reconcile exception

### ISSUE THREAD

**Issue by simardst** [Azure/iotedge#528] opened 2018-11-08 20:44 UTC
From a clean iot edge runtme install, I create a deployement with only the egdeAgent and the edgeHub module.  When starting, the edgeAgent is always complaining because os an ArgumentNullException.

## Expected Behavior
No exception

## Current Behavior
Argument Null Exception

### Device (Host) Operating System
Ubuntu 18.04

### Architecture
amd64

### Container Operating System
 Linux containers

#### iotedged
iotedge 1.0.4

#### Edge Agent
mcr.microsoft.com/azureiotedge-agent:1.0

#### Edge Hub
mcr.microsoft.com/azureiotedge-hub:1.0

#### Docker
3.0.1

## Logs
![image](https://user-images.githubusercontent.com/1949586/48226040-a4767580-e36c-11e8-8102-d18b3fb87fe9.png)

**Comment by mrohera** [comment] 2018-11-08 22:21
Thanks for reporting this issue. Couple of things to note: 

* If you have used the portal we have noticed this recent behavior where instead of an empty JSON object {} a null is being set by default. A quick fix is to adjust the CreateOptions of the $edgeAgent and set it to {}. This you can do easily in the portal by navigating to your edge device ->click "Set Modules" -> click "Configure advanced Edge Runtime settings" --> Scroll to the $edgeAgent section and add {}. --> click Save and follow all the UI prompts and finally hit submit. The device should recover once this is set.

* We can add changes to the Edge Agent to be tolerant to this as well.

**Comment by mrohera** [comment] 2018-11-08 22:31
I would also like to note that this will be fixed in the portal as well in short order.

**Comment by mrohera** [comment] 2018-11-09 18:30
I wanted to follow up to see if the workaround mentioned above has worked for you. Please let us know if there is anything else we can help with.

**Comment by simardst** [comment] 2018-11-09 18:33
Yes, the workaround works.

However, I had trouble to deploy new images.  I'm still trying to find the
repro steps.  I'll create another bug if I figure out out to fall into this
state.

**Comment by myagley** [comment] 2018-11-28 17:02
I'm going to close this issue as the root cause was the Azure portal setting the createOptions to the string null (`"null"`). This is a deserialization error and the runtime was ultimately doing the correct thing.

**Closed by myagley** 2018-11-28 17:02 UTC
Labels: bug
