### ISSUE TITLE
EdgeAgent don't start anymore after applying proxy configuration (reproduced on 3 different devices)

### ISSUE THREAD

**Issue by Jeroenqu** [Azure/iotedge#1899] opened 2019-10-24 12:58 UTC
## Expected Behavior
Iotedge list should return 1 module (edgeagent) and EdgeAgent should start.

## Current Behavior
iotedge list returns 0 modules without EdgeAgent.

<6> 2019-10-24 19:19:11.401 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"EnableUploadLogs":false}
<0> 2019-10-24 19:19:11.454 +00:00 [FTL] - Fatal error building application.
System.FormatException: Malformed Token
   at Microsoft.Azure.Devices.Common.CommonExtensionMethods.ToDictionary(String valuePairString, Char kvpDelimiter, Char kvpSeparator)
   at Microsoft.Azure.Devices.IotHubConnectionStringBuilder.Parse(String iotHubConnectionString)
   at Microsoft.Azure.Devices.IotHubConnectionStringBuilder.Create(String iotHubConnectionString)
   at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 117

 Error in watchdog when checking for edge runtime status:
okt 24 14:37:52 jeroenlin iotedged[1437]: 2019-10-24T12:37:52Z [WARN] - A module runtime error occurred.
okt 24 14:37:52 jeroenlin iotedged[1437]: 2019-10-24T12:37:52Z [WARN] -         caused by: Could not get identity $edgeAgent
okt 24 14:37:52 jeroenlin iotedged[1437]: 2019-10-24T12:37:52Z [WARN] -         caused by: Could not get module $edgeAgent
okt 24 14:37:52 jeroenlin iotedged[1437]: 2019-10-24T12:37:52Z [WARN] -         caused by: Could not perform HTTP request
okt 24 14:37:52 jeroenlin iotedged[1437]: 2019-10-24T12:37:52Z [WARN] -         caused by: an error occurred trying to …ror 

## Steps to Reproduce

1.Follow https://docs.microsoft.com/nl-nl/azure/iot-edge/how-to-configure-proxy-support

**docker** 
https-proxy.conf

[Service]
Environment="HTTPS_PROXY=https://192.168.251.254:3128/"

**Config.yaml**
 agent:
  name: "edgeAgent"
  type: "docker"
  env:
     https_proxy: "https://192.168.251.254:3128"
     UpstreamProtocol: "AmqpWs"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}

**Environment**
[Service]
Environment="https_proxy=https://192.168.251.254:3128"

## Context (Environment)
Ubuntu 18.04 LTS
### Output of `iotedge check`

jeroen@jeroenlin:~$ sudo iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
‼ production readiness: certificates - Warning
    Device is using self-signed, automatically generated certs.
    Please see https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: certificates expiry - OK
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
× Edge Hub can bind to ports on host - Error
    Could not check current state of Edge Hub container

20 check(s) succeeded.
2 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
<details>
<summary>Click here</summary>

`

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS, Ubuntu 18.04 
* Architecture [amd64]: 
* Container OS [Linux containers] 

### Runtime Versions
* iotedged [1.0.8]: 
* Edge Agent [1.0.0]: 
* Edge Hub [1.0.8]: 
* Docker/Moby [3.0.8]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

**Comment by dmolokanov** [comment] 2019-10-24 21:21
Hello @Jeroenqu,
Could you please provide more logs for both EdgeAgent and iotedged? Edge Agent [1.0.0] seems like a very old version and should not be used anymore. We need more information to investigate this issue. Thanks!

**Comment by Jeroenqu** [comment] 2019-10-25 14:48
Good observation! I've updated the EdgeAgent to 1.0.8, but unfortunately still not working. It is an pending item for our 2k device deployment, so we would be more than happy when this issue would be resolved. 

Thanks in advance! 

The logs:
![image](https://user-images.githubusercontent.com/56964303/67580750-23fc8080-f747-11e9-8eb7-837d9deb3213.png)

![image](https://user-images.githubusercontent.com/56964303/67580764-2b238e80-f747-11e9-8eb8-dc7b08247d24.png)

**Comment by vipeller** [comment] 2019-10-28 23:46
@Jeroenqu According to the error message, $edgeAgent doesn't have it's twin setup correctly and has an empty block for the "desired properties" section. This section should specify what other modules should be deployed on your device. As this is missing, that is why you get a fatal error.
The first step should be to check if this is the case.
Could you login the azure portal, search for your IoT hub (e.g. testhub) name then select it, then search for "IoT Edge" on the left side of the screen (this is under "Automatic Device Management")

This should lead to your device list, please select the device in questions. Now you should see a module list at the bottom half of the screen, with a module name $edgeAgent. If you click this, a screens shows up wit "IoT Edge Module Details", and at the top section of the screen you should see "Module Identity Twin". Click that, it will lead you to an editor showing the module twin for edge agent.

In normal cases, you should see something similar structure:

 "version": 5,
  "properties": {
    "desired": {
      "modules": {
        "SimMod": {
          "settings": {
            "image": "simmid",
            "createOptions": ""
          },
          "type": "docker",
          "status": "running",
          "restartPolicy": "always",
..... many more.....

but in your case, according to the error message, this is empty. Could you confirm it for me?

**Comment by Jeroenqu** [comment] 2019-10-30 15:29
Thanks.

I think the below happens:

1. Initial iotedge load with internet connectivity.
2. Healthy state of the deployment config.
3**. Proxy configuration with a proxy which actually don't exist yet.**
4. Restart of iotedge, cleaning deployment config, attempt to get a new one.
5. Broken state. 

![image](https://user-images.githubusercontent.com/56964303/67872534-64d30b80-fb32-11e9-9ea8-15af3a67e13b.png)

**Comment by vipeller** [comment] 2019-10-30 16:29
@Jeroenqu thank you for the screenshot. It shows that the "modules" part is empty - that what tells $edgeAgent what modules are needed on the edge-device. At minimum edgeAgent and edgeHub should be there.

You are saying that before applying proxy settings it was all good and then it get deleted somehow?

**Comment by Jeroenqu** [comment] 2019-10-30 16:32
@vipeller  yes, exactly. Jus fill in a fake proxy on the three required config locations (docker, daemon, agent) and you will experience the same situation.

**Comment by Jeroenqu** [comment] 2019-10-30 16:36
> @Jeroenqu ok I try it. is the systemModules part populated well? I made a mistake saying that moduels should have edgeAgent and edgeHub. systemModules should

I need to commute, let you know in the evening. Thanks for looking at my issue!

**Comment by Jeroenqu** [comment] 2019-10-31 11:10
@vipeller see the systemModules population.
![image](https://user-images.githubusercontent.com/56964303/67942037-35c2a580-fbd7-11e9-9b89-2fec0aff7d6e.png)

These were updated while I had the non-proxy setup. After the fake proxy setup, it will corrupt the offline json file which results in not starting the edgeAgent.

**Comment by Jeroenqu** [comment] 2019-11-06 15:24
Guys? @vipeller @dmolokanov

**Comment by vipeller** [comment] 2019-11-06 17:36
@Jeroenqu sorry, I haven't tried it yet. I am going to reproduce it in a couple of hours and let you know if managed to make the settings disappear - from that point we can chase down the root cause.

**Comment by vipeller** [comment] 2019-11-06 18:01
@Jeroenqu I wanted to setup the environment in your description, but then reading it through I realized that all proxy settings (docker, edge daemon, agent) are 'offline' and it wouldn't take effect on the agent desired properties stored in the cloud (describing the modules to be downloaded for edge)

could we try to:
1) restore edgeAgent desired properties section in your twin
2) see if in that case the system starts up with your current settings
3) remove/add back the proxy settings to see if the twin properties get deleted again?

**Comment by Jeroenqu** [comment] 2019-11-08 14:46
> @Jeroenqu I wanted to setup the environment in your description, but then reading it through I realized that all proxy settings (docker, edge daemon, agent) are 'offline' and it wouldn't take effect on the agent desired properties stored in the cloud (describing the modules to be downloaded for edge)
> 
> could we try to:
> 
> 1. restore edgeAgent desired properties section in your twin
> 2. see if in that case the system starts up with your current settings
> 3. remove/add back the proxy settings to see if the twin properties get deleted again?

Hi, bit busy these days. Sorry for the delay, but I will pick it up in the weekend.

**Comment by ancaantochi** [comment] 2019-11-19 19:00
@Jeroenqu, 
I noticed in iotedged logs that it fails to get edgeAgent identity because the certificate validation fails, it looks like a self signed certificate is used by the https_proxy. Did you install the certificate http proxy CA on the machine? 

You can do a quick check to see if the certificate validation passes when connecting to the proxy:

`openssl s_client -connect 192.168.251.254:3128 `

If this check fails you have to install the CA cert on the machine (for Ubuntu):

```
sudo cp <path>/proxy-ca.cert.pem /usr/local/share/ca-certificates/proxy-ca.cert.pem
sudo update-ca-certificates
```

**Comment by Jeroenqu** [comment] 2019-11-20 12:25
@ancaantochi thanks for your reply. You're right, I've requested the proxy certificate from the service supplier. The previous remark from the service supplier was that it is only required for SSL deep packet inspection, which they didn't turn on.

![image](https://user-images.githubusercontent.com/56964303/69238816-21037d00-0b99-11ea-9037-e2e90d226700.png)

**Comment by ancaantochi** [comment] 2019-11-22 19:30
@Jeroenqu, was the issue fixed in edgeAgent after the proxy certificate was installed?

**Comment by ancaantochi** [comment] 2019-11-23 21:51
It looks that the problem  was because of the proxy certificate, I will close this issue, please reopen if needed.

**Closed by ancaantochi** 2019-11-23 21:51 UTC
Labels: area:edgeagent, needinfo

**Comment by Jeroenqu** [comment] 2019-11-25 13:35
> It looks that the problem was because of the proxy certificate, I will close this issue, please reopen if needed.

I've installed the certifiate, and still busy validating the outcome with the supplier.

**Comment by anilchoudhury** [comment] 2021-04-22 07:53
I think the problem may be with DNS.
Check the content of '/etc/docker/daemon.json' file as this defines the DNS servers.

To get the DNS server for your device, run the following command:
```
~ $ nslookup -type=any google.com
Server: 192.168.7.1
Address: 192.168.7.1:53
Non-authoritative answer:
Name: google.com
Address: 142.250.191.206
google.com nameserver = ns1.google.com
google.com nameserver = ns4.google.com
google.com nameserver = ns2.google.com
google.com nameserver = ns3.google.com
```

DNS Server: 192.168.7.1
Update the file with DNS settings. 
```
~ $ cat /etc/docker/daemon.json
{
    "dns": ["192.168.7.1"]
}
```
Also ensure that you have set proxy settings for docker and iotedge in following paths:
```
~ $ cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTPS_PROXY=<proxy address:port>
Environment="HTTP_PROXY=<proxy address:port>
Environment="NO_PROXY=localhost,127.0.0.1"

~ $ cat /etc/systemd/system/iotedge.service.d/http-proxy.conf
[Service]
Environment="HTTPS_PROXY=http://proxy.etn.com:8080"
Environment="HTTP_PROXY=http://proxy.etn.com:8080"
Environment="NO_PROXY=localhost,127.0.0.1"
```

In 'Edge Agent module spec' section of '/etc/iotedge/config.yaml' file:
```
agent:
  name: "edgeAgent"
  type: "docker"
  env:
    https_proxy: "http://proxy.corp.com:8080"
    http_proxy: "http://proxy.corp.com:8080"
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.1"
    auth: {}
```

Later restart all services:
~$ sudo systemctl daemon-reload
~$ sudo systemctl restart docker

check docker running status:
~ $ sudo journalctl -u docker | tail

~$ sudo systemctl restart iotedge

Check iotedge running status:
~ $ sudo journalctl -u iotedge | tail

You can also check iotedge status but its less importance as I am getting 12 errors, still i am able to access IotEdge and able to deploy containers from cloud:
~ $ sudo iotedge check 2>&1 | tee /tmp/iotedge-check.log
