### ISSUE TITLE
Error during edgeHub startup as connection not yet established

### ISSUE THREAD

**Issue by sebader** [Azure/iotedge#500] opened 2018-10-30 12:38 UTC
## Expected Behavior
No errors during normal startup

## Current Behavior
In our case our EdgeHub connects via AMQP_Websockets (over a Proxy server) to the cloud. This seems to take longer than the edgeHub usually expects and thus it gives this warning/error:
2018-10-30 12:18:14.606 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...

## Steps to Reproduce
1. Connect edgeHub over AMQP_WebSockets

### Device (Host) Operating System
Windows 10 Enterprise

### Architecture
amd64

### Container Operating System
Linux container

#### iotedged
1.0.3

#### Edge Agent
1.0.3

#### Edge Hub
1.0.3

#### Docker
18.06.1-ce

## Logs
[2018-10-30 12:18:05 : Starting Edge Hub
[10/30/2018 12:18:05.574 PM] Edge Hub Main()
2018-10-30 12:18:12.201 +00:00 [INF] - Created persistent store at /tmp/edgeHub
2018-10-30 12:18:12.370 +00:00 [INF] - Starting Edge Hub
2018-10-30 12:18:12.379 +00:00 [INF] - Version - 1.0.3.17521421 (1ccb9b0728cd046f89a7d6eb0af000b3cbd7bb6a)
2018-10-30 12:18:12.380 +00:00 [INF] -
        ¦¦¦¦¦+ ¦¦¦¦¦¦¦+¦¦+   ¦¦+¦¦¦¦¦¦+ ¦¦¦¦¦¦¦+
       ¦¦+--¦¦++--¦¦¦++¦¦¦   ¦¦¦¦¦+--¦¦+¦¦+----+
       ¦¦¦¦¦¦¦¦  ¦¦¦++ ¦¦¦   ¦¦¦¦¦¦¦¦¦++¦¦¦¦¦+
       ¦¦+--¦¦¦ ¦¦¦++  ¦¦¦   ¦¦¦¦¦+--¦¦+¦¦+--+
       ¦¦¦  ¦¦¦¦¦¦¦¦¦¦++¦¦¦¦¦¦++¦¦¦  ¦¦¦¦¦¦¦¦¦¦+
       +-+  +-++------+ +-----+ +-+  +-++------+

 ¦¦+ ¦¦¦¦¦¦+ ¦¦¦¦¦¦¦¦+    ¦¦¦¦¦¦¦+¦¦¦¦¦¦+  ¦¦¦¦¦¦+ ¦¦¦¦¦¦¦+
 ¦¦¦¦¦+---¦¦++--¦¦+--+    ¦¦+----+¦¦+--¦¦+¦¦+----+ ¦¦+----+
 ¦¦¦¦¦¦   ¦¦¦   ¦¦¦       ¦¦¦¦¦+  ¦¦¦  ¦¦¦¦¦¦  ¦¦¦+¦¦¦¦¦+
 ¦¦¦¦¦¦   ¦¦¦   ¦¦¦       ¦¦+--+  ¦¦¦  ¦¦¦¦¦¦   ¦¦¦¦¦+--+
 ¦¦¦+¦¦¦¦¦¦++   ¦¦¦       ¦¦¦¦¦¦¦+¦¦¦¦¦¦+++¦¦¦¦¦¦++¦¦¦¦¦¦¦+
 +-+ +-----+    +-+       +------++-----+  +-----+ +------+

2018-10-30 12:18:12.381 +00:00 [INF] - Installing intermediate certificates.
2018-10-30 12:18:12.486 +00:00 [INF] - Started task to cleanup processed and stale messages
2018-10-30 12:18:12.496 +00:00 [INF] - Created new message store
2018-10-30 12:18:12.523 +00:00 [INF] - Created device scope identities cache
2018-10-30 12:18:12.642 +00:00 [INF] - Starting refresh of device scope identities cache
2018-10-30 12:18:13.147 +00:00 [INF] - Initializing configuration
2018-10-30 12:18:13.267 +00:00 [INF] - New device connection for device MYDEVICEID/$edgeHub
2018-10-30 12:18:13.555 +00:00 [INF] - Attempting to connect to IoT Hub for client MYDEVICEID/$edgeHub via AMQP over WebSocket...
2018-10-30 12:18:14.027 +00:00 [INF] - Created cloud proxy for client MYDEVICEID/$edgeHub via AMQP over WebSocket, with client operation timeout 20000.
2018-10-30 12:18:14.047 +00:00 [INF] - Initialized cloud proxy 30d53f04-565e-459a-9928-5f73f74ad302 for iiot-edge-pl-polk-003-2/$edgeHub
2018-10-30 12:18:14.049 +00:00 [INF] - Created cloud connection for client MYDEVICEID/$edgeHub
2018-10-30 12:18:14.079 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client MYDEVICEID/$edgeHub.
2018-10-30 12:18:14.606 +00:00 [WRN] - Encountered an error while refreshing the device scope identities cache. Will retry the operation in some time...
2018-10-30 12:18:14.864 +00:00 [INF] - Processing subscription Methods for client MYDEVICEID/$edgeHub.
2018-10-30 12:18:21.714 +00:00 [INF] - Cloud connection for MYDEVICEID/$edgeHub is True
2018-10-30 12:18:21.767 +00:00 [INF] - Connection status for MYDEVICEID/$edgeHub changed to ConnectionEstablished
2018-10-30 12:18:21.789 +00:00 [INF] - Processing subscriptions for client MYDEVICEID/$edgeHub.
2018-10-30 12:18:21.827 +00:00 [INF] - Exiting disconnected state
2018-10-30 12:18:21.837 +00:00 [INF] - Entering connected state
2018-10-30 12:18:21.899 +00:00 [INF] - Processing subscription DesiredPropertyUpdates for client MYDEVICEID/$edgeHub.
2018-10-30 12:18:21.930 +00:00 [INF] - Processing subscription Methods for client MYDEVICEID/$edgeHub.
2018-10-30 12:18:24.844 +00:00 [INF] - Obtained edge hub config from module twin
2018-10-30 12:18:25.074 +00:00 [INF] - Set the following 1 route(s) in edge hub
2018-10-30 12:18:25.077 +00:00 [INF] - route: FROM /messages/* INTO $upstream
2018-10-30 12:18:25.082 +00:00 [INF] - Updated message store TTL to 7200 seconds
2018-10-30 12:18:25.085 +00:00 [INF] - Updated the edge hub store and forward configuration
2018-10-30 12:18:25.086 +00:00 [INF] - Initialized edge hub configuration
2018-10-30 12:18:25.137 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
2018-10-30 12:18:25.364 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
2018-10-30 12:18:25.379 +00:00 [INF] - Starting MQTT head
2018-10-30 12:18:25.504 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
2018-10-30 12:18:25.621 +00:00 [INF] - Starting AMQP head
2018-10-30 12:18:25.909 +00:00 [INF] - Started AMQP head
2018-10-30 12:18:25.922 +00:00 [INF] - Starting HTTP head
2018-10-30 12:18:26.310 +00:00 [INF] - User profile is available. Using '"/home/edgehubuser/.aspnet/DataProtection-Keys"' as key repository; keys will not be encrypted at rest.
2018-10-30 12:18:26.406 +00:00 [INF] - Creating key {79f59c9f-804e-4e9a-9f17-3c38e6aa4ea4} with creation date 2018-10-30 12:18:26Z, activation date 2018-10-30 12:18:26Z, and expiration date 2019-01-28 12:18:26Z.
2018-10-30 12:18:26.450 +00:00 [WRN] - No XML encryptor configured. Key {79f59c9f-804e-4e9a-9f17-3c38e6aa4ea4} may be persisted to storage in unencrypted form.
2018-10-30 12:18:26.467 +00:00 [INF] - Writing data to file '"/home/edgehubuser/.aspnet/DataProtection-Keys/key-79f59c9f-804e-4e9a-9f17-
3c38e6aa4ea4.xml"'.
2018-10-30 12:18:27.281 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined in "UseKestrel()" instead.
2018-10-30 12:18:27.335 +00:00 [INF] - Started HTTP head
2018-10-30 12:18:27.372 +00:00 [INF] - Started MQTT head
2018-10-30 12:18:28.608 +00:00 [INF] - New token received on the Cbs link

## Additional Information
Does not seem to be a critical error but I would say the edgeHub should wait with any attempt to sync with the cloud until it's actually connected first.

**Comment by sebader** [comment] 2018-10-30 12:43
To add: I see the same error, when I disconnect the network (while Edge is all up and running) and connecting the network again after a few minutes.

**Comment by myagley** [comment] 2018-10-30 15:30
Hi Sebastian,

What region is this IoT Hub in? This warning is related to the new extended offline features (in public preview) and is truly only a warning.

The extended offline has not been enabled in East US or West Europe, which can cause this warning. This is a temporary situation until the feature is released in these regions.

We can look at ways of suppressing the error messages, but since this feature is in preview, we aimed to be conservative and get as much data on how it is operating as we can.

**Comment by sebader** [comment] 2018-10-30 15:54
ah yes, our IoT Hub is indeed in West Europe.

**Comment by myagley** [comment] 2018-11-05 16:46
I'm going to close this issue for now, as this is expected behavior in the West Europe region.

**Closed by myagley** 2018-11-05 16:46 UTC
