### ISSUE TITLE
Automatic deployment in Azure DevOps fails

### ISSUE THREAD

**Issue by svejstrup** [Azure/iotedge#1900] opened 2019-10-24 15:50 UTC
Hi

Im not sure if this is the right repo for this issure so you're free to redirect me elsewhere.

The problem is that the release step 'Azure IoT Edge - Deploy to IoT Edge devices' in Azure DevOps fails with the message:

> ERROR: az iot edge deployment create: error: the following arguments are required: --deployment-id/-d

This seems to be related to a recent change to the Azure-CLI where **--config-id** has been deprecated in favor of **--deployment-id**. 
[Documentation](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/edge/deployment?view=azure-cli-latest)

'Azure IoT Edge - Deploy to IoT Edge devices' still use --config-id and therefore fails.

**Comment by veyalla** [comment] 2019-10-24 19:50
@shizn PTAL

**Comment by shizn** [comment] 2019-10-30 10:07
@blackchoey this issue is caused by https://github.com/Azure/azure-iot-cli-extension/issues/113. And it's already fixed. Please help close this issue.

**Comment by lt72** [comment] 2019-11-19 17:46
Closing issue, please re-open as needed.

**Closed by lt72** 2019-11-19 17:46 UTC
Labels: area:app
