### ISSUE TITLE
Multiple requests per second per device to IoT Hub when container repository password is out of date

### ISSUE THREAD

**Issue by benmacdonell** [Azure/iotedge#7120] opened 2023-10-05 01:39 UTC
## Expected Behavior
An expired container registry password does not cause multiple messages per second from identityd and keyd. 

## Current Behavior
An expired container registry password causes multiple messages per second from identityd and keyd. The consequence of this is IoT Hub throttles messages which impacts the connectivity (and application configuration) of other devices on the same Hub. The requests appear to be constant and do not back-off over time.

## Steps to Reproduce
Roll the password of a container registry being used by IoT Edge and don’t update the container registry password on the device. Note that although we have seen this happen on production and test environments, we can’t reliably trigger it so suspect there is a time component (it’s not as simple as roll the password and restart IoT Edge). We are confident the container registry password is the cause because the problem got so bad we had to scale up our IoT Hub to handle the traffic and the traffic went away as soon as the password on the device was updated.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
× identityd config toml file specifies a valid hostname - Error
    identityd config has hostname ubuntu but device reports hostname XXXX.
    Hostname in identityd config must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
× aziot-identity-service package is up-to-date - Error
    could not query https://aka.ms/latest-aziot-identity-service for latest available version
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
× host can connect to and perform TLS handshake with iothub AMQP port - Error
    Failed to do TLS Handshake, Connection Attempt Timed out in 70 Seconds
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
× host can connect to and perform TLS handshake with iothub MQTT port - Error
    Failed to do TLS Handshake, Connection Attempt Timed out in 70 Seconds

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.4.10' locally
    1.4.10: Pulling from azureiotedge-diagnostics
    31e352740f53: Pulling fs layer
    08363c02f724: Pulling fs layer
    745293437288: Pulling fs layer
    f33d80730e9f: Pulling fs layer
    01e137d23cf0: Pulling fs layer
    f33d80730e9f: Waiting
    01e137d23cf0: Waiting
    31e352740f53: Retrying in 5 seconds
    745293437288: Retrying in 5 seconds
    08363c02f724: Retrying in 5 seconds
    31e352740f53: Retrying in 4 seconds
    745293437288: Retrying in 4 seconds
    08363c02f724: Retrying in 4 seconds
    31e352740f53: Retrying in 3 seconds
    745293437288: Retrying in 3 seconds
    08363c02f724: Retrying in 3 seconds
    31e352740f53: Retrying in 2 seconds
    745293437288: Retrying in 2 seconds
    08363c02f724: Retrying in 2 seconds
    31e352740f53: Retrying in 1 second
    745293437288: Retrying in 1 second
    08363c02f724: Retrying in 1 second
    docker: error pulling image configuration: download failed after attempts=6: Forbidden.
    See 'docker run --help'.
× aziot-edge package is up-to-date - Error
    Error while fetching latest versions of edge components: could not send HTTP request
× container time is close to host time - Error
    Could not query local time inside container
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
‼ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - Warning
    The proxy setting for IoT Edge Agent "http://172.17.0.1:3128/", IoT Edge Daemon "", IoT Identity Daemon "", and Moby "" may need to be identical.

Connectivity checks
-------------------
× container on the default network can connect to upstream AMQP port - Error
    Container on the default network could not connect to <removed in bug report>.azure-devices.net:5671
× container on the default network can connect to upstream HTTPS / WebSockets port - Error
    Container on the default network could not connect to <removed in bug report>.azure-devices.net:443
× container on the default network can connect to upstream MQTT port - Error
    Container on the default network could not connect to <removed in bug report>.azure-devices.net:8883
× container on the IoT Edge module network can connect to upstream AMQP port - Error
    Container on the azure-iot-edge network could not connect to <removed in bug report>.azure-devices.net:5671
× container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - Error
    Container on the azure-iot-edge network could not connect to <removed in bug report>.azure-devices.net:443
× container on the IoT Edge module network can connect to upstream MQTT port - Error
    Container on the azure-iot-edge network could not connect to <removed in bug report>.azure-devices.net:8883
19 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
13 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Ubuntu 20.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.4.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.4.10
* Edge Hub [image tag (e.g. 1.0.0)]: 1.4.10
* Docker/Moby [run `docker version`]: 23.0.6+azure-2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

Support bundle for device experiencing this issue is attached to TrackingID#2309170010000552

```
</details>

<details>
<summary>edge-agent logs</summary>

```

Support bundle for device experiencing this issue is attached to TrackingID#2309170010000552

```
</details>

<details>
<summary>edge-hub logs</summary>

```

Support bundle for device experiencing this issue is attached to TrackingID#2309170010000552

```
</details>

## Additional Information
aziot-keyd example

Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - --> 200 {"content-type": "application/json"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "418"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - --> 200 {"content-type": "application/json"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - <-- POST /key?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "74"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - --> 200 {"content-type": "application/json"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - <-- POST /encrypt?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "22782"}
Sep 19 16:29:41 xxxx-platform aziot-keyd[1392381]: 2023-09-19T16:29:41Z [INFO] - --> 200 {"content-type": "application/json"}

**Comment by bishal41** [comment] 2023-11-21 18:17
@benmacdonell we investigated this issue and came to find out that this issue needs a significant refactoring before we make any fixes/changes to our code as it may also bring regression(s). Since we have a workaround for this i.e. user making sure to set correct registry password, we won't fix this issue for the time being and put this into our backlog for the future. I will proceed and close this issue unless you have any questions/feedback.  @gordonwang0 fyi

**Comment by bishal41** [comment] 2023-11-28 22:10
Closing this issue, please read my comments above.

**Closed by bishal41** 2023-11-28 22:10 UTC
Labels: no-issue-activity, iotedge, customer-reported
