### ISSUE TITLE
Message not send, no error

### ISSUE THREAD

**Issue by nhuurnink** [Azure/iotedge#448] opened 2018-10-16 08:00 UTC
Hi,

I have two devices. Both are showing no errors and log the part where the message is send to the hub.
Message from device A actually reach the hub, messages from device B don't.

I used the extended logging as described in https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot  but no luck, no errors.

Restarting everything didn't help either.

What am I missing and how can I debug further?

**Comment by varunpuranik** [comment] 2018-10-16 12:05
Thanks for reporting the issue. 
A few questions that can help investigate what is going on - 
- Are your routes set up correctly, so that messages from both modules should go to IotHub?
- Did you check if the edgeHub logs to see if they have any errors? Do you mind sharing them here so that we can look at it as well?

**Comment by nhuurnink** [comment] 2018-10-16 15:18
I don't have any messages routes set up, so it should default to the build-in route (event/messages), this works for my other device.

pi@MI-DataCollector-003-Utrecht-Norbert:~ $ iotedge list
NAME             STATUS           DESCRIPTION      CONFIG
DsmrReader       running          Up 7 hours       tmicolreg01.azurecr.io/p1collector:0.0.257-arm32v7
edgeHub          running          Up 7 hours       mcr.microsoft.com/azureiotedge-hub:1.0
edgeAgent        running          Up 7 hours       mcr.microsoft.com/azureiotedge-agent:1.0

[edgelog.txt](https://github.com/Azure/iotedge/files/2483732/edgelog.txt)
[systemlog.txt](https://github.com/Azure/iotedge/files/2483753/systemlog.txt)

I did check both, and can't find anything useful.

Do you need anything else?

**Comment by varunpuranik** [comment] 2018-10-16 18:04
Looks like this is the iotedged log. I need the edgeHub log. You can get them like so -
$>iotedge logs edgeHub

**Comment by nhuurnink** [comment] 2018-10-17 09:44
This is pretty much the gist of it. I'm not sure why it's staying at offset 7917 all the time and I don't know what the 'authentication not found' means, as it's authenticating succesfully afterwards.

[edgehub-log.txt](https://github.com/Azure/iotedge/files/2486752/edgehub-log.txt)

**Comment by varunpuranik** [comment] 2018-10-23 18:52
From the log snippet that you shared, it looks like the EdgeHub is not receiving any more messages from your device. This would also explain why the offset stays at 7917.

To see if the device got disconnected, simply stopped sending messages or something else, I believe I would have to look at the entire log file for the EdgeHub.

Also, I don't see the authentication not found error in the log you shared, so not sure why you are seeing that. Can you share that part of the log?

**Comment by nhuurnink** [comment] 2018-10-24 11:48
[edgelog.txt](https://github.com/Azure/iotedge/files/2510340/edgelog.txt)

This is the part of the edgehub logging close to 7916 / 7917.

**Comment by varunpuranik** [comment] 2018-10-24 13:12
These are the interesting lines from the log - 
2018-10-15 07:38:48.896 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.LinkHandler] - Closing link Events for MI-DataCollector-003-Utrecht-Norbert/DsmrReader
2018-10-15 07:38:48.903 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.LinkHandler] - Closing link TwinReceiving for MI-DataCollector-003-Utrecht-Norbert/DsmrReader
2018-10-15 07:38:48.904 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.LinkHandler] - Closing link TwinSending for MI-DataCollector-003-Utrecht-Norbert/DsmrReader

These indicate that the interesting links between the client and server (EdgeHub) were dropped. This would explain why the server did not receive any telemetry after this. My current understanding is that this link drop is initiated by the client. 
Just to confirm - was your device actively sending telemetry at that time? And if so, it was able to do so successfully without any exceptions?

**Comment by nhuurnink** [comment] 2018-10-24 13:15
My device was sending messages succesfully before. I'm not sure if it
stopped exactly at this moment, but I would think so, yes.
I didn't change any configuration/keys besides the device twin (and tried
some code to react on variable changes, but I deleted this code after the
messaging stopped).

With kind regards,
Norbert Huurnink
+31 6 2278 3221
norbert.huurnink@meterinsight.com

**Comment by varunpuranik** [comment] 2018-10-24 14:02
I see... so if I understand right, the loop (to send telemetry messages) was still going, but you started getting some exceptions?

**Comment by nhuurnink** [comment] 2018-10-24 14:28
I don't see exceptions, the messages just don't arrive.

Op wo 24 okt. 2018 16:02 schreef Varun Puranik <notifications@github.com>:

**Comment by myagley** [comment] 2019-02-01 19:03
Does this still reproduce?

**Comment by myagley** [comment] 2019-02-19 20:16
I'm going to close this issue due to inactivity. Please feel free to reopen.

**Closed by myagley** 2019-02-19 20:16 UTC
