### ISSUE TITLE
Module client connections fail and do not reconnect

### ISSUE THREAD

**Issue by AnlauTriCloud** [Azure/iotedge#5856] opened 2021-11-22 13:59 UTC
Hi,

I have an issue where all deployed modules loose their ability to communicate with the edgeHub. I experience this on both development devices and in production. This is similar to a previous issue: https://github.com/Azure/iotedge/issues/3234

As an example, the localblobstorage module:

<6> 2021-11-22 10:59:56.182 +00:00 [INF] - Error authenticating token for testdevice1/localblobstorage because the token is expired or could not be parsed
<6> 2021-11-22 10:59:56.182 +00:00 [INF] - Credentials for client testdevice1/localblobstorage are not valid.
<4> 2021-11-22 10:59:56.182 +00:00 [WRN] - Reauthenticating client testdevice1/localblobstorage failed, removing client connection
<6> 2021-11-22 10:59:56.182 +00:00 [INF] - Unable to re-authenticate testdevice1/localblobstorage, dropping client connection.
<6> 2021-11-22 10:59:56.182 +00:00 [INF] - Removing device connection for device testdevice1/localblobstorage with removeCloudConnection flag 'True'.
<4> 2021-11-22 10:59:56.182 +00:00 [WRN] - Closing connection for device: testdevice1/localblobstorage, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device testdevice1/localblobstorage., 
<6> 2021-11-22 10:59:56.182 +00:00 [INF] - Disposing MessagingServiceClient for device Id testdevice1/localblobstorage because of exception - Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device testdevice1/localblobstorage.
<6> 2021-11-22 10:59:56.183 +00:00 [INF] - Closing device proxy for device Id testdevice1/localblobstorage
...

After approximately one hour, this repeats:

<6> 2021-11-22 12:04:56.184 +00:00 [INF] - Error authenticating token for testdevice1/localblobstorage because the token is expired or could not be parsed
<6> 2021-11-22 12:04:56.184 +00:00 [INF] - Credentials for client testdevice1/localblobstorage are not valid.
<4> 2021-11-22 12:04:56.184 +00:00 [WRN] - Reauthenticating client testdevice1/localblobstorage failed, removing client connection
<6> 2021-11-22 12:04:56.184 +00:00 [INF] - Unable to re-authenticate testdevice1/localblobstorage, dropping client connection.
<6> 2021-11-22 12:04:56.184 +00:00 [INF] - Removing device connection for device testdevice1/localblobstorage with removeCloudConnection flag 'True'.
<4> 2021-11-22 12:04:56.184 +00:00 [WRN] - Closing connection for device: testdevice1/localblobstorage, Microsoft.Azure.Devices.Edge.Hub.Core.EdgeHubConnectionException: Connection closed for device testdevice1/localblobstorage., 
...

Restarting the VM seems to resolve the problem, but that is not a viable solution for devices in production.

## Expected Behavior
I expect the module clients to authenticate and reconnect when the token has expired.

## Current Behavior
Module clients never reconnect upon token expiration.

## Steps to Reproduce
Recently this happens for all modules after the edge device has been running for some time (days, weeks ..)

### Device Information
* Host OS: Ubuntu 18.04 
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: Version - 1.2.6.48918552 
* Edge Agent: mcr.microsoft.com/azureiotedge-agent:1.2 
* Edge Hub: mcr.microsoft.com/azureiotedge-hub:1.2
* Docker/Moby: 20.10.11+azure-1

**Comment by nyanzebra** [comment] 2021-11-29 23:36
Hi, could you provide a support bundle (`iotedge support-bundle`)? This will provide us with all the logs necessary to effectively diagnose the problem

**Comment by nyanzebra** [comment] 2021-11-30 18:09
I got the support-bundle, but I went ahead and redacted the link in your post, and this is my bad, but support-bundle in sharing all logs and containers might be more information than you might want to share.

**Comment by nyanzebra** [comment] 2021-12-02 22:46
So, this is in our backlog and should be fixed in an upcoming release, I will post here to keep you apprised of when that might occur :)

**Comment by AnlauTriCloud** [comment] 2021-12-03 10:07
Thanks @nyanzebra , looking forward to that release :)

**Comment by nyanzebra** [comment] 2021-12-16 20:59
@AnlauTriCloud Just to clarify, what lead you to https://github.com/Azure/iot-identity-service/issues/300 for your problem and have you verified that the connection string or equivalent mechanism for using blob storage module is correct?

**Comment by AnlauTriCloud** [comment] 2021-12-17 07:51
@nyanzebra, the connection string for the blob storage is working fine. 

The issue is causing all module clients to fail to reconnect to the edge hub. The localblodstore module was just an example. 
My understanding of the issue is that the module workload certificates are used to authenticate the modules to the edge hub (and retrieve a token). The certificates eventually expire, but should automatically be renewed at around 80% of their lifespan. Apparantly that does not seem til happen, and this is why I think the issue is related to Azure/iot-identity-service#300.

This is unfortunately a major issue for us, having multiple edge devices running in production at remote places.

**Comment by nyanzebra** [comment] 2022-01-06 22:35
Hi @AnlauTriCloud, just investigating this a bit further, know you are still waiting on the release, and hopefully I can find out when that is coming soon (exact date). Also, I just want to clarify something from looking into the logs you sent; were there any changes to the routes that were made around the time you saw this issue? Want to determine if this is related issue or not (e.g. need better log message if related to connectivity or different problem from something else) :)

**Comment by varunpuranik** [comment] 2022-01-18 14:18
@AnlauTriCloud - 
The tokens generated by the Azure IoT SDKs have a default expiry of 1 hr. When the connection is over MQTT, there is no way to re-new the token. So when the token expires, EdgeHub drops the connection to that module. This is by design. The module (and the Azure IoT SDK it uses) should detect this, create a new token, and re-create a connection to EdgeHub. 
If that is not happening, then it would indicate an issue with the SDK. Which SDK are you using in your module?

However, from the logs in your issue above, it seems like the module did re-connect after EdgeHub dropped the connection with a new token for an hour, and after that hour, EdgeHub dropped the connection again. This is all expected behavior, and I don't see any errors/issues in the logs you have shared. It also does not seem to be related to expired certificates.

If this is still causing issues for you, then one mitigation might be to move to AMQP - with AMQP, the token can be refreshed without dropping the connection, so you won't see the hourly connection drop that you are seeing right now.

**Comment by nyanzebra** [comment] 2022-01-31 21:35
@AnlauTriCloud, did the suggestion from @varunpuranik help? We also have new releases out for 1.1 and 1.2. Let us know if either of these solve your problem!

**Comment by nyanzebra** [comment] 2022-02-09 00:24
Closing for inactivity, if above did not solve your problem please reopen!

**Closed by nyanzebra** 2022-02-09 00:24 UTC
Labels: iotedge, customer-reported, 1.2.6

**Comment by AnlauTriCloud** [comment] 2022-02-09 08:22
I believe the issue has been addressed here:

Fix edgeHub shutdown for renew certificate by ancaantochi · Pull Request #6037
https://github.com/Azure/iotedge/pull/6037
