### ISSUE TITLE
The GA edgeHub does not return connectionState

### ISSUE THREAD

**Issue by shizn** [Azure/iotedge#39] opened 2018-07-19 03:16 UTC
The EdgeHub module does not return connectionState, in VS Code, we cannot visualize the module states without it.
![image](https://user-images.githubusercontent.com/3619378/42919481-abc9d762-8b44-11e8-97b1-b7784c20b348.png)

## Expected Behavior

By returning the connectionState, customer can visualize edgeHub module states during development.

## Current Behavior

![image](https://user-images.githubusercontent.com/3619378/42919508-e471e794-8b44-11e8-9838-63f0c0553441.png)
Always blue because no connectionState

## Steps to Reproduce

1. Expand an active IoT Edge device in VS Code and look into the module list.

### Device (Host) Operating System

All

### Architecture

NA

### Container Operating System

All

**Comment by darobs** [comment] 2018-07-19 15:31
Hello @shizn,

Thank you for the report, Xin.

This is in the reported properties of the $edgeHub module twin, correct?  I will mark this as a bug and put it in our back log.

**Comment by varunpuranik** [comment] 2018-07-20 01:37
Hi Xin,

So this behavior is because IoTHub uses the D2C telemetry link status to determine if the device is connected or now. But since the EdgeHub doesn't send any telemetry, it never opens that link. So the module shows up as disconnected. 

Either of those will be hard to fix at this point. Can you use the RuntimeStatus of the module in the EdgeAgent reported properties instead? That should give you an accurate status of which modules are running and which are not.

**Comment by shizn** [comment] 2018-07-20 02:37
Thanks for the information, Varun. We will take a look and use RuntimeStatus to update the status in VS Code.

**Comment by myagley** [comment] 2018-08-24 15:48
This is related to #80

**Comment by myagley** [comment] 2018-09-18 23:13
Closing this as it is a duplicate of #80

**Closed by myagley** 2018-09-18 23:13 UTC
Labels: bug
