### ISSUE TITLE
IoT Edge installation and configuration issues

### ISSUE THREAD

**Issue by wudiqiang2024** [Azure/iotedge#7322] opened 2024-07-10 00:40 UTC
I installed Azure IoT Edge on ubuntu-22.04 according to Microsoft documentation. 

![image](https://github.com/Azure/iotedge/assets/152937666/0e6f40dc-0d3c-450c-8e19-26e7c6b80700)

The configuration file is as follows

```
 [provisioning]
 source = "manual"
 iothub_hostname = "xxx.azure-devices.net"
 device_id = "my-device-id"

 [provisioning.authentication]
 method = "x509"
 identity_cert = "file:///var/aziot/certs/xxx.pem"
 identity_pk = "file:///var/aziot/secrets/private-key.pem"
```
The private key file "private-key.pem" is generated using the tpm2-openssl software and the openssl 3 provider

![image](https://github.com/Azure/iotedge/assets/152937666/f528a325-4e96-4291-a5f3-80c5eb2082a9)

Use the command "iotedge system logs" to view the log and find the following error log

![image](https://github.com/Azure/iotedge/assets/152937666/417dcee1-9247-4c76-8db1-81cc539080a8)

Please help me
1. Does this mean that my IoT edge failed to start?
2. The private key is protected by TPM, how can I use it normally in IoT edge?
3. Or is there any other solution?

Thank you very much!

**Comment by lfitchett** [comment] 2024-07-19 17:12
Duplicate of https://github.com/Azure/iot-identity-service/issues/620

**Closed by lfitchett** 2024-07-19 17:12 UTC
