### ISSUE TITLE
Route ingest queue gets stuck after getting twin data or calling direct methods

### ISSUE THREAD

**Issue by SammyWhamy** [Azure/iotedge#6662] opened 2022-09-09 09:23 UTC
## Expected Behavior
Messages should be getting removed from queue regardless of other updates happening

## Current Behavior
Messages never get removed from the queue. The same message gets repeated indefinitely. I have confirmed that every possible code path of the input message handler returns `MessageResponse.Completed`. I've also replaced the method by a lambda that only returns `MessageResponse.Completed`, this also makes no change and the messages stay on the queue.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Set up a simple module (Default C# template is fine)
2. Add desired properties and register a callback, or register a callback for a direct method
3. Note that after updating desired properties or calling a direct method, routed messages will now get stuck in the queue

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
31 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS - Ubuntu 20.04.5 LTS x86_64
* Architecture - amd64
* Container OS - linux

### Runtime Versions
* aziot-edged: iotedge 1.4.0
* Edge Agent: azureiotedge-agent:1.2
* Edge Hub: azureiotedge-hub:1.2
* Docker/Moby: 20.10.17+azure-1

## Additional Information
Using either of these functions alone poses no problem. The problem only occurs when using either both routed message input + direct method, or routed message input + desired properties

The module is written in C# using .NET 6, the issue also occurs in .NET Core 3.1.

**Comment by vipeller** [comment] 2022-09-12 16:37
@SammyWhamy Hello, best would be if we had a call where I can see what you do. Could you send me a mail, my address is like my user id at microsoft dot com.

**Comment by jlian** [comment] 2022-09-15 20:31
@SammyWhamy @vipeller did you have a call? Any updates?

**Comment by SammyWhamy** [comment] 2022-09-15 20:42
@jlian Sorry been a bit busy, will try to schedule one now.

**Comment by vipeller** [comment] 2022-09-21 16:23
summary: we've just had a call and the problem was demonstrated to me. It seems that using the C# sdk, the the module gets a direct method call, that breaks something and the acknowledgements for the module to module messages are not propagated back anymore to edgeHub. 
This happens with MQTT, changing the protocol between the modules and edgehub to AMQP, the problem cannot be reproduced. That indicates to me that the bug is in the MQTT protocol specific part of the C# SDK.
Submitting an issue at the C# SDK team for this issue.

**Comment by vipeller** [comment] 2022-09-21 16:43
Transferred this issue to the SDK team, closing here now.

**Closed by vipeller** 2022-09-21 16:43 UTC
Labels: iotedge, customer-reported
