### ISSUE TITLE
Error while deploying custom module to Azure IoT Edge Device

### ISSUE THREAD

**Issue by sumit-sp** [Azure/iotedge#6961] opened 2023-03-16 20:49 UTC
Hi,

I am trying to resolve this error since a week now.
Whenever I try to deploy custom module to Azure IoT edge, I'm getting this error.
I am storing docker images in azure container registry and providing all the correct details to deployment manifest still getting error.
Plan execution ended for deployment 55
<3> 2023-03-16 20:39:31.815 +00:00 [ERR] - Edge agent plan execution failed.
System.AggregateException: One or more errors occurred. (Error calling prepare update for module SampleModule: registry operation error: pull image "aipedgemoduleregistry.azurecr.io/squeezemodule:0.0.1")
 ---> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling prepare update for module SampleModule: registry operation error: pull image "aipedgemoduleregistry.azurecr.io/squeezemodule:0.0.1", StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2022_08_03.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2022_08_03/ModuleManagementHttpClient.cs:line 232
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 171
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2022_08_03.ModuleManagementHttpClient.PrepareUpdateAsync(ModuleSpec moduleSpec) in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2022_08_03/ModuleManagementHttpClient.cs:line 216
   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.ModuleManagementHttpClient.<>c__DisplayClass26_0.<<Throttle>b__0>d.MoveNext() in /mnt/vss/_work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs:line 145
--- End of stack trace from previous location ---

**Comment by brotherneeru** [comment] 2023-03-20 16:24
Hi there. Please reformat your issue with the following context:
Provide a general summary of the issue in the Title above
-->
## Expected Behavior
Tell us what should happen

## Current Behavior
Tell us what happens instead of the expected behavior

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.
2.
3.
4.

## Context (Environment)

### Output of `iotedge check`

<details>
<summary>Click here</summary>
```
<Paste here between the triple backticks>
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]: 

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>
```
<Paste here between the triple backticks>
```
</details>
<details>
<summary>edge-agent logs</summary>
```
<Paste here between the triple backticks>
```
</details>
<details>
<summary>edge-hub logs</summary>
```
<Paste here between the triple backticks>
```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by sumit-sp** [comment] 2023-03-23 12:02
**Summary:**
I want to deploy a machine learning model trained using azure machine learning on an Edge device.
I am building docker image using " az acr build ...." command. It builds docker image and pushes it to Azure container registry.

**Expected Behavior**

The $edgeAgent shall pull image from azure container registry and run the module.

**Current Behavior**

Error while image pull from Azure container registry

**Output iotedge check**

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
30 check(s) succeeded.
4 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

**Device Information**
Operating System: Ubuntu 20.04.5 LTS
Kernel: Linux 5.15.0-1033-azure
Architecture: x86-64

**Runtime version**

iotedge 1.4.9
[myEdgeDevice_$edgeAgent_Logs (2).txt](https://github.com/Azure/iotedge/files/11050486/myEdgeDevice_.edgeAgent_Logs.2.txt)

Edge Agent [image tag (e.g. 1.0.0)]: 1.4
Edge Hub [image tag (e.g. 1.0.0)]: 1.4

Docker/Moby [run docker version]: 
Client:
 Version:           20.10.23+azure-2
 API version:       1.41
 Go version:        go1.19.6
 Git commit:        715524332ff91d0f9ec5ab2ec95f051456ed1dba
 Built:             Wed Jan 18 20:42:16 UTC 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Logs:**

[myEdgeDevice_$edgeAgent_Logs (2).txt](https://github.com/Azure/iotedge/files/11050491/myEdgeDevice_.edgeAgent_Logs.2.txt)

**Comment by brotherneeru** [comment] 2023-03-23 17:53
Can you validate that you have the correct registryCredentials with your azurecr and credentials?

**Comment by sumit-sp** [comment] 2023-03-26 06:49
yes, I did validate it.
The issue I noticed is sometimes the edge device pulls image while sometimes it gives error while doing pull image from same registry.
All the IoT hub, edge device, VM on which edge device is running and azure container registry are part of same resource group.

**Comment by brotherneeru** [comment] 2023-03-27 17:45
Looking at ACR issues, it looks like some other folks have been dealing with some intermittent 500s when pulling images as well. Since your credentials are correct and it sometimes pulls and sometimes not, I think this may be an ACR issue, not an IoT Edge problem

**Comment by sumit-sp** [comment] 2023-03-28 07:54
Does this ACR issue has any permanent solution or atleast a temporary solution like restarting device, logout and login etc.

**Comment by brotherneeru** [comment] 2023-03-28 14:44
https://github.com/Azure/acr/issues/679
It does not look like there is any headway on a solution unfortunately

**Comment by brotherneeru** [comment] 2023-04-28 17:15
Closing as nothing actionable from IotEdge side

**Closed by brotherneeru** 2023-04-28 17:15 UTC
Labels: no-issue-activity, iotedge, customer-reported
