### ISSUE TITLE
edgeHub in a disconnected state and does not recover

### ISSUE THREAD

**Issue by emilm** [Azure/iotedge#6535] opened 2022-07-25 14:00 UTC
Hello!
 
I came across a device where edgeHub had stopped working. But the log is just kept for a week so I don’t know the precursor.
I restarted edgeHub module and it worked again. Has this been a known issue?

Question: Is there a way to connect directly as a module using TPM without needing edgeHub? I need to know disconnection events and afaik, those events are not conveyed from edgeHub to the modules. I need this to know when to send a full state from the device when coming back online.

Thanks!

## Expected Behavior
Should recover disconnection

## Current Behavior
Is in a bad state, needs  module restart to work

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. wait.. ?

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
× config.yaml has correct hostname - Error
    config.yaml has hostname <redacted> but device reports hostname <redacted>.
    Hostname in config.yaml must either be identical to the device hostname or be a fully-qualified domain name that has the device hostname as the first component.
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: certificates - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
√ production readiness: Edge Hub's storage directory is persisted on the host filesystem - OK

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with DPS endpoint - OK
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

21 check(s) succeeded.
1 check(s) raised warnings.
1 check(s) raised errors.

```
</details>

### Device Information
* Host OS: Custom yocto dunfell
* Architecture: arm32
* Container OS: Linux

### Runtime Versions
* aziot-edged iotedge 1.1.13
* Edge Agent: mcr.microsoft.com/azureiotedge-agent:1.1.13-linux-arm32v7 
* Edge Hub: mcr.microsoft.com/azureiotedge-hub:1.1.13-linux-arm32v7
* Docker/Moby:  
```
Client:
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.14.15
 Git commit:        eb310fca49
 Built:             Wed Jul 21 14:24:06 2021
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.15
  Git commit:       420b1d36250f9cfdc561f086f25a213ecb669b6f
  Built:            Wed Jul 21 14:23:45 2021
  OS/Arch:          linux/arm
  Experimental:     true
 containerd:
  Version:          v1.2.14-3-g3b3e9d5f6.m
  GitCommit:        3b3e9d5f62a114153829f9fbe2781d27b0a2ddac.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683-dirty

```

## Logs

<details>
<summary>edge-hub logs</summary>

```
<4> 2022-07-25 07:15:35.477 +00:00 [WRN] - Error processing message in TwinReceiving link for <redacted>/controller
System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.HandleTwinOperationException(String correlationId, Exception e) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 301
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage, String correlationId) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 253
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.TwinReceivingLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/TwinReceivingLinkHandler.cs:line 99
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.ReceivingLinkHandler.ProcessMessageAsync(AmqpMessage amqpMessage) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ReceivingLinkHandler.cs:line 99
<6> 2022-07-25 07:15:36.551 +00:00 [INF] - Updated reported properties for <redacted>/controller
<4> 2022-07-25 07:16:36.033 +00:00 [WRN] - Error updating reported properties for <redacted>/controller
System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage, String correlationId) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 253
<4> 2022-07-25 07:17:36.047 +00:00 [WRN] - Error processing message in TwinReceiving link for <redacted>/controller
System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.EndSendMessage(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.HandleTwinOperationException(String correlationId, Exception e) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 301
   at Microsoft.Azure.Devices.Edge.Hub.Core.Device.DeviceMessageHandler.UpdateReportedPropertiesAsync(IMessage reportedPropertiesMessage, String correlationId) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs:line 253
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.TwinReceivingLinkHandler.OnMessageReceived(AmqpMessage amqpMessage) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/TwinReceivingLinkHandler.cs:line 99
   at Microsoft.Azure.Devices.Edge.Hub.Amqp.LinkHandlers.ReceivingLinkHandler.ProcessMessageAsync(AmqpMessage amqpMessage) in /mnt/vss/_work/1/s/edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ReceivingLinkHandler.cs:line 99
```
</details>

## Additional Information

my module's log:

```
2022-07-25T07:15:35,514Z [azure-iot-sdk-ReactorRunner] WARN  c.m.a.s.i.d.transport.IotHubTransport - Handling an exception from sending message: Attempt number 1
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: An unknown transport exception occurred
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:19)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onMessageAcknowledged(AmqpsIotHubConnection.java:664)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onMessageAcknowledged(AmqpsSessionHandler.java:276)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler.onDelivery(AmqpsSenderLinkHandler.java:83)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by huguesBouvier** [comment] 2022-07-25 18:36
We don't have a know issue where IoTHub stops after a few weeks. I am not sure there is no bug but know some devices have been running for months.

For the TPM, you cannot connect directly to it if IoTEdge is connected. However, if you disconnect IoTEdge then you should be able to access normaly.

Depending on what you do, you can access the Rest API of keyd which is accessing the TPM. Details here: https://azure.github.io/iot-identity-service/

**Comment by emilm** [comment] 2022-07-25 18:44
Thanks @huguesBouvier ! I just wonder if you have seen this exception before. Ideally the SDK client should never disconnect from the local edgeHub over time since they run on the same system.


What I mean by direct access to iotedge with TPM is that I can have the SDK client connect directly to the iot edge hub without going through edgeHub

**Comment by huguesBouvier** [comment] 2022-07-26 18:36
" An unknown transport exception" doesn't give details about the root cause but looking around it seems we have another issue with the SDK getting stuck and not been able to reconnect.
We are investigating the issue. I'll update the ticket what we have new.

Yes, you should be able to connect the SDK directly and connect to edgeHub. I am less knowledgeable about their product but they do have examples: https://github.com/Azure/azure-iot-sdk-java/blob/2019-12-20/provisioning/provisioning-samples/provisioning-tpm-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningTpmSample.java

**Comment by emilm** [comment] 2022-07-26 18:52
Thanks @huguesBouvier!

I was unsure which one to contact. Because it has to do with edgeHub but also the SDK. :)

**Comment by vipeller** [comment] 2022-08-18 17:02
Hi @emilm, is there any progress with this, do you need more assistance? Is this related to the issue with the clock behind?
Also, the goal is not quite clear, "connect directly to the iot edge hub without going through edgeHub". Do you mean connect directly to Iot Hub?

**Comment by vipeller** [comment] 2022-08-23 17:33
@emilm I am closing this, feel free to reopen whenever you need assistance.

**Comment by emilm** [comment] 2022-08-23 17:33
Thank you! I haven't seen it again.

**Closed by vipeller** 2022-08-23 17:33 UTC
Labels: iotedge, customer-reported
