### ISSUE TITLE
Log Retention Setting is not being set at module level when we are changing it in deployment template as create option

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#3129] opened 2020-06-23 07:05 UTC
Hi Team,
    We have changed the log retention settings in the create options of the modules. And then trigger the deployment. We observe that some of module it has applied on the gateway. And some of module still having default log retention setting which we have set in the daemon.json. 
So please could you let me know the cause of this and how we can enforce it to apply on all the modules. 
**We are using environment** 
Windows
Edge Runtime 1.0.8 
Production env. 

Log settings we have verified in the below path `C:\ProgramData\iotedge-moby\containers\<ContainerID>\hostconfig.json`

**Comment by sachidanand** [comment] 2020-06-24 06:36
Is there any update on this ...

**Comment by ggjjj** [comment] 2020-06-24 16:09
Can you share the versions of edge agent and iotedged?

**Comment by sachidanand** [comment] 2020-06-24 19:35
1.0.8 version we are using of edge runtime , edgeAgent and edgeHub

**Comment by ggjjj** [comment] 2020-06-24 20:18
Can you confirm which modules don't have the log retention? Sometimes change in create options doesn't trigger a new module deployment.

**Comment by sachidanand** [comment] 2020-06-25 05:03
On Some of device it was edgeHub, and on some of devices it was custom module ... We have 7 modules on the Edge Gateway and on 6 modules the create option was applied but one module was still having default value..  And this one module is not fixed some time it was edgeHub and some time it was custom module

**Comment by ggjjj** [comment] 2020-06-25 22:30
Can you try the https://docs.docker.com/engine/reference/commandline/inspect/ command and see if the log settings are applied for all the modules?

**Comment by ggjjj** [comment] 2020-06-25 22:37
Can you try the https://docs.docker.com/engine/reference/commandline/inspect/ command and see if the log settings are applied for all the modules?

**Comment by sachidanand** [comment] 2020-06-26 05:26
I did it and it was applied for all the module except one Custom module.. And on another gateway it was not applied on edgeHub

**Comment by sachidanand** [comment] 2020-06-29 05:55
Is there any update on this ???

**Comment by ggjjj** [comment] 2020-06-29 21:51
To be clear, so the log settings are not applied to one custom module and edge hub module in another gateway. It was verified that the log settings are not applied to these two modules? is that right? what is the version of docker daemon?

**Comment by sachidanand** [comment] 2020-06-30 08:26
> To be clear, so the log settings are not applied to one custom module and edge hub module in another gateway. It was verified that the log settings are not applied to these two modules via `docker inspect` ?is that right? what is the version of docker daemon?

Yes thats correct ... Moby docker we are using .. version is 3.0.5 we are using .. This issue is on production so your prompt reply will really help us ... 

`
PS C:\WINDOWS\system32> docker -H npipe:////.////pipe/iotedge_moby_engine version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.1
  Git commit:       dbe4a30
  Built:            Thu Apr 18 22:07:58 2019
  OS/Arch:          windows/amd64
  Experimental:     false
`

**Comment by ggjjj** [comment] 2020-06-30 18:18
Is it possible to upgrade to 1.0.9.? As 1.0.8 is at least an year old release ... Also can you share the create options settings for the custom module or the custom module so I can reproduce at my side.?

**Comment by CindyXing** [comment] 2020-06-30 18:32
@sachidanand, would you please share the deployment json that we can go through in detail? Theoretically if edgeagent log rotation setting is applied, other containers should be applied as well. Thanks.

**Comment by sachidanand** [comment] 2020-07-01 05:58
Majorly we are facing this issue with Edge Agent Module.. Log retention setting which we are setting from Azure portal is not applying on Edge Agent Module. All rest of modules it is applying...

**Comment by ggjjj** [comment] 2020-07-01 15:45
Is this after the update to 1.0.9? So you no longer face issue with edge hub and custom module? can you share the log retention setting for edge agent?

**Comment by sachidanand** [comment] 2020-07-01 15:47
We can't go with 1.0.9 as of now as we have many plant where we are using 1.0.8

**Comment by veyalla** [comment] 2020-07-01 15:55
After setting log limits, the saved container should be removed for the changes to take affect. There is a bug currently where the edgeAgent can only update itself if its image URI changes. 

Try manually removing the edgeAgent module using `docker rm -f edgeAgent`, the edge daemon should detect that it is not running and start it with the updated createOptions.

**Comment by sachidanand** [comment] 2020-07-02 12:50
This work around would leads to longer downtime then on gateway ...

we are using edgeAgent container image version 1.0.8 and runtime version also 1.0.8 so is edgeAgent 1.0.8 pointing to latest version 1.0.8.5 or it points to 1.0.8.0 ????

**Comment by ggjjj** [comment] 2020-07-02 17:49
you can check the version of the edge agent that is currently running via logs. If  you tried the workload of deleting the edgeagent container, then it would update to the latest version of 1.0.8 which is 1.0.8.5.

**Comment by ancaantochi** [comment] 2020-07-03 03:28
@sachidanand 

Another workaround to trigger a deployment is to change the image version from the deployment. For example if you're deployment uses 1.0.8 you can change to 1.0.8.5 and this will trigger edgeAgent update together with the logs config. There will be a downtime because any module config change it will restart the module, but it should be faster than removing the container and waiting for iotedged to start it.

If the deployment uses 1.0.8 it won't update to 1.0.8.5 if you remove the container, 1.0.8.x doesn't get tagged with 1.0.8. You can check the version by looking at the logs: 

docker logs edgeHub | grep Version

**Comment by sachidanand** [comment] 2020-07-03 11:59
The version it is showing like this so which version it is pointing ???

PS C:\Users\Administrator> docker -H npipe:////./pipe/iotedge_moby_engine logs edgeHub | findstr Version
<6> 2020-07-01 14:54:32.206 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
<6> 2020-07-01 16:32:28.394 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
PS C:\Users\Administrator> docker -H npipe:////./pipe/iotedge_moby_engine logs edgeAgent | findstr Version
<6> 2020-06-30 13:55:24.888 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
<6> 2020-07-01 14:52:36.047 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
<6> 2020-07-01 14:53:10.182 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)
<6> 2020-07-01 16:32:01.878 +02:00 [INF] - Version - 1.0.8.23694809 (f5186c42ebb721893c5a497c789236803de42fb7)

**Comment by ancaantochi** [comment] 2020-07-04 04:10
1.0.8.23694809 is for 1.0.8 release
1.0.8.5 has version 1.0.8.5.28262167

Did you try any of the workarounds for updating edgeAgent?

**Comment by sachidanand** [comment] 2020-07-06 07:14
No we didn't apply this work around as it will leads longer downtime on Plant gateway

**Comment by ancaantochi** [comment] 2020-07-06 16:59
The edgeAgent not being updated it's a bug we have in our backlog, once we fix it if there are changes in the deployment to edgeAgent will triggered remove and recreate the container, same as the workaround.

**Comment by ggjjj** [comment] 2020-07-07 04:17
the bug has been fixed in 1.0.10. So any log setting would be applied to the edge agent with create options settings without a need to restart iotedge daemon.

**Closed** 2020-07-24 17:50 UTC
