### ISSUE TITLE
moby-engine: Invalid 80-moby-engine.rules

### ISSUE THREAD

**Issue by afoui** [Azure/iotedge#3703] opened 2020-10-12 15:18 UTC
## Expected Behavior
No systemd-udevd error.

## Current Behavior
An error message shows up in the systemd journal:
```
systemd-udevd[170]: /usr/lib/udev/rules.d/80-moby-engine.rules:1: Invalid key/value pair, starting at character 1 ('c') 
```

## Steps to Reproduce
1. Create `/etc/apt/sources.list.d/microsoft-prod.list` with:
```
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/debian/stretch/multiarch/prod stretch main
```
2. Install moby-engine

### Output of `iotedge check`
(iotedge install is broken for unrelated reasons)

### Device Information
* Host OS: Debian Buster
* Architecture: arm32
* Container OS: Linux containers

### Runtime Versions
* iotedged [run `iotedge version`]: 
* Edge Agent [image tag (e.g. 1.0.0)]: 
* Edge Hub [image tag (e.g. 1.0.0)]: 
* Docker/Moby [run `docker version`]:
```
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:22:16 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>
(irrelevant)
</details>

<details>
<summary>edge-agent logs</summary>
(irrelevant)
</details>

<details>
<summary>edge-hub logs</summary>
(irrelevant)
</details>

## Additional Information

Rather than a udev rule, `80-moby-engine.rules` contains a relative path:
```
# cat /usr/lib/udev/rules.d/80-moby-engine.rules 
contrib/udev/80-docker.rules
```

80-moby-engine.rules belongs to moby-engine:
```
# dpkg -S /lib/udev/rules.d/80-moby-engine.rules 
moby-engine: /lib/udev/rules.d/80-moby-engine.rules
```
moby-engine package details:
```
# apt show moby-engine
Package: moby-engine
Version: 3.0.13+azure-0
Priority: optional
Section: admin
Maintainer: Microsoft <support@microsoft.com>
Installed-Size: 141 MB
Depends: init-system-helpers (>= 1.18~)
Recommends: apparmor, ca-certificates, iptables, kmod, moby-cli, pigz, xz-utils
Suggests: cgroupfs-mount | cgroup-lite, git
Conflicts: docker-ce, docker-ee, docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package, moby-containerd, moby-runc
Replaces: docker, docker-ce, docker-ee, docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Homepage: https://mobyproject.org
Download-Size: 33,0 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.microsoft.com/debian/stretch/multiarch/prod stretch/main armhf Packages
Description: Moby: the open-source application container engine
```

**Comment by massand** [comment] 2020-10-13 07:57
@afoui - thanks for reporting this issue. Generally speaking, the udev error seems benign because moby-engine operates without issues and never seems to use the loopback devices listed in the actual moby repo (80-docker.rules)[https://github.com/moby/moby/blob/master/contrib/udev/80-docker.rules] file. Do you see any issues arising from this error, other than the error message showing up in journal logs?

**Comment by afoui** [comment] 2020-10-13 08:55
I haven't noticed any other problem related to this but such log entries are a potential source of questions from QA for something that looks like an easy-to-fix packaging issue.

**Comment by veyalla** [comment] 2020-10-13 15:50
Adding @cpuguy83

**Comment by cpuguy83** [comment] 2020-10-13 17:10
The error seems strange... what is the contents of 80-docker.rules in your actual machine?
Since line 1 char 1 is not a `c`... actually the first line is a comment.

The issue is generally going to be benign. The rules are there for the case of using devicemapper with loopback devices instead of the default overlay2 storage driver... and even then for desktop users.

**Comment by afoui** [comment] 2020-10-13 17:32
@cpuguy83 There is no 80-docker.rules file on my device. The problem is with 80-moby-engine.rules, and it does start with a 'c':

```
# cat /usr/lib/udev/rules.d/80-moby-engine.rules 
contrib/udev/80-docker.rules
```

`contrib/udev/80-docker.rules` refers to a valid file in the moby/moby github repo though.

Could it be that, when the moby-engine deb package is built, something like this runs:
`echo -n contrib/udev/80-docker.rules > .../80-moby-engine.rules`
where `cat contrib/udev/80-docker.rules > .../80-moby-engine.rules` was intended instead?

**Comment by cpuguy83** [comment] 2020-10-13 17:34
Not exactly that problem no.
It's a disconnect in the format that debian is expecting in the packaging.

**Comment by cpuguy83** [comment] 2020-10-13 17:42
We can fix this in packaging, no biggie.

However we have not been building for Debian Stretch for a few months now since the last security update was in the beginning of July.... I see now there's this weird LTS status where some other team picks up maintenance until 2022, though.

**Comment by massand** [comment] 2020-10-26 06:02
@cpuguy83 Please keep this thread posted on availability of the fix for this bug. Ideally, we should have this in the next moby-engine package release. There are no iotedge changes needed for issue.

**Closed by massand** 2020-10-26 06:02 UTC
Labels: area:packaging, bug, customer-reported, iotedge, upstream
