### ISSUE TITLE
Edge runtime status is failed (Failed to create CoreCLR, HRESULT: 0x80004005)

### ISSUE THREAD

**Issue by felixmondelo** [Azure/iotedge#6039] opened 2022-01-25 16:42 UTC
## Expected Behavior
edgeAgent is not running, we have only edgeAgent and edgeHub modules.

## Current Behavior
edgeAgent is throwing an error: Failed to create CoreCLR, HRESULT: 0x80004005

And the iotedge logs says that 'Edge runtime status is failed':
[INFO] - Successfully started module edgeAgent
[INFO] - Checking edge runtime status
**[INFO] - Edge runtime status is failed, starting module now...**
[INFO] - Starting module edgeAgent...
[INFO] - Starting new listener for module edgeAgent
[INFO] - Listener  edgeAgent already started, removing old listener
[DBUG] - [hyper::proto::h1::io] parsed 1 headers
[DBUG] - [hyper::proto::h1::conn] incoming body is empty
[INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
[INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
[INFO] - --> 200 {"content-type": "application/json"}
[DBUG] - [hyper::proto::h1::io] flushed 1224 bytes
[INFO] - Successfully started module edgeAgent

## Steps to Reproduce
After install iotedge.

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
√ DNS server - OK
√ production readiness: logs policy - OK
√ production readiness: Edge Agent's storage directory is persisted on the host filesystem - OK
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
35 check(s) succeeded.
1 check(s) raised errors. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS: Ubuntu 20.04.3 LTS 
* Architecture [e.g. amd64, arm32, arm64]: amd64

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.7
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2
* Docker/Moby [run `docker version`]:  20.10.11+azure-3

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

[INFO] - Successfully started module edgeAgent
[INFO] - Checking edge runtime status
**[INFO] - Edge runtime status is failed, starting module now...**
[INFO] - Starting module edgeAgent...
[INFO] - Starting new listener for module edgeAgent
[INFO] - Listener  edgeAgent already started, removing old listener
[DBUG] - [hyper::proto::h1::io] parsed 1 headers
[DBUG] - [hyper::proto::h1::conn] incoming body is empty
[INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "2f72756e2f617a696f742f63657274642e736f636b:0"}
[INFO] - Listening on unix:///var/lib/aziot/edged/mnt/edgeAgent.sock with 1 thread for workload API.
[INFO] - --> 200 {"content-type": "application/json"}
[DBUG] - [hyper::proto::h1::io] flushed 1224 bytes
[INFO] - Successfully started module edgeAgent


```
</details>

<details>
<summary>edge-agent logs</summary>

```

2022-01-25 16:41:22  Starting Edge Agent
2022-01-25 16:41:22  Changing ownership of management socket: /var/run/iotedge/mgmt.sock
Failed to create CoreCLR, HRESULT: 0x80004005


```
</details>

<details>
<summary>edge-hub logs</summary>

```

No logs

```
</details>

**Comment by scb01** [comment] 2022-01-26 18:31
@felixmondelo 
Sorry to hear that you are having issues. This error is consistent with incorrect dependencies i.e., Edge Agent is unable to look up the dot net runtime that it depends upon. 

I tried to reproduce this issue by doing a fresh install on an AMD machine and I was unable to. 

Can you provide details about how you installed IotEdge and what image you are pointing to for edgeAgent?

**Comment by varunpuranik** [comment] 2022-02-10 18:41
@felixmondelo - Can you please provide the information as requested by @scb01 above? If you were able to resolve the problem, can you please close this issue? Thanks!

**Comment by varunpuranik** [comment] 2022-02-15 19:09
@felixmondelo - since we have not heard back from you, I will go ahead and close this issue. If you run into more problems with IoT Edge, please free to open a new issue.

**Closed by varunpuranik** 2022-02-15 19:09 UTC
Labels: needinfo, iotedge, customer-reported
