### ISSUE TITLE
Deactivated IotEdge consuming a lot of data on WAn

### ISSUE THREAD

**Issue by matpelchat** [Azure/iotedge#7014] opened 2023-05-03 11:38 UTC
### Device Information
* Host OS: Ubuntu 20.04.5 LTS
* Architecture: amd64:  Intel(R) Celeron(R) N6210 @ 1.20GHz 
 
### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.4.9
* Docker/Moby : Docker version 20.10.23+azure-2
 
## Logs
 
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Starting Azure IoT Edge Daemon
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Version - 1.4.9
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Obtaining Edge device provisioning data...
May 01 15:23:19 uno aziot-identityd[1588367]: 2023-05-01T15:23:19Z [INFO] - <-- POST /identities/device?api-version=2020-09-01 {"content-type": "application/json", "host": "identityd.sock", "content-length": "16"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-identityd[1588367]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Device is %%DEVICE%%.azure-devices.net
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Initializing module runtime...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Using runtime network id azure-iot-edge
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Successfully initialized module runtime
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - <-- POST /keypair?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "61"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-certd[1588382]: 2023-05-01T15:23:19Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "certd.sock"}
May 01 15:23:19 uno aziot-certd[1588382]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Using existing Edge CA certificate
May 01 15:23:19 uno aziot-certd[1588382]: 2023-05-01T15:23:19Z [INFO] - <-- GET /certificates/aziot-edged-ca?api-version=2020-09-01 {"host": "certd.sock"}
May 01 15:23:19 uno aziot-certd[1588382]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Certificate aziot-edged-ca will be auto-renewed. Next renewal at 2023-05-27T16:03:29+00:00.
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Stopping all modules...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Stopping module edgeAgent...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - All modules stopped
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Detecting if device information has changed...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Change to device information detected
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Removing all modules...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Removing module edgeAgent...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Removed all modules
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Updating cached device information
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Starting management API...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Starting workload API...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Stopping listener for module edgeAgent
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Removing listener for module edgeAgent
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Stopping listener for module edgeAgent
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Starting watchdog with 60 second period...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Starting image garbage collection task...
May 01 15:23:19 uno aziot-edged[1598532]: 2023-05-01T15:23:19Z [INFO] - Watchdog checking Edge runtime status
May 01 15:23:19 uno aziot-identityd[1588367]: 2023-05-01T15:23:19Z [INFO] - <-- PUT /identities/modules/$edgeAgent?api-version=2020-09-01&type=aziot {"content-type": "application/json", "host": "identityd.sock", "content-length": "40"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:19 uno aziot-keyd[1588370]: 2023-05-01T15:23:19Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- GET /key/aziot_identityd_master_id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "340"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "736"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "340"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "748"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:20 uno aziot-keyd[1588370]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-identityd[1588367]: 2023-05-01T15:23:20Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Creating and starting Edge runtime module edgeAgent...
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Pulling image via tag mcr.microsoft.com/azureiotedge-agent:1.4...
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Successfully pulled image mcr.microsoft.com/azureiotedge-agent:1.4
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Creating module edgeAgent...
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Creating image via tag mcr.microsoft.com/azureiotedge-agent:1.4...
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Created Edge runtime module edgeAgent
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Starting module edgeAgent...
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Starting new listener for module edgeAgent
May 01 15:23:20 uno aziot-edged[1598532]: 2023-05-01T15:23:20Z [INFO] - Starting workload API...
May 01 15:23:21 uno aziot-edged[1598532]: 2023-05-01T15:23:21Z [INFO] - Started Edge runtime module edgeAgent
May 01 15:23:21 uno aziot-edged[1598532]: 2023-05-01T15:23:21Z [INFO] - <-- GET /trust-bundle?api-version=2020-07-07 {"accept": "application/json", "host": "workload.sock:80", "connection": "close"}
May 01 15:23:21 uno aziot-certd[1588382]: 2023-05-01T15:23:21Z [INFO] - <-- GET /certificates/aziot-edged-trust-bundle?api-version=2020-09-01 {"host": "certd.sock"}
May 01 15:23:21 uno aziot-certd[1588382]: 2023-05-01T15:23:21Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:21 uno aziot-edged[1598532]: 2023-05-01T15:23:21Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - <-- GET /systeminfo?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Querying system info...
May 01 15:23:22 uno aziot-edged[1598679]: none
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Successfully queried system info
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - <-- GET /systeminfo?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Querying system info...
May 01 15:23:22 uno aziot-edged[1598689]: none
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Successfully queried system info
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - <-- GET /systeminfo?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Querying system info...
May 01 15:23:22 uno aziot-edged[1598700]: none
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - Successfully queried system info
May 01 15:23:22 uno aziot-edged[1598532]: 2023-05-01T15:23:22Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - <-- GET /modules?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - <-- POST /modules/%24edgeAgent/genid/638145792905802593/sign?api-version=2018-06-28 {"accept": "application/json", "host": "workload.sock:80", "connection": "close", "content-type": "application/json", "content-length": "185"}
May 01 15:23:23 uno aziot-identityd[1588367]: 2023-05-01T15:23:23Z [INFO] - <-- GET /identities/modules/$edgeAgent?api-version=2020-09-01&type=aziot {"host": "identityd.sock"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- GET /key/aziot_identityd_master_id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "340"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "736"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "340"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "748"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-identityd[1588367]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - <-- POST /sign?api-version=2020-09-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "926"}
May 01 15:23:23 uno aziot-keyd[1588370]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - <-- POST /device/reprovision?api-version=2022-08-03 {"host": "mgmt.sock:80", "connection": "close", "content-type": "application/json; charset=utf-8", "content-length": "0"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - --> 204 {}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Edge daemon will reprovision and restart
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Watchdog stopped
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Stopping all modules...
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Stopping module edgeAgent...
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Stopping listener for module edgeAgent
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Workload API stopped
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - <-- GET /systeminfo?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Querying system info...
May 01 15:23:23 uno aziot-edged[1598721]: none
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - Successfully queried system info
May 01 15:23:23 uno aziot-edged[1598532]: 2023-05-01T15:23:23Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - <-- GET /modules?api-version=2022-08-03 {"accept": "application/json", "host": "mgmt.sock:80", "connection": "close"}
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - All modules stopped
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - watchdog finished
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - Stopping management API...
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - Stopping workload API...
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - Management API stopped
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - Workload Manager stopped
May 01 15:23:28 uno aziot-edged[1598532]: 2023-05-01T15:23:28Z [INFO] - Stopping listener for module edgeAgent
May 01 15:23:28 uno aziot-identityd[1588367]: 2023-05-01T15:23:28Z [INFO] - <-- POST /identities/device/reprovision?api-version=2020-09-01 {"content-type": "application/json", "host": "identityd.sock", "content-length": "16"}
May 01 15:23:28 uno aziot-identityd[1588367]: 2023-05-01T15:23:28Z [INFO] - Provisioning starting. Reason: Api
May 01 15:23:28 uno aziot-identityd[1588367]: 2023-05-01T15:23:28Z [INFO] - %%DEVICE%%.
May 01 15:23:28 uno aziot-identityd[1588367]: 2023-05-01T15:23:28Z [INFO] - Provisioning complete.
May 01 15:23:28 uno aziot-identityd[1588367]: 2023-05-01T15:23:28Z [INFO] - Identity reconciliation started. Reason: Api
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:28 uno aziot-keyd[1588370]: 2023-05-01T15:23:28Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-identityd[1588367]: 2023-05-01T15:23:29Z [INFO] - Hub identity "DefenderIotMicroAgent" will be recreated
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- GET /key/aziot_identityd_master_id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "352"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "792"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /derivedkey?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "356"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /derivedkey/export?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "800"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- GET /key/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - <-- POST /sign?api-version=2021-05-01 {"content-type": "application/json", "host": "keyd.sock", "content-length": "390"}
May 01 15:23:29 uno aziot-keyd[1588370]: 2023-05-01T15:23:29Z [INFO] - --> 200 {"content-type": "application/json"}
May 01 15:23:29 uno aziot-identityd[1588367]: 2023-05-01T15:23:29Z [INFO] - Hub identity "DefenderIotMicroAgent" added
May 01 15:23:29 uno aziot-identityd[1588367]: 2023-05-01T15:23:29Z [INFO] - Identity reconciliation complete.
May 01 15:23:29 uno aziot-identityd[1588367]: 2023-05-01T15:23:29Z [INFO] - --> 204 {}
May 01 15:23:29 uno systemd[1]: aziot-edged.service: Main process exited, code=exited, status=154/n/a
May 01 15:23:29 uno aziot-edged[1598532]: 2023-05-01T15:23:29Z [INFO] - Successfully reprovisioned
May 01 15:23:29 uno aziot-edged[1598532]: 2023-05-01T15:23:29Z [INFO] - Device provisioning has changed. Restarting Edge daemon to get new provisioning info.
May 01 15:23:29 uno systemd[1]: aziot-edged.service: Failed with result 'exit-code'.
May 01 15:23:34 uno systemd[1]: aziot-edged.service: Scheduled restart job, restart counter is at 5892.
May 01 15:23:34 uno systemd[1]: Stopped Azure IoT Edge daemon.
May 01 15:23:34 uno systemd[1]: Started Azure IoT Edge daemon.
 
## Additional Information

The log extract we have here is basically repeated infinitely. Once it reaches "Started AzureIOT Edge daemon" it will go through the same sequence. This causes a lot of data transmit/receive on our aircard connected device. We are seeing roughly 30+MB per hour of data sent/received to this device (20MB downstream 10MB, upstream) on a device that has no edge module active beside the edge agent and edge hub. The device is also currently disabled on the IoT Hub. The device is basically standing "idle". Is it the intended behavior for the iotedge to check the iot hub all the time? This causes a lot of unintended data consumption.

**Comment by konichi3** [comment] 2023-05-11 20:49
@matpelchat Can you help understand the problem with the following information?

- Clarity on `consuming a lot of data`. What is the behavior and expected behavior?
- Repro steps 
- Any smoking guns in the log attached that you noticed?

**Comment by matpelchat** [comment] 2023-05-12 13:10
Hi, 
-device is consuming 30MB+ an hour, when device is disabled at the Hub. when the device is enabled, it barely consumes 1MB per hour. 
-repro: deploy a ubuntu 20.04. install azure-iot edge, provision device in IOT HUB but set "Enable connection to IoT Hub" to "Disabled"
-only smoking gun i see is that it will loop the log i posted as fast as it can. there is no pause. it just tries and tries again.

**Comment by nlcamp** [comment] 2023-05-12 15:05
@matpelchat - I was able to reproduce this issue and I understand your concern. Unfortunately, I don't see any configuration parameters that allow you to change this behavior.

After edgeAgent starts, it soon receives a connection status change callback from the Azure IoT SDK stating that the device is disabled. EdgeAgent then immediately issues a reprovision request to the edge daemon, which is why you see the logs continually cycling:

https://github.com/Azure/iotedge/blob/057e7febf94eb9e58a3ef12e61e9b4d3048cb0f9/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs#L243-L248

I think we would need to change the behavior to support a configurable reprovision timer or add some kind of exponential backoff mechanism. Since this would be a new feature, I would suggest filing a feature request at https://aka.ms/iotedge-suggestion.

As a workaround, you may want to consider turning off the iotedge runtime via `iotedge system stop` instead of disabling the device in IoT Hub. Of course, this will require logging into the device to issue the command, which may or may not be feasible for you.

**Comment by matpelchat** [comment] 2023-05-12 18:16
i would too advocate for the exponential backoff mechanism, i will file a feature request. thank you for your feedback.

**Comment by nlcamp** [comment] 2023-05-15 13:14
No problem. Feel free to post a link to your feature request here when you're ready. Closing the issue at this time.

**Closed by nlcamp** 2023-05-15 13:14 UTC
Labels: iotedge, customer-reported

**Comment by matpelchat** [comment] 2023-05-16 17:46
@nlcamp here's the link to the feature request. 
https://feedback.azure.com/d365community/idea/c952a34f-11f4-ed11-a81c-000d3a7a9cdb
thanks for your help again.

**Comment by florian-fischer-swarm** [comment] 2023-05-22 13:18
We have found a similar issue related to very high data consumption, however, tied into retry / reconnect handling of edgeHub in our case. This caused huge data traffic from the edgeHub Module to IoTHub via AQMPS.

Upgrading to https://github.com/Azure/iotedge/releases/tag/1.4.10 made that not reproducible for us anymore.

I suspect the underlying reason is the upgrade of https://github.com/Azure/azure-iot-sdk-csharp/releases/tag/lts_2021-3-18_patch8. However, I cannot say with certainty.
