### ISSUE TITLE
Upgrade Edge Runtime Version from 1.0.8 to 1.0.9 on all the Gateway

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#2809] opened 2020-04-07 05:52 UTC
Hi Team,
    We want to upgrade Edge Runtime version from 1.0.8 to 1.0.9. So will edgeHub and edgeAgent 1.0.8 Container image work with Runtime version 1.0.9. Because currently we have deployed the edgeAgent and edgeHub container version 1.0.8 on the gateway. 

Also is there any dependency of the edgeHub and edgeAgent image version with Runtime version ?  Also will the semantic versioning works or not ?? Please could you let me know it in details..

**Comment by ancaantochi** [comment] 2020-04-07 16:43
@sachidanand,

edgeHub and edgeAgent images had a bug which was fix in 1.0.8.4 so the deployment has to explicitly use 1.0.8.4 to work with iotedged 1.0.9. If the deployment you use 1.0 or 1.0.8 it won't work with 1.0.9 runtime.

**Comment by massand** [comment] 2020-04-07 20:25
Version differences between system modules (edgeHub and edgeAgent) and Edge runtime (iotedged) don't matter generally. This is because the Edge runtime API interface for edgeHub and edgeAgent is backwards compatible with previous versions of system modules. However, couple of things to keep in mind - 
1) there might be some exceptions due to critical fixes, as @ancaantochi mentioned (thanks!), where a minor version upgrade maybe required for system modules to sustain normal functionality, and
2) it is recommended the Edge runtime be maintained at a higher version than system modules. The SDK (used within modules) is not tested with older versions of Edge runtime AFAIK. So, if it works for you, then great!

Please close the issue if this answers your question. Thanks.

**Comment by sachidanand** [comment] 2020-04-08 06:31
Hi Team,
    Thanks for your response.. Now I have one more question, will it be always two steps upgrade first main version to minor version and then upgrade to main version?? Actually we need to setup a process for these kind of upgrade and then all fleet gateway will be upgraded accordingly. 

So are you recommending that we should always move first from 1.0.x to 1.0.x.x and then it would work with the latest main version of Edge Runtime? 

If it is the case then we can set up a process around it and then we can adopt this practice.

**Comment by massand** [comment] 2020-04-08 15:51
The overall [guidance](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-update-iot-edge) is always the following - As the IoT Edge service releases new versions, you'll want to update your IoT Edge devices for the latest features and security improvements. This applies to both runtime and daemon equally, i.e. we release them in sync and they should be updated in sync.

The daemon version is the minimum version for the runtime version, since runtime is backwards-compatible with older daemon versions (although it isn't well tested. Again, we recommend devices always have current versions of both, as much as possible.  

Diving deeper into versioning, all released versions of daemon and runtime follow [semver](https://semver.org/) conventions. Release precedence would be as follows: 1.0.0 < 1.0.x < 1.0.x.hotfix < 1.0.y < 1.0.y.hotfix < 1.0.y-rc1

The latest hotfix is always recommended. If you plan to stick a specific release for daemon and upgrade runtime, then it is prudent to upgrade daemon to latest hotfix release (like 1.0.8.4). We are backwards compatible, so runtime 1.0.y versions (like 1.0.9) will generally work with daemon 1.0.x, but you should upgrade daemon to the 1.0.x.latesthotfix (like 1.0.8.4) version.

**Comment by cmenzi** [comment] 2020-04-08 20:37
I understand that the runtime and the system modules **should** be in sync. But our fleet management which is responsible for OS updates, security patches and controlling the software installed on the OS should not be coupled to the running contrainers. Or at least not minor changes.

Scenario:

We have deployment templates with routes and version pinned modules including version pinned system modules (edgeHub & egdeAgent). Which is for _production usage_ according to the guidance.

Now, a new runtime is released (e.g 1.0.9). Then, our fleet mangement will update the runtime at some point of time and via some ring updates. The runtime restarts and fetches the deployment template for a specific IoT device, which includes a edgeHub and edgeHub with the version 1.0.8. You now saying, that it could happen that nothing works anymore. This should realy be avoided.

To create an atomic upgrade in fleet mangement and IoT Hub deployment templates is very difficult. This would mean, that we need to update the runtime and changing all deploment templates of all IoT Gateway in single operation.

Those are two different teams, two different systems. One is the OS and software distribution system and the other is Azure IoT Hub API.

When the system modules are that tight coupled to the runtime, why are those not part of the runtime itself?

For us, it's important that we can rely on semver or on a **2-phase upgrade** option.

Sidenote:

If you referring to [semver](https://semver.org/), then you also need to follow it: **If an API is incompatible, then you need to change the _MAJOR_ version.** 

> Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

On Azure IoT Edge Runtime, you always releasing **PATCH** versions.

**Comment by massand** [comment] 2020-04-08 22:20
> To create an atomic upgrade in fleet mangement and IoT Hub deployment templates is very difficult.
I certainly appreciate the complexity in coordinating OS and container updates. I also see we need to add more tests here to cover the gamut of hops each component can perform. We are working on this.   

> You now saying, that it could happen that nothing works anymore. This should realy be avoided.
Definitely not saying that will always be the case :) We always support mismatched versions. 
In this instance for upgrade to 1.0.9 though, @ancaantochi provided a heads up that a hotfix (1.0.8.4) is needed to the container runtime. We recommend the deployment always be tested before roll out. I am unsure what the bug is here. @ancaantochi can add more details on the criticality of the fix.

**Comment by ancaantochi** [comment] 2020-04-08 23:17
The issue that is fixed in 1.0.8.4 is to support a higher version of iotedged from the system modules. It was a bug in the edgeAgent and edgeHub that the version was not correctly used and as a result edgeAgent would not start with a higher version of iotedged. 

You only need to update edgeAgent and edgeHub to 1.0.8.4 first (no need to update the runtime) and then you can update the runtime to 1.0.9.

**Comment by sachidanand** [comment] 2020-04-09 05:58
It means we should go for two phase upgradation first upgrade 1.0.8 to 1.0.8.4 and then upgrade runtime from 1.0.8 to 1.0.9 and then update the System Module version again from 1.0.8.4 to 1.0.9

**Comment by ancaantochi** [comment] 2020-04-09 20:13
If you want to upgrade images first for edgeAgent and edgeHub you can directly upgrade to 1.0.9 and then the runtime to 1.0.9. 
It doesn't work the other way around if you upgrade the runtime first and the images are 1.0.8. So the bug fix is in 1.0.8.4 and later versions in edgeAgent and edgeHub, any version after 1.0.8.4 should be able to handle the runtime with a higher version (1.0.9 in this case).

**Comment by cmenzi** [comment] 2020-04-09 21:12
Thank you very much for clarification! @ancaantochi 

Do you think it may be worth to document this on the release notes or in in the guidance page?

I guess we are not the only one who needs this valueable information.

Thanks!

**Comment by sachidanand** [comment] 2020-04-16 14:16
Hi Team,
    Is edgeHub version 1.0 pointing to 1.0.9 ???

**Comment by massand** [comment] 2020-04-16 16:41
Yes it is (since the digests match) - 
```
$ docker image pull mcr.microsoft.com/azureiotedge-hub:1.0
1.0: Pulling from azureiotedge-hub
89d9c30c1d48: Already exists
b02340cc0a47: Already exists
32e673fc12c4: Already exists
a22bfc1623f8: Pull complete
bb139864839f: Pull complete
6f03dfccad3e: Pull complete
515fc2a498e1: Pull complete
4862e45e6fbf: Pull complete
cfb0f9997d7e: Pull complete
Digest: sha256:d5969237146d382ae74e4a75934c194f63ec737d4aaaf4a03a2ef7f4f716f153
Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-hub:1.0
mcr.microsoft.com/azureiotedge-hub:1.0

$ docker image pull mcr.microsoft.com/azureiotedge-hub:1.0.9
1.0.9: Pulling from azureiotedge-hub
Digest: sha256:d5969237146d382ae74e4a75934c194f63ec737d4aaaf4a03a2ef7f4f716f153
Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-hub:1.0.9
mcr.microsoft.com/azureiotedge-hub:1.0.9
```

**Comment by sachidanand** [comment] 2020-04-17 05:39
We are facing issue currently in production where we are having edgeHub 1.0 image and the Runtime is 1.0.8 .. edgeHub 1.0 is not working with Edge Runtime 1.0.8 version..

**Comment by ancaantochi** [comment] 2020-04-20 17:46
@sachidanand, can you please provide edgeHub logs? 
I tried to reproduce using runtime 1.0.8 and edgeHub:1.0, edgeAgent:1.0 and it worked. Please check that the image for edgeHub:1.0 on the device is 1.0.9:

`docker inspect image <imageid>`

and check the digest

**Comment by sachidanand** [comment] 2020-04-21 08:31
Agent is working but edgeHub is not working

**Comment by ancaantochi** [comment] 2020-04-21 17:38
Can you please provide the logs for edgeHub? I was not able to reproduce. Please also check the digest for edgeHub image.

**Comment by ancaantochi** [comment] 2020-04-23 18:37
@sachidanand, do you still have this issue? Please upload logs if edgeHub 1.0 is not working with 1.0.8

**Comment by sachidanand** [comment] 2020-04-24 12:32
We have updated it now with 1.0 to 1.0.8 and it works with it ..

**Comment by ancaantochi** [comment] 2020-04-30 00:24
Closing issue, please reopen if you have this issue again.

**Closed by ancaantochi** 2020-04-30 00:24 UTC
Labels: customer-reported, iotedge, question
