### ISSUE TITLE
Module is disconnected from edgeHub after some hours

### ISSUE THREAD

**Issue by DennisK92** [Azure/iotedge#731] opened 2019-01-18 08:25 UTC
## Expected Behavior
The edgeHub should establish a new connection, when it registers that a module is not connected.

## Current Behavior
The edgeHub registers that a module is not connected but doesn't establish a new connection.

## Steps to Reproduce
1. Create 3 modules, where module A sends messages (2 sec interval) to module B and module B sends those messages to module C, where messages are sent to upstream.  A => B => C => IoT Hub
2. Deploy on RaspberryPi 3 and let it run for some hours, while everything runs as expected.
3. At some point module B won't receive messages anymore, because it is not connected.
4. Messages are not transferred anymore, while all modules are up and running.

### Device (Host) Operating System
Device: RaspberryPi 3 
OS: Raspbian Stretch

### Architecture
arm32

### Container Operating System
Linux containers

#### iotedged
iotedge 1.0.5

#### Edge Agent

Agent 1.0.5.19141174

#### Edge Hub

Hub 1.0.5.19141174

#### Docker
Docker 3.0.2

## Logs

Logs: https://gist.github.com/DennisK92/8e75c3698b03c3ba7abbeb6987a6534a

## Additional Information

The dataFeeder creates a message every 2 seconds and sends them to anomalySimulator. This module sends the received messages to edgeMetering, which adds some additional parameters to the message and sends it to upstream to be received by the IoT Hub. However, this only works correctly for a few hours. After that, the module anomalySimulator is not connected anymore and doesn't reconnect. Therefore, messages aren't sent to the IoT Hub anymore.

**Comment by MPapst** [comment] 2019-01-18 18:45
Sounds a bit like the issue I was having (explained in #673). 
Actually it helped upgrading the SDK to the latest version for my C# modules. I think the root cause was fixed here: Azure/azure-iot-sdk-csharp#558 (only applies if your modules are C# )

**Comment by DennisK92** [comment] 2019-01-22 07:12
The latest C# SDK should automatically be pulled when building the modules, if I understand correctly, or is a manual SDK update required? I rebuild all of my modules yesterday and my module still gets disconnected after some hours. What the disconnected module basically does is receive a message and forward it to the next module.

**Comment by DennisK92** [comment] 2019-01-22 09:14
Okay I set the PackageReference to explicitly use version 1.19.0 now and rebuild all modules. Will update later today/tomorrow whether the module messaging chain keeps the connection alive.

**Comment by varunpuranik** [comment] 2019-01-22 18:02
@DennisK92 - yes, SDK update to 1.19.0 should resolve this issue. Please note that you might have to update the module image version and do another deployment to make sure the updated module is picked up by the Edge runtime. 

Also, please note that connecting/reconnecting is done by the client (your module) and not by the server (EdgeHub). So this is not a bug in EdgeHub, but in the SDK you are using. The v1.19.0 has the fix for it.

**Comment by DennisK92** [comment] 2019-01-23 08:46
Using the 1.19.0 SDK explicitly, rebuilding all modules and deploying them again solved the connectivity issue.
However, now the edgeHub and my dataFeeder module crashed after some hours.
`dataFeeder        failed           Failed (132) 16 hours ago
edgeHub           failed           Failed (132) 16 hours ago `
The dataFeeder module crashed because of an unhandled TimeoutException, which is fine at first but the module isn't restarted by the edgeAgent even though restartPolicy is set to "always". In addition, the edgeHub crashed shortly afterwards because of a bad_alloc and is also not restarted anymore.
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
`

"OptimizeForPerformance" for edgeHub on resource constrained devices is set to false in the deployment.
`          "edgeHub": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
            },
            "env": {
              "OptimizeForPerformance": {
                "value": "false"
              }
            },
            "status": "running",
            "restartPolicy": "always"
          }`

Please see the following logs of edgeHub, edgeAgent and my dataFeeder module.
[https://gist.github.com/DennisK92/9fa8c4d7c92affc52ea2db819bb7acde](url)

**Comment by varunpuranik** [comment] 2019-01-23 15:21
Interesting, edgeAgent should have restarted the modules. I am not able to access the logs in the link above. Can you please check access on the link?

**Comment by DennisK92** [comment] 2019-01-24 07:17
@varunpuranik Sorry with the link, edited my post. The link is correct now. https://gist.github.com/DennisK92/9fa8c4d7c92affc52ea2db819bb7acde
Today all modules are still running and connected, so this problem doesn't seem to always happen. Since a timeout occured while sending a message, this could have to do something with unstable network service? However this doesn't explain why the modules theren't restarted by the edgeAgent while the edgeAgent itself was running.

**Comment by myagley** [comment] 2019-02-19 20:20
It's possible that the Edge Agent didn't restart the Edge Hub because of a deadlock in the dotnet core runtime. This was fixed in `1.0.6`. Is it possible to upgrade?

**Comment by DennisK92** [comment] 2019-02-20 09:34
Yes I will upgrade the version to `1.0.6` on every Pi in use. The problem of edgeHub not being restarted actually occurred multiple times on version `1.0.5` in the meantime, so possibly this will fix it.

**Comment by DennisK92** [comment] 2019-06-12 12:09
I'm not encountering this issue anymore. It is solved.

**Closed** 2019-06-12 12:09 UTC
