### ISSUE TITLE
Unable to load the service index for source https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by bechynsky** [Azure/iotedge#2054] opened 2019-11-29 12:18 UTC
Environment: Dev machine running supported version of Windows 10 IoT Enterprise, latest Docker CE switched to Windows containers, Visual Studio COde and IoT Edge plugin. IoT Edge is tested and running. There was known issue with DNS solved by adding fix DNS on OS level. 
 
If we try to build custom C# module based using microsoft/dotnet:2.1-sdk base container we get this error
 
docker build  --rm -f
"c:\Users\stepanb\Documents\IoT Edge Dome\EdgeSolution101\modules\SampleModule101\Dockerfile.windows-amd64" -t stepanb.azurecr.io/samplemodule101:0.0.1-amd64 "c:\Users\stepanb\Documents\IoT Edge Dome\EdgeSolution101\modules\SampleModule101"
Sending build context to Docker daemon  17.41kB
Step 1/10 : FROM microsoft/dotnet:2.1-sdk AS build-env
2.1-sdk: Pulling from microsoft/dotnet
d0c6a1b3dba2: Pull complete
5da99380d93e: Pull complete
23add0d71b40: Pull complete
10c60d2f3305: Pull complete
467e8374427a: Pull complete
4df65c6b837f: Pull complete
eed65dfedd9a: Pull complete
Digest: sha256:3613ad07fc7c9abeb24fccef21de7b8a2d32efbd7299e4b91a5765bc48e3cda5
Status: Downloaded newer image for microsoft/dotnet:2.1-sdk
 ---> 3b323b0465ee
Step 2/10 : WORKDIR /app
 ---> Running in 3b098be2d38b
Removing intermediate container 3b098be2d38b
 ---> 9f6f6daf374f
Step 3/10 : COPY *.csproj ./
 ---> 9d9d8d3304dc
Step 4/10 : RUN dotnet restore
 ---> Running in 07145db12328
C:\Program Files\dotnet\sdk\2.1.802\NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\SampleModule101.csproj]
C:\Program Files\dotnet\sdk\2.1.802\NuGet.targets(123,5): error :   No such host is known [C:\app\SampleModule101.csproj]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1
 
If we switch on same computer to Linux containers it works.

**Comment by varunpuranik** [comment] 2019-12-02 17:47
Hi @bechynsky, this seems like a docker with windows containers issue, and not related to IoT Edge as such. Did you try restarting the docker service? I read reports of that fixing it. 
@adashen, @xinshiMSFT - any other pointers to help resolve this issue?

**Comment by bechynsky** [comment] 2019-12-03 06:38
Hi, I did all recommended steps to fix it. I have same issue on my dev laptop running Windows 10 Enterprise.

**Comment by veyalla** [comment] 2019-12-03 15:58
Adding @shizn

**Comment by shizn** [comment] 2019-12-03 20:53
Thanks for looping me in. Please check this nuget issue https://github.com/NuGet/Home/issues/5358 to see if those workarounds work for you.

**Comment by blackchoey** [comment] 2019-12-04 02:37
```
C:\Program Files\dotnet\sdk\2.1.802\NuGet.targets(123,5): error : No such host is known [C:\app\SampleModule101.csproj]
```
According to above logs, the ip address of `api.nuget.org` cannot be resolved in docker container.
Could you try command `docker run microsoft/dotnet:2.1-sdk ping api.nuget.org` to see whether the DNS resolution in docker container works well?

**Comment by bechynsky** [comment] 2019-12-06 09:26
Version of Docker is 2.1.0.1
Result of ping

```
docker run microsoft/dotnet:2.1-sdk ping api.nuget.org
Ping request could not find host api.nuget.org. Please check the name and try again.
```

After update to 2.1.0.5 is problem same.

**Comment by veyalla** [comment] 2019-12-07 18:41
You mentioned some DNS issues fixed at the host level, you might be running into similar issues from within the container.

You can try the resolution from [here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#edge-agent-module-continually-reports-empty-config-file-and-no-modules-start-on-the-device).

You'll need to use the path `C:\ProgramData\docker\config` for `daemon.json` file (and restart `docker` service) since you're using Docker Desktop.

**Comment by bechynsky** [comment] 2019-12-08 16:06
This is not working, I already tested it before I created issue here. I tried to setup DNS inside Docker container using this command

`netsh interface ip set dns "Ethernet" static 8.8.8.8`

Command completes with no effect to host find host. Interesting is that I can ping servers after running this.

**Comment by bechynsky** [comment] 2019-12-08 16:18
Here is test I did

Command: 
`docker run -it --user administrator microsoft/dotnet:2.1-sdk  ping google.com`
Output: 
`Ping request could not find host google.com. Please check the name and try again.`

Command: 

`docker run -it --user administrator microsoft/dotnet:2.1-sdk netsh interface ip set dns "Ethernet" static 8.8.8.8 & ping google.com
`
Output:

```
Pinging google.com [172.217.20.238] with 32 bytes of data:
Reply from 172.217.20.238: bytes=32 time=25ms TTL=56
Reply from 172.217.20.238: bytes=32 time=40ms TTL=56
Reply from 172.217.20.238: bytes=32 time=2ms TTL=56
Reply from 172.217.20.238: bytes=32 time=5ms TTL=56

Ping statistics for 172.217.20.238:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 40ms, Average = 18ms
```

Updated Docker file

```
FROM microsoft/dotnet:2.1-sdk AS build-env

USER administrator
RUN netsh interface ip set dns "Ethernet" static 8.8.8.8

USER ContainerUser
WORKDIR /app
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "SampleModule101.dll"]

```

Same error

```
Step 7/13 : RUN dotnet restore
 ---> Running in 755ec223ffe5
C:\Program Files\dotnet\sdk\2.1.802\NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\SampleModule101.csproj]
C:\Program Files\dotnet\sdk\2.1.802\NuGet.targets(123,5): error :   No such host is known [C:\app\SampleModule101.csproj]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

```

I got same result running all under _administrator_ user.

**Comment by veyalla** [comment] 2019-12-08 16:34
The only valid admin user I know for Windows containers is `ContainerAdministrator`, so might want to try that.

Also this Moby issue/fix seems relevant: https://github.com/moby/moby/pull/30383

**Comment by bechynsky** [comment] 2019-12-08 16:44
If you not use _administrator_ DNS setup is not working.

Command:

`docker run -it microsoft/dotnet:2.1-sdk netsh interface ip set dns "Ethernet" static 8.8.8.8 & ping google.com`

Output

`The requested operation requires elevation (Run as administrator).`

**Comment by veyalla** [comment] 2019-12-10 18:10
@seanmcd-msft Can you help here please?

**Comment by seanmcd-msft** [comment] 2019-12-10 19:27
are you trying to run IotEdge-Moby and Docker CE at the same time?  If so, that is not supported.  They can both be installed simultaneously and thus maintain separate configurations. but, only one can be enabled at a time.

**Comment by bechynsky** [comment] 2019-12-11 08:20
Moby is not installed on computer.

**Comment by seanmcd-msft** [comment] 2019-12-11 21:04
Earlier in the thread you said that iotedge was tested and running successfully after a DNS change.  did I misunderstand that comment?  The iotedge install includes the iotedge-moby service.  Also, can you share the entire Dockerfile?

**Comment by bechynsky** [comment] 2019-12-12 09:34
On one computer it was never installed on second we removed before we installed Docker.

**Comment by seanmcd-msft** [comment] 2019-12-13 01:29
ok, so this doesn't appear to be an IoT Edge issue.  if you replace the 'RUN dotnet restore' with 'RUN curl http://nuget.org' do you get back html from the nuget site?

**Comment by auroramo** [comment] 2019-12-31 10:24
Hi,

I have the same issue as bechynsky. I've made the replacement that seanmcd-msft said and the result is 
![image](https://user-images.githubusercontent.com/8794808/71618487-0a9d0800-2bc0-11ea-9ba4-22b555603d3c.png)

Do you have an idea about what the problem is?

**Comment by veyalla** [comment] 2020-01-07 18:16
@seanmcd-msft Can you PTAL?

**Comment by seanmcd-msft** [comment] 2020-01-07 19:49
i'm not sure what's going on here.  but, this doesn't look like an iot edge issue. it seems like some kind of local network configuration problem or a nuget issue.  if you can't access the initial .html page from nuget.org then you're not going to be able to download any packages from there either.  the result from that curl command should be a simple .html page that redirects you to www.nuget.org.  You're likely to get better help from dotnet build or nuget folks.

**Comment by seanmcd-msft** [comment] 2020-01-07 21:09
it occurs to me that this could be another manifestation of the dual vnet problem as described here:
https://social.msdn.microsoft.com/Forums/en-US/dd2cf0b1-e5ac-4295-89e7-3d29893a3781/problem-of-experimenting-azure-iot-edge-offline-connectivity?forum=iotedge

does the output from 'ipconfig /all' show 2 vEthernet(nat) interfaces?

**Comment by auroramo** [comment] 2020-01-08 16:24
The output from 'ipconfig /all' shows only 1 vEthernet(nat) interface in my case: Hyper-V Virtual Ethernet Adapter #2

**Comment by LarsKemmann** [comment] 2020-02-12 00:31
Can we please keep this issue alive? I'm running into the same problem, or at least the symptoms are all exactly the same. Any guidance would be appreciated. @bechynsky or @auroramo -- have either of you been able to resolve this for yourselves, and if so what did you have to do?

**Comment by arsing** [comment] 2020-02-17 04:08
Given that none of your containers can resolve hostnames, this is an issue with Docker for Windows rather than anything specific to IoT Edge. You likely want to open an issue at https://github.com/docker/for-win

---

FWIW, I'm confused by @bechynsky 's comment in https://github.com/Azure/iotedge/issues/2054#issuecomment-562965293

>Command:
>
>`docker run -it --user administrator microsoft/dotnet:2.1-sdk netsh interface ip set dns "Ethernet" static 8.8.8.8 & ping google.com `
>Output:
>
>```
>Pinging google.com [172.217.20.238] with 32 bytes of data:
>Reply from 172.217.20.238: bytes=32 time=25ms TTL=56
>```

If this is actually what they ran, and assuming this is being run from `cmd.exe`, then `cmd.exe` would split the command at the `&` so that the `ping google.com` would run on the host, not inside the container. (I don't have `cmd.exe` on hand to check for myself.)

If that command really *did* run `ping google.com` inside the container, implying the `netsh` command fixed the issue, then I don't see a reason why the solution would work with `docker run` but not in a `Dockerfile`.

One possibility is that the `Dockerfile` splits the `netsh` command and the `dotnet restore` command into separate `RUN` steps. If `netsh` is only changing an unpersisted configuration then it might be lost by the time the `dotnet restore` step runs. So it might work to have a single `RUN` step that does `netsh ... & dotnet ...` (Of course this means both will need to run as `Administrator`, so maybe you can wrap the `dotnet` command in a `runas` or something. It also means that the actual runtime stage of the image will also need to run `netsh ...` instead of just running `dotnet` via `ENTRYPOINT`.)

If that doesn't help, or if the `netsh` command never actually helped even with `docker run`, then again you likely want to ask at https://github.com/docker/for-win

**Closed by arsing** 2020-02-17 04:08 UTC
Labels: WindowsOnly, area:docker, no-issue-activity

**Comment by Type1JGB** [comment] 2020-06-15 20:42
I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:

There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.

Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.

After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.

I hope this helps somebody.

**Comment by Vijay-Karthick** [comment] 2020-07-06 21:58
> 
> 
> I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:
> 
> There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.
> 
> Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.
> 
> After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.
> 
> I hope this helps somebody.

This solved the issue I had. Thanks @Type1JGB :)

**Comment by durairajasivam** [comment] 2020-07-13 03:50
I had a similar issue. following is worked for me 
I have added  **"bridge":"none"**  in  **C:\ProgramData\Docker\config\daemon.json** after removing this **"bridge":"none"** started to work for me.

**Comment by piyaln** [comment] 2020-08-30 10:41
> > I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:
> > There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.
> > Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.
> > After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.
> > I hope this helps somebody.
> 
> This solved the issue I had. Thanks @Type1JGB :)

This worked for me too

**Comment by RenganathanRennie** [comment] 2020-10-07 01:54
> > > I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:
> > > There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.
> > > Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.
> > > After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.
> > > I hope this helps somebody.
> > 
> > 
> > This solved the issue I had. Thanks @Type1JGB :)
> 
> This worked for me too

Worked for me too ,Thanks so much

**Comment by amialeo** [comment] 2021-08-16 23:51
> I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:
> 
> There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.
> 
> Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.
> 
> After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.
> 
> I hope this helps somebody.

You are a life saver. Thank you so much!

**Comment by manjulaperera** [comment] 2021-12-05 13:11
> I really would like this fixed. Just to help anybody else that came across this issue, here's what I did:
> 
> There's a file at the path `C:\ProgramData\Docker\config\daemon.json`. Add the line: `"dns": ["8.8.8.8"]` in the JSON object.
> 
> Ideally, replace it with your actual DNS server. 8.8.8.8 is just a well known DNS server, so it should work.
> 
> After adding that line, restart the Docker daemon. You can use the context menu from the system tray for that.
> 
> I hope this helps somebody.

This worked for me. Thanks!

**Comment by foka** [comment] 2022-12-01 18:12
> I don't have this file existing, so I created such a file with the said content. No luck. Psst.

@nicholasyin, try `%userprofile%\.docker\daemon.json`
