### ISSUE TITLE
edgeAgent is not picking changes from config.toml.

### ISSUE THREAD

**Issue by anoop18pant** [Azure/iotedge#6231] opened 2022-03-24 09:12 UTC
Dear all,
I am using azureiotedge-agent:1.2 and azureiotedge-hub:1.2

OS : Raspbian GNU/Linux 10 (buster)

I have a edge device running in my network now due to some network changes i have to use Proxy setting to access the internet. So for that i have done ssh to my edegDevie and done follwoing things:

1. sudo iotedge system stop >>>> All the modules stopped.
2. open /etc/aziot/config.toml and added  following
   [agent.env]
    "http_proxy" = "proxy_url"
    "https_proxy" = "proxy_url"
     "no_proxy" = "localhost,127.0.0.1"

after that
3. sudo iotedge config apply

But still edgeAgent is not picking the proxy settings. Its using older network information without proxy. Its not hitting proxy server.

Can some pleasehelp what can be the issue.

**Comment by huguesBouvier** [comment] 2022-03-24 17:15
Hello,

I think the issue is that when you do "iotedge system stop" it stops the container but doesn't "kill" them. So edgeAgent module is stopped and resume operation upon " sudo iotedge config apply". For edgeAgent to pick the new environment variable you need a new edgeAgent container.
Do "iotedge system stop" and remove the current edgeAgent. That will force a new edgeAgent with the correct settings.

**Comment by jlian** [comment] 2022-04-07 21:24
@anoop18pant can you try doing `docker rm -f edgeAgent` and see if that resolves your issue?

**Comment by jlian** [comment] 2022-04-07 21:25
We should document this

**Comment by huguesBouvier** [comment] 2022-04-12 17:20
I am closing the issue. Please re-open if it is still a problem.

**Closed by huguesBouvier** 2022-04-12 17:20 UTC
Labels: docs, iotedge, customer-reported
