### ISSUE TITLE
edgeHub and modules are not able to connect with AMQP or MQTT using modem connection

### ISSUE THREAD

**Issue by wvangeem** [Azure/iotedge#6783] opened 2022-11-15 15:31 UTC
## Behavior
I have an Ubuntu 20.04 device with integrated modem/LTE device.
When connecting with LAN cable everything works perfect, but when only when using the modem, the edgeHub and other modules fail to connect to IoTHub

## Current Behavior
On LAN cable, all protocols are OK when doing 'iotedge check'
As you can see in the 'iotedge check' below on modem connection only (LAN disconnected), the host is able to connect to iothub using all protocols.
But on modem connection only, the default container network and azure-iot-edge network fail to connect to the Websockets ports. Reason is unknown.
But they do allow connection on both AMQP and MQTT ports.
I forced both edgeAgent and edgeHub to connection via MQTT (UpStreamProtocol = MQTT), and added a startupsequence for the modules.
Only the edgeAgent connects, edgeHub and other modules fail to connect.

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. Only modem connection to internet
2. Set env "UpStreamProtocol" = "MQTT"
3. Check logs of edgeHub

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
[iotedge-check.txt](https://github.com/Azure/iotedge/files/10013930/iotedge-check.txt)
```
</details>

### Device Information
* Host OS: Ubuntu 20.04 
* Architecture: amd64 
* Container OS: Linux containers

### Runtime Versions
* aziot-edged: 1.4.2
* Edge Agent: 1.4
* Edge Hub: 1.4
* Docker/Moby: 20.10.20+azure-1

## Logs

<details>
<summary>aziot-edged logs</summary>

```
[aziot-edged1.txt](https://github.com/Azure/iotedge/files/10013936/aziot-edged1.txt)
```
</details>

<details>
<summary>edgeAgent Log</summary>

```
[edgeAgent_log1.txt](https://github.com/Azure/iotedge/files/10013940/edgeAgent_log1.txt)
```
</details>

<details>
<summary>edge-hub logs</summary>

```
[edgeHub_log1.txt](https://github.com/Azure/iotedge/files/10013948/edgeHub_log1.txt)
```
</details>

<details>
<summary>docker inspect network bridge</summary>

```
[bridge.json.txt](https://github.com/Azure/iotedge/files/10013952/bridge.json.txt)
```
</details>

<details>
<summary>docker inspect network azure-iot-edge</summary>

```
[azure-iot-edge.json.txt](https://github.com/Azure/iotedge/files/10013954/azure-iot-edge.json.txt)
```
</details>

<details>
<summary>docker inspect network host</summary>

```
[host.json.txt](https://github.com/Azure/iotedge/files/10013964/host.json.txt)
```
</details>

<details>
<summary>docker inspect edgeAgent</summary>

```
[edgeAgent.json.txt](https://github.com/Azure/iotedge/files/10013969/edgeAgent.json.txt)
```
</details>

<details>
<summary>docker inspect edgeHub</summary>

```
[edgeHub.json.txt](https://github.com/Azure/iotedge/files/10013976/edgeHub.json.txt)
```
</details>

**Comment by nyanzebra** [comment] 2022-11-15 20:35
@varunpuranik have we seen this before? I will try to make a local setup... but want to know if team has ever encountered something like this before.

**Comment by onalante-msft** [comment] 2022-11-16 02:14
I stumbled across a SDK issue reporting connectivity problems with cellular modems while investigating https://github.com/Azure/iotedge/issues/6686: https://github.com/Azure/azure-iot-sdk-csharp/issues/1720.

**Comment by wvangeem** [comment] 2022-11-16 07:28
I already tried to lower MTU without success. edgeAgent was not connecting anymore.
But as [#1720] [#6686] described, I could try with 1400 and lower down per 40.
Already the diagnostics container (iotedge check) is having problems connecting.
The iotedge check takes a long time on the failing protocols, probably a timeout.
But strange thing is that the AMQP check always goes quick and is OK.

**Comment by nyanzebra** [comment] 2022-11-16 21:18
@wvangeem a few questions:
1. It seems from above that edgeAgent works but edgeHub and other modules do not? Is this correct?
2. Are you wanting to use Websockets? You mentioned it doesn't work, but want to be sure if this is something you are wanting?
3. Just to make sure problem is understood, are you saying that everything works now with AMQP or that just iotedge check works but modules still don't work?
4. Is this single device specific? Or do you have multiple devices and do you have any proxies/gateways?

**Comment by wvangeem** [comment] 2022-11-17 07:22
@nyanzebra:
1. It seems that only 1 module is able to connect. In the beginning I worked without startuporder, and then edgeAgent sometimes didn't connect. But indeed, using only celullar connection, edgeAgent connects, and edgeHub and custom modules do not connect.
2. I would prefer to use AMQP, but in fact we have no preference. If celullar connection would limit the choice of upstream protocol, we have no problem with that. I've tested with AMQP and MQTT since iotedge check says Websockets are not working.
3. No it doesn't work with neither AMQP or MQTT. Only edgeAgent is connecting, other modules fails as shown in the logfiles.
4. I currently only have 1 such a device. Our customer is wanting to buy more, but are waiting for this to be resolved. The device is a Welotec Arrakis MK3. The device has integrated celullar, so there's no proxy, gateway or whatever.
We have another setup using RaspberryPI, connected to a Teltonika modem, but there the connection is through LAN cable, and there everything works fine. Just like we connect the Arrakis MK3 with LAN cable to the internet, there everythings works fine too.

In my opinion it is just like a first module can connect, and then next modules fail.
Therefore the diagnostics container (used by iotedge check) succeeds in the first test, but fails in the next ones.

**Comment by nyanzebra** [comment] 2022-11-17 23:38
@wvangeem from the attached logs I see this for edgeagent, which tells me that this device only has edgeAgent and edgeHub at the moment? Would you mind trying to create a deployment by clicking on what is highlighted in picture and then do a review+create?
![image](https://user-images.githubusercontent.com/6096983/202582872-29c577dc-908f-4a82-bf99-81dfb84359dd.png)


```shell
<4> 2022-11-15 15:19:34.363 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<6> 2022-11-15 15:19:35.790 +00:00 [INF] - Current module client closed. Initializing a new one
<6> 2022-11-15 15:19:35.790 +00:00 [INF] - Edge agent attempting to connect to IoT Hub via Mqtt_Tcp_Only...
<4> 2022-11-15 15:19:44.376 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-11-15 15:19:54.390 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-11-15 15:20:04.406 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-11-15 15:20:14.420 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-11-15 15:20:24.438 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
<4> 2022-11-15 15:20:34.447 +00:00 [WRN] - Empty edge agent config was received. Attempting to read config from backup (/tmp/edgeAgent/backup.json) instead
```

**Comment by wvangeem** [comment] 2022-11-18 07:28
@nyanzebra 
There are already 2 custom modules deployed, named Simulator and APIServer.
You can see this in the edgehub_log1.txt:

```
<6> 2022-11-15 15:17:16.597 +00:00 [INF] - Version - 1.4.2.61356014 (bb9a26162c4c88b3ef9a50d33632ab78bd4247d6)
<6> 2022-11-15 15:17:16.597 +00:00 [INF] - OptimizeForPerformance=True
<6> 2022-11-15 15:17:16.597 +00:00 [INF] - MessageAckTimeoutSecs=30
<6> 2022-11-15 15:17:16.599 +00:00 [INF] - Loaded server certificate with expiration date of "2022-12-15T15:17:13.0000000+00:00"
<6> 2022-11-15 15:17:16.625 +00:00 [INF] - Using Asp Net server for metrics
<6> 2022-11-15 15:17:16.763 +00:00 [INF] - Created new message store
<6> 2022-11-15 15:17:16.763 +00:00 [INF] - Started task to cleanup processed and stale messages
<6> 2022-11-15 15:17:16.887 +00:00 [INF] - Add node: 787052036B1B
<6> 2022-11-15 15:17:16.892 +00:00 [INF] - Add node: 787052036B1B/$edgeAgent
<6> 2022-11-15 15:17:16.892 +00:00 [INF] - Add node: 787052036B1B/$edgeHub
<6> 2022-11-15 15:17:16.893 +00:00 [INF] - Add node: 787052036B1B/APIServer
<6> 2022-11-15 15:17:16.893 +00:00 [INF] - Add node: 787052036B1B/Simulator
<6> 2022-11-15 15:17:16.900 +00:00 [INF] - Created device scope identities cache
<6> 2022-11-15 15:17:16.925 +00:00 [INF] - Starting refresh of device scope identities cache
<6> 2022-11-15 15:17:16.971 +00:00 [INF] - Created DeviceConnectivityManager with connected check frequency 00:05:00 and disconnected check frequency 00:02:00
<6> 2022-11-15 15:17:17.039 +00:00 [INF] - Initialized storing twin manager
<6> 2022-11-15 15:17:17.106 +00:00 [INF] - Updated node: 787052036B1B/$edgeHub
<6> 2022-11-15 15:17:17.106 +00:00 [INF] - Initializing configuration
<6> 2022-11-15 15:17:17.144 +00:00 [INF] - New device connection for device 787052036B1B/$edgeHub
<6> 2022-11-15 15:17:17.172 +00:00 [INF] - Client 787052036B1B/$edgeHub connected to edgeHub, processing existing subscriptions.
<6> 2022-11-15 15:17:17.300 +00:00 [INF] - Attempting to connect to IoT Hub for client 787052036B1B/$edgeHub via MQTT...
<6> 2022-11-15 15:17:17.343 +00:00 [INF] - Processing pending subscriptions for 787052036B1B/$edgeHub
<6> 2022-11-15 15:17:17.949 +00:00 [INF] - Experimental features configuration: {"Enabled":false,"DisableCloudSubscriptions":false,"DisableConnectivityCheck":false}
<6> 2022-11-15 15:17:17.999 +00:00 [INF] - Starting timer to authenticate connections with a period of 300 seconds
<6> 2022-11-15 15:17:18.164 +00:00 [INF] - Scheduling server certificate renewal for "2022-12-15T15:14:43.0003954Z".
<6> 2022-11-15 15:17:18.483 +00:00 [INF] - Created cloud endpoint iothub with max batch size 10 and fan-out factor of 10.
<6> 2022-11-15 15:17:18.963 +00:00 [INF] - Set the following 2 route(s) in edge hub
<6> 2022-11-15 15:17:18.964 +00:00 [INF] - APIServerToIoTHub: FROM /messages/modules/APIServer/outputs/* INTO $upstream
<6> 2022-11-15 15:17:18.964 +00:00 [INF] - SimulatorToIoTHub: FROM /messages/modules/Simulator/outputs/* INTO $upstream
<6> 2022-11-15 15:17:18.967 +00:00 [INF] - Updated message store TTL to 7200 seconds
<6> 2022-11-15 15:17:18.968 +00:00 [INF] - Updated the edge hub store and forward configuration
<6> 2022-11-15 15:17:19.015 +00:00 [INF] - Started operation Get EdgeHub config
<6> 2022-11-15 15:17:19.016 +00:00 [INF] - Initialized edge hub configuration
<6> 2022-11-15 15:17:19.020 +00:00 [INF] - Starting protocol heads - (MQTT, AMQP, HTTP)
<6> 2022-11-15 15:17:19.026 +00:00 [INF] - Starting MQTT head
<6> 2022-11-15 15:17:19.076 +00:00 [INF] - Initializing TLS endpoint on port 8883 for MQTT head.
<6> 2022-11-15 15:17:19.108 +00:00 [INF] - Starting AMQP head
<6> 2022-11-15 15:17:19.112 +00:00 [INF] - Started MQTT head
<6> 2022-11-15 15:17:19.266 +00:00 [INF] - Started AMQP head
<6> 2022-11-15 15:17:19.274 +00:00 [INF] - Starting HTTP head
<4> 2022-11-15 15:17:19.896 +00:00 [WRN] - Overriding address(es) '"http://+:80"'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
<6> 2022-11-15 15:17:19.933 +00:00 [INF] - Started HTTP head
<6> 2022-11-15 15:17:21.572 +00:00 [INF] - New token received on the Cbs link
<6> 2022-11-15 15:17:21.958 +00:00 [INF] - Client 787052036B1B/APIServer in device scope authenticated locally.
<6> 2022-11-15 15:17:22.008 +00:00 [INF] - **New device connection for device 787052036B1B/APIServer**
<6> 2022-11-15 15:17:22.012 +00:00 [INF] - Client 787052036B1B/APIServer connected to edgeHub, processing existing subscriptions.
<6> 2022-11-15 15:17:22.020 +00:00 [INF] - Attempting to connect to IoT Hub for client 787052036B1B/APIServer via MQTT...
<6> 2022-11-15 15:17:22.065 +00:00 [INF] - Bind device proxy for device 787052036B1B/APIServer
<6> 2022-11-15 15:17:22.067 +00:00 [INF] - Initialized device listener in the AMQP protocol head for 787052036B1B/APIServer
<6> 2022-11-15 15:17:22.068 +00:00 [INF] - New token received on the Cbs link
<6> 2022-11-15 15:17:22.087 +00:00 [INF] - Opened link Events for 787052036B1B/APIServer
<6> 2022-11-15 15:17:22.180 +00:00 [INF] - Client 787052036B1B/Simulator in device scope authenticated locally.
<6> 2022-11-15 15:17:22.182 +00:00 [INF] - **New device connection for device 787052036B1B/Simulator**
<6> 2022-11-15 15:17:22.182 +00:00 [INF] - Client 787052036B1B/Simulator connected to edgeHub, processing existing subscriptions.
<6> 2022-11-15 15:17:22.184 +00:00 [INF] - Attempting to connect to IoT Hub for client 787052036B1B/Simulator via MQTT...
<6> 2022-11-15 15:17:22.191 +00:00 [INF] - Bind device proxy for device 787052036B1B/Simulator
<6> 2022-11-15 15:17:22.191 +00:00 [INF] - Initialized device listener in the AMQP protocol head for 787052036B1B/Simulator
<6> 2022-11-15 15:17:22.191 +00:00 [INF] - Opened link Events for 787052036B1B/Simulator
<6> 2022-11-15 15:17:22.277 +00:00 [INF] - Opened link TwinReceiving for 787052036B1B/Simulator
<6> 2022-11-15 15:17:22.283 +00:00 [INF] - Opened link TwinSending for 787052036B1B/APIServer
<6> 2022-11-15 15:17:22.286 +00:00 [INF] - Opened link TwinSending for 787052036B1B/Simulator
<6> 2022-11-15 15:17:22.286 +00:00 [INF] - Opened link TwinReceiving for 787052036B1B/APIServer
<4> 2022-11-15 15:18:19.732 +00:00 [WRN] - Error creating cloud connection for client 787052036B1B/$edgeHub
System.TimeoutException: The operation timed out.
 ---> Microsoft.Azure.Devices.Client.Exceptions.IotHubCommunicationException: Transient network error occurred, please retry.
 ---> System.TimeoutException: Connection hasn't been established in time.
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
```

I also copied the configuration below:

![image](https://user-images.githubusercontent.com/72979554/202645361-f9121786-958a-4efc-92cf-5d72c7e40e4f.png)

```
{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {
              "EUHARVCOACREGD01": {
                "username": "***",
                "password": "***",
                "address": "***"
              }
            }
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.4",
              "createOptions": "{}"
            },
			"env": {
                "UpstreamProtocol": {
                    "value": "MQTT"
                }
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
			"startupOrder": 0,
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.4",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5671/tcp\":[{\"HostPort\":\"5671\"}],\"8883/tcp\":[{\"HostPort\":\"8883\"}],\"443/tcp\":[{\"HostPort\":\"443\"}]}}}"
            },
			"env": {
                "UpstreamProtocol": {
                    "value": "MQTT"
                }
            }
          }
        },
        "modules": {
          "APIServer": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
			"startupOrder": 10,
            "settings": {
              "image": "***/apiserver:0.2.31-amd64",
              "createOptions": "{\"ExposedPorts\":{\"8080/tcp\":{}},\"HostConfig\":{\"Mounts\":[{\"Target\":\"/data\",\"Source\":\"apiserverdata\",\"Type\":\"volume\",\"RW\":true}],\"Binds\":[\"/cnh:/cnh\"],\"PortBindings\":{\"8080/tcp\":[{\"HostPort\":\"1066\"}]}}}"
            },
            "env": {
              "ApiKey": {
                "value": "45ea7595-7923-4d6a-ac55-2ee70ddf4b4a"
              }
            }
          },
          "Simulator": {
            "version": "1.0.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
			"startupOrder": 20,
            "settings": {
              "image": "***/simulator:0.0.18-amd64",
              "createOptions": "{}"
            }
		  }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "APIServerToIoTHub": "FROM /messages/modules/APIServer/outputs/* INTO $upstream",
          "SimulatorToIoTHub": "FROM /messages/modules/Simulator/outputs/* INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
  }
}

```

**Comment by nyanzebra** [comment] 2022-11-18 18:40
@wvangeem Thanks for the clarification, to get a few more data points.

1. Would you mind clarifying the network layout a bit more between the LAN and modem? Do you mean that you have some network device (say modem/router of a home network for example) that is partitioned into a LAN for a set of devices and that works with iotedge and then another that is directly connected to network via cable and that does not work?

2. would you mind seeing what the output of these are in your modem-only setup? Let's see if any network calls work out of the containers; expectation being (based on above info) that edgeAgent will succeed but edgeHub will fail.

![image](https://user-images.githubusercontent.com/6096983/202774935-eb9b3bca-de67-45a4-8fcb-68dad83acb16.png)


3. If for some reason it works, then would you mind capturing a tcpdump? So that we can debug where the issue is at that level

**Comment by wvangeem** [comment] 2022-11-21 07:50
@nyanzebra Thanks for the follow-up. Here are the answers to your questions.
1. Network Layout
The Welotec Arrakis MK3 is an industrial device.

![image](https://user-images.githubusercontent.com/72979554/202989155-1262a881-f627-4ac6-93a3-0d8500d43a9b.png)

It has integrated LAN-ports and modem. As you can see, there are 2 LAN ports, enp3s0 and enp4s0

[ipaddr.txt](https://github.com/Azure/iotedge/files/10054298/ipaddr.txt)

The integrated modem can be queries with ModemManager, this is the output of mmcli -m 0

[mmcli.txt](https://github.com/Azure/iotedge/files/10054307/mmcli.txt)

The goal is to integrate this device in an agriculture machine, so in normal conditions, it will work with modem only.
Attaching the network cable is only for installation/debugging/... In my case, when working with network cable, it is simply connected with my home network, so directly receiving IP from my routers DHCP server.

2. Output of internet connection of both edgeAgent and edgeHub. As you can see, both containers are able to connect to the internet. So that's what's strange about it!

![docker-output](https://user-images.githubusercontent.com/72979554/202990234-51338c8a-b2eb-4df5-ba3f-184ac0648b92.jpg)

3. tcpdump

There's a tcpdump of a few minutes.

[tcpdump.txt](https://github.com/Azure/iotedge/files/10054434/tcpdump.txt)

I also added edgeAgent and edgeHub logs during these times for reference.
[edgeAgent_2.txt](https://github.com/Azure/iotedge/files/10054456/edgeAgent_2.txt)
[edgeHub_2.txt](https://github.com/Azure/iotedge/files/10054457/edgeHub_2.txt)

Best regards,

Wim.

**Comment by nyanzebra** [comment] 2022-11-23 00:45
@wvangeem 

So, from tcpdump it seems that connections happen with amqp but end almost immediately. Basically getting a packet or two and then stopping...

So I think next steps are this:
1. try to do an openssl connect from host with upstream and see if host is able to get certificate (if that fails that at least points in the right direction); might be good to try with both LAN and modem
2. If can still do the setup that works, would you mind sharing iotedge check & edgeagent logs that way we can verify there aren't any subtle issues in the 'normal' case too
3. Just to confirm health of the host device, when switching between LAN and modem, does host having any network issues?

**Comment by wvangeem** [comment] 2022-11-23 15:21
@nyanzebra 

I executed `openssl s_client -connect iothub:8883`
I hope it's the command you suggested. I added the printed data below.
This was with modem only:
[openssl.host.mqtt.txt](https://github.com/Azure/iotedge/files/10076718/openssl.host.mqtt.txt)
As `iotedge check` points out, it is never a problem on the host.
I tried it inside the edgeHub container, but it is missing the openssl command.

Here is a support-bundle when connected with LAN
[support_bundle_2022_11_23_14_55_10_UTC.zip](https://github.com/Azure/iotedge/files/10076746/support_bundle_2022_11_23_14_55_10_UTC.zip)

I connected LAN at 2022-11-23 14:53:46. You can see this in the edgeHub_log.txt file, where suddenly the connection resolved and everything starts to work fine.

I disconnected LAN at  2022-11-23 15:12 and added the support-bundle below. You can see in the edgeHub_log.txt that things go wrong again, whereas I can still ping to google.com from within the edgeHub container.
I must say that generating a support bundle with modem takes a few minutes because of all the timeouts. With LAN it takes a few seconds.
[support_bundle_2022_11_23_15_13_58_UTC.zip](https://github.com/Azure/iotedge/files/10076810/support_bundle_2022_11_23_15_13_58_UTC.zip)

**Comment by nyanzebra** [comment] 2022-11-23 22:56
@wvangeem 

Interesting that it stops working like that... there does seem to be a maybe similar issue here: [Docker Compose Networking Issue: TCP Request Stops Sending - Open Source Projects / Compose - Docker Community Forums](https://forums.docker.com/t/docker-compose-networking-issue-tcp-request-stops-sending/125922)

Also, looking at the support bundles and previous info, it seems that docker connectivity outside of containers works as expected in LAN but after you switch it doesn't (even though pings still work).... And iotedge doesn't care about the difference (basically don't think this is an edge issue at the moment)...

This is super weird! I will try to see if there is anyone on my team with some ideas to try, but might also be worthwhile to see if there any threads online for docker bridge to host networks not working when network change occurs.

**Comment by nyanzebra** [comment] 2022-12-05 20:35
@wvangeem hope above pointed you in the right direction, I am closing this issue for now, but please feel free to re-open if still seems like an edge issue :)

**Closed by nyanzebra** 2022-12-05 20:35 UTC
Labels: iotedge, customer-reported

**Comment by wvangeem** [comment] 2022-12-06 07:36
Hi @nyanzebra, it's not solved at all, but I'm in contact with the supplier, and hoping they can help me out. They claim they cannot simulate the problem on their device.
Thanks for your help.

**Comment by nyanzebra** [comment] 2022-12-06 17:52
@wvangeem  sorry to hear! Hope supplier can help, and once again don't hesitate to re-open this issue if you determine this to be an edge issue after checking these other options

**Comment by wvangeem** [comment] 2023-03-01 07:14
Hi @nyanzebra,
Just to inform you that this issue is solved now. I had some new insights in the problem, and the information is in following issue:
#6928

**Comment by nyanzebra** [comment] 2023-03-02 23:04
@wvangeem glad you got it all worked out! never would have guessed needing to mess around with docker network with MTU.
