### ISSUE TITLE
Unable to locate package moby-cli

### ISSUE THREAD

**Issue by sympthom** [Azure/iotedge#92] opened 2018-07-28 14:12 UTC
I'm trying to install Azure IoT using the instructions at https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux but keep getting an error in a fresh installed distribution.

## Expected Behavior
The installation should find the package.

## Current Behavior
The instructions in not complete for finding the package.

## Steps to Reproduce
https://docs.microsoft.com/en-us/azure/iot-edge/quickstart-linux

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
arm32

### Container Operating System
Linux containers

## Logs
ubuntu@ubuntu:~$ sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease
Reading package lists... Done
ubuntu@ubuntu:~$ sudo apt-get install moby-cli
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package moby-cli

**Comment by veyalla** [comment] 2018-07-28 16:49
Duplicate of https://github.com/Azure/iotedge/issues/91

**Closed by veyalla** 2018-07-28 16:49 UTC
