### ISSUE TITLE
Using Production Certs for Transparent Gateway

### ISSUE THREAD

**Issue by sitembun** [Azure/iotedge#4103] opened 2020-12-16 20:19 UTC
## Expected Behavior

A certificate created in Azure Key Vault and signed by a trusted authority should be useable as a transparent gateway certificate in IoT Edge on Kubernetes. 

## Current Behavior

When running the Edge on Kubernetes helm chart with a certificate from keyvault, edgeAgent fails to make HTTP call to TrustBundleAsync with a SocketException.

## Steps to Reproduce

1. Create a certificate in Key Vault with the following options:
    - Method of Certificate Creation: Generate
    - Certificate Name: keyvault-cert
    - Type of Certificate Authority (CA): Certificate Issued by an integrated CA
    - MSPKI (OneCertV2-PublicCA) (DigiCert)
    - Content Type: PEM
    - Key Size: 4096
2. Download the certificate into file keyvault-cert.pem
2. Copy the root certificate into its own file root.ca.pem
3. Extract the private key into its own file keyvault-cert.key.pem
4. Run the following bash script to execute helm deployment:

```bash
export nsp='cert-test'
kubectl create ns $nsp

export connStr='foo'

kubectl create secret generic -n $nsp edge-certs \
--from-file=fullchain=keyvault-cert.pem \
--from-file=privatekey=keyvault-cert.key.pem \
--from-file=root=root.ca.pem

helm install --repo https://edgek8s.blob.core.windows.net/staging edge-kubernetes \
--generate-name \
--namespace $nsp \
--set "provisioning.deviceConnectionString=$connStr" \
--set "iotedged.certificates.secret=edge-certs" \
--set "iotedged.certificates.device_ca_cert=fullchain" \
--set "iotedged.certificates.device_ca_pk=privatekey" \
--set "iotedged.certificates.trusted_ca_certs=root" \
--set "iotedged.image.repository=dmsdgacr0.azurecr.io/azureiotedge-iotedged" \
--set "iotedged.image.tag=0.1.0-beta12" \
--set "iotedgedProxy.image.repository=dmsdgacr0.azurecr.io/azureiotedge-proxy" \
--set "iotedgedProxy.image.tag=0.1.0-beta12" \
--set "edgeAgent.image.repository=dmsdgacr0.azurecr.io/azureiotedge-agent" \
--set "edgeAgent.image.tag=0.1.0-beta12"
```

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```

N/A

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers 

### Runtime Versions
* iotedged [run `iotedge version`]: 1.0.10~dev
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.10-dev.36051614 (25af5f5abe05165544b97f683e32de955b871abc)
* Edge Hub [image tag (e.g. 1.0.0)]: N/A
* Docker/Moby [run `docker version`]: N/A

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>iotedged logs</summary>

```

<6>2020-12-16T19:46:24Z [INFO] - Starting Azure IoT Edge Security Daemon - Kubernetes mode
<6>2020-12-16T19:46:24Z [INFO] - Version - 1.0.10~dev
<6>2020-12-16T19:46:24Z [INFO] - Using config file: /etc/iotedged/config.yaml
<6>2020-12-16T19:46:24Z [INFO] - Configuring /var/lib/iotedge as the home directory.
<6>2020-12-16T19:46:24Z [INFO] - Configuring certificates...
<6>2020-12-16T19:46:24Z [INFO] - Configuring the Device CA certificate using "/etc/edgecerts/device_ca_cert".
<6>2020-12-16T19:46:24Z [INFO] - Configuring the Device private key using "/etc/edgecerts/device_ca_pk".
<6>2020-12-16T19:46:24Z [INFO] - Configuring the trusted CA certificates using "/etc/edgecerts/trusted_ca_certs".
<6>2020-12-16T19:46:24Z [INFO] - Finished configuring provisioning environment variables and certificates.
<6>2020-12-16T19:46:24Z [INFO] - Initializing hsm...
<6>2020-12-16T19:46:24Z [INFO] - Finished initializing hsm.
<6>2020-12-16T19:46:24Z [INFO] - Provisioning edge device...
<6>2020-12-16T19:46:24Z [INFO] - Starting provisioning edge device via manual mode using a device connection string...
<6>2020-12-16T19:46:24Z [INFO] - Manually provisioning device "foo" in hub "bar"
<6>2020-12-16T19:46:24Z [INFO] - Finished provisioning edge device.
<6>2020-12-16T19:46:24Z [INFO] - Initializing the module runtime...
<6>2020-12-16T19:46:24Z [INFO] - Attempting to use config from /home/edgeletuser/.kube/config file.
<6>2020-12-16T19:46:24Z [INFO] - Using in-cluster config
<6>2020-12-16T19:46:24Z [INFO] - Finished initializing the module runtime.
<6>2020-12-16T19:46:24Z [INFO] - Detecting if configuration file has changed...
<6>2020-12-16T19:46:24Z [INFO] - Change to configuration file detected.
<6>2020-12-16T19:46:24Z [INFO] - Removing all modules...
<6>2020-12-16T19:46:24Z [INFO] - Finished removing modules.
<6>2020-12-16T19:46:24Z [INFO] - Edge issuer CA expiration date: 2021-12-11T17:05:04Z
<6>2020-12-16T19:46:33Z [INFO] - Starting management API...
<6>2020-12-16T19:46:33Z [INFO] - Starting workload API...
<6>2020-12-16T19:46:33Z [INFO] - Starting watchdog with 60 second frequency...
<6>2020-12-16T19:46:33Z [INFO] - Listening on https://0.0.0.0:35000/ with 1 thread for management API.
<6>2020-12-16T19:46:33Z [INFO] - Listening on https://0.0.0.0:35001/ with 1 thread for workload API.
<6>2020-12-16T19:46:33Z [INFO] - Checking edge runtime status
<6>2020-12-16T19:46:33Z [INFO] - Creating and starting edge runtime module edgeAgent
<6>2020-12-16T19:46:33Z [INFO] - Updating identity for module $edgeAgent
<6>2020-12-16T19:46:36Z [INFO] - [mgmt] - - - [2020-12-16 19:46:36.902193151 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:46:40Z [INFO] - [mgmt] - - - [2020-12-16 19:46:40.657274444 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:46:46Z [INFO] - [mgmt] - - - [2020-12-16 19:46:46.901967391 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:46:50Z [INFO] - [mgmt] - - - [2020-12-16 19:46:50.654042082 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:46:56Z [INFO] - [mgmt] - - - [2020-12-16 19:46:56.916852241 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:00Z [INFO] - [mgmt] - - - [2020-12-16 19:47:00.654196623 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:06Z [INFO] - [mgmt] - - - [2020-12-16 19:47:06.903397373 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:10Z [INFO] - [mgmt] - - - [2020-12-16 19:47:10.654651465 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:16Z [INFO] - [mgmt] - - - [2020-12-16 19:47:16.900795313 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:20Z [INFO] - [mgmt] - - - [2020-12-16 19:47:20.655353607 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:26Z [INFO] - [mgmt] - - - [2020-12-16 19:47:26.901027156 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:30Z [INFO] - [mgmt] - - - [2020-12-16 19:47:30.654869550 UTC] "GET /systeminfo?api-version=2019-01-30 HTTP/1.1" 200 OK 104 "-" "kube-probe/1.18" auth_id(-)
<6>2020-12-16T19:47:33Z [INFO] - Checking edge runtime status
<6>2020-12-16T19:47:33Z [INFO] - Edge runtime is running.

```
</details>

<details>
<summary>edge-agent logs</summary>

```

2020-12-16 19:46:35  Starting Edge Agent
2020-12-16 19:46:37.274 +00:00 Edge Agent Main()
<6> 2020-12-16 19:46:42.173 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Initializing Edge Agent.
<6> 2020-12-16 19:46:45.877 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Version - 1.0.10-dev.36051614 (25af5f5abe05165544b97f683e32de955b871abc)
<6> 2020-12-16 19:46:45.972 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] -
█████╗ ███████╗██╗   ██╗██████╗ ███████╗
██╔══██╗╚══███╔╝██║   ██║██╔══██╗██╔════╝
███████║  ███╔╝ ██║   ██║██████╔╝█████╗
██╔══██║ ███╔╝  ██║   ██║██╔══██╗██╔══╝
██║  ██║███████╗╚██████╔╝██║  ██║███████╗
╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
██╗ ██████╗ ████████╗    ███████╗██████╗  ██████╗ ███████╗
██║██╔═══██╗╚══██╔══╝    ██╔════╝██╔══██╗██╔════╝ ██╔════╝
██║██║   ██║   ██║       █████╗  ██║  ██║██║  ███╗█████╗
██║██║   ██║   ██║       ██╔══╝  ██║  ██║██║   ██║██╔══╝
██║╚██████╔╝   ██║       ███████╗██████╔╝╚██████╔╝███████╗
╚═╝ ╚═════╝    ╚═╝       ╚══════╝╚═════╝  ╚═════╝ ╚══════╝
<6> 2020-12-16 19:46:47.278 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Experimental features configuration: {"Enabled":true,"DisableCloudSubscriptions":false,"EnableUploadLogs":false,"EnableGetLogs":false,"EnableMetrics":false}
<6> 2020-12-16 19:46:47.773 +00:00 [INF] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Experimental features configuration: {"Enabled":true,"EnableExtensions":true}
<7> 2020-12-16 19:46:48.376 +00:00 [DBG] [Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClient] - Making a Http call to http://localhost:35001/ to TrustBundleAsync
<0> 2020-12-16 19:46:51.374 +00:00 [FTL] [Microsoft.Azure.Devices.Edge.Agent.Service.Program] - Fatal error building application.
System.Net.Http.HttpRequestException: Address not available ---> System.Net.Sockets.SocketException: Address not available
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
at System.Threading.Tasks.ValueTask`1.get_Result()
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.GeneratedCode.HttpWorkloadClient.TrustBundleAsync(String api_version, CancellationToken cancellationToken) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/generatedCode/HttpWorkloadClient.cs:line 689
at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout)
at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation)
at Microsoft.Azure.Devices.Edge.Util.Edged.WorkloadClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/WorkloadClientVersioned.cs:line 66
at Microsoft.Azure.Devices.Edge.Util.Edged.Version_2019_01_30.WorkloadClient.GetTrustBundleAsync() in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/version_2019_01_30/WorkloadClient.cs:line 49
at Microsoft.Azure.Devices.Edge.Util.CertificateHelper.GetTrustBundleFromEdgelet(Uri workloadUri, String workloadApiVersion, String workloadClientApiVersion, String moduleId, String moduleGenerationId) in /home/vsts/work/1/s/edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs:line 261
at Microsoft.Azure.Devices.Edge.Agent.Service.Program.MainAsync(IConfiguration configuration) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs:line 235

```
</details>

<details>
<summary>edge-hub logs</summary>

```

N/A

```
</details>

## Additional Information

N/A

**Comment by darobs** [comment] 2020-12-16 23:42
Hi @sitembun, can you also provide the logs to to proxy sidecar in the edgeagent pod?

**Comment by sitembun** [comment] 2020-12-16 23:44
@darobs Absolutely, here it is:

```
Loading...
INFO 2020-12-16T23:39:59Z: Starting proxy server
INFO 2020-12-16T23:39:59Z: Using config file: /etc/iotedge-proxy/config.yaml
INFO 2020-12-16T23:39:59Z: Starting proxy server management http://localhost:35000/
INFO 2020-12-16T23:39:59Z: Starting proxy server workload http://localhost:35001/
INFO 2020-12-16T23:40:00Z: Starting api server http://localhost:8080/
INFO 2020-12-16T23:40:01Z: Listening on http://localhost:8080/ with 1 thread for api
ERROR 2020-12-16T23:40:01Z: The proxy could not start up successfully: Could not load proxy client config
ERROR 2020-12-16T23:40:01Z: 	caused by: error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table:x509_lu.c:370:
```

**Comment by darobs** [comment] 2020-12-17 00:22
Thank you - that helps a lot.  I have a couple of possibilities for that error:
`tls.build()` failed,
https://github.com/Azure/iotedge/blob/edge-on-k8s-public-preview/edgelet/iotedge-proxy/src/proxy/config.rs#L82
or `X509::stack_from_pem` failed,
https://github.com/Azure/iotedge/blob/edge-on-k8s-public-preview/edgelet/iotedge-proxy/src/proxy/config.rs#L61

I'm leaning towards the `tls.build()` statement without digging into the Rust library code. Are there duplicate certificates in the `root.ca.pem` file?  If so, a work-around would be to edit the file and remove any duplicates.

**Comment by sitembun** [comment] 2020-12-17 00:27
The `root.ca.pem` file doesn't have any duplicates as far as I can tell (there is only one BEGIN CERTIFICATE block). This file is one that  I made myself by copying the last cert in the full chain cert created by Key Vault and pasting it into its own file. So I guess there is a duplicate in that this cert exists both in this file and at the end of the chain in the original.

**Comment by sitembun** [comment] 2020-12-17 00:29
It's also entirely possible that my entire process of hacking together these various files has been incorrect. If there is a tried and true way that you guys have of getting certs from trusted roots, I am more than open to it :)

**Comment by darobs** [comment] 2020-12-17 00:48
That proxy container should only be referencing the trusted root, would you confirm this?

Run:
```sh
kubectl get configmap -n "<your namespace>" iotedged-proxy-trust-bundle -o json | jq -r '.data."trust_bundle.pem"'
```

You don't need to share the output, but confirm this matches the contents of your `root.ca.pem` file.

Thank you!

**Comment by sitembun** [comment] 2020-12-17 00:55
Yep, the output of that command matches my `root.ca.pem` file exactly.

**Comment by darobs** [comment] 2020-12-17 01:07
All right. I will need to spend some time reproducing this and investigating the "error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table:x509_lu.c:370" error.

**Comment by sitembun** [comment] 2020-12-17 17:27
Thanks so much David! I really appreciate your help.

**Comment by sitembun** [comment] 2020-12-21 18:35
Hey @darobs, were you able to reproduce the error? Let me know if I can provide anything else to help :)

**Comment by darobs** [comment] 2021-01-06 18:45
Still working on this - setup is a bear, and I don't have privileges to do some steps myself. Thank you for your patience.

**Comment by darobs** [comment] 2021-01-30 01:09
Hi - still waiting on internal sources. I apologize for the delay.

**Comment by darobs** [comment] 2021-02-02 19:26
Hi @sitembun, I got someone with access to walk me through the process.  There were two differences. First, our team doesn't have an integrated certificate authority, and we used an EST server to sign the certificate and merged it back into KeyVault. We are expecting this is the same steps an integrated vendor would provide. Second, we only have access to a different vendor.
...and because the person who did it was proficient at this process, it worked without problems.

The other people I've consulted with didn't know why you received this error. We think it's something with the either with how you created the certificate in KeyVault, or how you created the files on disk.  
Here are some hints from when we tried:
- Make sure the attributes are set correctly. The most important is that CA=true for the device CA certificate.
- The device CA should be the full chain, from device CA to root.
- The trusted root can be downloaded from the CA (DigiCert in your case). This is public information.
- The key and certificate should be saved into separate files - one containing the key, the other the full chain.

You can probably [generate test certificates](https://docs.microsoft.com/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2018-06) to compare with your own, if there are some questions on the details.

Thank you for your patience.

**Comment by darobs** [comment] 2021-04-20 20:52
Closing this issue. Please reopen if there is something more we can do to help.

**Closed by darobs** 2021-04-20 20:52 UTC
Labels: customer-reported, iotedge, no-issue-activity
