### ISSUE TITLE
After installing our certificates on the IoT Edge device system modules don't report any errors but custom modules are in an invalid state

### ISSUE THREAD

**Issue by draganrmijailovic** [Azure/iotedge#6459] opened 2022-06-20 13:46 UTC
We have one IoT Edge device on Production that works properly. It uses temporary certificates. Before there were interruptions every month. But after installing a new version of IoT Edge runtime there weren’t any interruptions (the last two months).

But we want to install our certificates on an IoT Edge device on Staging before their installation on the production IoT Edge.

After installing our certificates on the IoT Edge device system modules don't report any errors but custom modules are in an invalid state. The IoT Edge device returns a 200 - OK status:
![IoT Edge Device - Azure Portal](https://user-images.githubusercontent.com/28098446/174614802-be9d925c-183a-4135-9885-ea93205f788b.jpg)

The logs for the last 12 hours are attached.  They were created by _sudo iotedge support-bundle --since 12h_ command.
[support_bundle.zip](https://github.com/Azure/iotedge/files/8941099/support_bundle.zip)

There is information about installing certificates after restarting the IoT Edge Hub module:
![IoT Edge Hub restart - After restart certificates are installed](https://user-images.githubusercontent.com/28098446/174615006-622abfb8-7a08-45b7-823a-9606eff9c30a.jpg)
[IoT Edge Hub restart - Logs after restarting.txt](https://github.com/Azure/iotedge/files/8941103/IoT.Edge.Hub.restart.-.Logs.after.restarting.txt)

One custom module returns a TLS authentication exception:
![Custom Module - TLS authentication error after restarting](https://user-images.githubusercontent.com/28098446/174615112-b09416ad-a491-4f55-99e9-94d37305bb27.jpg)

Certificates are installed based on the following post message https://github.com/Azure/iotedge/issues/6044#issuecomment-1024538995.

My questions are the following:

1. Is the installation of certificates valid? How can I check that?
2. Should the configuration of the custom modules be changed after the installation of certificates or not? Their code and configuration weren’t changed.

IoT Edge version: 1.2.10
VM Operating system: Linux (ubuntu 18.04)
result of iotedge check command:
[sudo iotedge check.txt](https://github.com/Azure/iotedge/files/8941114/sudo.iotedge.check.txt)

**Comment by nlcamp** [comment] 2022-06-21 17:02
> Is the installation of certificates valid? How can I check that?
The iotedge check output indicates that the certificates are valid. See the following 3 lines from your check output:
```
√ preloaded certificates are valid - OK
...
√ read all preloaded certificates from the Certificates Service - OK
...
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK
```

> Should the configuration of the custom modules be changed after the installation of certificates or not? Their code and configuration weren’t changed.
You shouldn't have to change your custom modules. It's possible that the runtime is still using the Edge Hub Server Cert that was previously generated with the temporary test certificates. To see if this is the problem, can you delete all the certs and keys in `/var/lib/aziot/certd/certs` `/var/lib/aziot/keyd/keys` and restart iotedge with `sudo iotedge system restart` so that a new Edge Hub Server Cert will be generated?

**Comment by nlcamp** [comment] 2022-06-21 18:12
@draganrmijailovic - Can you also confirm you've followed the 6 steps listed under "Configure IoT Edge with the New Certificates" on the following page? 
* https://docs.microsoft.com/en-us/azure/iot-edge/how-to-manage-device-certificates?view=iotedge-2020-11&tabs=linux#configure-iot-edge-with-the-new-certificates

**Comment by nlcamp** [comment] 2022-06-24 18:20
@draganrmijailovic 

> Should our own certificates be renewed - from IoT Edge automatically (our action is not needed), or not?
Yes, EdgeHub should automatically renew the server cert 5 minutes before the current one expires.

As a sanity check, could you run the following command to verify the server cert against your edge CA cert?
`openssl verify -CAfile /var/certificates/edge_ca.cer /var/lib/aziot/certd/certs/<edge-hub-server-cert>`

**Comment by draganrmijailovic** [comment] 2022-06-24 20:52
Thanks @nicamp for the post.

> Yes, EdgeHub should automatically renew the server cert 5 minutes before the current one expires.

OK, thanks for the information.

> As a sanity check, could you run the following command to verify the server cert against your edge CA cert?
> openssl verify -CAfile /var/certificates/edge_ca.cer /var/lib/aziot/certd/certs/<edge-hub-server-cert>
I performed the command and the validation failed:
![Certificate verification failed](https://user-images.githubusercontent.com/28098446/175663621-cd4cd62b-88da-486f-83ca-8c7187afd98e.jpg)
What should I do related to the validation failure? Before I created certification files based on the following post https://github.com/Azure/iotedge/issues/6044#issuecomment-1024538995  I performed openssl pkcs12 for creating edge_ca.cert and edge_ca.pk from .pfx. For the third file I took existing .cer file if I remember correctly.

**Comment by draganrmijailovic** [comment] 2022-06-28 14:44
Thanks @nlcamp 
We just opened a support ticket. Its ID is 2206280040005148. We are waiting further instructions regarding a call and/or gather additional information.

**Comment by nlcamp** [comment] 2022-06-28 16:04
@draganrmijailovic - Great. I've contacted our support engineers to see if we can setup a call.

One thing I'll want to check is that the Issuer for your EH server cert matches the subject/CN for your edge CA cert.

**Comment by nlcamp** [comment] 2022-07-25 16:12
Just an update here in case other users run into a similar issue. The root cause seems to be a bad Edge CA cert. Running `openssl x509 -text -noout -in <edge-ca-cert> | grep -A 1 "X509v3 Basic Constraints: critical"`, produces the following output:

>             X509v3 Basic Constraints: critical
>                CA:FALSE

Similarly, running the command, `openssl x509 -purpose -noout -in <edge-ca-cert>  | grep "^SSL server CA"`, produces the following output:

> SSL server CA : No

The above output shows that the cert is not a CA cert and therefore cannot be used to successfully generate and sign the edge hub server cert. The PKI provider needs to re-issue a production edge CA cert that meets the following requirement from our public doc,  [Certificates for device security - Azure IoT Edge | Microsoft Docs](https://docs.microsoft.com/en-us/azure/iot-edge/iot-edge-certs?view=iotedge-2020-11):


> Because the edge CA certificate is used by the IoT Edge security daemon to generate the final IoT Edge certificates, it must itself be a signing certificate, meaning it has certificate signing capabilities. Applying "V3 Basic constraints CA:True" to the edge CA certificate automatically sets up the required key usage properties.

**Comment by nlcamp** [comment] 2022-08-09 17:54
Closing this issue because the root cause has been identified (see previous comment) and also because it is being tracked by a support ticket.

We'll update this issue if there are any new findings from the support ticket that may be of use to the wider iotedge user community.

**Closed by nlcamp** 2022-08-09 17:54 UTC
Labels: iotedge, customer-reported
