### ISSUE TITLE
TLS authentication error

### ISSUE THREAD

**Issue by chr22** [Azure/iotedge#4261] opened 2021-01-21 13:16 UTC
## Expected Behavior
Device <-> Cloud communication should be functional.

## Current Behavior
Device can't receive or send messages to IoTHub and throws an "TLS authentication error"

## Steps to Reproduce
It has happened a few times in our production environment and the only way I could get rid of the error was to delete the module from the Edge device and then set it up again in the IoTHub.

![Steynsburg-error](https://user-images.githubusercontent.com/3649594/104594057-e8faab80-5670-11eb-8cd9-a3789c328ba6.png)

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
skiold-iot@iotedge:~$ sudo iotedge check
Configuration checks
--------------------
√ config.yaml is well-formed - OK
√ config.yaml has well-formed connection string - OK
√ container engine is installed and functional - OK
√ config.yaml has correct hostname - OK
√ config.yaml has correct URIs for daemon mgmt endpoint - OK
√ latest security daemon - OK
√ host time is close to real time - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: certificates - Warning
    The Edge device is using self-signed automatically-generated development certificates.
    They will expire in 18 days (at 2021-02-09 09:46:49 UTC) causing module-to-module and downstream device communication to fail on an active deployment.
    After the certs have expired, restarting the IoT Edge daemon will trigger it to generate new development certs.
    Please consider using production certificates instead. See https://aka.ms/iotedge-prod-checklist-certs for best practices.
√ production readiness: container engine - OK
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.

Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK

18 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS [e.g. Ubuntu 16.04, Ubuntu 18.04, Windows IoT Core]: Ubuntu 18.04.3
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.0.10.4
* Edge Agent [image tag (e.g. 1.0.0)]: 1.0.10
* Edge Hub [image tag (e.g. 1.0.0)]: 1.0.10
* Docker/Moby [run `docker version`]: 3.0.8

**Comment by davilu** [comment] 2021-01-22 19:36
@chr22 thanks for reporting the issue. Could you please provide more details? Seems in your module `Skiold.EsfProxy` is trying to create a device client instance to connect to edge hub with MQTT protocol but get a TLS auth error. I guess it might be caused by remote cert validation failure. You could either add edge device CA cert as trusted cert on your module deployment or [customize `RemoteCertificateValidationCallback`](https://github.com/Azure/azure-iot-sdk-csharp/blob/dc8b430bdf20522b44e7267a4ef0824ab4092b9f/iothub/device/src/Edge/CustomCertificateValidator.cs) in `MqttTransportSettings`.

**Comment by davilu** [comment] 2021-02-02 18:59
@chr22 And from the log, you're using self-signed automatically-generated development certificates which will be expired in 18 days. Please using production certificates instead. Please let us know if you still have the issue. Thanks.

**Comment by chr22** [comment] 2021-02-05 14:18
@davilu Thanks for the help. I will let you know if the problem persists.

**Comment by micahl** [comment] 2021-02-09 18:20
@chr22 thanks for opening this issue.  I'm going to close this for now, but if it does persist or happens again, please re-open.

**Closed by micahl** 2021-02-09 18:20 UTC
Labels: customer-reported, iotedge, needinfo
