### ISSUE TITLE
DPS with TPM is causing problem if device get rebooted after successful provision

### ISSUE THREAD

**Issue by pratson20** [Azure/iotedge#734] opened 2019-01-22 20:19 UTC
Hi,

I am using auto device provision for Azure Edge on Linux(Ubuntu). It is working fine for GW. Provision completed successfully.

**Following below steps to do Device Provisioning using TPM**
https://docs.microsoft.com/bs-latn-ba/azure/iot-edge/how-to-auto-provision-simulated-device-linux?toc=%2Fbs-latn-ba%2Fazure%2Fiot-dps%2Ftoc.json&bc=%2Fbs-latn-ba%2Fazure%2Fbread%2Ftoc.json&view=azure-java-stable

## Steps to Reproduce
After auto DPS using TPM. Keep running edge modules for longer duration and later reboot the device. Not able to list out running docker.

run below command-

1. sudo docker ps -a
**ERROR-  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?**

2. sudo iotedge list
**ERROR- An error in the management http client occurred.
	caused by: Hyper error
	caused by: an error occurred trying to connect: Connection refused (os error 111)**

This issue is getting reproduced always. I have seen this issue on four gateway device from Aaeon.

**Solution to resolve this issue-** Always, I need to follow below steps to resolve this issue.

**Uninstall Docker-**

- sudo apt-get remove --purge moby-cli
- sudo apt-get remove --purge moby-engine

- sudo apt-get remove docker-*
- sudo apt autoremove
- sudo rm -rf /etc/docker
- sudo rm -rf /usr/bin/docker-*

**Reboot device after above steps-**

**Reinstall Docker-**

- sudo apt-get update
- sudo apt-get install moby-engine
- sudo apt-get install moby-cli

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
Run `iotedge version`  1.0.5

#### Edge Agent
Image tag (i.e. 1.0.5)

#### Edge Hub
Image tag (i.e. 1.0.5)

#### Docker
Run `docker version` 3.0.2

########################
########################

Kindly let me know if you need any information.

**Comment by varunpuranik** [comment] 2019-01-23 00:10
@pratson20 - Thanks for reporting this issue. We will investigate the issue and get back to you.

**Comment by myagley** [comment] 2019-01-23 00:13
Is it possible to see the output of `systemctl status docker` when this issue reproduces? It seems like Docker is no longer running after a reboot.

**Comment by pratson20** [comment] 2019-01-23 16:48
@myagley @varunpuranik 
Today,  i have seen this issue first time with Manual device provision with connection_string. Never seen this issue with manual provision on Linux machine.

Resolved this issue with same above steps.

I have captured output of  _**systemctl status docker**_

**● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: e
   Active: failed (Result: start-limit-hit) since Wed 2019-01-23 16:34:23 GMT; 3
     Docs: https://docs.docker.com
  Process: 1689 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILU
 Main PID: 1689 (code=exited, status=1/FAILURE)

Jan 23 16:34:23 acniot-VirtualBox systemd[1]: docker.service: Start request repe
Jan 23 16:34:23 acniot-VirtualBox systemd[1]: Failed to start Docker Application
Jan 23 16:34:23 acniot-VirtualBox systemd[1]: docker.service: Failed with result
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: Dependency failed for Docker Appli
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: docker.service: Job docker.service
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: Dependency failed for Docker Appli
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: docker.service: Job docker.service
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: docker.service: Start request repe
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: Failed to start Docker Application
Jan 23 16:34:24 acniot-VirtualBox systemd[1]: docker.service: Failed with result
lines 1-17/17 (END)**

**Comment by myagley** [comment] 2019-01-23 16:54
The docker daemon is failing to start. 

Can we see the output of `journalctl -u docker`? These are the docker daemon logs and may give insight into why docker is failing.

**Comment by pratson20** [comment] 2019-01-23 17:18
@myagley  I have re-configured it and doing testing for prod. I will share the output if face this issue again after reboot. Do you need any other information. So, will capture that for debug.

**Comment by pratson20** [comment] 2019-02-04 10:04
@myagley @varunpuranik 

 Please find attached log for below commands-

**- systemctl status docker**

![error1](https://user-images.githubusercontent.com/7486266/52201634-15f19180-2892-11e9-8101-b1702d51f42e.png)

**- journalctl -u docker**

![error2](https://user-images.githubusercontent.com/7486266/52201645-2144bd00-2892-11e9-816e-23d744016ac3.png)

**Comment by myagley** [comment] 2019-02-04 17:01
From the third line down in the logs it looks like you have an invalid character in the `/etc/docker/daemon.json`. I can't really tell from the screenshot but it looks like an 'a' with an accent. This is preventing the docker daemon from starting. Is it possible to fix this character?

**Comment by pratson20** [comment] 2019-02-08 06:27
Hi @myagley thanks for your support. 

It was causing issue because of an invalid character  in _/etc/docker/daemon.json_. I have modified the special character in the file and now seeing no issue after reboot.

**Comment by myagley** [comment] 2019-02-08 17:32
Glad to hear you got it working. I'm going to close this issue for now. Please feel free to reopen if you have more questions.

**Closed by myagley** 2019-02-08 17:32 UTC
