### ISSUE TITLE
edgeHub 1.2.3: edgehub_queue_length metric wrong during offline scenarios (messages dropped by TTL)

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#5438] opened 2021-08-31 06:36 UTC
## Expected Behavior
edgehub_queue_length should show the 'real' queue length - the count of messages that could be consumed from the queue. Also during offline scenarios.

## Current Behavior
The metric seems to bounce between a reasonable value and a value that doesn't take the dropped messages into account.

## Additional Information

This https://github.com/Azure/iotedge/issues/3793#issuecomment-715627822 suggests that edgehub_queue_length is just an estimate during offline scenarios. Also https://github.com/Azure/iotedge/commit/4068369c4e32326809c3d5cfde33a8da0215dcfc indicates that things might have been improved since the comment was made - but I'm unsure if this change relates to offline scenarios.

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: RHEL 7.9
* Architecture [e.g. amd64, arm32, arm64]: amd64
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.3
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.3
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.3
* Docker/Moby [run `docker version`]: 20.10.7+azure

**Comment by and-rewsmith** [comment] 2021-09-02 21:37
Yep things should have improved for the next 1.2 release. Here is a description of the PR where the improvement was made:
https://github.com/Azure/iotedge/pull/4952#issue-631081169

Looping in @nyanzebra who made the change. Will this result in an accurate measurement while offline?

**Comment by nyanzebra** [comment] 2021-09-03 23:01
@and-rewsmith What happens now is we will maintain the count of the stored messages, so if we hold onto the messages in the queue for EH it will be reported. Since it must be the case any message that makes it onto disk can be reported later, this should be an accurate representation now of what the count is... if there is some odd behaviour here still, could we get a graph example?

**Comment by alaendle** [comment] 2021-09-06 11:58
![2021-09-06_13h53_20](https://user-images.githubusercontent.com/969523/132214123-9ac0e311-441c-4ad7-b5e4-31d194836769.png)

**Comment by and-rewsmith** [comment] 2021-09-09 17:55
@nyanzebra Do you think there are still issues which need fixing?

**Comment by nyanzebra** [comment] 2021-09-14 17:06
@alaendle and @and-rewsmith  Hmm, yep that looks super weird... let me see what I can do here. Let me come back after I try to replicate and see if I can figure this out.

**Comment by nyanzebra** [comment] 2021-09-15 19:52
I see what the problem is and am working on a fix now :)

**Comment by nyanzebra** [comment] 2021-11-09 20:22
This fix is merged into 1.2 release branch, just needs to be part of an upcoming release. Will post here when the release happens with the change

**Comment by nyanzebra** [comment] 2021-11-17 19:49
https://github.com/Azure/azure-iotedge/releases/tag/1.2.5 This is the release with the fix :)

**Comment by nyanzebra** [comment] 2021-11-22 22:21
I am closing this issue, but feel free to reopen if you see the problem persisting! :)

**Closed by nyanzebra** 2021-11-22 22:21 UTC
Labels: no-issue-activity, iotedge, customer-reported
