### ISSUE TITLE
Edge 1.4: Unable to provision device using DPS individual enrollment in .us gov cloud, Unsupported API version error

### ISSUE THREAD

**Issue by wright-mike** [Azure/iotedge#6631] opened 2022-08-29 18:03 UTC
## Expected Behavior
The device should provision and pull down the modules specified in the deployment based on the tags in the device twin. 

## Current Behavior
When we run `sudo iotedge config apply -c '/etc/aziot/config.toml'`, all checks are successful, but no modules are downloaded. iotege system logs shows a DPS client error, "Unsupported API version 2021-06-01."

## Steps to Reproduce
We are using the same process we currently use in our commercial cloud dev environment as we try to set up a staging environment in the .us gov cloud.
1.  Generate test certificates using this: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11&tabs=windows
2.  Create individual dps enrollment
3.  Provision using a config file with the following:
```##########################################
# DPS provisioning with X.509 certificate
##########################################
[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.us"
id_scope = "0us000278B1"
##########################################
[provisioning.attestation]
method = "x509"
registration_id = "mike-stage"
## identity certificate private key
identity_pk = "file:///var/secrets/mike-stage.key.pem"
## identity certificate
identity_cert = "file:///var/secrets/mike-stage.cert.pem"
#
##########################################
```

## Context (Environment)
Azure gov cloud (.us)

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ production readiness: identity certificates expiry - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
× read all preloaded certificates from the Certificates Service - Error
    could not load cert with ID "aziot-edged-trust-bundle"

    Caused by:
        parameter "id" has an invalid value
        caused by: not found
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
‼ host can connect to and perform TLS handshake with iothub AMQP port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
‼ host can connect to and perform TLS handshake with iothub MQTT port - Warning
    Could not retrieve iothub_hostname from provisioning file.
    Please specify the backing IoT Hub name using --iothub-hostname switch if you have that information.
    Since no hostname is provided, all hub connectivity tests will be skipped.
√ host can connect to and perform TLS handshake with DPS endpoint - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
× configuration has correct URIs for daemon mgmt endpoint - Error
    Unable to find image 'mcr.microsoft.com/azureiotedge-diagnostics:1.4.0' locally
    1.4.0: Pulling from azureiotedge-diagnostics
    213ec9aee27d: Pulling fs layer
    a273679c143b: Pulling fs layer
    74806c801e16: Pulling fs layer
    3d1f74f29f71: Pulling fs layer
    d43c7c0f2b47: Pulling fs layer
    3d1f74f29f71: Waiting
    d43c7c0f2b47: Waiting
    213ec9aee27d: Verifying Checksum
    213ec9aee27d: Download complete
    a273679c143b: Verifying Checksum
    a273679c143b: Download complete
    213ec9aee27d: Pull complete
    a273679c143b: Pull complete
    3d1f74f29f71: Download complete
    d43c7c0f2b47: Download complete
    74806c801e16: Verifying Checksum
    74806c801e16: Download complete
    74806c801e16: Pull complete
    3d1f74f29f71: Pull complete
    d43c7c0f2b47: Pull complete
    Digest: sha256:1d9a955f7529e4e5a5b1532381fb2a9efde6d038412ffbaae06caeaf46d1ccfc
    Status: Downloaded newer image for mcr.microsoft.com/azureiotedge-diagnostics:1.4.0
    SocketError - SocketErrorCode (TimedOut) : Operation timed out
    One or more errors occurred. (Got bad response: )
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
× production readiness: Edge Agent's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeAgent container
× production readiness: Edge Hub's storage directory is persisted on the host filesystem - Error
    Could not check current state of edgeHub container
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
23 check(s) succeeded.
5 check(s) raised warnings. Re-run with --verbose for more details.
4 check(s) raised errors. Re-run with --verbose for more details.
7 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.

```
</details>

### Device Information
* Host OS : Ubuntu 20.4
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: 

### Runtime Versions
* aziot-edged: 1.4.0
* Docker/Moby: 20.10.17+azure-1

## Logs
<details>
<summary>iotedge system logs</summary>

```

): error trying to connect: Connection refused (os error 111)
Aug 29 16:04:52 mike-dev systemd[1]: Started Azure IoT Identity Service.
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [INFO] - Starting service...
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [INFO] - Version - 1.4.0
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [INFO] - Provisioning starting. Reason: Startup
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- GET /keypair/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-certd[4090422]: 2022-08-29T16:04:52Z [INFO] - <-- GET /certificates/device-id?api-version=2020-09-01 {"host": "certd.sock"}
Aug 29 16:04:52 mike-dev aziot-certd[4090422]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [INFO] - Sending DPS registration request.
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - <-- POST /encrypt?api-version=2021-05-01 {"content-length": "355", "content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:52Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [ERR!] - service encountered an error
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [ERR!] - caused by: DPS client error
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [ERR!] - caused by: Unsupported API version 2021-06-01.
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]: 2022-08-29T16:04:52Z [ERR!] -    0: <unknown>
Aug 29 16:04:52 mike-dev aziot-identityd[4090461]:    1: <unknown>
Aug 29 16:04:52 mike-dev systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 16:04:52 mike-dev systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 29 16:04:57 mike-dev systemd[1]: aziot-identityd.service: Scheduled restart job, restart counter is at 335.
Aug 29 16:04:57 mike-dev systemd[1]: Stopped Azure IoT Identity Service.
Aug 29 16:04:57 mike-dev aziot-edged[4090393]: 2022-08-29T16:04:57Z [WARN] - Failed to send HTTP request (attempt 2 of 2): connection error: Connection reset by peer (os error 104)
Aug 29 16:04:57 mike-dev aziot-edged[4090393]: 2022-08-29T16:04:57Z [WARN] - Failed to reprovision: connection error: Connection reset by peer (os error 104)
Aug 29 16:04:57 mike-dev systemd[1]: Started Azure IoT Identity Service.
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [INFO] - Starting service...
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [INFO] - Version - 1.4.0
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [INFO] - Provisioning starting. Reason: Startup
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- GET /keypair/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-certd[4090422]: 2022-08-29T16:04:58Z [INFO] - <-- GET /certificates/device-id?api-version=2020-09-01 {"host": "certd.sock"}
Aug 29 16:04:58 mike-dev aziot-certd[4090422]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [INFO] - Sending DPS registration request.
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - <-- POST /encrypt?api-version=2021-05-01 {"content-length": "355", "content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-keyd[4090403]: 2022-08-29T16:04:58Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [ERR!] - service encountered an error
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [ERR!] - caused by: DPS client error
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [ERR!] - caused by: Unsupported API version 2021-06-01.
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]: 2022-08-29T16:04:58Z [ERR!] -    0: <unknown>
Aug 29 16:04:58 mike-dev aziot-identityd[4090481]:    1: <unknown>
Aug 29 16:04:58 mike-dev systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 16:04:58 mike-dev systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.
Aug 29 16:05:02 mike-dev aziot-edged[4090393]: 2022-08-29T16:05:02Z [INFO] - Obtaining Edge device provisioning data...
Aug 29 16:05:03 mike-dev systemd[1]: aziot-identityd.service: Scheduled restart job, restart counter is at 336.
Aug 29 16:05:03 mike-dev systemd[1]: Stopped Azure IoT Identity Service.
Aug 29 16:05:03 mike-dev aziot-edged[4090393]: 2022-08-29T16:05:03Z [WARN] - Failed to send HTTP request (attempt 1 of 2): connection error: Connection reset by peer (os error 104)
Aug 29 16:05:03 mike-dev systemd[1]: Started Azure IoT Identity Service.
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [INFO] - Starting service...
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [INFO] - Version - 1.4.0
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [INFO] - Provisioning starting. Reason: Startup
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- GET /keypair/device-id?api-version=2021-05-01 {"host": "keyd.sock"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-certd[4090422]: 2022-08-29T16:05:03Z [INFO] - <-- GET /certificates/device-id?api-version=2020-09-01 {"host": "certd.sock"}
Aug 29 16:05:03 mike-dev aziot-certd[4090422]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/algorithm?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/rsa-modulus?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /parameters/rsa-exponent?api-version=2021-05-01 {"content-length": "248", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [INFO] - Sending DPS registration request.
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - <-- POST /encrypt?api-version=2021-05-01 {"content-length": "355", "content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-keyd[4090403]: 2022-08-29T16:05:03Z [INFO] - --> 200 {"content-type": "application/json"}
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [ERR!] - Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [ERR!] - service encountered an error
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [ERR!] - caused by: DPS client error
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [ERR!] - caused by: Unsupported API version 2021-06-01.
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]: 2022-08-29T16:05:03Z [ERR!] -    0: <unknown>
Aug 29 16:05:03 mike-dev aziot-identityd[4090509]:    1: <unknown>
Aug 29 16:05:03 mike-dev systemd[1]: aziot-identityd.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 16:05:03 mike-dev systemd[1]: aziot-identityd.service: Failed with result 'exit-code'.

```
</details>

## Additional Information
Please provide any additional information that may be helpful in understanding the issue.

**Comment by ggjjj** [comment] 2022-08-29 22:05
Is the issue reproducible when downgrading to 1.3?

**Comment by wright-mike** [comment] 2022-08-30 20:07
Yes. I got the same error with aziot-edge 1.3. 

I also tried with aziot-edge 1.2.7 and got a DPS error with the message ```Message":"ErrorCode:IotHubUnauthorizedAccess;Unauthorized","ExceptionMessage":"Tracking ID:7ed33e46715041e485aa200259f92446-G```

**Comment by jlian** [comment] 2022-09-01 18:56
We're checking with DPS team

**Comment by micahl** [comment] 2022-09-08 01:36
The DPS team has identified the issue and is working on a resolution.

**Comment by wright-mike** [comment] 2022-09-12 16:43
Do you have an ETA on a fix? This is blocking us.

**Comment by jlian** [comment] 2022-09-12 16:46
I believe it should be very soon if not already almost done, but I'm following up.

**Comment by jlian** [comment] 2022-09-12 17:49
DPS team says this should now be fixed. Could you try again?

**Comment by jlian** [comment] 2022-09-13 21:12
Closing since DPS team provided fix. If you have continued problems let me know and we can reopen.

**Closed by jlian** 2022-09-13 21:12 UTC
Labels: iotedge, customer-reported

**Comment by wright-mike** [comment] 2022-09-14 15:18
I'm now getting a new error.
``` Failed to provision with IoT Hub, and no valid device backup was found: DPS client error
- service encountered an error
 - caused by: DPS client error
 - caused by: Invalid certificate.
 -    0: <unknown>```
 Do you allow test certs in the gov cloud? I was using this guide to make certs until we figured out a certificate authority. https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates?view=iotedge-2020-11&tabs=windows

**Comment by wright-mike** [comment] 2022-09-14 15:20
sorry, should I make a new issue for the new error?

**Comment by micahl** [comment] 2022-09-14 15:21
@wright-mike yes please
