### ISSUE TITLE
Edge Module is not working with AMQP over websocket 

### ISSUE THREAD

**Issue by sachidanand** [Azure/iotedge#846] opened 2019-02-15 03:47 UTC
Edge Module is not working with AMQP over websocket so please suggest me how to implement it. We can not open the port 5672 QMQP

**Comment by myagley** [comment] 2019-02-15 16:07
Hello. Can you please give a few more details on your scenario? If you have a module connecting to the Edge Hub locally, you may be able to connect over 5671 without opening this port up on the device.

What aspect of AMQP over Websockets isn't working for you? Do you have any errors or logs?

**Comment by sachidanand** [comment] 2019-02-22 04:26
this is the error we are getting on Windows container 
System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The certificat
e chain was issued by an authority that is not trusted
--- End of inner exception stack trace ---

**Comment by myagley** [comment] 2019-02-22 16:32
This seems like a duplicate of https://github.com/Azure/iotedge/issues/868. I'm going to close this so that we can keep the conversation in one place.

**Closed by myagley** 2019-02-22 16:32 UTC
