### ISSUE TITLE
IoT Edge module stops receiving data - Reconcile failed because of the an exception System.TimeoutException: Operation timed out

### ISSUE THREAD

**Issue by draganrmijailovic** [Azure/iotedge#4992] opened 2021-05-17 16:05 UTC
**Expected Behavior**
The edgeAgent and the whole runtime runs reliably and stable, without interruptions.

**Current Behavior**
We have created a IoT Edge module for receiving data from the devices. For a time, a few hours, a day or two, the IoT Edge module receives data without problems and then suddenly stops receiving data. After restarting IoT Edge service data are received again for a certain time. I often saw the following in the IoT Edge Agent's log file before stopping receiving data:

> Reconcile failed because of the an exception
> System.TimeoutException: Operation timed out
>    at Microsoft.Azure.Devices.Edge.Util.TaskEx.TimeoutAfter[T](Task`1 task, TimeSpan timeout) in C:\agent\_work\2\s\edge-util\src\Microsoft.Azure.Devices.Edge.Util\TaskEx.cs:line 128
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 146
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2020_07_07\ModuleManagementHttpClient.cs:line 248
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\versioning\ModuleManagementHttpClientVersioned.cs:line 146
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.GetModules[T](CancellationToken cancellationToken) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Edgelet\version_2020_07_07\ModuleManagementHttpClient.cs:line 171
>    at Microsoft.Azure.Devices.Edge.Agent.Docker.DockerEnvironment.GetModulesAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Docker\DockerEnvironment.cs:line 51
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.GetCurrentModuleSetAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 256
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.ReconcileAsync(CancellationToken token) in C:\agent\_work\2\s\edge-agent\src\Microsoft.Azure.Devices.Edge.Agent.Core\Agent.cs:line 208

We used Windows device (Azure Windows VM), Windows container and IoT Edge 1.0.10 for Windows but the IoT Edge module stopped receiving data. After that we upgraded the IoT Edge to 1.1 (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-windows-on-windows?view=iotedge-2018-06) but the same thing happens.
I attached the logs files for the disputed situation. Our module is IotEdgeModuleReceivingDataFromPt40. You can see its last line – the eventTimeStamp property is **2021-05-16T18:01:11**.
The edgeAgent_log.txt contains line:
 <4> **2021-05-16 17:57:27.919 +00:00** [WRN] - Reconcile failed because of the an exception
But there were the same three logs before ...

**Output of iotedge check**
We use temporary certificate but we will create another certificate for the production. 
![IoT Edge - Configuration Checks](https://user-images.githubusercontent.com/28098446/118519667-9b36a280-b739-11eb-9207-1200ad0db110.PNG)

**Runtime Versions**
•	iotedge: 1.1.1 
•	Edge Agent: 1.1.2.41361617
•	Edge Hub: 1.1.2.41361617

**Logs**
The logs are attached
[logs.zip](https://github.com/Azure/iotedge/files/6495117/logs.zip)

**Comment by dylanbronson** [comment] 2021-05-17 18:18
Hello, firstly I want to clarify your situation. Your module simply sends some data as messages to IoTHub is that correct? It may be worthwhile to add some print statements there if there is any possibility that the module itself is hanging for some reason (if you are simply just sending messages then that is probably not the case, but if you are doing more complicated things, then it would be good to check).

EdgeHub logs look clean for the time that the module stops sending data. 
When you run "iotedge list" is your module still running? Or has it stopped? If it's still running, then we can basically ignore the edgeAgent error you are posting about, since edgeAgent just keeps modules running in their docker containers.

Regardless of that, though, Debug logs would be very helpful in this situation. You can turn them on using these instructions: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#view-the-messages-going-through-the-iot-edge-hub
You set the "RuntimeLogLevel" environment variable to "debug" in edgeHub and in edgeAgent in the deployment manifest. Seeing what is happening with edgeHub at the time of your module stopping would be very helpful

**Comment by draganrmijailovic** [comment] 2021-05-17 19:45
Hello,

Thanks for your answer.
 
_firstly I want to clarify your situation. Your module simply sends some data as messages to IoTHub is that correct?_
Yes, you are right. Our module sends data as messages to IoT Hub and via our event hub triggered Azure function we store messages in the database.

_It may be worthwhile to add some print statements there if there is any possibility that the module itself is hanging for some reason (if you are simply just sending messages then that is probably not the case, but if you are doing more complicated things, then it would be good to check)._
Before I already added print statements in try-catch. The data is received from devices in a separate thread. The main method in the separate thread has an infinite loop and the parser parses the data obtained from the devices (we got the parser from the manufacturer of devices). Sometimes the parser generates an error but the infinite loop is not left. Then the error is written in the log file. There are two errors in the earlier attached log file of the module. The logs have the prefix 'Exception - Message:'. I attached the module:
[Program.zip](https://github.com/Azure/iotedge/files/6496208/Program.zip)

_When you run "iotedge list" is your module still running?_
Yes, our module always still running. It never stopped.

_Regardless of that, though, Debug logs would be very helpful in this situation. You can turn them on using these instructions: https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#view-the-messages-going-through-the-iot-edge-hub
You set the "RuntimeLogLevel" environment variable to "debug" in edgeHub and in edgeAgent in the deployment manifest. Seeing what is happening with edgeHub at the time of your module stopping would be very helpful_
I set the environment variables for both modules via Azure portal. And I'm getting debug logs. Logs files are attached. But, IoT Edge module has stopped again. I will start it. New logs are attached:
 
[support_bundle.zip](https://github.com/Azure/iotedge/files/6496476/support_bundle.zip)

**Comment by dylanbronson** [comment] 2021-05-17 21:02
From what I can tell, edge runtime is working as expected. I don't see any errors in edgeAgent or edgeHub, and edgeAgent claims that it is starting up your custom module successfully. 

I also see this comment in the program you attached: "//Be careful, as the Receive method will block until a datagram arrives from a remote host"
Could it be that the module is blocking here waiting for a datagram to arrive? Can you set some sort of timeout there (maybe this is helpful https://stackoverflow.com/questions/2281441/can-i-set-the-timeout-for-udpclient-in-c) and add some print statements to see if maybe it is stopping because of that line?

The module is still running, so edgeAgent won't do anything to restart it unless it crashes. And edgeHub is simply relaying messages that the module gives it, and there's no mention of messages coming it. So it seems like the issue is coming from the module.

**Comment by draganrmijailovic** [comment] 2021-05-18 06:55
Thanks a lot for your answer. You are right! 

I added a timeout for receiving messages and the module receives messages as well:
![IoT Edge Module - Timeout for receiving is added](https://user-images.githubusercontent.com/28098446/118604214-2ef98480-b7b5-11eb-95b6-fc107ed0afac.PNG)

In the log file, there are a lot of exceptions related to receiving messages. That is a topic that concerns UDP protocol and not IoT Edge :) But, do you have some comments about that, is it regular? Logs in two minutes are attached:
[IotEdgeModuleReceivingDataFromPt40_log.txt](https://github.com/Azure/iotedge/files/6498973/IotEdgeModuleReceivingDataFromPt40_log.txt)

But, messages are received as well :) 

I think that the issue can be closed, IoT edge works well.

Thank you for your cooperation.

**Comment by dylanbronson** [comment] 2021-05-18 16:03
I took a look but I'm sorry I don't know what those exceptions mean, I am no UDP expert :) 
Good luck with it, though.
Closing the issue.

**Closed by dylanbronson** 2021-05-18 16:03 UTC
Labels: customer-reported, iotedge

**Comment by draganrmijailovic** [comment] 2021-05-18 18:19
I only increased the timeout to 10 seconds and there are no more exceptions. The attached module's log:
[IotEdgeModuleReceivingDataFromPt40_log.txt](https://github.com/Azure/iotedge/files/6503414/IotEdgeModuleReceivingDataFromPt40_log.txt)

Thanks again for the help.

**Comment by draganrmijailovic** [comment] 2021-05-30 16:57
Unfortunately, timeout did not resolve the issue - the IoT edge module has stopped receiving data. I tried to improve the module and created two threads - one thread receives messages and stores them in the BlockingCollection. Another thread reads messages from the BlockingCollection, parses them, and forwards them to an IoT Hub. But again, the data reception was interrupted. **But today I saw that the interruption occurs at the same time, 2:01 AM or 02:02 AM.** I checked the IoT Hub diagram for the last twenty days and attached screenshots for the last four days. After the interruption, I usually redeployed the IoT Edge module on the device and the module received messages again. 
Why does the interruption always occur at the same time? It's as if some planned maintenance operation interrupts receiving messages by the module? The interruption is not related to the number of messages, because even on weekends there is an interruption when there are significantly fewer messages. 
![IoT Hub - 2021-05-27](https://user-images.githubusercontent.com/28098446/120112947-73533000-c178-11eb-87c1-a4dfe1853641.png)
![IoT Hub - 2021-05-28](https://user-images.githubusercontent.com/28098446/120112949-751cf380-c178-11eb-8344-882fe13e680f.png)
![IoT Hub - 2021-05-29](https://user-images.githubusercontent.com/28098446/120112950-764e2080-c178-11eb-95eb-4c7c171d71df.png)
![IoT Hub - 2021-05-30](https://user-images.githubusercontent.com/28098446/120112952-777f4d80-c178-11eb-82b8-3a9d32131103.png)

**Comment by draganrmijailovic** [comment] 2021-06-04 19:34
Unfortunately, the problem was not resolved and I had to open another issue https://github.com/Azure/iotedge/issues/5065 because this issue was closed. I improved the program but without effect. Interruptions are still happening.
