### ISSUE TITLE
edgeAgent does not honor `startupOrder` on restart

### ISSUE THREAD

**Issue by stefanb2** [Azure/iotedge#7144] opened 2023-11-03 10:07 UTC
## Expected Behavior
`edgeAgent` should honor the module property `startupOrder` when

- deployment is updated, i.e. when containers are created from image
- restarting the IoT solution, f.ex. when existing containers are started after device reboot

## Current Behavior
`edgeAgent` only honors the module property `startupOrder` when deployment is updated, i.e. when containers are created.

When the IoT solution is restarted then `edgeAgent` simply starts all existing containers at once. This can lead to at least to the following issues
1. module A starts up before `edgeHub` is ready: `ModuleClient.fromEnvironment()` throws an exception in module A
2. module B (`"startupOrder": 2`) starts up before module A (`"startupOrder": 1`) is ready: `client.invokeMethod(..., 'moduleA', ...)` in module B fails

## Steps to Reproduce
1. create a deployment that uses `startupOrder` (`edgeHub` 0, `moduleA` 1, `moduleB`: 2, etc.)
2. apply deployment to device
4. reboot device

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
# iotedge check

Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
√ aziot-identity-service package is up-to-date - OK
√ host time is close to reference time - OK
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ check all EST server URLs utilize HTTPS - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ aziot-edge package is up-to-date - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
32 check(s) succeeded.
3 check(s) raised warnings. Re-run with --verbose for more details.
2 check(s) were skipped due to errors from other checks. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS:  `Debian GNU/Linux 11 (bullseye)` (tailored build of Raspberry Pi OS)
* Architecture:  `aarch64`
* Container OS: Linux containers (`node:lts-alpine`)

### Runtime Versions
* aziot-edged: `iotedge 1.4.20`
* Edge Agent: `mcr.microsoft.com/azureiotedge-agent:1.4`
* Edge Hub: `mcr.microsoft.com/azureiotedge-hub:1.4`
* Docker/Moby: 
```
# docker version
Client:
 Version:           23.0.7+azure-1
 API version:       1.42
 Go version:        go1.19.12
 Git commit:        92955ed461e91154ed722ed831e9f22ea93fd7e9
 Built:             Wed Aug 23 12:04:52 UTC 2023
 OS/Arch:           linux/arm64
 Context:           default

Server:
 Engine:
  Version:          23.0.7+azure-1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.12
  Git commit:       606a7a76949ec08cb26940037b1c71c0024c6b44
  Built:            Wed Sep  6 06:38:37 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.24-2
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9-1
  GitCommit:        ccaecfcbc907d70a7aa870a6650887b901b25b82
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

## Logs

Example log for issue (1): module A started before `edgeHub` is ready:

~~~
# docker logs moduleA
/home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_translate_error.js:71
            err = new azure_iot_common_1.errors.UnauthorizedError('mqtt.js returned ' + mqttError.message + ' error');
                  ^

UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.3:8883 error
    at translateError (/home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_translate_error.js:71:19)
    at constructor._onEnter (/home/node/module/node_modules/azure-iot-device-mqtt/dist/mqtt.js:85:95)
    at constructor.transition (/home/node/module/node_modules/machina/lib/machina.js:653:28)
    at Fsm.<computed> [as transition] (/home/node/module/node_modules/machina/lib/machina.js:466:63)
    at /home/node/module/node_modules/azure-iot-device-mqtt/dist/mqtt.js:224:59
    at constructor._onEnter (/home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:146:29)
    at constructor.transition (/home/node/module/node_modules/machina/lib/machina.js:653:28)
    at Fsm.<computed> [as transition] (/home/node/module/node_modules/machina/lib/machina.js:466:63)
    at /home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:225:39
    at /home/node/module/node_modules/mqtt/lib/client.js:994:11 {
  transportError: Error: Failure on first connection (Not authorized): connect ECONNREFUSED 172.18.0.3:8883
      at /home/node/module/node_modules/azure-iot-device-mqtt/dist/mqtt.js:224:103
      at constructor._onEnter (/home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:146:29)
      at constructor.transition (/home/node/module/node_modules/machina/lib/machina.js:653:28)
      at Fsm.<computed> [as transition] (/home/node/module/node_modules/machina/lib/machina.js:466:63)
      at /home/node/module/node_modules/azure-iot-mqtt-base/dist/mqtt_base.js:225:39
      at /home/node/module/node_modules/mqtt/lib/client.js:994:11
      at Store.close (/home/node/module/node_modules/mqtt/lib/store.js:124:5)
      at /home/node/module/node_modules/mqtt/lib/client.js:988:26
      at Store.close (/home/node/module/node_modules/mqtt/lib/store.js:124:5)
      at MqttClient.closeStores (/home/node/module/node_modules/mqtt/lib/client.js:987:24)
}

Node.js v20.9.0
        <----- module exits and then is restarted by edgeAgent
2023-11-03T09:39:25.656Z IoT Edge module <REDACTED>: client initialized.
~~~

## Additional Information

1. is just an annoyance, i.e. ignoring `startupOrder` leads to unnecessary module restarts and unnecessary errors in the logs on restart, but eventually the IoT solution is up & running correctly
2. can lead to subtle bugs, i.e. the developer must write extra code to detect an incorrect startup sequence to avoid such bugs.

**Comment by david-emakenemi** [comment] 2023-11-14 19:47
@nlcamp any ideas?

**Comment by nlcamp** [comment] 2023-11-17 21:54
@stefanb2  - I will attempt a repro and discuss with the team to see if this is something we can fix.

**Comment by nlcamp** [comment] 2023-12-15 15:55
@stefanb2 - Sorry for the delay. I was able to repro this using 3 simulated temperature sensor modules in my deployment where I set the desired startup order to be: edgeHub, tempSim0, tempSim1, tempSim2. I saw the following _actual_ startup order when I ran `sudo iotedge system restart`: tempSim0, tempSim1, tempSim2. I suspect the reason edgeHub starts last in this scenario is because it takes the longest to shutdown.

As a workaround, I've found that if you run two commands for restart, `iotedge system stop` followed by `iotedge system restart` the specified startup order is preserved. Please try this workaround and let us know if it works for your scenario.

On our side, we'll be discussing whether this is a regression/bug or a new feature. If the former, we'll be able to fix it as part of the 1.4 LTS, however if it's considered a new feature, we may not change it as part of 1.4 and will need to prioritize it against features targeting our next LTS version.

See the following screenshots showing the two scenarios I mentioned above.
1. `sudo iotedge system restart`, resulting in undesired startup order
![module_startup_order_restart_1](https://github.com/Azure/iotedge/assets/7676015/9d111e4a-711c-4934-9116-ae3fb06966d2)

2. `sudo iotedge system stop && sleep 60s && sudo iotedge system restart`, resulting in desired startup order
![module_startup_order_stop_then_restart_1](https://github.com/Azure/iotedge/assets/7676015/72285512-9de2-4712-b176-a4c0c5c21967)

**Comment by stefanb2** [comment] 2024-01-03 08:04
I tried the work around 5 times on my device and it worked every time. When looking at the information from docker it becomes obvious why: `edgeAgent` container always recreates the IoT solution from scratch, i.e. all other containers are deleted first.

To quote from `Steps To Reproduce` above

> 3. reboot device

i.e. the workaround doesn't help unless I implement an additional `systemd` unit.

**Comment by jlian** [comment] 2024-01-11 19:23
@nlcamp any thoughts?

**Comment by nlcamp** [comment] 2024-01-16 19:28
I'm able to repro the reboot issue. We need to look into whether we can fix the reboot scenario with a change to our systemd units. I think the incorrect startup order on `iotedge system restart` can be treated as a separate issue.

**Comment by jlian** [comment] 2024-01-25 19:41
@stefanb2 we discussed internally, and unfortunately we probably won't be able to take this bug fix for now.

From our [docs](https://learn.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-1.4#module-configuration-and-management):

> However, you should always design your modules to handle failures of other modules. It's the nature of containers that they may stop and restart at any time, and any number of times.

It seems like you're already doing this, because I see from the original issue description:

> is just an annoyance, i.e. ignoring startupOrder leads to unnecessary module restarts and unnecessary errors in the logs on restart, but **eventually the IoT solution is up & running correctly**

My impression is that this issue doesn't represent a critical problem for you. Is this correct?

**Comment by stefanb2** [comment] 2024-01-26 10:00
@jlian not even the documentation will be updated to reflect that `startupOrder` has a bug?

**Comment by jlian** [comment] 2024-01-29 18:31
If you can give me an assessment on how serious this issue is for you, by answering the questions above, that would help with our backlog management. 

And yes we will update the docs either way.

**Comment by stefanb2** [comment] 2024-01-30 07:11
At this moment this issue isn't critical for my project.

Of course the module logs are now unusable, because they are flooded with false errors. Only time will tell if this is going to be a problem in production or not.

**Comment by bishal41** [comment] 2024-02-21 18:11
@stefanb2 I will proceed and close this issue but let me know when the issue will be significant for you, and we can further discuss.

**Closed by bishal41** 2024-02-21 18:11 UTC
Labels: iotedge, customer-reported
