### ISSUE TITLE
[Function] outputName configured in edge function does not work

### ISSUE THREAD

**Issue by adashen** [Azure/iotedge#100] opened 2018-07-31 06:42 UTC
## Expected Behavior
The output name of function module should respect the one defined in function.json

## Current Behavior
Edge routes does not work if using the outputName defined in function.json (output1).
when replace the exact outputName to "*", routes works.
So it seems the outputName is not respected

## Steps to Reproduce
1. Follow the steps in https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-function
2. Check the function.json in the created function project. The outputName is "output1"
3. But there is no message received to IoT Hub
4. However if we changes the routes to  "FROM /messages/modules/<functionname>/* INTO $upstream" it works.

There is a same issue filed in docs: 
https://github.com/MicrosoftDocs/azure-docs/issues/5878

### Device (Host) Operating System
linux unbutu

### Architecture
amd64

### Container Operating System
Linux containers

#### iotedged
1.0

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
18.03.1

#### Other info
Found the code of sending batch amqp message. It seems the batch mode event in amqp mis-parsing the output name and just merge the list of message into one. Maybe the root cause of this issue

https://github.com/Azure/azure-iot-sdk-csharp/blob/2c9bce0bc060b1869ec7a5bcfe9e63e736ed450f/iothub/device/src/Transport/AmqpTransportHandler.cs#L186

**Comment by mrohera** [comment] 2018-08-01 18:36
Thanks for reporting this problem. We suspect that this is problem at our end and are still triaging this issue to determine the root cause.

**Comment by myagley** [comment] 2018-08-06 15:19
This is fixed by #124 and will make it into the next release of the Edge Hub.

**Comment by kgremban** [comment] 2018-08-06 21:35
@myagley Thanks for the info about the fix. When is the next Edge Hub release?

**Comment by myagley** [comment] 2018-08-21 15:59
This has been fixed in 1.0.1 of the IoT Edge runtime, released this morning. Closing this issue.

**Closed by myagley** 2018-08-21 15:59 UTC
Labels: bug, checkedin
