### ISSUE TITLE
edgeAgent v1.2.4 reported properties - modules.{moduleId}.restartCount - seems inconsistent

### ISSUE THREAD

**Issue by alaendle** [Azure/iotedge#5732] opened 2021-10-22 07:29 UTC
We have noticed that the edgeAgent reports the following:

```json
[...]
                "round-trip-rabbitmq": {
                    "exitCode": 0,
                    "statusDescription": "running",
                    "lastStartTimeUtc": "2021-10-21T22:40:12.0257254",
                    "lastExitTimeUtc": "2021-10-21T22:39:06.7258003",
                    "restartCount": 0,
                    "lastRestartTimeUtc": "2021-10-21T22:39:06.7258003",
                    "runtimeStatus": "running",
                    "version": "1.0",
                    "status": "running",
                    "restartPolicy": "always",
[...]
```
Simply explained, when `lastRestartTimeUtc` contains a value I would expect `restartCount` to be greater than zero, right?
Also I know that at this time no interference happened and that the module was automatically restarted by the edge agent.

What looks strange at the edgeAgent log is the fact that the agent tries to stop the already stopped module:

```
<6> 2021-10-21 22:39:11.109 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (55s left).
<6> 2021-10-21 22:39:11.305 +00:00 [INF] - Updated reported properties
<6> 2021-10-21 22:39:16.321 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (50s left).
<6> 2021-10-21 22:39:21.342 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (45s left).
<6> 2021-10-21 22:39:26.370 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (40s left).
<6> 2021-10-21 22:39:31.391 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (35s left).
<6> 2021-10-21 22:39:36.416 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (30s left).
<6> 2021-10-21 22:39:41.444 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (25s left).
<6> 2021-10-21 22:39:46.466 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (20s left).
<6> 2021-10-21 22:39:51.490 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (15s left).
<6> 2021-10-21 22:39:56.513 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (10s left).
<6> 2021-10-21 22:40:01.538 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (05s left).
<6> 2021-10-21 22:40:06.561 +00:00 [INF] - Module 'round-trip-rabbitmq' scheduled to restart after 00s (00s left).
<6> 2021-10-21 22:40:11.582 +00:00 [INF] - Plan execution started for deployment 237
<6> 2021-10-21 22:40:11.582 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module round-trip-rabbitmq]\n  [Start module round-trip-rabbitmq]\n  [Saving round-trip-rabbitmq to store]\n)"
<6> 2021-10-21 22:40:11.582 +00:00 [INF] - Executing command: "Stop module round-trip-rabbitmq"
<6> 2021-10-21 22:40:11.584 +00:00 [INF] - Executing command: "Start module round-trip-rabbitmq"
<6> 2021-10-21 22:40:12.029 +00:00 [INF] - Executing command: "Saving round-trip-rabbitmq to store"
<6> 2021-10-21 22:40:12.030 +00:00 [INF] - Plan execution ended for deployment 237
<6> 2021-10-21 22:40:17.271 +00:00 [INF] - Updated reported properties
```
Please let me know if I could contribute further information.

**Comment by nlcamp** [comment] 2021-11-17 20:30
@aleandle - Sorry for the delay. I've been able to repro this issue and it does seem like a bug. I'm seeing that the `restartCount` gets updated when edgeAgent restarts the module after I do a `sudo docker stop <module-name>`. However after the restart of the module following a `sudo kill -9 <module-pid>` I don't see the restartCount get updated.

We'll start looking into a fix for this issue. Thanks again for reporting it.

**Comment by nlcamp** [comment] 2021-11-29 14:30
@alaendle - I looked into this some more and discovered that the behavior seen after a kill is actually correct, though arguably non-intuitive. In the Edge Agent code, a restart is defined as a scenario where an unhealthy state is detected and Edge Agent stops and starts a module. For example, when a user executes `docker stop` on a module as I did, Edge Agent detects that it's not running, executes a `stop` followed by a `start`, and increments the restart count. (Note: this explains the stop and start log messages you mentioned in your description of the problem).

However, when Edge Agent detects that a module container does not exist, it executes a `create` command. As part of this `create` command, the restart count is initialized to zero. The lastRestartTimeUtc field also gets initialized the to the current time when the `create` command executes, which explains your first comment about the presence of a lastRestartTime when the restart count is zero. I'll see if we can change this to be consistent with our definition of 'restart', which does not include initial module creation.

Please let me know if this makes sense or if you have any additional concerns. Also, can you please provide more details about the scenario where your module was restarted so I can be sure my repro is valid.

**Comment by alaendle** [comment] 2021-11-29 17:18
@nlcamp - Thanks for the detailed breakdown. This indeed explains my observation, however I'm still unsure if I'm happy with the current definition/behaviour. In my scenario the module intentionally exits gracefully every 9 hours; so it's debatable if this leads to an unhealthy state, because exit code is zero. But I would argue that this state indeed is unhealthy, because the deployment manifest determines that the target state is `running`. Also the edgeAgent somehow makes the same conclusion, it ensures that the module is restarted - so I would still expect a `restartCount` > 0 😉 . Please let me know if the description of our scenario is not sufficient or if I could contribute other/additional information or arguments. Again many thanks for your analysis!

**Comment by nlcamp** [comment] 2021-11-30 16:55
@alaendle - Thanks for the additional info about your scenario. I ran a test with a module that I had exit gracefully as you mentioned with an exit code of 0 every 60 seconds. In this setup, I saw the module show up as `stopped` in a console where I had `watch -- iotedge list` running. After a few seconds, Edge Agent restarted the stopped module and I saw the restart count get incremented when I looked at the module twin in the portal UI.

Is there something else that's happening in your scenario after the module exits? Do you see it listed by `iotedge list` in a `stopped` state as I do in my setup? Is there some other process in your scenario that's removing the exited/stopped container before EA restarts it?

**Comment by alaendle** [comment] 2021-12-01 06:22
@nlcamp - My guess is that the `restartCount` value in the device twin is just not the metric we expect; so my assumption is that it is reset after 10 succesfull minutes. Take a look at the `edgeAgent`log:

```
<6> 2021-12-01 02:19:15.647 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (57s left).
<6> 2021-12-01 02:19:20.830 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (51s left).
<6> 2021-12-01 02:19:25.846 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (46s left).
<6> 2021-12-01 02:19:30.859 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (41s left).
<6> 2021-12-01 02:19:35.879 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (36s left).
<6> 2021-12-01 02:19:40.898 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (31s left).
<6> 2021-12-01 02:19:45.913 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (26s left).
<6> 2021-12-01 02:19:50.928 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (21s left).
<6> 2021-12-01 02:19:55.944 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (16s left).
<6> 2021-12-01 02:20:00.958 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (11s left).
<6> 2021-12-01 02:20:05.975 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (06s left).
<6> 2021-12-01 02:20:10.991 +00:00 [INF] - Module 'visu-poc-solace-gateway' scheduled to restart after 00s (01s left).
<6> 2021-12-01 02:20:16.007 +00:00 [INF] - Executing command: "Command Group: (\n  [Stop module visu-poc-solace-gateway]\n  [Start module visu-poc-solace-gateway]\n  [Saving visu-poc-solace-gateway to store]\n)"
<6> 2021-12-01 02:20:16.007 +00:00 [INF] - Executing command: "Stop module visu-poc-solace-gateway"
<6> 2021-12-01 02:20:16.008 +00:00 [INF] - Executing command: "Start module visu-poc-solace-gateway"
<6> 2021-12-01 02:20:16.358 +00:00 [INF] - Executing command: "Saving visu-poc-solace-gateway to store"
<6> 2021-12-01 02:30:19.143 +00:00 [INF] - HealthRestartPlanner is clearing restart stats for module 'visu-poc-solace-gateway' as it has been running healthy for 00:10:00.
<6> 2021-12-01 02:30:19.143 +00:00 [INF] - Executing command: "Saving visu-poc-solace-gateway to store"
```

The device twin for the module shows zero restarts:

```
                "visu-poc-solace-gateway": {
                    "exitCode": 0,
                    "statusDescription": "running",
                    "lastStartTimeUtc": "2021-12-01T02:20:16.3551751",
                    "lastExitTimeUtc": "2021-12-01T02:19:12.7350129",
                    "restartCount": 0,
                    "lastRestartTimeUtc": "2021-12-01T02:19:12.7350129",
                    "runtimeStatus": "running",
                    "version": "1.0",
                    "status": "running",
                    "restartPolicy": "always",
                    "imagePullPolicy": "on-create",
                    "type": "docker",
```

While the prometheus metric proofs that the module was restarted:

```
edgeAgent_module_start_total{iothub="<hub>",edge_device="<device>",instance_number="70f768e9-4ea6-4715-b28e-c09b86739ae5",module_name="visu-poc-solace-gateway",module_version="1.0",ms_telemetry="True"} 4
```

This would also explain why with a restart rate of 60 seconds you notice increased `restartCount` values, while I wasn't looking within the 10 minute timeframe after restart - and so always got `0`. Please note that this is only a theory for now.

**Comment by nlcamp** [comment] 2021-12-03 02:38
@alaendle - I think you're right. There's a config parameter in edge-agent called `IntensiveCareTimeInMinutes`, which specifies the interval after which the restart count gets reset. For your use case I'd suggest setting it to a very high number so that it does not reset. Also, you'll probably want to change the `MaxRestartCount` so that edge-agent continues to restart your module after the default of 20 restarts. You can see these parameters in the following appsettings_agent.json file:

https://github.com/Azure/iotedge/blob/release/1.2/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/appsettings_agent.json#L10-L11

You can set these parameters using Edge Agent environment variables in your deployment manifest. Plesae let me know if this resolves the issue.

**Comment by alaendle** [comment] 2021-12-03 06:09
@nlcamp - Yep, many thanks 👍 , this insight indeed resolves my issue (or more my confusion around the topic). Since we both are somehow surprised by the actual behaviour, maybe it is nonetheless a good idea to improve implementation/documentation or rename things to be crystal clear. E.g. I still could question why the `lastRestartTimeUtc`contains a value, while the documentation for `IntensiveCareTimeInMinutes` states "Time span for a module to be running before considered completely healthy (restart time / count cleared)". I also can't say whether the discovery you noted in https://github.com/Azure/iotedge/issues/5732#issuecomment-971967697 is still an issue. So since my concrete issue is resolved, feel free to close this issue, or leave it open and use it to resolve the mentioned imperfections - if you have the feeling that anything should be done.

**Comment by nlcamp** [comment] 2021-12-03 15:01
@alaendle - Great! Glad that helped. Regarding https://github.com/Azure/iotedge/issues/5732#issuecomment-971967697, I no longer believe that is a bug because in the case of a `docker rm` the container is completely removed rather than just being stopped like in your scenario. When the container is removed, edge-agent does a `create` by design, so all stats are re-initialized.

Regarding `lastRestartTImeUtc` and `lastRestartCount` being out of sync with each other, I _do_ believe that should be fixed and will spend a bit of time looking into it and/or filing a new bug ticket on our internal backlog.  I'll keep this issue open until I've had a chance to look into this last item.

**Comment by nlcamp** [comment] 2021-12-10 22:05
@aleandle - I filed an internal bug ticket to address the need to clear `lastRestartCountUtc` when `lastRestartCount` gets reset. I'll circle back to this ticket when we have a fix planned for release, but I'll close this issue since your main concern has been addressed. Thanks again for reporting these bugs.

**Closed by nlcamp** 2021-12-10 22:06 UTC
Labels: bug, area:diagnostics, iotedge, customer-reported, 1.2
