### ISSUE TITLE
when API Proxy connects to edgeHub in Nested child it is throwing an SSL error

### ISSUE THREAD

**Issue by niharsamineni** [Azure/iotedge#6405] opened 2022-06-02 21:07 UTC
## Expected Behavior
when API proxy is connected to edge Hub, It should be running with out errors

## Current Behavior
Created Nested edge with a parent and two children.
Child Device is throwing exception on edge hub with error as below
 2022-06-02 20:48:39.330 +00:00 [WRN] - TLS handshake failed., System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---, 51e8ea65

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1. create nested edge devices with edgeAgent,edgeHub,IoTEdgeApiProxy modules in both parent and child.
2. Install/copy certificates that are created.
3. when IoTEdgeApiProxy connects with edgeAgent in Child device, it throws errors as provided above.
4. when we stop IotEdgeAPIProxy module errors are not thrown on IOTHub but when added back it throws same error message again

### Output of `iotedge check`
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK
‼ host time is close to reference time - Warning
    Could not query NTP server
        caused by: could not resolve NTP pool hostname: failed to lookup address information: Temporary failure in name resolution
        caused by: failed to lookup address information: Temporary failure in name resolution
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct parent_hostname - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
√ production readiness: logs policy - OK
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
‼ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - Warning
    The proxy setting for IoT Edge Agent "", IoT Edge Daemon "string", IoT Identity Daemon "", and Moby "" may need to be identical.

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
30 check(s) succeeded.
5 check(s) raised warnings.

<details>
<summary>Click here</summary>

```

<Paste here between the triple backticks>

```
</details>

### Device Information
* Host OS [e.g. Ubuntu 18.04, Windows Server IoT 2019]: Ubuntu 18.04 
* Architecture [e.g. amd64, arm32, arm64]: 
* Container OS [e.g. Linux containers, Windows containers]: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: 1.2.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.4
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.4
* Docker/Moby [run `docker version`]: 20.10.16+azure-3
* azureiotedge-api-proxy : 1.1.2

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>aziot-edged logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-agent logs</summary>

```

<Paste here between the triple backticks>

```
</details>

<details>
<summary>edge-hub logs</summary>
<4> 2022-06-02 21:06:26.544 +00:00 [WRN] - TLS handshake failed., System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---, 35b19e48

<summary>IoTEdgeApiProxy</summary>
[2022-06-02T21:11:33Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:12:03Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:12:34Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:13:04Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:13:35Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:14:05Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:14:36Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:15:06Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:15:37Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T21:16:07Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)

<Paste here between the triple backticks>

```
</details>

## Additional Information
[support_bundle.zip](https://github.com/Azure/iotedge/files/8827835/support_bundle.zip)

Please provide any additional information that may be helpful in understanding the issue.

**Comment by ksaye** [comment] 2022-06-02 22:41
FYI, my understanding was that this was setup and working and IoTEdgeAPIProxy was able to authenticate to edgeHub.

@niharsamineni  then had to change the edge_ca certificates used.  EdgeHub, EdgeAgent and aziot-edged are working and able to communicate with the parent.  He is able to pull images from the parent, indicating that trust bundle is correct.

We have also stopped aziot-edged, delete the files in /var/lib/aziot/certd/certs and /var/lib/aziot/keyd/keys and restarted.

**Comment by huguesBouvier** [comment] 2022-06-03 04:05
Some clarification:
API proxy works this way:
child edge hub -> Parent API proxy -> Parent edge hub.
If you just stop the API proxy module it just cannot work. It is possible to work without API proxy but not without some other re-configuration.

An interesting piece: The iotedge check is able to connect to the API proxy correctly but it seems that you child edgeHub cannot.

IoTEdge has a policy of not deleting the modules by default. What I think is happening is that the certificate got changed but the modules where not restarted. The tell-tale sign is that iotedge check on the child is successful. Since it doesn't work with edgeHub, edgeHub is probably running with the old certificate.

So my bet would be on the edgehub child but I think it would be better to clean everything if you can.

Start with the parent:
sudo iotedge system stop
sudo docker ps -a
sudo docker rm "name of all the image that are there"
sudo iotedge system restart

Then do the same on the child. (I think the issue is here because iotedge check works).

**Comment by ksaye** [comment] 2022-06-03 16:10
@huguesBouvier perhaps @niharsamineni was not clear.

the Parent is fine and when we try to start the proxy on the child (consider leaf devices may need it) Proxy on the child can not talk to edgeHub on the child.

Looking at aziot-keyd log, I see:

``
Jun 02 14:58:36 naughty-jennings aziot-keyd[3097]: 2022-06-02T19:58:36Z [INFO] - <-- GET /keypair/device-id?api-version=2020-09-01 {"host": "keyd.sock"}
Jun 02 14:58:36 naughty-jennings aziot-keyd[3097]: 2022-06-02T19:58:36Z [ERR!] - error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
Jun 02 14:58:36 naughty-jennings aziot-keyd[3097]: 2022-06-02T19:58:36Z [ERR!] - !!! internal error
Jun 02 14:58:36 naughty-jennings aziot-keyd[3097]: 2022-06-02T19:58:36Z [ERR!] - !!! caused by: could not load key pair
Jun 02 14:58:36 naughty-jennings aziot-keyd[3097]: 2022-06-02T19:58:36Z [ERR!] - !!! caused by: could not load key pair: AZIOT_KEYS_RC_ERR_EXTERNAL
``

Also Proxy on the child show the errors below, which seem to match what is in edgeHub on the child: 

``
[2022-06-02T20:25:15Z INFO  api_proxy_module] Starting/Restarting API-Proxy
[2022-06-02T20:25:15Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T20:25:18Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
[2022-06-02T20:25:22Z WARN  mqtt3::client::connect] could not connect to server: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)
``

**Comment by ksaye** [comment] 2022-06-03 21:05
So I agree that API Proxy is not used by the child.  For this case, consider the APIProxy just another Module.  If we had TempSensor in the registry, we would have deployed that to show it.

What we are seeing from the logs of APIProxy is that it cannot connect to edgeHub on the child, getting an MQTT error stating "self signed cert".  I assume that is when Proxy tries to get the twin, as it does make a connection (which surprises me because all items are set in Environment Variables).

We also see the same type of error in edgeHub on the child.

If you would feel better if we deploy TempSensor to reproduce the error, happy to comply.

**Comment by huguesBouvier** [comment] 2022-06-06 16:24
Then what's most likely happening is that the certificates on the child are not set up.
If you want to set an API proxy on the child you need to set the certificate like you would on the parent.

You need to set up edgeCa and root CA.

**Comment by ksaye** [comment] 2022-06-07 21:35
Thanks for the suggestion @huguesBouvier.  We verified the settings in /etc/aziot/config.toml and then emptied out the following directories:

- /var/lib/aziot/certd/certs
- /var/lib/aziot/keyd/keys
- /var/lib/aziot/identityd
- /var/lib/aziot/identityd/modules
- /var/lib/aziot/edged/cache
- /etc/aziot/tpmd
- /etc/aziot/edged/config.d
- /etc/aziot/identityd/config.d
- /etc/aziot/keyd/config.d
- /etc/aziot/tpmd/config.d

deleted all the docker containers by running:
``
sudo docker stop $(docker ps -a -q) && sudo docker rm $(docker ps -a -q)
``
ran 
``
iotedge config apply
``

and it all started working.  I think there was something incorrect probably in the /var/lib/aziot/identityd/modules directory, but could not find it 100%.

@niharsamineni  will close this ticket.

**Comment by niharsamineni** [comment] 2022-06-07 21:39
Issue is now resolved on my devices. as per ksaye comments. Can be closed

**Closed** 2022-06-07 21:39 UTC
Labels: iotedge, customer-reported
