### ISSUE TITLE
Container runtime error - ApiError

### ISSUE THREAD

**Issue by PNWang** [Azure/iotedge#385] opened 2018-10-02 09:47 UTC
## Expected Behavior
After `start-service iotedge`, iotedge service should be started and got the edgeAgent. 

## Current Behavior
Failed to get edgeAgent becouse of the ApiError.

## Steps to Reproduce
1. Begin from a new Win10 Enterprise
2. Install Docker for Windows and use Windows container
3. Install iotedge
4. Start iotedge

### Device (Host) Operating System
Windows 10 Enterprise Build 17134 Release 1804

### Architecture
amd64

### Container Operating System
Windows container

#### iotedged
iotedge 1.0.2 ( f6fcdb2e24ac2af977e748e9f2b8a37245b92738 )

#### Edge Agent
Failed to get edgeAgent

#### Edge Hub
Failed to get edgeHub

#### Docker
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:36:40 2018
  OS/Arch:          windows/amd64
  Experimental:     false

## Logs
```
10/2/2018 2:11:53 AM info: iotedged::windows -- Starting iotedged service.
10/2/2018 2:11:53 AM info: iotedged -- Using runtime network id nat
10/2/2018 2:11:53 AM info: iotedged -- Initializing the module runtime...
10/2/2018 2:11:53 AM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
10/2/2018 2:11:53 AM info: iotedged::app -- Version - 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)
10/2/2018 2:11:53 AM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
10/2/2018 2:11:53 AM info: iotedged -- Finished initializing the module runtime.
10/2/2018 2:11:53 AM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
10/2/2018 2:11:53 AM info: iotedged -- Finished configuring certificates.
10/2/2018 2:11:53 AM info: iotedged -- Initializing hsm...
10/2/2018 2:11:53 AM info: iotedged -- Configuring certificates...
10/2/2018 2:11:53 AM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
10/2/2018 2:11:53 AM info: iotedged -- Detecting if configuration file has changed...
10/2/2018 2:11:53 AM info: iotedged -- Finished initializing hsm.
10/2/2018 2:11:53 AM info: iotedged -- Removing all modules...
10/2/2018 2:11:53 AM info: iotedged -- Change to configuration file detected.
10/2/2018 2:11:53 AM info: iotedged -- Finished removing modules.
10/2/2018 2:11:54 AM info: iotedged -- Starting management API...
10/2/2018 2:11:54 AM info: iotedged -- Listening on http://xxx:15580/ with 1 thread for management API.
10/2/2018 2:11:54 AM info: iotedged -- Starting workload API...
10/2/2018 2:11:54 AM info: iotedged -- Provisioning edge device...
10/2/2018 2:11:54 AM info: provisioning::provisioning -- Manually provisioning device "xxx" in hub "xxx"
10/2/2018 2:11:54 AM info: iotedged -- Finished provisioning edge device.
10/2/2018 2:11:54 AM info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
10/2/2018 2:11:54 AM info: iotedged -- Listening on http://xxx:15581/ with 1 thread for workload API.
10/2/2018 2:11:54 AM info: edgelet_core::watchdog -- Checking edge runtime status
10/2/2018 2:11:54 AM info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
10/2/2018 2:11:55 AM info: edgelet_core::watchdog -- Updating identity for module $edgeAgent
10/2/2018 2:11:56 AM warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
10/2/2018 2:11:56 AM warn: edgelet_utils::logging --    caused by: Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("Failed to unmarshall layerchain json - 
                     invalid character \'\\x00\' looking for beginning of value")})) })
10/2/2018 2:11:56 AM warn: edgelet_utils::logging -- A module runtime error occurred.
10/2/2018 2:12:54 AM info: edgelet_core::watchdog -- Checking edge runtime status
10/2/2018 2:12:54 AM info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
10/2/2018 2:12:54 AM info: edgelet_core::watchdog -- Updating identity for module $edgeAgent
10/2/2018 2:13:03 AM warn: edgelet_utils::logging --    caused by: Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("Failed to unmarshall layerchain json - 
                     invalid character \'\\x00\' looking for beginning of value")})) })
10/2/2018 2:13:03 AM warn: edgelet_utils::logging -- A module runtime error occurred.
10/2/2018 2:13:03 AM warn: edgelet_core::watchdog -- Error in watchdog when checking for edge runtime status:
10/2/2018 2:13:54 AM info: edgelet_core::watchdog -- Checking edge runtime status
10/2/2018 2:13:54 AM info: edgelet_core::watchdog -- Creating and starting edge runtime module edgeAgent
10/2/2018 2:13:54 AM info: edgelet_core::watchdog -- Updating identity for module $edgeAgent
10/2/2018 2:13:56 AM warn: edgelet_utils::logging --    caused by: Container runtime error - ApiError(ApiError { code: InternalServerError, content: Some(Object({"message": String("Failed to unmarshall layerchain json - 
                     invalid character \'\\x00\' looking for beginning of value")})) })
```

## Additional Information
The ApiError is thrown continually.  Creating another new iot hub did not solve this issue.

**Comment by myagley** [comment] 2018-10-02 15:55
I just verified IoT Edge on this release of Windows and Docker. It looks like there may be something wrong with the docker installation. Is it possible to run `docker ps` and see what the response is?

**Comment by PNWang** [comment] 2018-10-03 02:49
Hello, `docker ps` lists nothing.
I re-prepared my vm then the iotedge log became these:
```
10/3/2018 10:32:12 AM info: iotedged::windows -- Starting iotedged service.
10/3/2018 10:32:12 AM info: iotedged -- Using runtime network id nat
10/3/2018 10:32:12 AM info: iotedged -- Initializing the module runtime...
10/3/2018 10:32:12 AM info: iotedged::app -- Starting Azure IoT Edge Security Daemon
10/3/2018 10:32:12 AM info: iotedged::app -- Version - 1.0.2 (f6fcdb2e24ac2af977e748e9f2b8a37245b92738)
10/3/2018 10:32:12 AM info: iotedged::app -- Using config file: C:\ProgramData\iotedge\config.yaml
10/3/2018 10:32:12 AM info: iotedged -- Configuring certificates...
10/3/2018 10:32:12 AM info: iotedged -- Transparent gateway certificates not found, operating in quick start mode...
10/3/2018 10:32:12 AM info: iotedged -- Finished initializing the module runtime.
10/3/2018 10:32:12 AM info: iotedged -- Configuring C:\ProgramData\iotedge as the home directory.
10/3/2018 10:32:12 AM info: iotedged -- Initializing hsm...
10/3/2018 10:32:12 AM info: iotedged -- Finished configuring certificates.
10/3/2018 10:32:12 AM info: iotedged -- No change to configuration file detected.
10/3/2018 10:32:12 AM info: iotedged -- Detecting if configuration file has changed...
10/3/2018 10:32:12 AM info: iotedged -- Finished initializing hsm.
10/3/2018 10:32:12 AM info: iotedged -- Starting workload API...
10/3/2018 10:32:12 AM info: iotedged -- Listening on http://xxx:15580/ with 1 thread for management API.
10/3/2018 10:32:12 AM info: edgelet_core::watchdog -- Starting watchdog with 60 second frequency...
10/3/2018 10:32:12 AM info: iotedged -- Listening on http://xxx:15581/ with 1 thread for workload API.
10/3/2018 10:32:12 AM info: iotedged -- Starting management API...
10/3/2018 10:32:12 AM info: iotedged -- Provisioning edge device...
10/3/2018 10:32:12 AM info: iotedged -- Obtaining workload CA succeeded.
10/3/2018 10:32:12 AM info: iotedged -- Finished provisioning edge device.
10/3/2018 10:32:12 AM info: provisioning::provisioning -- Manually provisioning device "xxx" in hub "xxx"
10/3/2018 10:32:12 AM info: edgelet_core::watchdog -- Checking edge runtime status
10/3/2018 10:32:12 AM info: edgelet_core::watchdog -- Edge runtime status is stopped, starting module now...
10/3/2018 10:32:30 AM info: edgelet_http::logging -- [mgmt] - - - [2018-10-03 02:32:30.213155700 UTC] "GET /systeminfo?api-version=2018-06-28 HTTP/1.1" 200 OK 105 "-" "-" pid(any)
10/3/2018 10:32:30 AM info: edgelet_http::logging -- [work] - - - [2018-10-03 02:32:30.300477900 UTC] "POST /modules/%24edgeAgent/genid/636741281470638323/sign?api-version=2018-06-28 HTTP/1.1" 200 OK 57 "-" "-" pid(any)
10/3/2018 10:32:30 AM info: edgelet_http::logging -- [mgmt] - - - [2018-10-03 02:32:30.410897500 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(any)
10/3/2018 10:32:36 AM info: edgelet_http::logging -- [mgmt] - - - [2018-10-03 02:32:36.696742300 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(any)
10/3/2018 10:32:41 AM info: edgelet_http::logging -- [mgmt] - - - [2018-10-03 02:32:41.819461900 UTC] "GET /modules?api-version=2018-06-28 HTTP/1.1" 200 OK 449 "-" "-" pid(any)
```

It stop here for much time and slowed down vm performance largely.
I tried to shutdown vm and gave it one more cpu core.
Then, everything is alright now.

Is there any hardware spec requirement for Win10 or iotedge?

**Comment by myagley** [comment] 2018-10-03 15:15
How large is the VM that you are running on?

We found and fixed a potential performance issue with the `list` command here: https://github.com/Azure/iotedge/pull/376, although I don't think you would hit it in this case.

**Comment by myagley** [comment] 2019-02-01 19:00
Is this still reproducing?

**Comment by PNWang** [comment] 2019-02-11 01:37
This problem has not happened for these months till now, maybe it is just a single case.
Thank you for recheck this issue.

**Comment by myagley** [comment] 2019-02-14 16:15
I'm going to close this for now. Feel free to reopen.

**Closed by myagley** 2019-02-14 16:15 UTC
