### ISSUE TITLE
unauthorized: authentication required when using ACR

### ISSUE THREAD

**Issue by chris-to-pher** [Azure/iotedge#368] opened 2018-09-27 20:25 UTC
I am not able to run my C#-based IoT Edge Module on my Azure Ubuntu 18.04 VM because I see an `InternalServiceError`.

## Expected Behavior
My C# IoT Edge Module should run on my Ubuntu VM

## Current Behavior
When I run `sudo journalctl -u iotedge` I get this error message:

`InternalServerError, content: Some(Object({"message": String("Get https://xyz.azurecr.io/v2/entrymodule/manifests/0.0.1-amd64: unauthorized: authentication required")})) })
`

## Steps to Reproduce
1. Configure an Ubuntu 18.04 Azure VM as described [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux)
2. Push an Azure IoT C# Module to the device using Visual Studio Code or Visual Studio 2017 as described [here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-develop-csharp-module) to ACR
3. Deploy the module to the Edge device

### Device (Host) Operating System
Ubuntu 16.04

### Architecture
x86_64

### Container Operating System
Linux Container

#### iotedged
iotedge 1.0.2

#### Edge Agent
1.0

#### Edge Hub
1.0

#### Docker
Client:
 Version:      18.06.0-dev
 API version:  1.37
 Go version:   go1.10.2
 Git commit:   daf021fe
 Built:        Mon Jun 25 21:07:53 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      dev
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   09f5e9d
  Built:        Wed Sep 19 16:55:45 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by chris-to-pher** [comment] 2018-09-28 13:56
@mrohera Thank you very much, that fixed it! The step should be added to [this ](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-csharp-module#build-and-push-images) documentation.

**Comment by mrohera** [comment] 2018-09-28 17:55
@shizn I want to inquire if this is expected behavior that the ACR creds do not make it to the deployment in IoT Hub. If this is the case, we should update the [documentation](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-csharp-module#build-and-push-images) to call this step out.

**Comment by kgremban** [comment] 2018-10-01 18:49
@mrohera I haven't tested the Visual Studio steps myself, but it looks like you enter your registry credentials into the deployment manifest in step 3 of the **Build and push images** section. You shouldn't have to use the portal to add your registry credentials. 


@chris-to-pher could you compare the deployment template from the successful deployment in the portal (in the review and submit step) to the deployment template that you manually updated in step 3 of the **Build and push images** section? If there's a formatting difference around the registry credentials section, then we should update the documentation to make it more clear how to manually add your creds.

**Comment by mrohera** [comment] 2018-10-04 17:41
@shizn is there something you can add to this conversation?

**Comment by chris-to-pher** [comment] 2018-10-05 06:43
> @mrohera I haven't tested the Visual Studio steps myself, but it looks like you enter your registry credentials into the deployment manifest in step 3 of the **Build and push images** section. You shouldn't have to use the portal to add your registry credentials.
> 
> @chris-to-pher could you compare the deployment template from the successful deployment in the portal (in the review and submit step) to the deployment template that you manually updated in step 3 of the **Build and push images** section? If there's a formatting difference around the registry credentials section, then we should update the documentation to make it more clear how to manually add your creds.

I updated the local deployment template file in VS but it was nevern shown in the Azure Portal so I had to enter the ACR creds manually as @mrohera suggested.

**Comment by erich-wang** [comment] 2018-10-15 09:47
@chris-to-pher which deployment json file did you choose to create deployment? I guess you choose the wrong file: deployment_for_local_debug.json. You should choose $(SolutionDir)\config\deployment.*.json, e.g. deployment.amd64.json. We'll update the document soon to make instruction clearer, thank you.

**Comment by myagley** [comment] 2018-11-16 16:46
Is there any update here?

**Comment by shizn** [comment] 2018-11-20 00:31
@myagley We made some updates in the tutorial. Have you got the same issue or?

**Comment by myagley** [comment] 2018-11-28 20:59
Can we close this issue if the tutorials have been updated?

**Closed** 2018-12-19 00:35 UTC
