### ISSUE TITLE
Kepware to IoT edge Connectivity

### ISSUE THREAD

**Issue by debinaik** [Azure/iotedge#2732] opened 2020-03-24 06:26 UTC
Hi Team,

Please find the context below ...

**Context**: Kepware to IoT Edge connectivity for  **Dev /Test Environment**

Details
--------
I was trying to establish Kepware to IoT edge connectvity by following link 

https://docs.microsoft.com/en-us/samples/azure-samples/iot-hub-how-to-kepware-edge/azure-iot-edge-connect-ptc/    . But Kepserver is unable to establish SSL connectivity wih IoT edge and results following error.

**Kepware console Error**

"Error           KEPServerEX\Runtime      MQTT agent 'Kep-IoTEdge-Agent' failed to connect - reason: 'unable to find valid certification path to requested target'."   

Note: "azure-iot-test-only.root.ca.cert.pem" is already imported to certificate store "mmc" at kepware box.

While investigating, It looks the root cause of failure  is associated with the certificate "azure-iot-test-only.root.ca.cert.pem" . Please follow below issues section for detail analysis.
 
**Issues**:
1. As per the instruction above I have created test certificate "azure-iot-test-only.root.ca.cert.pem" through the script (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates) provided by MSFT. But when I test this cert through openssl tool it reflects following error ..

**Error**

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\sa> openssl s_client -connect 127.0.0.1:8883 -CAfile C:/tmp/wkdir/certs/azure-iot-test-only.root.ca.cert.pem
Loading 'screen' into random state - done
CONNECTED(000001B0)
8136:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:./ssl/s23_lib.c:188:
PS C:\Users\sa>

Because of this above error ,kepserver is unable to negotiate SSL connectivity with IoT edge. Could you please confirm your end the instruction provide in (https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates) is still valid ? Because while testing through *openssl* tool locally , it fails...

**Queries  to be answered**:
1. Since I am establishing Kepware-->IoT edge connectivity in test environment , do I still required to generate  device_ca_cert and device_ca_pk and configure the same in config.yaml -> certificate section ?

2. How do I configure "azure-iot-test-only.root.ca.cert.pem" in IoT edge box ? Do I place it in "mmc" certificate store of IoT edge windows box or it has to be configured only in c:/programdata/iotedge/config.yaml -> certificate section ?

Request your quick response.

Thanks

**Comment by debinaik** [comment] 2020-03-25 09:12
Thanks Anca for above information. Above information in point 1) and 2) are already incorporated. But the core issue i.e. ssl handshaking still fails with openssl tool 

 While investigating I found the test certificate **azure-iot-test-only.root.ca.cert.pem** generated by the script provided by azure _https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates_ looks to be not generating correct certificate. You can follow above link and create a test certificate and test it locally in your PC by openssl command  [ _openssl s_client -connect 127.0.0.1:8883 -CAfile $CERTDIR/certs/azure-iot-test-only.root.ca.cert.pem_ ]. Definitely you will encounter error.

**Comment by ancaantochi** [comment] 2020-03-25 20:36
Hi @debinaik,

Did you use the IP when the certificate was generated? If you used the hostname you have to use it when connecting to edgeHub.

I searched the error that you encounter and I found other people complaining about this issue caused by an older version of openssl. Which version are you using?

I will also try reproduce it.

**Comment by debinaik** [comment] 2020-03-26 15:55
Hi Anca,

1. While generating the certificate , it didn't ask for the IP or hostname . I just entered this command in poweshell console  **New-CACertsCertChain rsa**  as per link _https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates#windows_

2. Today I have installed the latest version of openssl i.e**. OpenSSL 1.0.2j-fips**and retested but result is same as before. (I.e. Openssl is not validating certificate successfuly).

Is it fine for you to join a quick Zoom conference ? If yes, request you to share your free time slot, so that I can send you the invite.

**Comment by ancaantochi** [comment] 2020-03-27 16:22
@debinaik,

By default the scripts use the hostname of the machine to set the CN for edgeHub certificate. Please check in config.yaml what is the hostname value (on Windows config.yaml is at C:/ProgramData/iotedge)

I was not able to reproduce the issue, I set up iotedge with certs generated by the script and run openssl s_client command and it worked. Can you please provide edgeHub and iotedged logs? Which version of edge runtime and edgehub image are you using?

Please try: `openssl s_client -connect <hostname>:8883 -CAfile C:/tmp/wkdir/certs/azure-iot-test-only.root.ca.cert.pem -showcerts` and let me know what are the results.

Unfortunately I am not available for a  Zoom conference at this time, let's see if the logs show anything that could help identify the issue.

**Comment by debinaik** [comment] 2020-03-28 10:45
[SSLIssuesItems.zip](https://github.com/Azure/iotedge/files/4396960/SSLIssuesItems.zip)

Hi Acma,

1. Hostname of machine and at C:/ProgramData/iotedge is same i.e. iotAzureChanno
2. EdgeAgent version is  - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
3. EdgeHub Version is : Version - 1.0.9.29532150 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
4. iotedge version : iotedge 1.0.9 (1f7cf6a21dfa365c8f21475553c544f4df02dd44)
5. Openssl log is included in attachment. (With Hostname and without Hostname)

Please find the attachment. which includes logs ,certificates and config.yaml files.

Please let me know, if you need any info from me.

Thanks

**Comment by ancaantochi** [comment] 2020-03-31 03:04
@debinaik,

Please rotate your sas keys for the device as they appear in plain text the config.yaml.

From the openssl command with the IP I see the error is: `verify error:num=20:unable to get local issuer certificate`  This is because the certificates are not configured correctly and the runtime falls back to the generated certs. In config.yaml you need to provide device_ca_cert and device_ca_pk
After you configured please run: `iotedge check` and provide the output.

**Comment by debinaik** [comment] 2020-03-31 06:53
[logs_cert_config.zip](https://github.com/Azure/iotedge/files/4407214/logs_cert_config.zip)

Hi Acna,

I have generated the device_ca_cert and device_ca_pk and configured in config.yaml file as per the instruction provided in _https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-test-certificates#windows-1_ . But it still reflect the error in iotedge check command.

**iotedge check Error**

_× config.yaml has correct URIs for daemon mgmt endpoint - Error
    Error: could not execute list-modules request: an error occurred trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)
        caused by: docker returned exit code: 1, stderr = Error: could not execute list-modules request: an error occurred trying to connect: No connection could be made because the target machine actively refused it. (os error 10061)_

**Get-Iotedge log Error**
3/31/2020 6:24:18 AM error: iotedged::windows -- Error while running service. Quitting.                                                                       
3/31/2020 6:24:18 AM error: edgelet_utils::logging -- 	caused by: HSM Init failure: 48                                                                        
3/31/2020 6:24:18 AM error: edgelet_utils::logging -- 	caused by: HSM failure                                                                                 
3/31/2020 6:24:18 AM error: edgelet_utils::logging -- The daemon could not start up successfully: Could not initialize HSM  

Please find the attached logs, certs and config.yaml file for details.

Thanks

**Comment by ancaantochi** [comment] 2020-04-01 00:32
@debinaik,

There is a configuration issue in the config.yaml, the device_ca_cert has to be the path to full chain (iot-edge-device-MyEdgeDeviceCA-full-chain.cert.pem)

**Comment by debinaik** [comment] 2020-04-02 16:04
Thanks Anca. It's working now after configuring iot-edge-device-MyEdgeDeviceCA-full-chain.cert.pem in config.yaml file. End-to-end data transmission  i.e. kepware----->iotedge---->IoThub is successful. 

Now I am keeping the all the components (i.e. kepware----->iotedge---->IoThub ) up an running for few days for stability check. Update you further,if I get any discrepancies.

Thanks again.

**Comment by ancaantochi** [comment] 2020-04-02 17:38
Thanks for the update! I will close this issue, please open an new issue if anything fails during the long run.

**Closed by ancaantochi** 2020-04-02 17:38 UTC
Labels: needinfo
