### ISSUE TITLE
Use DPS with X.509 without providing identity_pk as key file

### ISSUE THREAD

**Issue by mma-mm** [Azure/iotedge#1740] opened 2019-09-23 10:42 UTC
Hi,

i'd like to use iotedge with dps with X.509 certificates. Sadly , iotedge only seems to support a file path as configuration option for the identitiy certificates private key. In our scenario, the private key must be stored inside a HSM. How can is use DPS with X.509-Certificates such that the iotedge security daemon uses the API of the HSM instead of filesystem access to the private key?

Thank you

## Expected Behavior

There is a way to configure the iotedge daemon to use a hsm which contains the device identity private key.

## Current Behavior

config.yaml requests a private key file for dps with x.509 certificates

## Context (Environment)
production environment

### Device (Host) Operating System

any

### Architecture

any

### Container Operating System

Linux containers

**Comment by myagley** [comment] 2019-09-23 15:10
Duplicate of #1728

**Closed by myagley** 2019-09-23 15:10 UTC
