### ISSUE TITLE
Direct method UploadModuleLogs doesn't upload logs if ContentType is json

### ISSUE THREAD

**Issue by giovannimele** [Azure/iotedge#6464] opened 2022-06-22 10:01 UTC
## Expected Behavior
In IOT hub UI, or in function code triggered periodically every 15min, we call the edgeAgent's **UploadModuleLogs** direct method to retrieve error and warning logs to insert them in a log-analytics db.

Here is an example of a query payload we do:

```
{
	"SchemaVersion": "1.0",
	"SasUrl": "https://xxxxx.blob.core.windows.net/yyyyyyyyyyy?skoid=aaaaccddd-7caf-0000-0000-abababababababa=11111111-1111-1111-1111-bababaabababa&skt=2022-06-22T07%3A01%3A21Z&ske=2022-06-22T19%3A01%3A21Z&sks=b&skv=2020-10-02&sv=2020-08-04&st=2022-06-22T07%3A01%3A21Z&se=2022-06-22T19%3A01%3A21Z&sr=c&sp=cw&sig=abababababababababa",
	"Items": [
		{
			"Id": "^(?!\\bedgeAgent|edgeHub\\b)",
			"Filter": {
				"Since": "0d, 0m, 0 days, 0 hours 15 minutes",
				"Regex": ".*\\b(WRN?|ERR?|CRIT?|FTL?)\\b.*"
			}
		}
	],
	"Encoding": "gzip",
	"ContentType": "json"
}
```

On the Azure backend, a function is triggered when the file is written in the blob container. We unzip and extract the json payload to insert it in log analytics

## Current Behavior

- If we call UploadModuleLogs with ContentType = json, nothing is created, even if there are error logs. No errors are reported on the edge agent.

- If we call UploadModuleLogs with ContentType = text, a file is uploaded on the blob container

## Steps to Reproduce
Provide a detailed set of steps to reproduce the bug.
1.generate a SAS token on a blob container
2.Have module generating logs on a Edge device
3.On the IOT Hub EdgeAgent direct method WEB UI, retrieve all logs using ContentType = json and Encoding = gzip, with the correct SAS token
4.Wait for the gzip files on the container

## Context (Environment)
N/A

### Output of `iotedge check`

<details>
<summary>Click here</summary>

```
Configuration checks (aziot-identity-service)
---------------------------------------------
√ keyd configuration is well-formed - OK
√ certd configuration is well-formed - OK
√ tpmd configuration is well-formed - OK
√ identityd configuration is well-formed - OK
√ daemon configurations up-to-date with config.toml - OK
√ identityd config toml file specifies a valid hostname - OK

× aziot-identity-service package is up-to-date - Error
    could not query https://aka.ms/latest-aziot-identity-service for latest available version
‼ host time is close to reference time - Warning
    Could not query NTP server
√ preloaded certificates are valid - OK
√ keyd is running - OK
√ certd is running - OK
√ identityd is running - OK
√ read all preloaded certificates from the Certificates Service - OK
√ read all preloaded key pairs from the Keys Service - OK
√ ensure all preloaded certificates match preloaded private keys with the same ID - OK

Connectivity checks (aziot-identity-service)
--------------------------------------------
√ host can connect to and perform TLS handshake with iothub AMQP port - OK
√ host can connect to and perform TLS handshake with iothub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with iothub MQTT port - OK

Configuration checks
--------------------
√ aziot-edged configuration is well-formed - OK
√ configuration up-to-date with config.toml - OK
√ container engine is installed and functional - OK
√ configuration has correct URIs for daemon mgmt endpoint - OK
‼ aziot-edge package is up-to-date - Warning
    Error while fetching latest versions of edge components: could not send HTTP request
√ container time is close to host time - OK
‼ DNS server - Warning
    Container engine is not configured with DNS server setting, which may impact connectivity to IoT Hub.
    Please see https://aka.ms/iotedge-prod-checklist-dns for best practices.
    You can ignore this warning if you are setting DNS server per module in the Edge deployment.
‼ production readiness: logs policy - Warning
    Container engine is not configured to rotate module logs which may cause it run out of disk space.
    Please see https://aka.ms/iotedge-prod-checklist-logs for best practices.
    You can ignore this warning if you are setting log policy per module in the Edge deployment.
‼ production readiness: Edge Agent's storage directory is persisted on the host filesystem - Warning
    The edgeAgent module is not configured to persist its /tmp/edgeAgent directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
‼ production readiness: Edge Hub's storage directory is persisted on the host filesystem - Warning
    The edgeHub module is not configured to persist its /tmp/edgeHub directory on the host filesystem.
    Data might be lost if the module is deleted or updated.
    Please see https://aka.ms/iotedge-storage-host for best practices.
√ Agent image is valid and can be pulled from upstream - OK
√ proxy settings are consistent in aziot-edged, aziot-identityd, moby daemon and config.toml - OK

Connectivity checks
-------------------
√ container on the default network can connect to upstream  AMQP port - OK
√ container on the default network can connect to upstream HTTPS / WebSockets port - OK
√ container on the default network can connect to upstream MQTT port - OK
√ container on the IoT Edge module network can connect to upstream AMQP port - OK
√ container on the IoT Edge module network can connect to upstream HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to upstream MQTT port - OK
29 check(s) succeeded.
6 check(s) raised warnings. Re-run with --verbose for more details.
1 check(s) raised errors. Re-run with --verbose for more details.
```
</details>

### Device Information
* Host OS : Ubuntu 18.04
* Architecture: amd64
* Container OS: Linux containers

### Runtime Versions
* aziot-edged [run `iotedge version`]: iotedge 1.2.10
* Edge Agent [image tag (e.g. 1.0.0)]: 1.2.9-linux-amd64
* Edge Hub [image tag (e.g. 1.0.0)]: 1.2.9-linux-amd64
* Docker/Moby [run `docker version`]: 20.10.17+azure-1

Note: when using Windows containers on Windows, run `docker -H npipe:////./pipe/iotedge_moby_engine version` instead

## Logs

<details>
<summary>edge-agent logs with contentType = json</summary>

```
<6> 2022-06-22 07:18:21.824 +00:00 [INF] - Received direct method call - UploadModuleLogs
<6> 2022-06-22 07:18:21.824 +00:00 [INF] - Received request UploadModuleLogs with payload
<6> 2022-06-22 07:18:21.825 +00:00 [INF] - Processing request to upload logs for {"schemaVersion":"1.0","items":{"id":"^(?!\\bedgeAgent|edgeHub\\b)","filter":{"tail":null,"since":"0d, 0m, 0 days, 0 hours 15 minutes","until":null,"loglevel":null,"regex":".*\\b(WRN?|ERR?|CRIT?|FTL?)\\b.*"},"encoding":1,"contentType":0}
<6> 2022-06-22 07:18:21.865 +00:00 [INF] - Successfully handled request UploadModuleLogs
<6> 2022-06-22 07:18:21.866 +00:00 [INF] - Initiating streaming logs for opcuaPublisher
<6> 2022-06-22 07:18:21.872 +00:00 [INF] - Initiating streaming logs for edgeMonitoring
<6> 2022-06-22 07:18:21.874 +00:00 [INF] - Initiating streaming logs for recordPublisher
<6> 2022-06-22 07:18:21.878 +00:00 [INF] - Initiating streaming logs for cubePublisher
<6> 2022-06-22 07:18:21.878 +00:00 [INF] - Initiating streaming logs for edgeStorage
<6> 2022-06-22 07:18:21.880 +00:00 [INF] - Initiating streaming logs for machineEventPublisher
<6> 2022-06-22 07:18:21.880 +00:00 [INF] - Initiating streaming logs for edgePublisher
<6> 2022-06-22 07:18:21.882 +00:00 [INF] - Initiating streaming logs for edgeBlob
<6> 2022-06-22 07:18:21.884 +00:00 [INF] - Initiating streaming logs for fileTransfer
<6> 2022-06-22 07:18:21.885 +00:00 [INF] - Initiating streaming logs for opcuaAdapter
<6> 2022-06-22 07:18:21.895 +00:00 [INF] - Initiating streaming logs for notificationPublisher
<6> 2022-06-22 07:18:21.896 +00:00 [INF] - Initiating streaming logs for fileTransferBlob
```

</details>

<details>
<summary>edge-agent logs with contentType = text</summary>

```
<6> 2022-06-22 07:18:51.353 +00:00 [INF] - Received direct method call - UploadModuleLogs
<6> 2022-06-22 07:18:51.353 +00:00 [INF] - Received request UploadModuleLogs with payload
<6> 2022-06-22 07:18:51.354 +00:00 [INF] - Processing request to upload logs for {"schemaVersion":"1.0","items":{"id":"^(?!\\bedgeAgent|edgeHub\\b)","filter":{"tail":null,"since":"0d, 0m, 0 days, 0 hours 15 minutes","until":null,"loglevel":null,"regex":".*\\b(WRN?|ERR?|CRIT?|FTL?)\\b.*"},"encoding":1,"contentType":1}
<6> 2022-06-22 07:18:51.384 +00:00 [INF] - Successfully handled request UploadModuleLogs
<6> 2022-06-22 07:18:51.385 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/opcuaPublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.387 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/edgeMonitoring-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.388 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/fileTransferBlob-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.388 +00:00 [INF] - Uploading blobxxx.azure-devices.net/yyy/cubePublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.389 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/edgePublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.389 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/notificationPublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.390 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/recordPublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.390 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/edgeStorage-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.391 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/machineEventPublisher-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.392 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/edgeBlob-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.392 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/fileTransfer-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.393 +00:00 [INF] - Uploading blob xxx.azure-devices.net/yyy/opcuaAdapter-2022-06-22--07-18-51.log.gz to container yyy
<6> 2022-06-22 07:18:51.864 +00:00 [INF] - Initiating streaming logs for fileTransfer
<6> 2022-06-22 07:18:51.893 +00:00 [INF] - Initiating streaming logs for machineEventPublisher
<6> 2022-06-22 07:18:51.911 +00:00 [INF] - Initiating streaming logs for edgeStorage
<6> 2022-06-22 07:18:51.935 +00:00 [INF] - Initiating streaming logs for edgePublisher
<6> 2022-06-22 07:18:51.954 +00:00 [INF] - Initiating streaming logs for edgeBlob
<6> 2022-06-22 07:18:51.969 +00:00 [INF] - Initiating streaming logs for recordPublisher
<6> 2022-06-22 07:18:52.126 +00:00 [INF] - Initiating streaming logs for cubePublisher
<6> 2022-06-22 07:18:52.649 +00:00 [INF] - Initiating streaming logs for edgeMonitoring
<6> 2022-06-22 07:18:52.652 +00:00 [INF] - Initiating streaming logs for opcuaAdapter
<6> 2022-06-22 07:18:52.661 +00:00 [INF] - Initiating streaming logs for fileTransferBlob
<6> 2022-06-22 07:18:52.677 +00:00 [INF] - Initiating streaming logs for notificationPublisher
<6> 2022-06-22 07:18:52.679 +00:00 [INF] - Initiating streaming logs for opcuaPublisher
```

</details>

<details>
<summary>edge-hub logs</summary>

```
N/A
```
</details>

## Additional Information
All works fine with GetModuleLogs direct method. If you use contentType = json or text, logs ar returned....

**Comment by nlcamp** [comment] 2022-06-24 21:13
@giovannimele Thanks for reporting this issue along with all the necessary information to reproduce it. I was able to repro it in my environment. I'll discuss with my team to confirm the expected behavior you listed and to determine next steps. I'll keep you posted.

**Comment by giovannimele** [comment] 2022-06-30 06:12
@nlcamp Hi Noel, please keep me informed as soon as possible of the availability of a fix because since our migration to iotedge 1.2.10 and edgeAgent 1.2.9, we lost all the monitoring of our deployed edge devices. This topic is becoming very hot for us. Thx!

**Comment by nlcamp** [comment] 2022-07-08 02:04
@giovannimele - we don't have a fix yet but I wanted to share with you that interestingly, the JSON content type query in our [documentation ](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11#upload-module-logs) succeeds:

`    {
        "schemaVersion": "1.0",
        "sasUrl": "<sasUrl>",
        "items": [
            {
                "id": ".*",
                "filter": {
                    "tail": 100
                }
            }
        ],
        "encoding": "gzip",
        "contentType": "json"
    }
 `
 
Given this finding, it's possible you could temporarily workaround this bug by changing your query.

**Comment by giovannimele** [comment] 2022-07-08 08:16
@micahl - I was using version 1.1 of the edgeAgent and iotedge 1.1.4-1. After we noticed the log problem, we tried to roll back the edgeAgent back to 1.1 but without any success.

**Comment by giovannimele** [comment] 2022-07-08 09:09
@nlcamp - I can give a try but I've a question: did you try your request with 'Regex' field in order to filter out logs?

**Comment by nlcamp** [comment] 2022-07-12 17:41
@giovannimele - Unfortunately, I have not been able to get any examples working with a regex in the id or filter->regex fields. I did confirm that this worked in 1.1.4 as you've stated. I'll keep you posted as we make plans for fixing this regression.

**Comment by nlcamp** [comment] 2022-08-10 19:52
@giovannimele - Looking into this some more, I see the issue is actually in your `Since` value. Instead of `"Since": "0d, 0m, 0 days, 0 hours 15 minutes"`, please try the following, which should work: `"Since": "0 hours 15 minutes"`

I can see where our description of the `since` field in our documentation on the following page is a bit confusing [Retrieve module logs](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-retrieve-iot-edge-logs?view=iotedge-2020-11#retrieve-module-logs). We'll see if we can clarify the example in the doc.

Also, I do see that the behavior is different when you use the `text` content type. A `.log.gz` file is successfully uploaded in this case, but you'll find that it's always empty. If you fix the `since` value, you'll see that it is no longer empty. We'll look into changing the behavior for consistency between the json and text content types, but the good news is that you should be able to proceed forward with 1.2.x or 1.3 once you change your `since` value.

**Comment by giovannimele** [comment] 2022-08-16 09:29
@nlcamp - back from vacation. I'll try your proposed fix asap. So if I understand it well, by fixing the 'Since' field, we should be able to retrieve logs... I'll keep you informed if it fixed my problem.

**Comment by giovannimele** [comment] 2022-08-17 06:47
@nlcamp - fix worked fine! We can retrieve logs and store them in our log analytics. 

What should we do with this issue? We keep it open until you unify the behaviour between json and text content types and fix the documentation?

**Comment by micahl** [comment] 2022-08-18 00:26
Closing this issue.  I opened a doc bug (referenced above) to track changing that page.

**Comment by micahl** [comment] 2022-08-18 00:27
Whoops... we should keep this open to rationalize the behavior difference between json and text content types.

**Comment by nlcamp** [comment] 2022-08-22 18:04
Closing this issue as the root cause has been discovered and addressed by fixing the `--since` filter. We've added an item to our internal backlog to investigate and fix the related issue involving the inconsistent behavior when json vs. text content type is requested along with an invalid filter.

**Closed by nlcamp** 2022-08-22 18:04 UTC
Labels: area:edgeagent, iotedge, customer-reported, 1.1, 1.2
