### ISSUE TITLE
EdgeHub does not forward messages from unnamed outputs

### ISSUE THREAD

**Issue by MaDOS** [Azure/iotedge#5345] opened 2021-08-10 09:27 UTC
# Expected behavior
EdgeHub should forward messages to IoTHub from all outputs of a module when the route is specifying a wildcard (`*`).

# Current behavior
EdgeHub only captures messages from the wildcard route but does not forward them to IoTHub when the output has no name.

# Platform
- iotedge v 1.2.3
- ubuntu 20.04 LTS arm64
- RPi 4B 8Gb

# Steps to reproduce
1. Setup default SimulatedTemperatureSensor test environment
2. Replace L227 (`await moduleClient.SendEventAsync("temperatureOutput", eventMessage);`)
3. With: `await moduleClient.SendEventAsync(eventMessage);`
4. Use a wildcard capture route to capture the messages
```json
"$edgeHub": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "routes": {
          "alloutputs": "FROM /messages/modules/SimulatedTemperatureSensor/outputs/* INTO $upstream"
        },
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    }
```
5. Enable debugging on edgeHub
```json
"edgeHub": {
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:DEFAULT_RT_IMAGE",
(...)
            },
            "env": {
              "RuntimeLogLevel": {
                "value": "debug"
              }
            }
          }
```

# Problem description
Now when the temperature sensor does send a message and we have `RuntimeLogLevel` set on `debug` for our edgeHub we see that the message is being received but not forwarded to IoTHub. As soon as we change L227 back and include an output name in our `SendEventAsync` call everything will work fine again.

**Comment by nlcamp** [comment] 2021-08-14 00:45
@MaDOS - Thanks for the detailed description and repro steps. This does look like a bug. We'll investigate it some more and provide a fix once it's confirmed.

**Comment by varunpuranik** [comment] 2021-08-18 01:02
@MaDOS -
This behavior is actually by design. If you don't want to use any output, then simply update the route to this -
"alloutputs": "FROM /messages/modules/SimulatedTemperatureSensor INTO $upstream".
That should send the messages from SimulatedTemperatureSensor to the destination (upstream). 

Please let us know if it doesn't work, or if you have any questions.

**Comment by nlcamp** [comment] 2021-08-20 18:46
Closing this issue because the described behavior is by design. @MaDOS if you run into any issues with the workaround provided by @varunpuranik then feel free to reopen this issue or a new one.

**Closed by nlcamp** 2021-08-20 18:46 UTC
Labels: bug, iotedge, customer-reported
