### ISSUE TITLE
iotedge installation from DEB assumes container runtime is already installed.

### ISSUE THREAD

**Issue by gri6507** [Azure/iotedge#5384] opened 2021-08-18 13:47 UTC
Installing iotedge DEB on Debian/Ubuntu systems fails when docker/moby is not installed. Since this is a dependency for `preinst` helper script, the `debian/control` file should list `Pre-Depends: moby-engine, moby-cli`

See https://github.com/Azure/iotedge/blob/master/edgelet/contrib/debian/control 
See https://www.debian.org/doc/debian-policy/ch-relationships.html#binary-dependencies-depends-recommends-suggests-enhances-pre-depends

**Comment by pmzara** [comment] 2021-08-18 17:02
Thanks for the report @gri6507
I will verify and take the appropriate actions.

**Comment by veyalla** [comment] 2021-08-18 20:26
@gri6507 - This is by design, IoT Edge has a hard dependency on the Moby container engine.

**Comment by gri6507** [comment] 2021-08-19 13:16
> IoT Edge has a hard dependency on the Moby container engine.

@veyalla - I understand and agree with your statement. However, This is currently an **implied** dependency. By adding a `Pre-Depends:` stanza to `debian/control` file, this dependency can be made explicit.

**Comment by veyalla** [comment] 2021-08-20 16:35
We have some customers who bring their own container engine (e.g. Docker Enterprise Edition). They understand and accept that their setup is not fully supported. This is the reason the packages are setup the way they are - without a hard dependency on Moby-engine.

**Comment by gri6507** [comment] 2021-08-20 16:46
Thank you for the clarification. Since moby packages are maintained by Microsoft, can their control files be enhanced to specify `Provides: docker-*` equivalents as virtual packages? This way, it would be possible to list a `Pre-Depends: docker-*` in iotedge without explicitly specifying moby

**Comment by veyalla** [comment] 2021-08-20 16:49
Can you please clarify in which scenario is the way things are setup right now not working for you?

**Comment by gri6507** [comment] 2021-08-20 18:01
> Can you please clarify in which scenario is the way things are setup right now not working for you?

Installation of `iotedge` is currently two steps:
1. `sudo apt -y install --no-install-recommends moby-engine moby-cli`
2. `sudo apt -y install iotedge`

The two steps cannot be combined into one

**Comment by veyalla** [comment] 2021-08-30 17:11
Since security updates for Moby-engine are released independently, we prefer customers install this explicitly so there is no expectation that updating edged will update Moby-engine.

**Closed by veyalla** 2021-08-30 17:11 UTC
Labels: iotedge, customer-reported
