### ISSUE TITLE
Update module when deploy using automatic deployment

### ISSUE THREAD

**Issue by Punnpd** [Azure/iotedge#6702] opened 2022-10-05 07:04 UTC
Expected behavior:
- module gets an update and restart once the automatic deployment is set.

Step to Reproduce:
- Create module image 
- Push to container registry
- automatic deploy on edge device with module version 0.0.1 and image tag 0.0.1
- Update something and recreate the module image 
- Push to container registry
- Redeploy with the same deployment id, but new module version 0.0.2 and new image tag 0.0.2 

Note:
`az iot edge deployment create` is used to redeploy in the last step, and it returns 
`'Message': "ErrorCode:ConfigurationAlreadyExists;Configuration with id 'xxxx' already exist on IotHub.`

So, Is there a proper command to update the deployed module in the edge device? or I have to delete the old deployment and redeploy the new one.

**Comment by Sethshan** [comment] 2022-10-08 00:45
Did we try " az iot edge deployment update " ? Pls refer to this article:
https://learn.microsoft.com/en-us/cli/azure/iot/edge/deployment?view=azure-cli-latest

**Comment by raisalitch** [comment] 2022-10-14 17:37
@Punnpd Did you manage to try Seth's suggestion? Thanks.

**Comment by AltoTechGithub** [comment] 2022-10-17 09:32
@Sethshan 
According to your suggestion and azure iot edge document 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/98011607/196141400-afdb8b5b-9ed4-441c-a732-b0a492cb8ff6.png">

This command : `az iot edge deployment update` doesn't allow us to update things in deployment manifest, and there is no parameter of `az iot edge deployment update` related to the update of deployment manifest.

Is there anything I missed out?
or
Is there a workaround here?

**Comment by Sethshan** [comment] 2022-10-19 23:19
@Punnpd : It seems to be by Design at this point, where we will have to delete the old deployment and re-deploy a new one.

**Comment by raisalitch** [comment] 2022-10-21 23:15
Hey @Punnpd I'm closing this since it is by design. If you need further help, please file a support ticket on DPS/IoT Hub. Thanks!

**Closed by raisalitch** 2022-10-21 23:15 UTC
Labels: iotedge, customer-reported
